### PR TITLE
dada2 fixes and upgrade to 1.14

### PR DESCRIPTION
**Pull request by bernt-matthias**
- dada: fix output collection naming error for non-batch mode
  - fixes https://github.com/galaxyproject/tools-iuc/issues/2912
    error probably indroduced with the update to 1.12. In 1.12
    the derep step was removed. probably the names came from the
    derep objects. Or it simply never worked.
- filterAndTrim: fail if all reads are filtered
  - according to https://github.com/benjjneb/dada2/issues/931
    empty files likely lead to problems in downstream analyses
  - non existant output files raised to a bug in Galaxy under
    certain conditions:
    https://github.com/galaxyproject/galaxy/issues/9287
    fixes https://github.com/galaxyproject/tools-iuc/issues/2843
- assignTaxonomyAndSpecies: add seed parameter for reproducibility
  and in particular testing
- make almost all test using two samples
- fixed two typos

I happily remove the test data if https://github.com/galaxyproject/tools-iuc/pull/2908 is accepted.

Ahh.. and the images seem not to be shown on usegalaxy.eu (but since they are shown on org I guess its some problem at the eu site)

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
OK. Done + upgrade to 1.14 ..

**Comment by bgruening** [comment]
Thanks.

**Comment by bernt-matthias** [comment]
@bgruening 

have you seen my comment: 

> Ahh.. and the images seem not to be shown on usegalaxy.eu (but since they are shown on org I guess its some problem at the eu site)

**Comment by bgruening** [comment]
Yes, thanks for the hint. I think this is fixed in 20.01 and I hope we upgrade soon.

**Pull request merged**
