### PR TITLE
maxbin2:  add idba out/err only if present (and update bioconda recipe)

### PR DESCRIPTION
**Pull request by bernt-matthias**
- replaced by `gzip -cd | tar -xf -`
- additionally add idba out/err only if present

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
bump?

**Comment by bgruening** [comment]
Think so yes! please bump.

**Comment by mvdbeek** [comment]
This is still failing in the container with:
```

Attaching package: 'gplots'

The following object is masked from 'package:stats':

    lowess

tar: invalid option -- 'z'
BusyBox v1.22.1 (2014-05-23 01:24:27 UTC) multi-call binary.

Usage: tar -[cxthvO] [-X FILE] [-T FILE] [-f TARFILE] [-C DIR] [FILE]...

Create, extract, or list files from a tar file

Operation:
	c	Create
	x	Extract
	t	List
	f	Name of TARFILE ('-' for stdin/out)
	C	Change to DIR before operation
	v	Verbose
	O	Extract to stdout
	h	Follow symlinks
	exclude	File to exclude
	X	File with names to exclude
	T	File with names to include

gzip: out.marker_of_each_bin.tar.gz: No such file or directory
tar: short read
```
I think maxbin2 might be using tar internally ?

**Comment by bernt-matthias** [comment]
https://github.com/bioconda/bioconda-recipes/pull/19012

**Pull request merged**
