### PR TITLE
Package updates

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/34/
Test FAILed.

**Comment by bgruening** [comment]
Not sure what is failing here. I see a lot of unrelated stuff.

**Comment by erasche** [comment]
@bgruening consider it passing :) Only things getting tested are tools, and apparently I accidentally set unstable builds to be marked as failed.

**Comment by erasche** [comment]
@bgruening they all look good to me, add .shed.yml and I'll merge.

**Comment by erasche** [comment]
ping @bgruening for a .shed.yml, all that's left :)

**Comment by erasche** [comment]
@bgruening shed.yml reminder, I want to close this PR :)

**Comment by martenson** [comment]
yamls added, put version in the ucsc package name

**Comment by erasche** [comment]
@martenson thanks!

**Pull request merged**
