### PR TITLE
[WIP] Update rnastar to version 2.7.3a

### PR DESCRIPTION
**Pull request by wm75**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by wm75** [comment]
This update will introduce also a new data table for STAR indices to address the issue of conflicting column names discovered in #2637.

**Comment by wm75** [comment]
@mtekman this is looking promising right from the start - all 4 STARsolo tests are now failing with a core dump! :angry:
Hope this can be solved somehow?

**Comment by mtekman** [comment]
Core dump? Ouch. Okay will have a look later

**Comment by nsoranzo** [comment]
@wm75 Any chance you can give another look at this? It has a conflict at the moment.

**Comment by wm75** [comment]
@nsoranzo I may have time for it next week. At least I'll try :)

**Comment by wm75** [comment]
@mtekman I think the situation with this PR has improved significantly with my latest changes (though I'm less sure what fixed what exactly).
The STARsolo tests are still all failing, but with debugable error messages it seems.
Would you have time to look at that part again? The wrapper now uses STAR 2.7.5a and quite some things have changed for the STARsolo functionality.

**Comment by mtekman** [comment]
I can start on this on the weekend :+1:

**Comment by bgruening** [comment]
https://github.com/alexdobin/STAR/releases/tag/2.7.5b :)

**Comment by wm75** [comment]
Closing this in favor of #3151.

**Comment by mtekman** [comment]
Thanks, still no idea how to push to someone else's PR

**Comment by wm75** [comment]
It's much easier if you're iuc member :)

**Pull request closed without merging**
