### PR TITLE
use single quotes in travis.yml

### PR DESCRIPTION
**Pull request by shiltemann**
Ran into this when using this testing in our own repo and our randomly generated password had some special characters in it. 

Any reason to not just use single quotes everywhere?

### CODE REVIEW

**Comment by peterjc** [comment]
Assuming TravisCI is happy, +1 from me.

Using single quotes was recently adopted as IUC best practise for the ``<command>`` tag for much the same reason.

**Comment by nsoranzo** [comment]
@shiltemann In bash you cannot use single quotes if you want the env variables to be interpreted, which is the case here.

**Comment by peterjc** [comment]
Do you know which special character was triggering this? That would help for testing.

**Comment by shiltemann** [comment]
@nsoranzo of course, I am an idiot ;P guess thinking too much of cheetah. So guess only solution is make sure password contains characters that play nice?

**Pull request closed without merging**
