### PR TITLE
Trinity: fix wrong sha256sum

### PR DESCRIPTION
**Pull request by abretaud**
Ok, I should have checked the sha256sum before committing instead of just pasting it from package_deseq2_1_10_0 (I fixed it there too just in case)

### CODE REVIEW

**Comment by nsoranzo** [comment]
Mmmh, actually I think there is something wrong with depot/cargoport here. It seems that [BiocGenerics 0.14.0 on depot](https://depot.galaxyproject.org/software/BiocGenerics/BiocGenerics_0.14.0_src_all.tar.gz) contains a copy of https://github.com/bgruening/download_store/raw/master/DESeq2-1_8_1/BiocGenerics_0.14.0.tar.gz (i.e. BiocGenerics **0.14.0+gx0**, sha256sum 5e55e0f5c6577935d169f62268dc05a168a2f607b652d44a919cb16caca7952e) instead of a copy of https://github.com/bgruening/download_store/raw/master/DEXSeq_1.14.2/BiocGenerics_0.14.0.tar.gz (sha256sum d16ad5910aee6247990a19745511a5d50e19fa8c236000cbf99395e06c73c9f8 ).

Ping @erasche @bgruening.

**Comment by abretaud** [comment]
Oh, strange...
(Anyway, the full install of trinity is now ok)

**Comment by erasche** [comment]
@nsoranzo yup. The deseq/dexseq packages have a large number of overlapping child dependencies with identical versions; I deduped when building the cargo-port rather than storing processing the deseq and dexseq dependencies individually.

Looking at those two the only difference is the bioconductor team modified the `DEPENDENCIES` file without changing a version number. The packages will be functionally equivalent.

**Comment by nsoranzo** [comment]
@erasche Then I guess https://github.com/galaxyproject/cargo-port/blob/master/urls.tsv should be updated accordingly?

**Comment by erasche** [comment]
@nsoranzo what would your suggested fix be?

This is what's on there now, i.e. both of them. Maybe I'm  not understanding your comment.

Id           | Version    | Platform | Architecture | Upstream                                                                                        | Url     | Extension                                                        | sha256sum
------------ | ---------- | -------- | ------------ | ----------------------------------------------------------------------------------------------- | ------- | ---------------------------------------------------------------- | ---------
BiocGenerics | 0.14.0     | src      | all          | https://github.com/bgruening/download_store/raw/master/DEXSeq_1.14.2/BiocGenerics_0.14.0.tar.gz | .tar.gz | d16ad5910aee6247990a19745511a5d50e19fa8c236000cbf99395e06c73c9f8 | True
BiocGenerics | 0.14.0+gx0 | src      | all          | https://github.com/bgruening/download_store/raw/master/DESeq2-1_8_1/BiocGenerics_0.14.0.tar.gz  | .tar.gz | 5e55e0f5c6577935d169f62268dc05a168a2f607b652d44a919cb16caca7952e | True

**Comment by nsoranzo** [comment]
- [ ] BiocGenerics 0.14.0+gx0 is not used in tools-iuc, tools-devteam or bgruening's galaxytools repositories, maybe it can be removed
- [ ] The row for BiocGenerics 0.14.0 in `urls.tsv` should have the values form Upstream and Extension substituted with the ones of 0.14.0+gx0 (i.e. https://github.com/bgruening/download_store/raw/master/DESeq2-1_8_1/BiocGenerics_0.14.0.tar.gz and 5e55e0f5c6577935d169f62268dc05a168a2f607b652d44a919cb16caca7952e respectively)
- [ ] files `packages/package_deseq2_1_8_1/tool_dependencies.xml` and `packages/package_deseq2_1_8_2/tool_dependencies.xml` in this repository should have the sha256sum patched as in this PR.

Sounds correct?

**Comment by erasche** [comment]
- BiocGenerics 0.14.0+gx0 may be used by other people. I do not believe it should be removed just because the IUC/devteam isn't using it. That goes against the purpose of cargo store, cargo store is not intended to be mutable storage, not intended to have files which disappear.
- No, switching out which (file, sha256sum) a (name, version) refers to and having people who might have been downloading something one day, find that they're downloading something slightly different is not a change I'm happy to see.
- yes, packages should be double checked for pointing to correct files + hashes.

Perhaps I'm missing your rationale for requesting the cargo port changes? Is it just so there's "one true" version of the package?

**Comment by nsoranzo** [comment]
As clarified on IRC, the problem is that `urls.tsv` is not in sync with depot. I agree that files should not disappear from depot, but I still think that removing BiocGenerics 0.14.0+gx0 from `urls.tsv` it's an option, since it points to a file identical to BiocGenerics 0.14.0.

**Comment by erasche** [comment]
The cargo port is fixed now.

**Comment by nsoranzo** [comment]
@erasche I think this PR should be reverted now.

**Pull request merged**
