### PR TITLE
Updating tools/iqtree from version 2.1.2 to
2.2.0.3

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/iqtree**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/iqtree from version 2.1.2 to 2.1.4_beta.

**Project home page:** http://www.iqtree.org

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Do we want beta releases? Also I can't find 2.1.4 on github or the project home page...

**Comment by simonbray** [comment]
> Do we want beta releases?

I assume not, but I don't think they should be in bioconda either

> Also I can't find 2.1.4 on github or the project home page...

https://github.com/iqtree/iqtree2/releases/tag/v2.1.4-beta

**Comment by bernt-matthias** [comment]
https://github.com/iqtree/iqtree2/issues/49

**Comment by bernt-matthias** [comment]
Converting this to a draft. Status should be changed only if there is a new stable release?

**Pull request closed without merging**
