### PR TITLE
QIIME core - align_seqs

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I cleaned `align_seqs` and add tests.

Bérénice

### CODE REVIEW

**Comment by shiltemann** [comment]
great :) ..the test dataset `core_set_aligned.fasta.imputed` is 37M large, can we make that smaller somehow?

**Comment by bebatut** [comment]
@shiltemann Thanks! I always forget to check the size. I extracted sequences out of the file to reduce the size (and adapt the tests)

**Comment by shiltemann** [comment]
great! mind if I do a squash-and-merge so the big file is not still present in the git history? (PR will go in a a single commit)

**Comment by bebatut** [comment]
Please do :)

**Pull request merged**
