### PR TITLE
Fix autoupdate macs2

### PR DESCRIPTION
**Pull request by elischberg**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by elischberg** [comment]
Adjust the param name in test 1 and test 2
Version number update
https://github.com/galaxyproject/tools-iuc/pull/5407

**Comment by bgruening** [comment]
The lint error needs to be fixed.

**Review by bernt-matthias — APPROVED** [review]

**Comment by wm75** [comment]
hmm, all tests are failing with `macs2: command not found`.
@bernt-matthias @bgruening any ideas?

**Comment by bgruening** [comment]
I guess the container with macs2 and gawk are not building or incompatible. You can sue https://github.com/BioContainers/multi-package-containers to create them a priori.

**Comment by wm75** [comment]
> I guess the container with macs2 and gawk are not building or incompatible. You can sue https://github.com/BioContainers/multi-package-containers to create them a priori.

only two of the wrappers require the macs2/gawk combination, but *all* tests are failing. Why could that be?

**Comment by wm75** [comment]
Ah, could be the shared r-base 3.4 requirement?

**Comment by wm75** [comment]
The first case is easy to understand, just look at the callpeak_part.tabular test-data. There are enough version-dependent and temporary filename-dependent lines there.
The randsample case I'm not so sure. It's probably ok, a new version of macs2 might call slightly different peaks.

**Comment by wm75** [comment]
In the first case, just adjusting the first line of the test file, will bring you back to three lines difference.

**Comment by wm75** [comment]
In the second case, you'd better compare the output of the old version (e.g. on .eu) with the new output to confirm that a single line (or few lines) are all the difference.

**Comment by elischberg** [comment]
Ok, didnt change anything about the second test failure, but it worked. Locally was everything fine.

**Comment by bgruening** [comment]
@elischberg the `macs2_randsample (Test #1): failed`

**Pull request merged**
