### PR TITLE
Update samtools_coverage.xml

### PR DESCRIPTION
**Pull request by o-william-white**
Corrected arguments for --rf and --ff

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by o-william-white** [comment]
Hello, 

I was running samtools coverage today and I hit an error that I think is related to the input arguments being specified as -ff and -rf rather than --ff and --rf. 

Think this is a simple fix

Best wishes
OIlie

**Comment by o-william-white** [comment]
image

**Comment by bernt-matthias** [comment]
Maybe use the long options:

```
--rf, --incl-flags STR|INT
Required flags: skip reads with mask bits unset [null]

--ff, --excl-flags STR|INT
Filter flags: skip reads with mask bits set
```

Would also look more readable.

**Comment by o-william-white** [comment]
> Maybe use the long options

Done

**Comment by o-william-white** [comment]
Is there anything else I need to do for this? Or is it good to go? @bernt-matthias

**Comment by bernt-matthias** [comment]
The original problem was that `samtools coverage` does not have a non zero exit code for the wrong argument. Therefore Galaxy did not realize the error (consequently the test data files are all empty).

@o-william-white I guess the following should be done to finish this:

- update the test data to make tests pass (use eg planemo's `--update_test_data` flag)
- remove the `from_workdir` from the output since the tool writes directly to `$output`
- could you file an upstream issue that samtools should always return a non-zero exit code for missing or wrong options?

**Pull request closed without merging**
