### PR TITLE
update minimap2 version

### PR DESCRIPTION
**Pull request by bgruening**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by mvdbeek** [comment]
There are some additional options introduced between 2.12 and 2.17:
- [ ] --junc-bed
- [ ] --sam-hit-only
- [ ] Added preset splice:hq
- [ ] --paf-no-hit
- [ ] --cap-sw-mem 
- [ ]  --hard-mask-level

Do we want to implement that in this PR or should I open a new issue and we merge when the tests pass ?

**Comment by bgruening** [comment]
Your call, I will not have time the next days and just wanted to ping us all as I consider this an important tool ... ideally, I will replace myself with a bot for those PRs in the future.

**Comment by mvdbeek** [comment]
There's also bedtools 2.28 that we should update.

**Comment by mvdbeek** [comment]
Let's move ahead when tests pass, we can keep the options to implement in a list. IMO it's most important to run the latest versions. We can always add missing options later.

**Pull request merged**
