### PR TITLE
Updating tools/datamash from version 1.1.0 to
1.8

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/datamash**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/datamash from version 1.1.0 to 1.7.

**Project home page:** https://www.gnu.org/software/datamash

### CODE REVIEW

**Comment by wm75** [comment]
Puh, quite useful new functionality, but needs some time to incorporate it all.

**Comment by wm75** [comment]
Thanks for making the wrapper autoupdate-compatible @bernt-matthias :)

**Comment by bgruening** [comment]
This is a very good opportunity for a first-time contributor.

**Comment by wm75** [comment]
completed via #5193

**Pull request closed without merging**
