### PR TITLE
Samtools: update version and fix macros

### PR DESCRIPTION
**Pull request by gallardoalba**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Do we want to add some of the new features: https://github.com/samtools/samtools/releases

**Comment by lldelisle** [comment]
Hi,
Any update on this PR?
I just found a 'bug' in the wrapper of samtools view with 'target'. The fix is: https://github.com/lldelisle/tools-iuc/commit/c8b3aab7ecddb377e9461305c2aa420e3f31004a
Should I write another PR?

**Comment by bgruening** [comment]
Can you apply the fix to this branch here?

**Comment by lldelisle** [comment]
For info, the bug is:
If your random seed is high like `10632` then awk prints only one decimal therefore your number of read can be quite far from the target.

**Comment by lldelisle** [comment]
@bgruening I can make a PR to this branch. Is it what you mean?

**Comment by bgruening** [comment]
Yes, thanks.

**Comment by lldelisle** [comment]
This is strange, I don't manage to create a PR to gallardoalba, it does not appear in the list of base repository... 
image

**Comment by wm75** [comment]
You should be able to `git remote add gallardoalba git@github.com:gallardoalba/tools-iuc.git` to your remotes, then `git fetch gallardoalba`, then checkout his PR branch. From there, you would create your own topic branch, add your change, push to your own fork on github, and should be able to create the PR. Untested, but that should roughly be the way.

**Comment by lldelisle** [comment]
For me it looks more like something strange on github because I can make a PR to galaxyproject, to your repo:
image
But not to gallardoalba.
Like if he protected his fork.

**Comment by wm75** [comment]
That may be true (and we probably should protect the master branches of our forks), but doesn't change the solution:

with:
```
$ git remote -v | grep gallardoalba
gallardoalba	git@github.com:gallardoalba/tools-iuc.git (fetch)
gallardoalba	git@github.com:gallardoalba/tools-iuc.git (push)
$ git remote -v | grep own
own	git@github.com:wm75/tools-iuc.git (fetch)
own	git@github.com:wm75/tools-iuc.git (push)
```
I can do:
```
$ git fetch gallardoalba 
$ git checkout samtools_view_fix_macros 
branch 'samtools_view_fix_macros' set up to track 'gallardoalba/samtools_view_fix_macros'.
Switched to a new branch 'samtools_view_fix_macros'
$ git checkout -b test-contrib
Switched to a new branch 'test-contrib'
$ vim tool_collections/samtools/macros.xml 
$ git add tool_collections/samtools/macros.xml 
$ git commit -S -m "Test contributing to gallardoalba topic branch"
[test-contrib 0222a2aba] Test contributing to gallardoalba topic branch
 1 file changed, 1 insertion(+)
[wolma@damaschin holiday-tools]$ git push own
Enumerating objects: 28, done.
Counting objects: 100% (28/28), done.
Delta compression using up to 8 threads
Compressing objects: 100% (13/13), done.
Writing objects: 100% (22/22), 2.49 KiB | 2.49 MiB/s, done.
Total 22 (delta 18), reused 12 (delta 9), pack-reused 0
remote: Resolving deltas: 100% (18/18), completed with 6 local objects.
remote: 
remote: Create a pull request for 'test-contrib' on GitHub by visiting:
remote:      https://github.com/wm75/tools-iuc/pull/new/test-contrib
remote: 
To github.com:wm75/tools-iuc.git
 * [new branch]          test-contrib -> test-contrib
```
Now if I go to my own fork, I can open the PR against his branch just fine.

**Comment by wm75** [comment]
> Now if I go to my own fork, I can open the PR against his branch just fine.

Correction: If I go to *his* fork, ...

**Comment by lldelisle** [comment]
OK thanks
I will do this, sorry.

**Comment by lldelisle** [comment]
@gallardoalba are you still working on it or should I write an independent PR?

**Comment by bgruening** [comment]
He is on vacation, feel free to take it over :)

**Comment by bgruening** [comment]
merged in https://github.com/galaxyproject/tools-iuc/pull/4713

**Pull request closed without merging**
