### PR TITLE
Krona: Correct package version

### PR DESCRIPTION
**Pull request by bebatut**
Hello,

I changed package version in `tool_dependencies.xml` to get the expected package in `taxonomy_krona_chart.xml`

Bérénice

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks!

**Comment by bebatut** [comment]
@bgruening Can you push it on TTS, please? Thanks

**Comment by bgruening** [comment]
It already is!

**Comment by bebatut** [comment]
Too fast :) Thanks

**Pull request merged**
