### PR TITLE
Hicexplorer 3.7

### PR DESCRIPTION
**Pull request by joachimwolff**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Test are failing @joachimwolff, please let us know when this PR is ready for review.

**Comment by joachimwolff** [comment]
The error message says some of my files are bigger 500 kb. Very difficult for me to decrease these files without crashes in the test cases. Please accept that these files are slightly bigger than your definition. 

The other errors I don't understand, but they could be caused by the first error.

**Comment by bgruening** [comment]
The first one is just a lint, it has no influence on the second.

**Comment by joachimwolff** [comment]
So it's fixed, and just the file sizes. Please review.

**Comment by joachimwolff** [comment]
No one?

**Comment by joachimwolff** [comment]
?

**Comment by bgruening** [comment]
Leave it open, we will get to it I hope. Its a large one :)

**Comment by bgruening** [comment]
This was merged with https://github.com/galaxyproject/tools-iuc/pull/5382
Thanks @joachimwolff

**Pull request closed without merging**
