### PR TITLE
Alternate fastqc reversal

### PR DESCRIPTION
**Pull request by mvdbeek**
ping @wm75, this only reverts the merge commits. The update then only needs to revert the revert and bump the version

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by wm75** [comment]
hmm, except for the wording I'm not seeing a difference between the two versions? Don't both ways make the exact same changes? Anyway, I'm fine with yours, too :)

**Comment by mvdbeek** [comment]
It's the same changes, I just ran `git revert -m 1 <merge commit>` individually. I guess it doesn't mater too much.

**Comment by nsoranzo** [comment]
One test is failing.

**Comment by mvdbeek** [comment]
Yeah, but I don't think we should fix it. I'd suggest merging this PR, upload manually and open a PR that reverts this PR. Does that seem like a good idea ?

**Comment by nsoranzo** [comment]
If we fix the test, use the normal TS upload and then revert this, won't we reach the same outcome?

**Comment by mvdbeek** [comment]
Same outcome, but we'll have to resolve the conflict.

**Comment by nsoranzo** [comment]
If we revert the commit merging this PR, there shouldn't be any conflict, I think.

**Comment by wm75** [comment]
I think the real question is: are we sure that this is correctly reverting the wrapper.
I tested one thing which makes me worried: I ran the inputs of the failing test through fastqc on main and on EU. Result:
- on main, I'm getting a file of the exact same size as the html output expected by the test
- on EU, I'm getting a file of the exact same size as during the failing test

but main has the version we are trying to revert to!

**Comment by nsoranzo** [comment]
You can run `planemo test --failed --update_test_data` and see if the changes to `test-data/fastqc_report2.html` make sense.

**Comment by wm75** [comment]
well, I'm always getting the file size expected by the test and generated by main when I test locally. This doesn't seem to depend on the fastqc or wrapper version. I've inspected the html reports generated by various sources and they all *look* the same. @bgruening suggested that the size differences may reflect different image encoding by different library versions and that sounds like a good explanation to me.

If you want the failing test to pass, why not change the comparison to the same `lines_diff` as in the other tests. It's pointless because the html is mostly on a single line, but at least it's consistently pointless ;)

**Comment by wm75** [comment]
LGTM. @bgruening once merged and in MTS we can reinstall the 0.72 version on eu.

**Comment by nsoranzo** [comment]
Uploaded to TTS and MTS.

**Pull request merged**
