### PR TITLE
Add IRIS-TCGA data source tool.

### PR DESCRIPTION
**Pull request by blankenberg**
WIP, due to https://github.com/galaxyproject/tools-iuc/pull/605.

### CODE REVIEW

**Comment by blankenberg** [comment]
Remove WIP

**Comment by mvdbeek** [comment]
@blankenberg can you add a bit of documentation on how to use this? 
There is an example [here](https://github.com/mdshw5/galaxy-json-data-source), but it's not quite clear how to call the tool.

**Comment by blankenberg** [comment]
@mvdbeek do you mean, how to use IRIS-TCGA?

> 1. select the disease BRCA (please wait some seconds, this disease has a lot of metadata);
2. insert information about the first query q1: Platform = IlluminaHiSeq_RNASeq , Data Type = RNASeq.gene , Level = Level_3 , Tissue = tumoral;
3. add a row and insert information about the second query q2: Platform = IlluminaHiSeq_RNASeq , Data Type = RNASeq.gene , Level = Level_3 , Tissue = normal;
4. write the following integration formula: q1∩q2;
5. submit the request clicking the "Compute" button.


The last time that I tested it, I found that, for each of the select drop-downs used above, I to click twice before the following list would populate.

**Comment by mvdbeek** [comment]
Yes, I guess that wouldn't be too bad as a description in the .shed.yml (plus the URL).

**Comment by blankenberg** [comment]
Description has been updated. Thanks @mvdbeek !

**Comment by bgruening** [comment]
LGTM. @mvdbeek can we merge it?

**Comment by mvdbeek** [comment]
yep, thanks @blankenberg !

**Pull request merged**
