### PR TITLE
Update ToolDistillator Galaxy Version 0.9.1+galaxy0 to 0.9.1+galaxy1

### PR DESCRIPTION
**Pull request by clsiguret**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

Here are the changes:
- Correction of an error when giving staramr outputs: need to have specific dataset names
- Conditional parameter added for the tools version generating the outputs given to ToolDistillator: automatic recovery of the tool version or not

Thanks :smiley:

### CODE REVIEW

**Comment by bgruening** [comment]
> 10/15/2024 03:48:33 PM: interfaces.py: No information for plot_file_path: Not analyzed
10/15/2024 03:48:33 PM: interfaces.py: [Errno 2] No such file or directory: '+': input file not found

Seems something is wrong here :(

**Comment by clsiguret** [comment]
Thanks @bgruening :smiley:

**Review by bebatut — APPROVED** [review]

**Comment by bebatut** [comment]
Thanks @clsiguret!

**Comment by clsiguret** [comment]
Thanks @bebatut :smiley:

**Pull request merged**
