### PR TITLE
Updating tools/rgrnastar from version 2.7.10b to 2.7.11a

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following tool: **tools/rgrnastar**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/rgrnastar from version 2.7.10b to 2.7.11a.

**Project home page:** https://github.com/alexdobin/STAR/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bgruening** [comment]
Some new features for https://github.com/alexdobin/STAR/releases

@TomHarrop do you want to work on this?

**Comment by TomHarrop** [comment]
@bgruening I will take a look! Is the aim to implement STARdiploid?

**Comment by bgruening** [comment]
That would be nice

**Comment by TomHarrop** [comment]
From my reading of the [manual](https://github.com/alexdobin/STAR/blob/master/doc/STARmanual.pdf), STAR Diploid will require a separate index 

> Provide the VCF file with diploid SNVs and InDels at the genome generation stage

I think this means it should be a separate tool, which I've started [here](https://github.com/galaxyproject/tools-iuc/pull/5686/files?diff=unified&w=0)

**Comment by bgruening** [comment]
Maybe it's just me, but I think this index should be built on the fly. No Data manager is needed here.

**Comment by TomHarrop** [comment]
Yes that's my intention too.

To add it to the current wrapper AFAICT it would go under `<conditional name="refGenomeSource">` then `<when value="history">`. 

I'm happy to do it like that if you are. I'm just wondering if users will be able to find the option with that logic.

**Pull request closed without merging**
