### PR TITLE
Ensure correct output formats of seqtk_seq and seqtk_mergefa in all cases

### PR DESCRIPTION
**Pull request by RZ9082**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

Adjust output format when using `-A        force FASTA output (discard quality)` to FASTA

### CODE REVIEW

**Comment by wm75** [comment]
You need to bump the wrapper version. Maybe just this single one and don't change the macros one.

In addition, I think the fasta output of the tool would likely have to be `fasta.gz` in case the input is compressed (see the `@CONDITIONAL_GZIP_OUT@` macro).

If you have the time, you could also pull in the changes from #6350 and fix the output format there. Very similar issue as yours: the output of that tool should always be fasta or fasta.gz, depending on input compression, but never fastq(.gz).

**Comment by RZ9082** [comment]
> You need to bump the wrapper version. Maybe just this single one and don't change the macros one.
> 
> In addition, I think the fasta output of the tool would likely have to be `fasta.gz` in case the input is compressed (see the `@CONDITIONAL_GZIP_OUT@` macro).
> 
> If you have the time, you could also pull in the changes from #6350 and fix the output format there. Very similar issue as yours: the output of that tool should always be fasta or fasta.gz, depending on input compression, but never fastq(.gz).

seqtk seq actually produces also FASTQ as an output !

**Comment by wm75** [comment]
yes, I realize. What I wanted to say is that the logic for handling output formats will be similar.

**Review by RZ9082 — COMMENTED** [review]
Does it look good now? @wm75

**Review by wm75 — APPROVED** [review]

**Pull request merged**
