### PR TITLE
Fix for genomeCoverageBed.xml

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by erasche** [comment]
jenkins: please test this

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/28/
Test PASSed.

**Comment by erasche** [comment]
@bgruening such coordination :)

image

**Comment by bgruening** [comment]
I call it a good team! :) Thanks Eric!

**Pull request merged**
