### PR TITLE
Fix STAR wrapper

### LINKED ISSUE #5144: Bug in the new STAR solo wrapper
I am really sorry. I just realized that I made a mistake and mislabelled one option:

https://github.com/galaxyproject/tools-iuc/blob/03a91f6c42c75dc36d09505c2e6a2236178e4695/tools/rgrnastar/rg_rnaStarSolo.xml#L328

### PR DESCRIPTION
**Pull request by lldelisle**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This Fix #5144 (both the bad labelling and the issue with STAR solo and indexed reference without gtf)
Also fixed a strange character
updated some labels
add some SAM attributes

Should we allow more options for BAM output in the solo wrapper like 
outSAMmapqUnique
outSAMunmapped
?

### CODE REVIEW

**Review by bernt-matthias — APPROVED** [review]
Looks good. 

> Should we allow more options for BAM output in the solo wrapper like outSAMmapqUnique outSAMunmapped ?

Up to you I would say :) If you have the time to add it and think that its useful. Otherwise we may also wait until the feature is demanded.

**Comment by lldelisle** [comment]
> Looks good.
> 
> > Should we allow more options for BAM output in the solo wrapper like outSAMmapqUnique outSAMunmapped ?
> 
> Up to you I would say :) If you have the time to add it and think that its useful. Otherwise we may also wait until the feature is demanded.

Testing the outSAMunmapped is easy because it changes the size of the BAM file but how can I test outSAMmapqUnique? Is there a way to check if one like is present in a BAM file?

**Comment by lldelisle** [comment]
@bernt-matthias I implemented the 2 options. Can you re-review, please?

**Review by bernt-matthias — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Merge? :)

**Comment by lldelisle** [comment]
There is a last thing I noticed: it seems that my action to rename column does not work.

**Comment by lldelisle** [comment]
Once these tests pass you can merge. Thank you. If you want I can ping you when done.

**Comment by lldelisle** [comment]
Youhou. It passed. @bernt-matthias

**Comment by bernt-matthias** [comment]
Excellent :)

**Comment by lldelisle** [comment]
Thanks for your reactivity

**Pull request merged**
