### PR TITLE
Updating tools/raven from version 1.8.0 to 1.8.1

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/raven**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/raven from version 1.8.0 to 1.8.1.

**Project home page:** https://github.com/lbcb-sci/raven/releases

### CODE REVIEW

**Comment by bernt-matthias** [comment]
New release seems only to concern installation which is not relevant for us. So I think we can skip this release.

**Comment by abretaud** [comment]
Should we close this, or the bot will open a new one if we close this one?

**Comment by simonbray** [comment]
> Should we close this, or the bot will open a new one if we close this one?

It will open a new one if you close it. If you leave it open, the bot will push a new commit for the next release.

**Comment by abretaud** [comment]
Ok, maybe we can set a label for this kind of situation? And have it deleted by the bot on next release?
By the way, I think adding a label to all autoupdate PRs would be great too, PRs proposed by human are a bit "drowned" in the automatic ones

**Comment by simonbray** [comment]
> Ok, maybe we can set a label for this kind of situation? And have it deleted by the bot on next release?

That would be great, that's how Bioconda does it as well.

> By the way, I think adding a label to all autoupdate PRs would be great too, PRs proposed by human are a bit "drowned" in the automatic ones

Yes, I suggested this a while ago, but the bot account doesn't have permissions to add labels.

**Comment by bgruening** [comment]
> Yes, I suggested this a while ago, but the bot account doesn't have permissions to add labels.

This we can fix. We just need to add the bot to this repo I think. @martenson can you do this?

**Pull request closed without merging**
