### PR TITLE
Add the vegan Conda dependency

### PR DESCRIPTION
**Pull request by remimarenco**

### CODE REVIEW

**Comment by bgruening** [comment]
Tests are running now but failing due to wrong test data ... would be great if you can either create a new tool_dependency.xml version or an older conda package.

@blankenberg what do you think?

**Comment by remimarenco** [comment]
There are 3 versions of the r-vegan package (https://github.com/bioconda/bioconda-recipes/tree/7154a85e649bbf8296df96577091431ccd426e17/recipes/r-vegan).

Do you want me to take the 2.3_0 to match the version of the toolshed one?

**Comment by bgruening** [comment]
exactly, or the other way around as you prefer, but both the conda and the TS one should be the same ... aka tests should pass.

**Comment by yhoogstrate** [comment]
@remimarenco I think it's working correctly but the test file needs a small patch according to the travis test:

```
( /home/travis/build/galaxyproject/tools-iuc/tools/vegan/vegan_diversity/test-data/output_diversity_index.tabular v. /tmp/tmpOEbvK6/tmp/tmpgNAtdNoutput_diversity_index.tabular )
--- local_file
+++ history_data
@@ -1,2 +1,2 @@
 	x
-1	1.58148247996845
+1	1.020620870138
````
Could you try to fix the test-file?

**Pull request closed without merging**
