### PR TITLE
Add meme 4.10.0

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by erasche** [comment]
@davebx would you mind terribly expanding the `.shed.yml` file? E.g. https://github.com/galaxyproject/tools-iuc/blob/shed_yml_updates/packages/package_aragorn_1_2_36/.shed.yml

**Comment by davebx** [comment]
@erasche will do.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/49/
Test (probably) passed

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/50/
Test (probably) passed

**Pull request merged**
