### PR TITLE
Add automatic TTS push after

### PR DESCRIPTION
**Pull request by bgruening**
Only if a tool was tested with planemo-test and only to TTS

### CODE REVIEW

**Comment by bgruening** [comment]
ping @martenson @jmchilton 
I have added the TS credentials to Travis. Let's see if this works.

**Comment by mvdbeek** [comment]
Nice, looks good! 👍

**Comment by yhoogstrate** [comment]
Yep, looks good! Great to see all the automation in iuc in just a few months time. :+1:

**Comment by bgruening** [comment]
Ok, I count 3 votes ... does anyone wants to merge it and take the responsibility ;)

**Comment by mvdbeek** [comment]
yes, let's do it. thanks @bgruening

**Pull request merged**
