### PR TITLE
ensembl_vep: link input fasta

### PR DESCRIPTION
**Pull request by bernt-matthias**
tool creates additional files next to the fasta

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]

**Comment by bgruening** [comment]
Hu ...

>    File "cheetah_DynamicallyCompiledCheetahTemplate_1656351261_1653545_67995.py", line 108, in respond
NameMapper.NotFound: cannot find 'ref'

How could this pass in the first place ... or is this a regression.

**Comment by wm75** [comment]
There's simply a third possible value for $refseq.ref_source ("no_ref") for which the new code doesn't set the `$ref` variable.

**Comment by mvdbeek** [comment]
You scare me @bgruening 😆! It's https://github.com/galaxyproject/tools-iuc/blob/253cee2af723a8cabc17dba323c97330169723f5/tools/ensembl_vep/ensembl_vep.xml#L33 -- there is actually an else, which is `no_ref`

**Comment by bgruening** [comment]
> You scare me @bgruening laughing! It's 

Upps sorry. I did not understand how could this pass in the initial PR.

LGTM.

**Pull request merged**
