### PR TITLE
Update to UMItools whitelist

### PR DESCRIPTION
**Pull request by mtekman**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Whitelist updated to accept barcode regex input

### CODE REVIEW

**Comment by bgruening** [comment]
There is one new parameter in the 0.5.5 release as far as I have seen, useful?

**Comment by mtekman** [comment]
`--assigned-status-tag` in [0.5.5](https://zenodo.org/record/1490058)? I have never seen this used. I think we can wait for a user to complain if it needed.

The main one is the `--knee-method` given in the [1.0.0](https://zenodo.org/record/2565442) release, and this broke most of my tests

**Comment by mtekman** [comment]
thanks for fixing the wrapper versions

**Comment by bgruening** [comment]
Thanks for the fix!

**Pull request merged**
