### PR TITLE
snpEFF COVID-19 start ... this needs cleanups, but should work

### PR DESCRIPTION
**Pull request by bgruening**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
This tool is a fork of the real tool, just stripped down to only offer COVID-19 databases. This tool only supports Genomes shipped with the package, not *.loc file support, no history support.
@mvdbeek snpeff uses `NC_045512__.2__`. EU also uses this ID for the build-in genome which we have been built. Maybe it's wise to switch the ID in the workflow as well?

Todo:

* cleanup needed, many test files are not needed
* check help
* check if all params are still meaningful

**Comment by wm75** [comment]
I've removed a bunch of snpeff options that don't make sense for viral genomes and I adjusted the selectable upstream/downstream region lengths to small genome sizes.
One could probably remove a couple of other options, but I tried to catch the obvious ones.

**Comment by mvdbeek** [comment]
I'm a bit confused, do you mean the contig name with ID ? We've gone back and forth between `NC_045512` and `NC_045512.2`. `NC_045512.2` seemed more accurate but wasn't suported by snpsift in 4.3 :(

**Comment by wm75** [comment]
Yes, it's about the version ID in the contig name. This version of SnpEff ships with a *NC_045512.2* genome (with version ID). So for annotations to succeed, input VCFs need to use this contig name, too.
Didn't know about the SnpSift problem until now.

**Comment by mvdbeek** [comment]
I guess this was because the interal database was still generated as `NC_045512 `, so I assume it was fixed now ?

**Comment by mvdbeek** [comment]
```
--------------------------------------
| 2 - SnpEff eff: on data 1 (HID - NAME) 
| Dataset State:
|  error
| Dataset Blurb:
|  tool error
| Dataset Info:
|  cannot find 'spliceSiteSize'
| Peek:
|  *Peek unavilable.*
| Dataset Job Standard Output:
|  *Standard output was empty.*
| Dataset Job Standard Error:
|  *Standard error was empty.*
|
```

**Comment by wm75** [comment]
Ups, too courageous :)

**Comment by wm75** [comment]
> I guess this was because the internal database was still generated as `NC_045512 `, so I assume it was fixed now ?

So you're talking about Snp*Eff*, not Snp*Sift* failing?

**Comment by mvdbeek** [comment]
Possibly ...

**Comment by wm75** [comment]
Yes, then, this got fixed in SnpEff as part of the covid19 release, too.

**Comment by wm75** [comment]
I was just a bit worried that changing back to the contig name with version ID now, would create huge diffs somewhere in the covid19 project variant lists?

**Comment by mvdbeek** [comment]
It would ... and it means we need to redo everything starting with the mapping step. The alternative would be to just add a step where we add the `.2` to the VCF files.

**Comment by bgruening** [comment]
Is the tool id and toolshed name `snpeff_sars_cov_2` ok?

**Comment by wm75** [comment]
LGTM :)

**Comment by bgruening** [comment]
Thanks @wm75 and @mvdbeek!

**Pull request merged**
