### PR TITLE
Trinotate: fix wget dependency 

### PR DESCRIPTION
**Pull request by loraine-gueguen**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Fix https://github.com/galaxyproject/tools-iuc/issues/2508
Use conda-forge::wget instead of bioconda::gnu-wget. And update test data.

### CODE REVIEW

**Comment by loraine-gueguen** [comment]
I don't know why the tests always stop before the end on Travis (`No output has been received`). They pass with planemo on my local machine.

**Comment by bernt-matthias** [comment]
Ideally this should be added to the requirements of the conda recipe. 

I'm fine with the change, but please add to comment, such that we might remove the dependency in the future (if it found its way in the conda recipe).

**Comment by loraine-gueguen** [comment]
@bernt-matthias I have added wget in the trinotate conda recipe: https://github.com/bioconda/bioconda-recipes/pull/16651. So, I removed the requirement in the xml file.

**Comment by bernt-matthias** [comment]
Few points: 

- the test just takes "to long", on my system it was 45min. is there a way to possibly speed this up. It seems that the perl script called in the beginning needs most of the time.
- the tests failed because of differences with the created files (trinotate_annotation_report_minus_tmhmm_signalp.xls) .. maybe the reference data changed since yesterday?
- I'm wondering if `Build_Trinotate_Boilerplate_SQLite_db.pl Trinotate` (which seems to download a lot of data bases) is a case for a data manager (this also seems to need most of the time). Somehow it seems to make less sense if all these DBs are downloaded (etc) separately for each job compared to doing it once (or regularly) in a data manager. The actual tool could then work with a copy of the provided sqlite db.

**Comment by loraine-gueguen** [comment]
Thank you for having a look on it.
The tests should probably be changed to be less strict and not fail each time the dataset reference has changed.
I don't know data manager (and the trinotate tool) very well, but maybe it could be the best long-term solution. What do you think @lecorguille @abretaud  ?
Unfortunately I don't have time now (holiday) and I guess I will simply deactivate this tool version in Galaxy at the moment...

**Pull request closed without merging**
