### PR TITLE
increase speed by not converting as a separate command

### PR DESCRIPTION
**Pull request by astrovsky01**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
@astrovsky01 such big changes warrant a version bump I think - next time.

**Comment by astrovsky01** [comment]
@bgruening the only thing I did was to remove the double run on vcf. Outputs are identical. Imo, it should be more considered  more of a bug fix than a version update.

**Comment by wm75** [comment]
@astrovsky01 I guess @bgruening is right. Outputs may be identical or not, but you are executing a different command line. These kinds of "small" changes without version bumps are causing issues more regularly than one would think.

**Comment by astrovsky01** [comment]
@wm75 That's fair. Will version bump next time. If you'd prefer, we could roll back the version, then pr this with a version bump?

**Pull request merged**
