### PR TITLE
Correcting a bug on the fastqsanger.gz output datatype

### PR DESCRIPTION
**Pull request by tiagoantao**
There was a serious typo on my submission:
fastqsangergz -> fastqsanger.gz

This PR corrects it.

Thanks

### CODE REVIEW

**Comment by peterjc** [comment]
Cross reference planemo lint enhancement issue https://github.com/galaxyproject/planemo/issues/678

**Comment by peterjc** [comment]
+1 on merging once the automated tests have passed.

**Comment by peterjc** [comment]
Cross reference discussion on https://github.com/galaxyproject/tools-iuc/issues/1323

**Comment by peterjc** [comment]
Thanks Tiago

**Comment by abretaud** [comment]
👍  Thanks!

**Comment by tiagoantao** [comment]
@peterjc  Do you have any idea when this will appear on the toolshed? I thought that process was automated...

**Comment by peterjc** [comment]
I thought so to - @bgruening @martenson should we have bumped the tool version or something?

(If so that was my mistake not catching this in review)

**Comment by mvdbeek** [comment]
https://travis-ci.org/galaxyproject/tools-iuc/jobs/234634913 -- looks like the upload to the test toolshed failed, and then planemo exits with status code 1:
https://travis-ci.org/galaxyproject/tools-iuc/jobs/234634913

Does this means we can't upload anymore to the TTS for testing?

**Comment by nsoranzo** [comment]
@mvdbeek This is broken anyway e.g. if only a tool in a suite is updated: https://github.com/galaxyproject/planemo/issues/494

**Comment by tiagoantao** [comment]
Do you want me to bump any number and submit a PR? Please note that it was not only clone_filter but also procrad that had some changes (they share macros now).

**Comment by peterjc** [comment]
It sounds worth trying, and if it works is much easier than a semi-manual Tool Shed update (e.g. using Planemo by hand at the terminal).

**Comment by nsoranzo** [comment]
@tiagoantao I've manually updated `stacks_clonefilter` and `suite_stacks`, no need for artificial version bumps.

> Do you want me to bump any number and submit a PR? Please note that it was not only clone_filter but also procrad that had some changes (they share macros now).

Repository `stacks_procrad` was already updated on the main ToolShed on 2017-05-21.

Hopefully the automatic TS upload problem will be solved when https://github.com/galaxyproject/planemo/pull/680 is merged.

**Comment by tiagoantao** [comment]
@nsoranzo Please note that the version from the 21 is not the most up to date, but I think it will actually work (there was some refactoring to macros shared with clone_filter).

Thanks!

**Comment by tiagoantao** [comment]
@nsoranzo I have noticed that all the stacks tools (i.e. stacks_) are still from the 21. I think they also need to be updated.

**Comment by nsoranzo** [comment]
The only file modified after 2017-05-19 in https://github.com/galaxyproject/tools-iuc/tree/master/tools/stacks is `stacks_clonefilter.xml`

**Comment by tiagoantao** [comment]
@nsoranzo You are totally right, sorry.

**Pull request merged**
