### PR TITLE
post-merge RAxML updates

### PR DESCRIPTION
**Pull request by bgruening**
Followup to https://github.com/galaxyproject/tools-iuc/pull/372.

* address @nsoranzo and Bjoern's reviews
* style fixes
* move seed into advanced config

ping @tiagoantao @nsoranzo

### CODE REVIEW

**Comment by martenson** [comment]
thanks @bgruening !

**Comment by bgruening** [comment]
@martenson sure thing. planemo seems to be broken and causes test to fail.

**Comment by nsoranzo** [comment]
The are a few more variables of type `data` to quote in `<command>`: `$selExtraOpts.constraint_file`, `$selExtraOpts.bin_model_parameter_file`, `$selExtraOpts.secondary_structure_file`, `$selExtraOpts.start_tree_file` and `$selExtraOpts.file_multiple_trees`

**Comment by bgruening** [comment]
Done! Thanks :)

**Comment by nsoranzo** [comment]
Thanks @bgruening!

**Pull request merged**
