### PR TITLE
Bump mitos to latest versions

### PR DESCRIPTION
**Pull request by bernt-matthias**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@o-william-white could you have a look on this one?

**Comment by o-william-white** [comment]
Hi @bernt-matthias sure thing, just to make sure I understamd, do you want me to test that the latest version works as expected?

**Comment by bernt-matthias** [comment]
> do you want me to test that the latest version works as expected

I hope that the tests show that already :). I think its sufficient to check the changes.

**Review by o-william-white — APPROVED** [review]
Looks good 👍

**Comment by o-william-white** [comment]
> > do you want me to test that the latest version works as expected
> 
> I hope that the tests show that already :). I think its sufficient to check the changes.

Thanks for confirming, I checked and approved the changes. Is that what you needed?

**Review by bgruening — APPROVED** [review]

**Pull request merged**
