### PR TITLE
DiffBind:  Add option to output interval, bed or tabular in 0-based format

### PR DESCRIPTION
**Pull request by mblue9**
Changes made as per discussion here: https://github.com/galaxyproject/tools-iuc/pull/1819
ping @jennaj

### CODE REVIEW

**Comment by mblue9** [comment]
Travis keeps erroring here with:

`No output has been received in the last 20m0s, this potentially indicates a stalled build or something wrong with the build itself.`

I've tried closing and repening but it doesn't make a difference. What can I do about this?

**Comment by mblue9** [comment]
Now I can't get these tests to even run locally :( I updated to 18.05 latest commit `c9641e1f` and the tests get stuck on uploading the test files. Have tried a few times and always gets stuck now at this line `Flushed transaction for job`:

```'/private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpZICPW_/files/000/dataset_12.dat' '/private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpZICPW_/files/000/dataset_6.dat' 1 2 3 0 0]
2018-05-29 16:25:42,237 WARNI [galaxy.util.object_wrapper] Unable to create dynamic subclass for <class 'galaxy.util.none_like.NoneDataset'>, None: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
2018-05-29 16:25:42,932 INFO  [galaxy.tools.actions] Handled output named outfile for tool diffbind (693.739 ms)
2018-05-29 16:25:43,592 INFO  [galaxy.tools.actions] Handled output named plots for tool diffbind (659.363 ms)
2018-05-29 16:25:43,940 DEBUG [galaxy.tools.deps] Using dependency bcftools version 1.5 of type conda
2018-05-29 16:25:43,940 DEBUG [galaxy.tools.deps] Using dependency bcftools version 1.5 of type conda
2018-05-29 16:25:44,046 INFO  [galaxy.tools.actions] Handled output named binding_matrix for tool diffbind (453.575 ms)
2018-05-29 16:25:45,189 INFO  [galaxy.tools.actions] Handled output named rdata for tool diffbind (1142.821 ms)
2018-05-29 16:25:45,767 INFO  [galaxy.tools.actions] Handled output named rscript for tool diffbind (578.380 ms)
2018-05-29 16:25:46,457 INFO  [galaxy.tools.actions] Handled output named analysis_info for tool diffbind (689.076 ms)
2018-05-29 16:25:46,751 INFO  [galaxy.tools.actions] Added output datasets to history (294.312 ms)
2018-05-29 16:25:48,456 INFO  [galaxy.tools.actions] Verified access to datasets for Job[unflushed,tool_id=diffbind] (431.885 ms)
2018-05-29 16:25:48,458 INFO  [galaxy.tools.actions] Setup for job Job[unflushed,tool_id=diffbind] complete, ready to flush (1707.012 ms)
2018-05-29 16:25:48,813 INFO  [galaxy.tools.actions] Flushed transaction for job Job[id=13,tool_id=diffbind] (354.668 ms)```

**Comment by mblue9** [comment]
I figured out what the issue is with the tests here (Galaxy 18.05 is stricter than 18.01?)
The tests use bed.gz files e.g. in the xml tests there was:

`<param name="peaks" value="BT474_ER_1.bed.gz,BT474_ER_2.bed.gz"/>`

which worked fine previously with 18.01, but since updating to 18.05 the tests no longer work. On a hunch I added ftype="bed" to the tests and now the tests run again e.g. changing the line above to this fixes the stuck tests:
`<param name="peaks" ftype="bed" value="BT474_ER_1.bed.gz,BT474_ER_2.bed.gz"/>`

**Comment by bgruening** [comment]
Thanks @mblue9!
ping @jennaj

**Pull request merged**
