### PR TITLE
Archiving Tool [WIP]

### PR DESCRIPTION
**Pull request by erasche**
This PR is mostly meant for feedback and should **not** be merged as is due to sanitization. I need suggestions regarding the input sanitisation; I'd like to allow `.`s but disallow 2 or more `.`s in a row. Is this possible in the XML validator/sanitizer syntax? The tool is almost done and I'd really rather not re-write as a python wrapper as that seems like overkill.

## Rationale

This tool provides an interface to create archives, letting you add multiple files to configurable subdirectories within the produced archive.

I have two example use cases:

### Example 1: Workflow Outputs

Using something like Saskia's workflow report generator, one can imagine creating an archive with that as the `index.html` file, and adding in data like interpro results in an `interpro/` subdirectory. Maybe blast results would be added in a `blast/` directory, and so on. 

### Example 2: Circos

Circos takes a large, variable number of files to produce graphics. The best way I've found of handling this locally is to have tools produce a `.tgz` and provide a circos tool which will unpack + make graphics out of a given archive. (Internally this could, of course, be swapped out for an `$output.files_path/` approach).

In getting people to start using/developing for Circos in Galaxy, I wanted to 

1. Provide an easy tool which would take an archive of files that a user might upload (in lieu of installing the giant piece of software), making it an easy transition for end users
2. Re-use that provided circos tool *without modification*; by having this archive generator tool I can use existing workflows/tools (e.g. cut/join/select) to produce all of the files, archive them, and then send them to the plotter.

## Todo

- [ ] datatypes in Galaxy
- [ ] sanitization
- [ ] are hardlinks a problem?

## Notes

- Filed under "Data Source" as that's what `files_to_ftp` is filed under.

### CODE REVIEW

**Comment by peterjc** [comment]
Since you are asking for feedback, some of these useless seem to overlap with @jmchilton's work on collections.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/107/
Test (probably) passed

**Comment by blankenberg** [comment]
For the validator, you probably use something like:
 <validator type="expression" message="No two dots (..) allowed">'..' not in value</validator>

**Comment by erasche** [comment]
@blankenberg thanks!

**Comment by erasche** [comment]
@peterjc My understanding of dataset collections didn't include these sort of usecases, at least not where structured data folders were concerned (the circos case). I also wasn't aware of them for use in collecting workflow outputs for download (but that seems more like what they'd be used for).

**Comment by jmchilton** [comment]
Yeah - this tool seems to allow a degree of heterogeneity that I would discourage collection use for currently. I do reserve the right to compete with this tool at the framework level at some point though :).

**Comment by erasche** [comment]
@jmchilton sounds good :)

**Comment by bgruening** [comment]
Eric as @jmchilton pointed out I would also like to see this as part of a history. It should be a plugin like system with different ways to create reports. Such a report should also be included in a history download.

Regarding your circos tool can you explain a little bit more what you want to do. I once started a circos wrapper and I think was heavily using configfiles and *optional* user uploaded files. Happy to chat with you about that in more detail.

**Comment by erasche** [comment]
@bgruening a plugin system for creating reports... that would be nice yes (but outside the scope of this). Definitely would be useful. Heck, a simple `index.html` would be useful in the downloaded history archive.

As for circos, yes, it *heavily* uses config files, and lots of optional ones at that to add supplementary data/tracks to config files. I've got a circos package to provide the binary (Blocking on #77 & galaxyproject/docker-build#10).

Now I'm trying to provide an easy way to onboard users into using Circos in Galaxy. Asking users to "Upload a .tar.gz with your config files and run it here" is the best solution for that, lowest amount of effort, IMO[1], and their structured data on disk will retain the structure (usually an `etc/` and a `data/` folder)

- As a result of the above, the circos tool would already be accepting .tar.gzs with the data
- If there was an archive creation tool, that would permit users to:
  - generate all of the circos config data in a workflow
  - archive it
  - plot it

[1] The other option, as I see it, is to write the circos tool, using this tool's interface (repeat of multiple files + paths) and have the users upload their 10? 20? files to their history and do processing that way. More normal for Galaxy, but also more messy to manage all of those files. If that would be a preferable solution, and history downloads will include reports eventually, then great, I'll scrap this PR. 

I may yet be convinced that an archive tool really isn't needed, so, please, let me know your thoughts.

**Comment by bgruening** [comment]
@erasche just a crazy idea, before I try to search my old script: Let's create simple Django based webapp to make this more pleasant for the user. (I think I read something about a circos webserver or advanced UI, maybe this is already done) and use this as IE. Such kind of things fits perfectly as IE :)

**Comment by erasche** [comment]
@bgruening yes, definitely a good use case for an IE, but there is a LOT of configurability to encode. There's the basic "table plotter" but nothing very advanced just due to the wildly complex config that can be done. (I hope that if we can build an IE out of Circos with Django, then someday we'll be able to reduce that down to a tool I imagine.)

**Comment by erasche** [comment]
@blankenberg added your example [to the wiki](https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax#Example-10)

**Comment by erasche** [comment]
@blankenberg are things different in the new tool form? I can pass illegal values through. My tool XML looks like:

```xml
<param name="component" type="text" label="Path name">
  <validator type="expression" message="No two dots (..) allowed">'..' not in value</validator>
  <sanitizer>
    <valid initial="string.letters,string.digits">
      <add value="_-." />
    </valid>
  </sanitizer>
</param>
```

and in the logs I'm seeing:

```
galaxy.jobs.handler INFO 2015-04-08 12:58:31,083 (20) Job dispatched
galaxy.jobs.runners DEBUG 2015-04-08 12:58:32,429 (20) command is: mkdir build; mkdir -p build/asdf.afdsXasdfXhjgfv/XsdfXsdf-X/../..;  ln /tmp/galaxy-tmp/database/files/000/datase
t_15.dat "build/asdf.afdsXasdfXhjgfv/XsdfXsdf-X/../../Pasted Entry.txt";   tar cf /tmp/galaxy-tmp/database/files/000/dataset_20.dat -C build/ .; return_code=$?; python /tmp/galaxy
```

characters are being sanitized out, but no validation is occuring. Is validation *really* just validation, not server side validation before tool running?

**Comment by blankenberg** [comment]
There have been some reports of validation not validating lately. What Galaxy version are you using?

**Comment by jmchilton** [comment]
See also - https://github.com/jmchilton/galaxy/commit/0304c345f42efa680d2e3693c13fad7ba0c861ce

**Comment by erasche** [comment]
@blankenberg git dev branch from a couple days ago. @jmchilton looking forward to the PR :)

**Comment by bgruening** [comment]
Eric, please bear with me, this is 5 years old: https://github.com/bgruening/circos_galaxy_wrapper

Not sure this is useful at all, but this is how I imagined it years, years ago.

**Comment by erasche** [comment]
@bgruening looks like a lot of work went into that! I've always been afraid of trying to write such a tool as it's hard to capture how flexible circos is in galaxy xml :/ That's definitely a good start, I may pull that code into my circos branch at some point whenever I PR the package/tools here.

**Comment by bgruening** [comment]
Not sure this was ever working, it's to long ago. I'm not sure it's feasible to get all flexibility from circos mapped to a tool, but is this really necessary? Who are your users and do they want to have every single detail available?

**Comment by erasche** [comment]
@bgruening fair enough. I'd love to see a flexible tool in the package, but if that isn't an option, OK. My users aren't competent using circos; I'm hoping that the circos package will let other tool devs start using it and make use-case-specific tools instead.

**Pull request closed without merging**
