### PR TITLE
fsd+repmatch_gff3: use recent matplotlib

### PR DESCRIPTION
**Pull request by bernt-matthias**
old versions wer unsatisfiable by conda

Galaxy actually installed an `_uv_` environment in my local test. 

python (3?) should come automatically

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
anyone with numpy experience can help with the error?

**Comment by mvdbeek** [comment]
https://github.com/galaxyproject/tools-iuc/blob/master/tools/fsd/fsd.py#L28 is not a valid dtype, I suppose this should be `str`, as the only integer column is cast explicitly in https://github.com/galaxyproject/tools-iuc/blob/master/tools/fsd/fsd.py#L90

**Comment by bernt-matthias** [comment]
I give up on fsd. I do not understand how a tool with citation year 2019 (even if unpublished) is based on a horribly outdated matplotlib version. 

Maybe we should ask the tool authors?

**Comment by bernt-matthias** [comment]
For now I would suggest to remove the fsd parts from this PR?

**Comment by gregvonkuster** [comment]
I'm not familiar with the fsd tool, but I'm the author of the rematch_gff3 tool.  Sorry I'm coming into this late, but please me the know if I can help with that tool in any way.

**Comment by bernt-matthias** [comment]
Hey @gregvonkuster everything seems fine with rematch_gff3. Thanks. 

@NickSto can you help with the fsd python scripts?

**Pull request merged**
