### PR TITLE
Update the version of HTSeq to 0.6.1p1, which is also available in bi…

### PR DESCRIPTION
**Pull request by dpryan79**
…oconda. Note that the package name is then a bit funky (to match bioconda).

### CODE REVIEW

**Comment by dpryan79** [comment]
@lparsons: You can update your htseq-count wrapper once this is merged. BTW, it might be nice to just centralize that within the IUC repository.

@bgruening: This should be good to go.

**Comment by lparsons** [comment]
@dpryan79 Waiting for this to be pushed to main toolshed before I push the updated htseq_count package. Also, I'll submit a PR to merge this in the IUC repo.

**Comment by lparsons** [comment]
I've attempted to merge htseq-count with my fork of the IUC tools, but it seems Github won't let me create a Pull Request: `There isn’t anything to compare.
galaxyproject:master and lparsons:htseq-count are entirely different commit histories.`.

What I did was to first [split the htseq-count subdirectory into a new repo](https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/), and then perform a [subtree merge](https://help.github.com/articles/about-git-subtree-merges/).

I suspect it may just be easier for someone with commit access to do the [subtree merge](https://help.github.com/articles/about-git-subtree-merges/)? Unless someone has a better procedure.

**Comment by bgruening** [comment]
You want to preserve the history? I will try next week but can not promise that I will find enough time for it.

**Comment by lparsons** [comment]
@bgruening I had thought to try to preserve history (and I thought this would have worked, so no big deal). But if it's a pain, preservation of history is not necessary.

**Pull request merged**
