### PR TITLE
Correct 'cached' option for selecting ref. gen. in Mutect2

### PR DESCRIPTION
**Pull request by lgpdv**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by lgpdv** [comment]
Hi @bgruening, I have created a new PR with additional changes to make for this tool. They're related to the 'cached' option for a reference genome, that has been remarked by @drosofff, and also to include the input BAM files in the main wrapper file as suggested by @davebx.

**Comment by bgruening** [comment]
@lgpdv could you please add a test for the cached reference genome?

**Comment by lgpdv** [comment]
@bgruening Thank-you very much for reviewing the changes. I've just added the test for a cached reference genome.

**Comment by bgruening** [comment]
Awesome, thanks!

**Pull request merged**
