### PR TITLE
deseq2 conda

### PR DESCRIPTION
**Pull request by lecorguille**

### CODE REVIEW

**Comment by lecorguille** [comment]
Ping @bgruening @abretaud 😄

**Comment by lecorguille** [comment]
I guess the pull was not a good idea ... my bad!

**Comment by bgruening** [comment]
@lecorguille this needs a rebase?

**Comment by lecorguille** [comment]
Oh Boy!
Again 😭

**Comment by bgruening** [comment]
Why is this the case? Oh I see the blacklist file ... Let me know if you need help.

**Comment by nsoranzo** [comment]
@lecorguille Can you remove `tools/deseq2/tool_dependencies.xml` since this is now unused?

**Comment by lecorguille** [comment]
Done
Now I will try a rebase ...
⚠️ Everything can happen!

**Comment by nsoranzo** [comment]
@lecorguille Thanks for removing the file. I can easily merge on the command line later if your rebase doesn't succeed.

**Comment by lecorguille** [comment]
@nsoranzo I accept with pleasure
`git rebase --continue` asks me to launch `git rebase --continue` I'm lost!

**Comment by nsoranzo** [comment]
@lecorguille Done!

**Pull request merged**
