### PR TITLE
add new tool rpreport v5.13.1

### PR DESCRIPTION
**Pull request by kenza12**
Add new tool **rpreport** v5.13.1 : https://github.com/brsynth/rptools/tree/master/rptools/rpreport

Thank you

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by gallardoalba — APPROVED** [review]

**Review by gallardoalba — CHANGES_REQUESTED** [review]
This tool should be in the same folder as https://github.com/galaxyproject/tools-iuc/pull/4897, as part of a toolkit.

**Comment by kenza12** [comment]
> This tool should be in the same folder as #4897, as part of a toolkit.

rpreport is now integrated to rptools suite, as well as rpviz: https://github.com/galaxyproject/tools-iuc/pull/4931

**Comment by bgruening** [comment]
@kenza12 I am correct that this one can be closed correct? If not please reopen it.

**Comment by kenza12** [comment]
Yes @bgruening , it's already in the rptools suite. Thank you !

**Pull request closed without merging**
