### PR TITLE
Updating tools/vardict tool version(s)

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/vardict**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

Please see https://github.com/planemo-autoupdate/autoupdate for more information.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Would be better to change the test assumptions, eg allowing lines_diff or use assertions instead.

**Review by bgruening — APPROVED** [review]
Agreed, but this could be done later, maybe?

**Review by bernt-matthias — APPROVED** [review]
Seems odd that the VCF version is decreased and the tool version is increased in the test data.

**Comment by bgruening** [comment]
Indeed, maybe they reverted the VCF version.

**Pull request merged**
