### PR TITLE
[Add] more wrappers for ont_fast5_api

### PR DESCRIPTION
**Pull request by stephanflemming**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Github: https://github.com/nanoporetech/ont_fast5_api/
Conda: https://bioconda.github.io/recipes/ont-fast5-api/README.html
Recipe: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/ont-fast5-api/meta.yaml
(My) parameter overview: https://docs.google.com/spreadsheets/d/1HgMI_6dJVicpV8eG6tkxKrL7e-sgAzle4v8XCO_L-0k/edit?usp=sharing

ping @bgruening @mmiladi

### CODE REVIEW

**Comment by mmiladi** [comment]
@stephanflemming Could you please point out to the CI error log line, where it complains about vbz plugin?

**Comment by bgruening** [comment]
To reproduce locally just run planemo with `--docker`

**Comment by mmiladi** [comment]
I can't push to this branch.
Can you please add 
```
            <requirement type="package" version="1.32">tar</requirement>
```
to the requirements in macro and try again?

**Comment by bgruening** [comment]
Ǹope, I fixed that in conda. This will turn green in 30min.

**Comment by mmiladi** [comment]
With having the gnu-tar added as the requirement, everything seems to work fine.
The interfaces are also functional and work properly. So all good. Thanks much @stephanflemming

**Comment by mmiladi** [comment]
@bgruening I don't know the behind the scene, but the planemo serve --docker version, works fine now for me :)

**Comment by bgruening** [comment]
You need to use `planemo test --docker` to get the underlying error of an missing vbz library.

**Comment by stephanflemming** [comment]
The mentioned VBZ error appears in compress_fast5 and fast5_subset when using the values "vbz" or "vbz_legacy_v0" for the parameter --compression. I will comment them out.

**Comment by bgruening** [comment]
Merci!

**Pull request merged**
