### PR TITLE
fix typo spotted by Nicola and revert the test data

### PR DESCRIPTION
**Pull request by bgruening**
Thanks @nsoranzo! This explains a lot :)

### CODE REVIEW

**Comment by peterjc** [comment]
Is this basically reverting #591 due to the typo?

Is there a real problem here as per https://github.com/galaxyproject/galaxy/issues/1818 with setting the datatype on tool test inputs?

**Comment by bgruening** [comment]
There is still a real problem, as the tabular file is not recognised as such.

**Comment by nsoranzo** [comment]
@bgruening You mean without the ftype?

**Comment by bgruening** [comment]
Yes, without forcing the filetype it is recognised as `csv` which caused all the error of the original PR. `ftype` if spelled correctly should fix it and it fixes it.

**Pull request merged**
