### PR TITLE
Add version 4.11.0.0 of the fimo tool

### PR DESCRIPTION
**Pull request by martenson**
cherry-picked from and supersedes #493
ping @gregvonkuster @bgruening

### CODE REVIEW

**Comment by martenson** [comment]
Is it possible to make test data smaller @gregvonkuster? This PR has almost 32000 lines.

**Comment by gregvonkuster** [comment]
@martenson Hopefully I did this correctly here: https://github.com/gregvonkuster/tools-iuc/commit/2326056ae673bd61bdc563ffecb9cb20f3e04e13  Thanks!  ;)

**Comment by martenson** [comment]
@gregvonkuster thank you. This PR now needs another rebase to get rid of the big files in commits. I will do it as the last thing before merging so please notify me when this is ready if I miss it myself.

**Comment by bgruening** [comment]
:+1: go ahead @martenson  :)

**Comment by martenson** [comment]
I will do so.

**Pull request merged**
