### PR TITLE
Travis MTS push

### PR DESCRIPTION
**Pull request by bgruening**
xref: https://github.com/galaxyproject/tools-iuc/issues/765

### CODE REVIEW

**Comment by blankenberg** [comment]
+1 

Really nice to have this automated.

Although it might be better if we were using API keys, e.g. `--shed_key $TEST_SHED_KEY` and  `--shed_key $SHED_KEY` or `--shed_key_from_env TEST_SHED_KEY`... instead of having usernames and passwords in the environment. (But this is the same methodology as the TTS pushing.)

**Comment by bgruening** [comment]
@blankenberg what is the advantage of API-key over user/passwd? Let me know if I should change this or feel free to merge :)

**Comment by bgruening** [comment]
Thanks, let's try it!

**Comment by martenson** [comment]
@bgruening Among others you can force change the key, expire it and do other fancy stuff; also you help eliminate the risk of exposing other services with the same password if you lose it.

**Comment by blankenberg** [comment]
Biggest issue tends to be leaking shared passwords. In practicality, it probably doesn't matter much key vs pw, especially if there is never a leak.

One thing to consider, I guess, is whether you can change the password using the key, if not thats a bit better to prevent a leak causing an account lockout (although we can manually fix that in our case).

**Comment by martenson** [comment]
@blankenberg I believe we do not allow changing passwords with just API key in `user.py`, good point

**Comment by bgruening** [comment]
@martenson all points are equally true for passwords, especially if we use them correctly :)
I don't mind changing it to API-key. I find it more verbose with user/password especially if we consider this repo as blueprint for users that want to understand what we are doing.

So happy we have tests and automatic pushs now! Exciting!

**Comment by nsoranzo** [comment]
As mentioned in https://github.com/galaxyproject/tools-iuc/issues/765#issuecomment-220469244 we should update the README.

**Pull request merged**
