### PR TITLE
[randomBed] Fix for "cannot find 'seed' while searching for 'seed.seed'

### PR DESCRIPTION
**Pull request by scholtalbers**
<code>#if $seed.seed_choose:</code> vs <code>#if str($seed.seed_choose) == "True": </code>

Test-data may be off and for the random seed not useful.

### CODE REVIEW

**Comment by nsoranzo** [comment]
+1 (but I have not run the tests).

**Comment by bgruening** [comment]
This looks good to me, but the new test should be removed I guess.
I haven't tested it, but if you do not choose a seed the result will be different every time.

Instead you could write a test that checks if the file is not empty.

Thanks for fixing!

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by erasche** [comment]
please test this

**Comment by erasche** [comment]
jenkins: please test this

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by jj-umn** [comment]
On 2/18/15 9:42 AM, Eric Rasche wrote:
>
> Can one of the admins verify this patch?
>
> —
> Reply to this email directly or view it on GitHub <https://github.com/galaxyproject/tools-iuc/pull/34#issuecomment-74885715>.
>
This seems like a case for an assertion based test.
     <output name="output">
         <assert_contents>
             <has_text_matching expression="chr1" />
         </assert_contents>
     </output>

-- 
James E. Johnson Minnesota Supercomputing Institute University of Minnesota

**Comment by erasche** [comment]
@jj-umn sorry, that was jenkins auto-commenting on this issue. My apologies.

**Comment by bgruening** [comment]
@scholtalbers can you implement the assertion based test as @jj-umn pointed out.
`re_match_multiline` is not supposed to have the regex as part of the result file as far as I know.

**Comment by erasche** [comment]
jenkins: please test this

**Comment by erasche** [comment]
let's try that again, jenkins: test this please

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/33/
Test FAILed.

**Comment by erasche** [comment]
randomBed passed, merging.

**Pull request merged**
