### PR TITLE
trinity: update README to clarify specification of memory limit

### PR DESCRIPTION
**Pull request by pjbriggs**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

PR to address issue #2513 by updating the `README.rst` instructions for specifying the memory limits for the `trinity` tool (NB there are no functional changes to the tool in this PR).

### CODE REVIEW

**Comment by abretaud** [comment]
Maybe I'm wrong, but I think the `GALAXY_MEMORY_MB` env var is set automatically by Galaxy now depending on the destination config (e.g. if I write `--mem=50000` in `nativeSpecification` for a slurm destination), just as SLOTS.
I think it's only needed to add this var in job_conf.xml for running new trinity versions on an old galaxy server.
If I'm not wrong (not guaranteed! :D) it would be good to write it in the README too

**Comment by pjbriggs** [comment]
@abretaud if you can provide a link to relevant documentation or similar for the automatic setting of the `GALAXY_MEMORY_MB` that you describe then I'll look and update the README again.

**Comment by abretaud** [comment]
I think you can refer to https://planemo.readthedocs.io/en/latest/writing_advanced.html#cluster-usage and/or https://docs.galaxyproject.org/en/latest/admin/cluster.html#special-environment-variables-for-job-resources

**Comment by abretaud** [comment]
Getting some 500 errors from TTS during upload https://travis-ci.org/galaxyproject/tools-iuc/jobs/611261627
I restarted 2 or 3 times this morning, but still the same, any idea what's going on?

**Comment by bgruening** [comment]
TS was/is down. But I'm actually happy that this is not uploaded, it does not touch the tool isn't it?

**Comment by abretaud** [comment]
No change to the tools, just the readme, so no hurry I guess

**Pull request merged**
