### PR TITLE
Updating tools/nextclade from version 1.10.3 to 1.11.0

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/nextclade**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/nextclade from version 1.10.3 to 1.11.0.

**Project home page:** https://github.com/nextstrain/nextclade/releases

### CODE REVIEW

**Review by simonbray — APPROVED** [review]
There are some new features here, but doesn't seem like anything which necessitates a wrapper update: https://github.com/nextstrain/nextclade/releases/tag/1.11.0

**Review by bernt-matthias — APPROVED** [review]

**Comment by wm75** [comment]
Sorry, but this is not so simple. The additional column also needs to be considered in the header line that the tool can optionally generate. @pvanheus or me will open another PR for that soonish.

**Comment by bernt-matthias** [comment]
Thanks @wm75

**Comment by simonbray** [comment]
OK, sorry about that. I'll ping you next time.

**Comment by bernt-matthias** [comment]
How about adding yourself to https://github.com/galaxyproject/tools-iuc/blob/master/.github/CODEOWNERS for this tool?

**Comment by simonbray** [comment]
> How about adding yourself to https://github.com/galaxyproject/tools-iuc/blob/master/.github/CODEOWNERS for this tool?

As an alternative, you can also add yourself as maintainer in the .shed.yml file, e.g. https://github.com/galaxycomputationalchemistry/galaxy-tools-compchem/pull/125/files

Then the bot will ping you in the PR.

**Pull request merged**
