### PR TITLE
Sina2

### PR DESCRIPTION
**Pull request by stephanflemming**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

summary:
- add wrapper for SINA, a tool for reference based multiple sequence alignment

notes:
- project website: https://sina.readthedocs.io/en/latest/index.html
- github: https://github.com/epruesse/SINA
- uses *.ARB files, that are not available in Galaxy
- additional reference libraries can be included via tool-data/sina_references.loc.sample as described in README.md
- parameter overview can be found here https://docs.google.com/spreadsheets/d/1oTS6BSzhWPrNQH9KdtOcjBn34ddOA9QowIJx07dR6Sw/edit?usp=sharing

### CODE REVIEW

**Comment by bgruening** [comment]
@nsoranzo I guess this one also needs a new planemo release.

**Comment by bgruening** [comment]
@galaxyproject/iuc we assume this is due to a Galaxy bug. Can anyone run loc-file-based tests against 19.09?

**Comment by bgruening** [comment]
Failing against 19.09 because of the loc files and against 19.05 because of the missing `has_n_lines` functionally ...

**Comment by nsoranzo** [comment]
> Failing against 19.09 because of the loc files and against 19.05 because of the missing has_n_lines functionally ...

@bgruening The lint stage passes now with the new Planemo.

**Comment by bgruening** [comment]
Thanks! But the problem with 19.09 is a loc file issue. It works with 19.05 as far as I understood @stephanflemming

**Comment by stephanflemming** [comment]
> Thanks! But the problem with 19.09 is a loc file issue. It works with 19.05 as far as I understood @stephanflemming

Exactly.

**Comment by bgruening** [comment]
Cool, thanks @stephanflemming! Please add it to our server.

**Pull request merged**
