### PR TITLE
change @VERSION@ to @TOOL_VERSION@ in plotDexseq.xml

### PR DESCRIPTION
**Pull request by cat-bro**
The latest plotDexseq has version @VERSION@.1.

FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bernt-matthias — COMMENTED** [review]
Good catch. Unfortunately `@` is larger than numbers, or? Thus the wrong version will always be considered the newest one.

Can you double check and ask on the iuc gitter channel if the wrong version can be removed from the toolshed if I'm right?

**Comment by bgruening** [comment]
I guess in this case people need to deinstall this specific version from their server.

**Comment by cat-bro** [comment]
Galaxy considers the previous version (1.28.1.0) to be newer than @VERSION@.1

```
>>> import packaging.version
>>> packaging.version.parse('1.28.1.0') > packaging.version.parse('@VERSION@.1')
True
```

**Comment by bernt-matthias** [comment]
> Galaxy considers the previous version (1.28.1.0) to be newer than `@VERSION@.1`
> 
> ```
> >>> import packaging.version
> >>> packaging.version.parse('1.28.1.0') > packaging.version.parse('@VERSION@.1')
> True
> ```

Then it should be fine.

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
