### PR TITLE
Fix hmmer3 tests

### PR DESCRIPTION
**Pull request by mvdbeek**
Fails with segfault locally, but could be due to the limited CPU instruction set
on docker for mac ?

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek there is a 3.3 version out there https://anaconda.org/bioconda/hmmer/files

Maybe this fixes the segfault as well?

**Comment by mvdbeek** [comment]
Tried it and it does not fix the segfault.

**Comment by abretaud** [comment]
So do we merge even if it segfaults on mac?

**Comment by bgruening** [comment]
I'm in favor. We also have tools that skip OSX builds entirely - and I doubt that anyone runs Galaxy in production on OSX.

**Comment by mvdbeek** [comment]
Let's re-run the tests, otherwise LGTM

**Comment by bernt-matthias** [comment]
Guess this supersedes https://github.com/galaxyproject/tools-iuc/pull/2720

**Comment by mvdbeek** [comment]
We can also merge yours. Seems you didn't have to remove any test data, so maybe that's better ?

**Comment by bernt-matthias** [comment]
Upgraded to 3.3 in the other PR (and reported the segfault: https://github.com/EddyRivasLab/hmmer/issues/190) .. Will close this for now. Maybe you can merge the other if tests pass?

**Pull request closed without merging**
