### PR TITLE
Changed seqtk_sample's subsample fraction/number variable to float to allow decimals

### PR DESCRIPTION
**Pull request by markiskander**
To allow decimal value input for seqtk_sample, I changed the variable to a float. That's pretty much it.

Thanks!

### CODE REVIEW

**Comment by nsoranzo** [comment]
:+1:

**Comment by bgruening** [comment]
@markiskander @nsoranzo is it ok when I change the `value="100.0"`

**Comment by markiskander** [comment]
@bgruening either way I think it shows up as 100.0 in the wrapper anyway

**Comment by erasche** [comment]
:+1: from me as well.

**Pull request merged**
