### PR TITLE
Upgrade Anndata to 0.7.4

### PR DESCRIPTION
**Pull request by mtekman**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Fixes a bad read error on some of the newer anndata sets when inspecting them

ping @nomadscientist

### CODE REVIEW

**Comment by bgruening** [comment]
@mtekman error report is here: https://github.com/galaxyproject/tools-iuc/suites/1303160227/artifacts/20478161

**Comment by pcm32** [comment]
Great work @mtekman! Are you adding an AnnData 0.7.4 file as well for the tests or only testing with AnnData 0.6.x files?

**Comment by mtekman** [comment]
@pcm32 Thanks, I definitely do plan to add some 0.7.4 test cases but I'm still trying to get the existing cases to work ;-)

Do you have a history with some datasets that I could use? 

Also, I have given you push access to this repo, so feel free to fork / work on this too -- I have some other priorities this week sadly, so progress may be slower than intended

**Comment by mtekman** [comment]
Waiting on https://github.com/galaxyproject/galaxy/pull/10555 to be merged before this can go green

**Comment by bgruening** [comment]
Restarted the tests.

**Comment by bgruening** [comment]
> .. ERROR: Error 'HTTPSConnectionPool(host='linnarssonlab.org', port=443): Max retries exceeded with url: /loompy/_images/Loom_components.png (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f02043a1b10>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))' accessing https://linnarssonlab.org/loompy/_images/Loom_components.png

**Comment by mtekman** [comment]
@bgruening thanks for the patch, and this is a weird error.... why would it start throwing this only now?

**Comment by bgruening** [comment]
Do you have a link to this image somewhere? Then the link disappeared? We do check if links exist.

**Comment by mtekman** [comment]
https://github.com/galaxyproject/tools-iuc/pull/3237/checks?check_run_id=1343423716#step:12:2805

Screenshot_2020-11-02 Upgrade Anndata to 0 7 4 by mtekman · Pull Request #3237 · galaxyproject tools-iuc

**Comment by bernt-matthias** [comment]
Lets see if this is reproducible. I restarted the tests.

**Comment by mtekman** [comment]
I tend to find that I can only spot these errors if I keep the run tab open.

If I look for them later I cannot find them in the logs, nor the tool test output, nor the artefact output

**Comment by bgruening** [comment]
@mtekman can you please rebase against master.

**Review by mtekman — COMMENTED** [review]
Can this be merged soon?

**Comment by mtekman** [comment]
ping @bgruening

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks M!

**Pull request merged**
