### PR TITLE
Fix misnamed parameter. Remove multiple.

### PR DESCRIPTION
**Pull request by davebx**
Addresses #326

### CODE REVIEW

**Comment by erasche** [comment]
I feel like the reads_f,reads_r should support a paired collection, but the wrapper is fairly well out of my area of expertise. On the basis of the changes alone, it looks good.

**Comment by davebx** [comment]
@erasche Paired collections are supported by both `reads_[fr]` and `input_format.paired.reads.(forward|reverse)`

**Comment by mvdbeek** [comment]
Can I go ahead and upload it to the TTS? Is there any policy describing when to upload stuff after a merge?

**Comment by erasche** [comment]
@davebx neat!

@mvdbeek https://jenkins.galaxyproject.org/view/Tools/job/iuc-TTS-GH-update/ this job handles uploads to TTS automatically :) It'll be done soon.

**Comment by mvdbeek** [comment]
nice!

**Pull request merged**
