### PR TITLE
Initial version of XPath tool

### PR DESCRIPTION
**Pull request by erasche**
Allows querying XML files.

### CODE REVIEW

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/128/
Test (probably) passed

**Comment by bgruening** [comment]
+1

**Comment by erasche** [comment]
@jmchilton would it be possible to do some typo detection to planemo lininting? It took me quite a while to figure out d999f74 just because I wasn't seeing the typo.

**Comment by jmchilton** [comment]
@erasche Sure - we would get this for free with XSD validation - but until then and because I never want lxml to be an unconditionally required dependency - I have committed this  https://github.com/galaxyproject/planemo/commit/4f6102500a4e06f0d967dfc632af107cf98f1c82

**Comment by erasche** [comment]
@jmchilton thanks, that'll help. Yeah... I definitely want better XSDs. I'll try and make some more effort on those soon.

**Comment by jmchilton** [comment]
@erasche awesome, any help is appreciated  - I dropped some notes into galaxyproject/planemo#127. https://github.com/JeanFred/Galaxy-XSD has some really useful automated benchmarks to determine how complete the XSD he is working on is - making it a very easy to contribute to.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/130/
Test (probably) passed

**Comment by erasche** [comment]
http://gx.hx42.org/job/IUC-Github/130/Planemo_HTML_Reports/xpath.html okay, this would've passed if the dependencies were handled. Anyone have any other concerns?

**Comment by nsoranzo** [comment]
> https://github.com/JeanFred/Galaxy-XSD has some really useful automated benchmarks to determine how complete the XSD he is working on is - making it a very easy to contribute to.

@jmchilton Interesting! I think that repository should be moved under galaxyproject account or merged in some of its repositories at some point.

**Comment by bgruening** [comment]
LGTM, thanks Eric. Let me know if I do not change this on my own. Did not wanted to bother you with such small things.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/132/
Test (probably) passed

**Pull request merged**
