### PR TITLE
kraken: test fixes

### PR DESCRIPTION
**Pull request by bernt-matthias**
Does not fix the error for kraken.xml:

```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
time="2019-11-30T21:47:30Z" level=error msg="error waiting for container: context canceled"
```

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by mvdbeek** [comment]
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:346: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown.
> time="2019-11-30T21:47:30Z" level=error msg="error waiting for container: context canceled"

might be due to an old biocontainers image, recent images should have bash. We could try to upgrade to 1.1.1, it seems there were no major changes introduced: https://github.com/DerrickWood/kraken/releases

**Comment by mvdbeek** [comment]
I've bumped kraken to 1.1.1. Tests pass when not run in docker, but the data table data is symlinked to outside of the tool directory, which breaks when mounting the tool-data volume in docker.

**Comment by mvdbeek** [comment]
I've restructured the kraken directory and used the advanced .shed.yml features to separate the tools into separate repos. This does pass containerized testing now.

**Comment by bgruening** [comment]
@mvdbeek have you tested that against the TTS with the IUC account if everything is still ok?
I looks ok to me but I'm always worried with those changes to the shed.yml

**Comment by mvdbeek** [comment]
Yes, it's all there and looks correct, e..g https://testtoolshed.g2.bx.psu.edu/view/devteam/kraken_filter/6e690205b306

**Comment by bgruening** [comment]
Ok! Cool! Thanks so much!

**Pull request merged**
