### PR TITLE
Fix bam_to_scidx functional test and add Java source

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by bgruening** [comment]
@gregvonkuster if you want to have proper testing with conda dependencies. This means that planemo test runs for your tool, pelease remove this tool from the .tt_blacklist in the root dir.

**Comment by gregvonkuster** [comment]
@bgruening Done, thanks for letting me know this.  I'm still learning some of these new things!  ;)

**Comment by bgruening** [comment]
Let me know if you want to learn conda packing ...!

**Comment by gregvonkuster** [comment]
I've been following your work over on the conda stuff.  I'll hit you up in the next week or two for some of your expertise.  I'm trying to get my plate cleared a bit - its stacked high right now.  ;)

**Comment by bgruening** [comment]
Awesome! Greg look at the tests ... its beautiful! https://travis-ci.org/galaxyproject/tools-iuc/builds/117034182

**Comment by bgruening** [comment]
I will leave this open until someone else has commented on the Java Code case.

**Comment by bgruening** [comment]
Anyone?
@yhoogstrate, @mvdbeek, @peterjc?
@gregvonkuster can you rebase this PR please.

**Comment by gregvonkuster** [comment]
@bgruening Thanks for the ping on these.  I have been thinking about the Java source inclusion, and have had discussions with the lab here and we have decided that we will open a separate github repo to contain the source code.  So I'll request the lab to create this new repo today so I can point to it from the tool repos here, then I'll eliminate the Java source from here.  I'll try to get this done today.

**Comment by gregvonkuster** [comment]
@bgruening I'm not quite sure how to rebase this PR.  Can you help?  Thanks!

**Comment by yhoogstrate** [comment]
This rebase has only one conflict so it shoudn't be too hard and a good practice. If you have broken your branch you could rename or delete it (git branch -D ...), check the one from github out again, git rebase master, modify .tt_blackist, git add, git commit, git merge galaxy-project/master and you should be fine. If you still don't succeed: https://github.com/yhoogstrate/tools-iuc/tree/bam_to_scidx

**Comment by gregvonkuster** [comment]
Closing, replacing with of https://github.com/galaxyproject/tools-iuc/pull/722

**Pull request closed without merging**
