### PR TITLE
Add bgzip/tabix

### PR DESCRIPTION
**Pull request by erasche**
@nsoranzo you mind testing? I don't have anything that isn't linux x86_64 so can't trigger that part of the installation recipe.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Me neither, sorry, but LGTM.

What about the file in depot.galaxyproject.org ?

**Comment by erasche** [comment]
That's an issue for docker-build. Will open shortly.

**Comment by erasche** [comment]
See galaxyproject/docker-build#20

**Comment by nsoranzo** [comment]
@erasche Thanks!

**Comment by erasche** [comment]
@lparsons @nsoranzo would either of you object to removing the docker-build option until a later date when someone writes the recipe for building samtools1.2 in docker-build?

**Comment by lparsons** [comment]
No objection from me @erasche.

**Comment by nsoranzo** [comment]
@erasche I don't mind either way.

**Comment by erasche** [comment]
Okay, removed depot DL, passes `shed_lint`, going to merge and push to TTS

**Comment by erasche** [comment]
On TTS, someone please test if you can to make sure I didn't screw anything up too terribly, and ping me and we can push to MTS

**Comment by lparsons** [comment]
@erasche I've installed package_samtools_1_2 from the testttoolshed, but I don't see where I would get bgzip or tabix from. They are not included in the depot binary and they are not installed via the source compile installation. Am I missing something?

**Comment by erasche** [comment]
@lparsons hah, okay, that's my fault. The automated TTS uploader overwrote the version I pushed manually.

https://testtoolshed.g2.bx.psu.edu/repos/iuc/package_samtools_1_2 (see top two commits there)

**Comment by erasche** [comment]
I've disabled the TTS pusher and re-pushed samtools if you wouldn't mind trying again. So sorry....

**Comment by lparsons** [comment]
Thanks @erasche, I did try again, but unfortunately ran into this:



    bam_tview_curses.c:30:20: fatal error: curses.h: No such file or directory
     #include <curses.h>
                        ^
    compilation terminated.
    make: *** [bam_tview_curses.o] Error 1
    tool_shed.galaxy_install.install_manager ERROR 2015-06-29 20:29:12,388 Error installing tool dependency samtools version 1.2.
    Traceback (most recent call last):
      File "lib/tool_shed/galaxy_install/install_manager.py", line 142, in install_and_build_package_via_fabric
        tool_dependency = self.install_and_build_package( tool_shed_repository, tool_dependency, actions_dict )
      File "lib/tool_shed/galaxy_install/install_manager.py", line 127, in install_and_build_package
        initial_download=False )
      File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/recipe_manager.py", line 32, in execute_step
        initial_download=initial_download )
      File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py", line 1737, in execute_step
        return_output=False )
      File "lib/tool_shed/galaxy_install/tool_dependencies/recipe/install_environment.py", line 146, in handle_command
        context.flush()
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/scoping.py", line 150, in do
        return getattr(self.registry(), name)(*args, **kwargs)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/session.py", line 2004, in flush
        self._flush(objects)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/session.py", line 2122, in _flush
        transaction.rollback(_capture_exception=True)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/util/langhelpers.py", line 60, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/session.py", line 2086, in _flush
        flush_context.execute()
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/unitofwork.py", line 373, in execute
        rec.execute(self)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/unitofwork.py", line 532, in execute
        uow
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/persistence.py", line 170, in save_obj
        mapper, table, update)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/orm/persistence.py", line 673, in _emit_update_statements
        execute(statement, multiparams)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 914, in execute
        return meth(self, multiparams, params)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
        return connection._execute_clauseelement(self, multiparams, params)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
        compiled_sql, distilled_params
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1146, in _execute_context
        context)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1335, in _handle_dbapi_exception
        util.reraise(*exc_info)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/base.py", line 1139, in _execute_context
        context)
      File "/galaxy-central/eggs/SQLAlchemy-1.0.1-py2.7-linux-x86_64-ucs4.egg/sqlalchemy/engine/default.py", line 442, in do_execute
        cursor.execute(statement, parameters)

    'ascii' codec can't encode character u'\u2018' in position 28: ordinal not in range(128)

**Comment by nsoranzo** [comment]
@lparsons Is iuc's `package_ncurses_5_9` installed correctly?

**Comment by lparsons** [comment]
@nsoranzo It appears to have been installed correctly. I don't see any red flags at least. A few warnings, but ultimately ended in apparent success. Looks like samtools just isn't finding it when building. I know there are a few sed lines to change curses to ncurses in the makefile...  And `curses.h` is in the `include/ncurses` directory after the install.

```
STDERR
/usr/bin/ld: total time in link: 0.050000
/usr/bin/ld: data size 6270976
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
make[1]: [/galaxy-central/tool_deps/ncurses/5.9/iuc/package_ncurses_5_9/387c0609c0b7/lib/libncurses.so.5.9] Error 1 (ignored)
/usr/bin/ld: total time in link: 0.030000
/usr/bin/ld: data size 3997696
/usr/bin/ld: total time in link: 0.020000
/usr/bin/ld: data size 3997696
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
make[1]: [/galaxy-central/tool_deps/ncurses/5.9/iuc/package_ncurses_5_9/387c0609c0b7/lib/libpanel.so.5.9] Error 1 (ignored)
/usr/bin/ld: total time in link: 0.030000
/usr/bin/ld: data size 4177920
/usr/bin/ld: total time in link: 0.040000
/usr/bin/ld: data size 4177920
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
make[1]: [/galaxy-central/tool_deps/ncurses/5.9/iuc/package_ncurses_5_9/387c0609c0b7/lib/libmenu.so.5.9] Error 1 (ignored)
/usr/bin/ld: total time in link: 0.030000
/usr/bin/ld: data size 4399104
/usr/bin/ld: total time in link: 0.030000
/usr/bin/ld: data size 4399104
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
make[1]: [/galaxy-central/tool_deps/ncurses/5.9/iuc/package_ncurses_5_9/387c0609c0b7/lib/libform.so.5.9] Error 1 (ignored)
1600 entries written to /export/galaxy-central/tool_deps/ncurses/5.9/iuc/package_ncurses_5_9/387c0609c0b7/share/terminfo
```

**Comment by yhoogstrate** [comment]
Just out of curiosity, why is tabix and bgzip part of package_samtools? Would it not make sense to put them in a separate package like package_htslib ? (I saw @bgruening has package_htslib_1_2_1 in the testtoolshed)

**Comment by nsoranzo** [comment]
@yhoogstrate It's mainly for historical reasons, they were originally in the samtools 0.x packages. Also, htslib is not that useful per se. See #146.

**Comment by nsoranzo** [comment]
@erasche @lparsons I've updated the PR to use the binary tgz kindly prepared by @natefoo.

**Comment by erasche** [comment]
@nsoranzo awesome. :)

**Pull request merged**
