### PR TITLE
iqtree: handle '+' character in custom models

### LINKED ISSUE #2834: iqtree: '+' char not handled in custom models
When running `iqtree`, models are combined using a `+` character, such as `GTR+G`:

http://www.iqtree.org/doc/Substitution-Models

...But when a model such as `GTR+G` is entered via the galaxy tool, it results in a command-line like this:
```
iqtree [parameters omitted for brevity] -m 'GTRXG'
```

...and the following message on stderr:

```
ERROR: Invalid model name GTRXG
```

### PR DESCRIPTION
**Pull request by dfornika**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Fixes #2834

### CODE REVIEW

**Comment by dfornika** [comment]
@wm75, ah that might be a cleaner solution (although some of those characters aren't used in the model specifications). I did notice that the model param seems to be the only one that doesn't use the `sanitize_query` macro.

**Comment by dfornika** [comment]
I think this might be ready to merge(?)

**Comment by mvdbeek** [comment]
Isn't it a problem that you're adding `'` as an allowed character ?

**Comment by dfornika** [comment]
@mvdbeek I believe that's removed in the `sanitize_query` macro? Unless I'm misunderstanding how it works.

https://github.com/galaxyproject/tools-iuc/blob/ea9a67b5711b53fb911a0c50b6b49eb9db2366a7/tools/iqtree/iqtree_macros.xml#L10-L18

**Comment by wm75** [comment]
Almost - this macro quotes the single quotes to turn them into literal quotes for the shell :smile:

**Comment by wm75** [comment]
Thanks @dfornika!

**Comment by mvdbeek** [comment]
The macro looks so close to the sanitizer I thought I was looking at the sanitizer!

**Pull request merged**
