### PR TITLE
Stringtie 1.3.3

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@MoHeydarian I would appreciate a review here. This tools in combination with DESeq2 could replace the cufflinks pipeline and would make a nice tutorial of reference-less RNAseq.

**Comment by MoHeydarian** [comment]
This looks great, thanks for doing this!

Yes, the new prepDE feature of Stringtie 1.3.3 will simplify a few RNA-seq pipelines and we'll definitely add this feature to the de novo RNAseq tutorial.

**Comment by nekrut** [comment]
:+1: not sure why test 5 is failing though

**Comment by bgruening** [comment]
@MoHeydarian @nekrut a review is appreciated. I haven't tested it with real data.

**Comment by bgruening** [comment]
It's green!

**Comment by bgruening** [comment]
Anyone ready for merging?

**Comment by bgruening** [comment]
ping @galaxyproject/iuc

**Pull request merged**
