### PR TITLE
multiqc: plot output seems only available with --flat

### PR DESCRIPTION
**Pull request by bernt-matthias**
fixes https://github.com/galaxyproject/tools-iuc/issues/3301

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
I have also this on my todo list: `Module 'samtools: 'This file was produced by samtools stats' not found in the file 'ERR4707731'` to fix in multiqc. Especially with a large collection with 4000 files multiqc fails as soon as "one" (?) file is empty?

**Comment by bernt-matthias** [comment]
> I have also this on my todo list: Module 'samtools: 'This file was produced by samtools stats' not found in the file 'ERR4707731' to fix in multiqc. Especially with a large collection with 4000 files multiqc fails as soon as "one" (?) file is empty?

Maybe open an issue for this. I would like to leave it as is for now ..

**Comment by mblue9** [comment]
Oh great @bernt-matthias ! I’ve just had a quick look & seems good but I can test tomorrow.

**Review by bgruening — APPROVED** [review]

**Comment by mblue9** [comment]
@bernt-matthias took me a bit longer to check you PR. It was good, I was just going to suggest making the plots raw data a selectable output (and updating to v 1.9) so I did that here https://github.com/galaxyproject/tools-iuc/pull/3324
Also v1.8 was always outputting a Stats file (wrongly) here for qualimap_bamqc_genome_results but updating to v1.9 fixes that.

**Pull request merged**
