### PR TITLE
Bwameth datamanager

### PR DESCRIPTION
**Pull request by dpryan79**
…es data table to include dbkey

@bgruening: I took a stab at making a data manager for bwameth. I have a copy in the testtoolshed that seems to work, but it's unclear to me what's "best practice" for these things. For whatever it's worth, I largely copied the hisat2 data manager.

Note that this also adds a `dbkey` column to the bwameth_indexes table. That seems to be more conformant with what hisat2 and other tools are doing.

### CODE REVIEW

**Comment by bgruening** [comment]
@blankenberg can you please look at this? 
Dan Is there any way we can test data managers with planemo?

**Comment by bgruening** [comment]
@dpryan79 your yaml file is not properly formatted. It the description is not correctly intended.

**Comment by dpryan79** [comment]
@bgruening Thanks, that's fixed now.

**Comment by bgruening** [comment]
@galaxyproject/iuc anyone? I think this one is ready to go.

**Comment by bgruening** [comment]
Thanks a lot @dpryan79!!!

**Pull request merged**
