### PR TITLE
Update URL with soon-to-be-live bioaRchive host

### PR DESCRIPTION
**Pull request by erasche**
Host is not live yet, please do not merge.

### CODE REVIEW

**Comment by bgruening** [comment]
I tried a few and they are working now. Ready for merging?

**Comment by erasche** [comment]
@bgruening yep, ready for merging. @nitesh1989 and I finished the move from s3 to galaxyproject.org last night.

**Comment by bgruening** [comment]
Thanks!

**Comment by martenson** [comment]
goodjob guys; thanks for moving it

**Pull request merged**
