### PR TITLE
pangolin tool (forked from jpalmer37 PR)

### PR DESCRIPTION
**Pull request by pvanheus**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by pvanheus** [comment]
This tool takes the work started in https://github.com/galaxyproject/tools-iuc/pull/3519 and corrects some bugs.

**Comment by bwlang** [comment]
@bgruening  I can take a quick pass at tsv conversion with csvtk. I'm curious -  what's wrong with the csv?  Is it just harder to use in galaxy downstream tools?  Worth keeping csv too in case people want that for other tools?

**Comment by bgruening** [comment]
> Is it just harder to use in galaxy downstream tools? 

That. We at some point took the decision to go with `tabular`. We could use csv, but what people than need to do is to convert csv to tabular before using all our 100 of table manipulation tool.

**Comment by pvanheus** [comment]
> > Is it just harder to use in galaxy downstream tools?
> 
> That. We at some point took the decision to go with `tabular`. We could use csv, but what people than need to do is to convert csv to tabular before using all our 100 of table manipulation tool.

I've adjusted the tool to convert to `tabular`

**Review by bwlang — APPROVED** [review]

**Review by bwlang — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Merci!

**Pull request merged**
