### PR TITLE
Fix xsd and requirement version linter errors

### PR DESCRIPTION
**Pull request by bernt-matthias**
FOR CONTRIBUTOR:
* [ ] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
For the XSD error we would need new packages: https://github.com/galaxyproject/galaxy/pull/18605. Is it worth to create some, or wait for 24.2?

**Comment by mvdbeek** [comment]
There's zero cost to more packages. Do you want to try this again or should I do it ?

**Comment by bernt-matthias** [comment]
Let me try :)

**Comment by bernt-matthias** [comment]
Cool. This worked now (after resetting the pip cache).

**Review by mvdbeek — APPROVED** [review]

**Pull request merged**
