### PR TITLE
Comment change to intervene pairwise

### PR DESCRIPTION
**Pull request by heylf**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by heylf** [comment]
This comment is relevant, because the tool runs into an error if the filenames have spaces. The error is a bit unclear and users are confused about it.

**Comment by bgruening** [comment]
@heylf do you have a reproducible case of that? Can you look at the commandline? In theory, we remove whitespaces with https://github.com/heylf/tools-iuc/blob/intervene_update/tools/intervene/macros.xml#L34 from the filenames.

**Comment by heylf** [comment]
@bgruening yes here is a history: https://usegalaxy.eu/u/heylf/h/intervene-test
You have two runs with intervene, once files names without space, and once with spaces. The call with spaces produces an error.

**Comment by bgruening** [comment]
Upps, I do not have access to the history. I think the proper way to address that is to add a test with a space in the element identifier and see how this fails and ultimately fix https://github.com/heylf/tools-iuc/blob/intervene_update/tools/intervene/macros.xml#L34 to make the test pass.

**Review by bernt-matthias — COMMENTED** [review]
I can reproduce the error with spaces .. seems to be a downstream problem. 

One should do the following:

1. rename one of the test files such that it contains a space. 
2. Add the following after computing the labels

```
#for $label, $file in zip($labels, $input)
    ln -s '$file' `$label` &&
#end for
```

and replace

`--input #echo " ".join(["'%s'" % file for file in $input])` by `--input #echo " ".join(["'%s'" % label for label in $labels])`

**Pull request closed without merging**
