### PR TITLE
Add kraken 0.10.5

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by bgruening** [comment]
Dave, does it make sense to commit a beta version? It the stable version far away?
No backup build if Galaxy is not running on Linux?

**Comment by davebx** [comment]
Apparently install_kraken.sh compiles and copies the binaries. Unconventional, but that's how they wrote it.

As for when a release will be out, I'm not sure, but I can ask the author.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/92/
Test (probably) passed

**Comment by davebx** [comment]
According to the author, the stable release should be around the end of summer, but the code is nominally stable now. If preferable, I'm happy to maintain this under my own account and put it up for adoption by the IUC when the stable release is out.

**Comment by bgruening** [comment]
@davebx I think this is ok if the next release will take so long. The next release will get a new package definition with a new version number, correct? Or is it better to put the beta into the package name?

**Comment by davebx** [comment]
My understanding is that he'll increment the version number for upcoming releases, so we should be good to go.

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
