### PR TITLE
Update InterProScan to 5.59-91.0

### PR DESCRIPTION
**Pull request by abretaud**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Here's the interproscan update following https://github.com/bioconda/bioconda-recipes/pull/38043
I had to update the DM too as the data indexing script has a new name in this version, and is not indexing exactly the same way as in previous versions.

I hope we won't get too much surprises with this update :crossed_fingers: 

ping @pvanheus

### CODE REVIEW

**Comment by abretaud** [comment]
Ah, green!
Do we merge or do you prefer to wait @bgruening ? Because you (or someone on .eu) will need to run the DM (new version) + do [manual stuff](https://github.com/galaxyproject/tools-iuc/blob/master/tools/interproscan/README.md#installing-licensed-components-manually) after the auto-update on .eu

**Comment by bgruening** [comment]
We can merge, and I will run the DM and ask you for help if something happens ;)

**Review by bgruening — APPROVED** [review]

**Comment by abretaud** [comment]
I've installed the new version galaxy.genouest.org and *everything* worked perfectly. It's the Christmas miracle probably :tada:

**Comment by bgruening** [comment]
:santa:

**Pull request merged**
