### PR TITLE
Condafy gemini tools and update to version 0.20.0

### PR DESCRIPTION
**Pull request by gregvonkuster**
Second part of handling this issue: https://github.com/galaxyproject/tools-iuc/issues/1130

### CODE REVIEW

**Comment by bgruening** [comment]
@gregvonkuster do you have time to create a few tests for this. Upstream has some slime databases that can be used as far as I recall.

**Comment by gregvonkuster** [comment]
Each of the tools has at least 1 functional test.  Are you looking for additional tests or something else?  Where are the slime databases, and how do they get used in tests for these tools?

**Comment by bgruening** [comment]
I have removed the tools from the blacklist, let's see what travis says. I expect a few failing tests due to the version change.

**Comment by gregvonkuster** [comment]
Ok, I'll take a look at anything that ends up broken.

**Comment by gregvonkuster** [comment]
@bgruening do you know about these tools, and how the gemini sqlite database test files were created?  
I've started looking at the first broken test, and am getting this error.
```
======================================================================
ERROR: GEMINI actionable_mutations ( gemini_actionable_mutations ) > Test-1
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/greg/work/git_workspace/galaxy/test/functional/test_toolbox.py", line 302, in test_tool
    self.do_it( td )
  File "/home/greg/work/git_workspace/galaxy/test/functional/test_toolbox.py", line 63, in do_it
    raise e
RunToolException: Error creating a job for these tool inputs - This version of Gemini will only work with Gemini files that are for version 0.19.1.
```
I know nothing about gemini, so will have to spend some time trying to figure this out.  :(

**Comment by gregvonkuster** [comment]
Looks like the database files were discussed here https://github.com/galaxyproject/tools-iuc/pull/10.

**Comment by bgruening** [comment]
@gregvonkuster a new database can be created with gemini-load. Problem here is you need to have this 50GB annotation data before.

**Comment by bgruening** [comment]
But my ideas was to reuse these scripts and files for our tests if possible: https://github.com/arq5x/gemini/blob/master/test/data-setup.sh

https://github.com/arq5x/gemini/tree/master/test

**Comment by gregvonkuster** [comment]
Ok, I see the VCF files there.  I'll take a look at this and see if I can make it work.  Thanks!

**Comment by gregvonkuster** [comment]
Currently waiting on this issue: https://github.com/arq5x/gemini/pull/832

**Comment by gregvonkuster** [comment]
@bgruening Another potential problem is that gemini will not install with miniconda3:
```
$ which conda
~/miniconda3/bin/conda
[greg@bigsky ~]$ conda --version
conda 4.3.14
[greg@bigsky ~]$ conda search gemini
Fetching package metadata .................
gemini                       0.17.3dev0               py27_1  bioconda        
                             0.17.3dev0               py27_2  bioconda        
                             0.17.3dev1               py27_3  bioconda        
                             0.17.3dev1               py27_4  bioconda        
                             0.18a                    py27_4  bioconda        
                             0.18.0                   py27_4  bioconda        
                             0.18.0                   py27_5  bioconda        
                             0.18.0                   py27_6  bioconda        
                             0.18.0                   py27_7  bioconda        
                             0.18.0                   py27_8  bioconda        
                             0.18.1                   py27_1  bioconda        
                             0.18.1                   py27_2  bioconda        
                             0.18.1                   py27_3  bioconda        
                             0.18.2                   py27_1  bioconda        
                             0.18.3                   py27_1  bioconda        
                             0.19.0                   py27_0  bioconda        
                             0.19.1                   py27_0  bioconda        
                             0.19.1                   py27_1  bioconda        
                             0.19.1                   py27_2  bioconda        
                             0.19.1                   py27_3  bioconda        
                             0.19.2a                  py27_0  bioconda        
                             0.19.2a                  py27_1  bioconda        
                             0.19.2a                  py27_2  bioconda        
[greg@bigsky ~]$ conda install gemini
Fetching package metadata .................
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - gemini -> bx-python -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```
It works with miniconda2.  Do you see this as a problem?

**Comment by bgruening** [comment]
There is no python3 version of this package. If you include python==3.5.3 it should work.

**Comment by gregvonkuster** [comment]
Hmm...another issue?  Miniconda2 installs gemini 0.20.0 even though it is not found when searching the Galaxy-standard channels...
```
$ which conda
~/miniconda2/bin/conda
```
```
$ conda search gemini
Fetching package metadata .................
gemini                       0.17.3dev0               py27_1  bioconda        
                             0.17.3dev0               py27_2  bioconda        
                             0.17.3dev1               py27_3  bioconda        
                             0.17.3dev1               py27_4  bioconda        
                             0.18a                    py27_4  bioconda        
                             0.18.0                   py27_4  bioconda        
                             0.18.0                   py27_5  bioconda        
                             0.18.0                   py27_6  bioconda        
                             0.18.0                   py27_7  bioconda        
                             0.18.0                   py27_8  bioconda        
                             0.18.1                   py27_1  bioconda        
                             0.18.1                   py27_2  bioconda        
                             0.18.1                   py27_3  bioconda        
                             0.18.2                   py27_1  bioconda        
                             0.18.3                   py27_1  bioconda        
                             0.19.0                   py27_0  bioconda        
                             0.19.1                   py27_0  bioconda        
                             0.19.1                   py27_1  bioconda        
                             0.19.1                   py27_2  bioconda        
                             0.19.1                   py27_3  bioconda        
                             0.19.2a                  py27_0  bioconda        
                             0.19.2a                  py27_1  bioconda        
                             0.19.2a                  py27_2  bioconda
```
```
$ conda install gemini
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/greg/miniconda2:

The following NEW packages will be INSTALLED:

<some logging deleted...>

gemini-0.19.2a 100% |#######################################################################################################| Time: 0:00:00  15.01 MB/s
$ which gemini
~/miniconda2/bin/gemini
$ gemini --version
gemini 0.20.0
```

**Comment by gregvonkuster** [comment]
Still cannot install with miniconda3:
```
$ which conda
~/miniconda3/bin/conda

[greg@bigsky ~]$ conda install gemini python==3.5.3
Fetching package metadata .................
Solving package specifications: .


UnsatisfiableError: The following specifications were found to be in conflict:
  - gemini -> bx-python -> python 2.7*
  - python ==3.5.3
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by mvdbeek** [comment]
that may be a bug that has been fixed in newer minicondas (here I'm using miniconda3):
```
mvandenb@u934-bdd-4-89-6580:~ $ conda --version
conda 4.3.14
mvandenb@u934-bdd-4-89-6580:~ $ python --version
Python 3.5.3
mvandenb@u934-bdd-4-89-6580:~ $ conda create -n gemini gemini
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/mvandenb/miniconda3/envs/gemini:

The following NEW packages will be INSTALLED:

    appnope:                0.1.0-py27_0
    backports:              1.0-py27_0
    backports_abc:          0.5-py27_0
    bcftools:               1.3.1-1            bioconda
    bcolz:                  1.0.0-py27_0
    bottle:                 0.12.9-py27_0      bioconda
    bx-python:              0.7.3-py27_0       bioconda
    curl:                   7.52.1-0
    cycler:                 0.10.0-py27_0
    cyordereddict:          0.2.2-py27_0       bioconda
    cython:                 0.25.2-py27_0
    cyvcf2:                 0.7.2-py27_0       bioconda
    decorator:              4.0.11-py27_0
    enum34:                 1.1.6-py27_0
    et_xmlfile:             1.0.1-py27_0
    freetype:               2.5.5-2
    functools32:            3.2.3.2-py27_0
    futures:                3.0.5-py27_0
    gemini:                 0.19.2a-py27_2     bioconda
    geneimpacts:            0.3.1-py27_0       bioconda
    get_terminal_size:      1.0.0-py27_0
    grabix:                 0.1.8-1            bioconda
    htslib:                 1.3.2-0            bioconda
    icu:                    54.1-0
    inheritance:            0.1.2-py27_0       bioconda
    ipykernel:              4.5.2-py27_0
    ipyparallel:            6.0.2-py27_0
    ipython:                5.3.0-py27_0
    ipython-cluster-helper: 0.5.1-py27_0       bioconda
    ipython_genutils:       0.1.0-py27_0
    jdcal:                  1.3-py27_0
    jinja2:                 2.9.5-py27_0
    jupyter_client:         5.0.0-py27_0
    jupyter_core:           4.3.0-py27_0
    libgcc:                 4.8.5-1
    libpng:                 1.6.27-0
    markupsafe:             0.23-py27_2
    matplotlib:             2.0.0-np112py27_0
    mkl:                    2017.0.1-0
    netifaces:              0.10.4-py27_1      bioconda
    networkx:               1.11-py27_0
    numexpr:                2.6.2-np112py27_0
    numpy:                  1.12.0-py27_0
    openpyxl:               2.4.0-py27_0       bioconda
    openssl:                1.0.2k-1
    pandas:                 0.19.2-np112py27_1
    path.py:                10.1-py27_0
    pathlib2:               2.2.0-py27_0
    pexpect:                4.2.1-py27_0
    pickleshare:            0.7.4-py27_0
    pip:                    9.0.1-py27_1
    prompt_toolkit:         1.0.13-py27_0
    ptyprocess:             0.5.1-py27_0
    pybedtools:             0.7.9-py27_0       bioconda
    pygments:               2.2.0-py27_0
    pyparsing:              2.1.4-py27_0
    pyqt:                   5.6.0-py27_2
    pysam:                  0.10.0-py27_2      bioconda
    python:                 2.7.13-0
    python-dateutil:        2.6.0-py27_0       bioconda
    python-snappy:          0.5-py27_0
    pytz:                   2016.10-py27_0
    pyyaml:                 3.12-py27_0
    pyzmq:                  16.0.2-py27_0
    qt:                     5.6.2-0
    readline:               6.2-2
    samtools:               1.3.1-5            bioconda
    scandir:                1.5-py27_0
    scipy:                  0.19.0-np112py27_0
    seaborn:                0.7.1-py27_0
    setuptools:             27.2.0-py27_0
    simplegeneric:          0.8.1-py27_1
    singledispatch:         3.4.0.3-py27_0
    sip:                    4.18-py27_0
    six:                    1.10.0-py27_0
    snappy:                 1.1.3-0
    sqlalchemy:             1.1.6-py27_0
    sqlite:                 3.13.0-0
    ssl_match_hostname:     3.4.0.2-py27_1
    subprocess32:           3.2.7-py27_0
    tk:                     8.5.18-0
    tornado:                4.4.2-py27_0
    traitlets:              4.3.2-py27_0
    unidecode:              0.04.20-py27_0
    wcwidth:                0.1.7-py27_0
    wheel:                  0.29.0-py27_0
    yaml:                   0.1.6-0
    zlib:                   1.2.8-3

Proceed ([y]/n)?
```

**Comment by mvdbeek** [comment]
Also @gregvonkuster, can you try just `conda create -n gemini gemini` ? Perhaps your current env has a package that is not compatible with python 2.7?

**Comment by nsoranzo** [comment]
> There is no python3 version of this package. If you include python==3.5.3 it should work.

@bgruening bx-python is Python2-only, so it is the other way around, you cannot require Python3 or you will get conflicting requirements.

**Comment by gregvonkuster** [comment]
@mvdbeek ok, you're approach worked, but it looks like I'm still getting version 0.20.0:
```
$ conda --version
conda 4.3.14
$ python --version
Python 3.6.0 :: Anaconda 4.3.0 (64-bit)
```
```
$ conda create -n gemini gemini
Fetching package metadata .................
Solving package specifications: .

Package plan for installation in environment /home/greg/miniconda3/envs/gemini:

The following NEW packages will be INSTALLED:

...stuff removed...

gemini-0.19.2a 100% |########################################################| Time: 0:00:00  21.68 MB/s
#
# To activate this environment, use:
# > source activate gemini
#
# To deactivate this environment, use:
# > source deactivate gemini
#
```
```
$ source activate gemini
$ gemini --version
gemini 0.20.0
```
Maybe this is just a bug in the version string for 0.19.2a?

**Comment by mvdbeek** [comment]
> Maybe this is just a bug in the version string for 0.19.2a?

I haven't actually gone through the install process, I'll check if I get the same result.

**Comment by nsoranzo** [comment]
@gregvonkuster You didn't specify the version in your `conda create` command, it should be:
```
conda create -n gemini gemini=0.19.2a
```

**Comment by mvdbeek** [comment]
@gregvonkuster @nsoranzo 
This is a problem in the gemini conda tarball, I get `gemini:                 0.19.2a-py27_2     bioconda` and yet if I source the environment and do `gemini --version` I get `0.20.0`.

**Comment by gregvonkuster** [comment]
Yet another strange issue -  the gemini releases / tags  on github don't have 0.19.2a: https://github.com/arq5x/gemini/releases
```
 on Jul 27, 2016
v0.19.1

    6fa8483 zip tar.gz 
```
The bioconda recipe uses this approach:
```
url: https://github.com/arq5x/gemini/archive/820ddf68.tar.gz
```

**Comment by nsoranzo** [comment]
You're right, the version in the Conda recipe is wrong, there is no 0.19.2 version, not even an alpha, it went from 0.19.1 to 0.20.0 (not released yet): https://github.com/arq5x/gemini/commit/b42593bfd3275e1a6b7bdac29b83a32ba0f0a36b
The recipe should be correct to use version `0.20.0.dev0` (or `0.20.0a0`).

**Comment by gregvonkuster** [comment]
I've added a PR for fixing the gemini release here https://github.com/bioconda/bioconda-recipes/pull/4220.  Its a bit concerning that the gemini recipe is installing alpha releases of the upcoming release.

**Comment by gregvonkuster** [comment]
I'm not sure how to proceed on this.  I'm currently blocked due to the gemini version issues that have been uncovered.  I'm not completely familiar with Gemini tools (this is my first look at them), so please let me know if my understanding is incorrect here.

It seems that Gemini requires its data to be available on $PATH to generate the databases (for the functional tests):
```
$ which gemini
~/miniconda2/bin/gemini

$ gemini load -v test.snpeff.vcf -t snpEff gemini_annotate_input.db
Traceback (most recent call last):
  File "/home/greg/miniconda2/bin/gemini", line 7, in <module>
    gemini_main.main()
  File "/home/greg/miniconda2/lib/python2.7/site-packages/gemini/gemini_main.py", line 1232, in main
    args.func(parser, args)
  File "/home/greg/miniconda2/lib/python2.7/site-packages/gemini/gemini_main.py", line 200, in load_fn
    gemini_load.load(parser, args)
  File "/home/greg/miniconda2/lib/python2.7/site-packages/gemini/gemini_load.py", line 23, in load
    annos = annotations.get_anno_files(args)
  File "/home/greg/miniconda2/lib/python2.7/site-packages/gemini/annotations.py", line 21, in get_anno_files
    config = read_gemini_config(args=args)
  File "/home/greg/miniconda2/lib/python2.7/site-packages/gemini/config.py", line 53, in read_gemini_config
    fname = _get_config_file(dirs, use_globals=use_globals)
  File "/home/greg/miniconda2/lib/python2.7/site-packages/gemini/config.py", line 48, in _get_config_file
    .format(CONFIG_FILE, dnames))
ValueError: GEMINI configuration file gemini-config.yaml not found in ['/usr/local/share/gemini', '/home/greg/.gemini'].
Please ensure the GEMINI data is installed using the install-data.py script
http://gemini.readthedocs.org/en/latest/content/installation.html
```

I have to install gemini using the instructions here: http://gemini.readthedocs.io/en/latest/content/installation.html.  The file resulting from this command ```wget https://raw.github.com/arq5x/gemini/master/gemini/scripts/gemini_install.py``` includes the following options...
```
parser.add_argument("tooldir", help="Directory to install 3rd party software tools", type=os.path.abspath)
parser.add_argument("datadir", help="Directory to install anaconda python and gemini data files", type=os.path.abspath)
parser.add_argument("--nodata", help="Do not install data dependencies", dest="install_data", action="store_false", default=True)
parser.add_argument("--gemini-version", dest="gemini_version", default="latest", help="Install one specific gemini version with a fixed dependency chain.")
```
...so using the following command line (since the latest gemini version that can be installed with conda is 0.20.0a0),I get the following error.  This is due to the conda recipe that installs this version using a URL that does not point to an actual release tag for gemini (i.e., https://github.com/arq5x/gemini/archive/820ddf68.tar.gz)
```
$ python gemini_install.py /home/greg/work/tmp/gemini_install/tools /home/greg/work/tmp/gemini_install/data --gemini-version 0.20.0a0
Checking required dependencies...
 wget found
Traceback (most recent call last):
  File "gemini_install.py", line 191, in <module>
    main(parser.parse_args())
  File "gemini_install.py", line 76, in main
    raise ValueError('Gemini version %s could not be found. Try the latest version.' % args.gemini_version)
ValueError: Gemini version 0.20.0a0 could not be found. Try the latest version.
```
Since the latest actual gemini release is 0.19.1, I've also tried installing gemini for that release, but encounter this error:
```
$ python gemini_install.py /home/greg/work/tmp/gemini_install/tools /home/greg/work/tmp/gemini_install/data --gemini-version 0.19.1
Checking required dependencies...
...some logging deleted here...
Installing base gemini package...
/home/greg/work/tmp/gemini_install/data/anaconda/bin/conda install --yes -c bioconda --file _conda-requirements-0.19.1.txt
Fetching package metadata .................


PackageNotFoundError: Package not found: '' Package missing in current linux-64 channels: 
  - gemini 0.19.0 py27_2

You can search for packages on anaconda.org with

    anaconda search -t conda gemini
```
The above error, I believe, is due to a bug which requires the fix in this PR, which has not yet been merged:
```
https://github.com/arq5x/gemini/pull/832
```
So I don't see a way forward on this.  Any advice is much appreciated!  ;)

**Comment by gregvonkuster** [comment]
@bgruening I'm taking another pass at this, upgrading to the recently released version 0.20.0 which has allowed me to make some progress.  

I've run my first Galaxy functional test to update the test files for the gemini_load.xml tool, specifically this output file:
```
~/tools-iuc/tools/gemini/test-data
115712 Mar 14  2016 gemini_load_result.db
```
The file has become even larger, so wanted to make sure these large files will be ok to commit:
```
262144 Apr 25 09:36 gemini_load_result.db
```

**Comment by bgruening** [comment]
@gregvonkuster I don't see any other way, so you have my :+1:. I also discussed a few ideas today with @jmchilton to make test data downloaded automatically and not store it here. So I hope we will have a better system soon for this.

Thanks for working on it!

**Comment by gregvonkuster** [comment]
@bgruening Thanks!  All tests except the one for the gemini_windower toool should now be passing.  I noticed that the output file ```gemini_windower_result.tabular``` defined in the test for the gemini_windower tool is not committed to the repo.  This is likely due to its size:
```
81314684 Apr 25 13:45 gemini_windower_result.tabular
```
How should I handle this?  Do you want this very large file committed too?

**Comment by bgruening** [comment]
Awesome work, thanks a lot! For this one file, can you please use `contains` or `md5sum` or similar tests?

**Comment by gregvonkuster** [comment]
Ok, done.  Thanks @bgruening ;)

**Comment by bgruening** [comment]
Thanks Greg, unfortunately, I have bad news:

https://travis-ci.org/galaxyproject/tools-iuc/jobs/225696891#L1851

I once implemented this https://github.com/arq5x/gemini/pull/321 to not require this configfile. It seems to not work anymore?

**Comment by bgruening** [comment]
Mh it seems to be still included: https://github.com/arq5x/gemini/blob/master/gemini/config.py#L65

**Comment by bgruening** [comment]
Even more wired are these errors: "RunToolException: Error creating a job for these tool inputs - This version of Gemini will only work with Gemini files that are for version 0.20.0."

**Comment by gregvonkuster** [comment]
> Mh it seems to be still included: https://github.com/arq5x/gemini/blob/master/gemini/config.py#L65

What is the fix for this issue?  Unfortunately I've not used gemini, so I'm a novice.  :(

> Even more wired are these errors: "RunToolException: Error creating a job for these tool inputs - This version of Gemini will only work with Gemini files that are for version 0.20.0."

Yes, this is strange.  From the logs it does look like gemini version 0.20.0 is being installed and used.  I have no idea what is causing this.  Could there be a prior version of gemini cached somewhere?

This also looks to be a concern: https://travis-ci.org/galaxyproject/tools-iuc/jobs/225696891#L1159

**Comment by nsoranzo** [comment]
I've rebased this PR and updated the requirements. The tests still fail as before:
- there's a validator in `tools/gemini/gemini_macros.xml` which prevents the use of input data of type `gemini.sqlite` if the gemini version is older than the one used in the tool requirements, so all '*.db' files in `tools/gemini/test-data/` need to be updated
- `gemini_load` fails with:
  ```
  ValueError: GEMINI configuration file gemini-config.yaml not found in ['/usr/local/share/gemini', '/usr/users/ga002/soranzon/.gemini'].
  Please ensure the GEMINI data is installed using the install-data.py script
  http://gemini.readthedocs.org/en/latest/content/installation.html
  ```

Not sure how to fix these problems, ping @bgruening @TorHou.

**Comment by bgruening** [comment]
Sorry, busy today. But I implemented --annotation_dir in gemini in: https://github.com/arq5x/gemini/pull/321/files

This way the config file was not needed anymore.

**Comment by nsoranzo** [comment]
Yeah, I read the comments above, but `--annotation-dir` is added to the command line only if the optional `annotation_databases` select param has a value, which is not the case for the test in `tools/gemini/gemini_load.xml` .

**Comment by TorHou** [comment]
Hi @nsoranzo 
- `gemini_load` requires the data. It adds annotation to the found variants in the vcf. The annotation is taken from the databases (the vcf.gz below) from its data folder.
The Gemini guys have their own [installer](https://github.com/arq5x/gemini/raw/master/gemini/scripts/gemini_install.py) that generates the `gemini-config.yaml` when used. The config looks like this.
```
annotation_dir: /home/houwaart/data/gemini/gemini_data
versions:
  ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.tidy.vcf.gz: 4
  ESP6500SI.all.snps_indels.tidy.v2.vcf.gz: 2
  ExAC.r0.3.sites.vep.tidy.vcf.gz: 3
  GRCh37-gms-mappability.vcf.gz: 2
  clinvar_20150305.tidy.vcf.gz: 5
  cosmic-v68-GRCh37.tidy.vcf.gz: 3
  dbsnp.b141.20140813.hg19.tidy.vcf.gz: 4
  detailed_gene_table_v75: 2
  geno2mp.variants.tidy.vcf.gz: 1
  hg19.rmsk.bed.gz: 2
  summary_gene_table_v75: 2 
```

- the validator for the Gemini version maybe is not needed. I don't think the schema of the databases has changed much, but maybe there is some internal test of the Gemini tools for the versions. I will try to test this.

**Comment by TorHou** [comment]
I tested `gemini de_novo` (version 0.20.1) with the current test-data. There is no problem with the versions, `de_novo` also doesn't require the annotation data. But the ordering of the ouput has changed slightly. So it seems all the test data ouput has to be regenerated.

**Comment by nsoranzo** [comment]
@gregvonkuster Closing in favour of #2208, hope that's OK and thanks for the contribution!

**Pull request closed without merging**
