### PR TITLE
PR workflow fix to early checkout

### PR DESCRIPTION
**Pull request by bernt-matthias**
@bgruening : lets see if this fixes it.

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Seems to work now. Successful run with mock tool change is here: https://github.com/galaxyproject/tools-iuc/actions/runs/96007320 

I cleaned the git history already removed the mock tool change.

**Comment by mvdbeek** [comment]
Why do you think this makes a difference ? Did you notice that the entire workflow only runs on the merge commit?

**Comment by bernt-matthias** [comment]
> Did you notice that the entire workflow only runs on the merge commit?

No. And not exactly sure what you mean. Which workflow run?

> Why do you think this makes a difference?

Before: the checkout action seems to change directory, then the fake planemo test run tries to consume the complete repo, e.g. here: https://github.com/galaxyproject/tools-iuc/actions/runs/95653778. 

Also the checkout seems to do more than `git clone ... && cd repo_dir` (the working dir after checkout seems to be not the working dir before the checkout / repo_dir). This is why the upload of galaxy.sha was moved up.

**Comment by mvdbeek** [comment]
> No. And not exactly sure what you mean. Which workflow run?
> 
> >

That was just a correlation, if you look at the action tab it's mostly the PRs on the master branch that run for 6 hours until they got killed. But there's also the medaka PR that ran for 6 hours.


> Before: the checkout action seems to change directory, then the fake planemo test run tries to consume the complete repo, e.g. here: https://github.com/galaxyproject/tools-iuc/actions/runs/95653778.

thanks, that's what I was wondering about.

**Pull request merged**
