### PR TITLE
dada2 use default_identifier_source

### PR DESCRIPTION
**Pull request by bernt-matthias**
FOR CONTRIBUTOR:
* [ ] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
How do we test this?

**Comment by mvdbeek** [comment]
yes

**Review by bgruening — APPROVED** [review]

**Comment by bernt-matthias** [comment]
I'm just testing this.

**Comment by bernt-matthias** [comment]
Works. But apparently also worked before? Seems that I still have not understood the problem completely. 

Regarding the PR I would say that it does not hurt and fixes a few minor problems, e.g. I bumped the DM profile such that containers are used (pre 18.09 containers are not used).

**Comment by mvdbeek** [comment]
Thank you @bernt-matthias!

**Pull request merged**
