### PR TITLE
Fix output tag set for the modern extract_genomic_dna tool

### PR DESCRIPTION
**Pull request by gregvonkuster**
so it exactly mimics the behavior of the original tool.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Increase tool version?

**Comment by gregvonkuster** [comment]
I don't think it is necessary on this one, but I'll take your advice.  It looks like the tool has not yet been installed: Times cloned / installed: 0, and this fix doesn't change tool output.

**Comment by nsoranzo** [comment]
The fix changes the output format: if `output_format` param is set to "fasta", before the fix the ouput format was "gff" or "inteval", after the fix is "fasta". So please update the tool version, since somebody can install the old repo in the time we publish an update.

**Comment by gregvonkuster** [comment]
Ok, done here: https://github.com/gregvonkuster/tools-iuc/commit/7c12f05466fbc04e71207fdfa919b70cf8d717f2 Thanks!

**Comment by bgruening** [comment]
Updated.

**Comment by gregvonkuster** [comment]
Thanks @bgruening !  ;)

**Pull request merged**
