### PR TITLE
Follow-up to "Hyperlink DOIs against preferred resolver #1906"

### PR DESCRIPTION
**Pull request by katrinleinweber**
I had deleted my fork, so my commit a047997 that now [addresses the review comment](https://github.com/galaxyproject/tools-iuc/pull/1906#discussion_r191839604) was not auto-associated with #1906 m-(

### CODE REVIEW

**Comment by nsoranzo** [comment]
@bgruening The failed build is due to an unrelated khmer issue (probably due to the conda package), merge?

**Comment by bgruening** [comment]
Sure, but are we stopping travis and prevent the push?

**Comment by nsoranzo** [comment]
No need, the build will fail, so no push stage.

**Comment by bgruening** [comment]
So let it fail. Thanks!

**Pull request merged**
