### PR TITLE
edgeR: update to 3.34.0

### PR DESCRIPTION
**Pull request by mblue9**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Puh, after a day trying with different containers I get this now:

```

 *** caught segfault ***
address (nil), cause 'memory not mapped'
```

This needs some more time :(

**Comment by mblue9** [comment]
Thanks for trying! And that's fine, no rush on my part.

**Comment by bgruening** [comment]
@mblue9 if you add `<requirement type="package" version="">xorg-libxt</requirement>` the segfault should go away. I'm working on an upstream fix but for now, you can fix your PRs by adding this requirement.

**Comment by mblue9** [comment]
Weird, the previous commit passed the linting check here even though it failed linting
https://github.com/galaxyproject/tools-iuc/pull/3330/checks?check_run_id=2737763863
```
Failed linting
Could not lint /tmp/planemo_tmp_a3epdqci/7d0b0f1c7adc861fadbae29f1597950b/edger/edger.xml due to malformed XML.
```

**Comment by bgruening** [comment]
@mblue9 thanks for the update! The failed linting is concerning. We recently have migrated to GitHub Actions as CI system and need to iron out some edges as it seems. I created an issue. Thanks!

**Review by bgruening — APPROVED** [review]

**Pull request merged**
