### PR TITLE
Fix for #417

### PR DESCRIPTION
**Pull request by bgruening**
Hopefully this fixes @dpryan79 issue in #417.

### CODE REVIEW

**Comment by bgruening** [comment]
@dpryan79 @erasche is this ok for you. I don't have a better idea.

**Comment by dpryan79** [comment]
I fear this is the only solution until matplotlib-1.5.1

**Comment by bgruening** [comment]
As soon as @erasche approve it I will update the TS's and rebuild the Docker container.

**Comment by erasche** [comment]
yeah, :+1:. Makes me feel gross, but if it works..

**Comment by bgruening** [comment]
@dpryan79 updated!
Thanks @erasche

**Pull request merged**
