### PR TITLE
add new deeptools version

### PR DESCRIPTION
**Pull request by bgruening**
ping @dpryan79

### CODE REVIEW

**Comment by dpryan79** [comment]
You might hold off until Monday or so, since 2.3.5 is imminent (I was waiting for Fidel to get back). I'll ping you before Wednesday, since I want to release before I leave for vacation :)

**Comment by bgruening** [comment]
Oki, doki!

**Comment by yhoogstrate** [comment]
X-ref: https://github.com/bioconda/bioconda-recipes/pull/2343

**Comment by dpryan79** [comment]
FYI: I have 2.3.5 in pypi but not yet bioconda (Travis is being really slow).

**Comment by dpryan79** [comment]
@bgruening 2.3.5 is now available via bioconda.

**Comment by bgruening** [comment]
Closed in favor of https://github.com/galaxyproject/tools-iuc/pull/950

**Pull request closed without merging**
