### PR TITLE
Use new group_tag parameter to allow selecting collection subsets

### PR DESCRIPTION
**Pull request by mvdbeek**
The idea here is that the user tags elements of a collection using tags that
start with `group:`. All of these tags can then be selected in the tool
form when choosing the factor levels.
This makes it very easy to select dataset combinations of interest
without having to re-shape collection contents for every contrast.

Technically the input does not need to be a collection, a
multiple="true" data input also works, but is currently not testable.
We might change this in the future.

The previous way of doing the analysis is still the default way of
using deseq2, as we currently don't auto-propagate group tags.
So in order to use this new feature users either have to manually tag collection
elements or use the `Tag elements from file from contents of a file`
to set the group tags. Hopefully we will enable auto-propagation
in 19.01 and enhance the apply rules tool to manipulate group tags.

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

FOR REVIEWER:
* [ ] .shed.yml file ok
    - [ ] Toolshed user `iuc` has access to associated toolshed repo(s)
* [ ] Indentation is correct (4 spaces)
* [ ] Tool version/build ok
* [ ] `<command/>`
  - [ ] Text parameters, input and output files `'single quoted'`
  - [ ] Use of `<![CDATA[ ... ]]>` tags
  - [ ] Parameters of type `text` or having `optional="true"` attribute are checked with `if str($param)` before being used
* [ ] Data parameters have a `format` attribute containing datatypes recognised by Galaxy
* [ ] Tests
  - [ ] Parameters are reasonably covered
  - [ ] Test files are appropriate
* [ ] Help
  - [ ] Valid restructuredText and uses `<![CDATA[ ... ]]>` tags
* [ ] Complies with other best practice in [Best Practices Doc](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

### CODE REVIEW

**Comment by mvdbeek** [comment]
I guess we need to update the xsd schema for the tags attribute ...

**Comment by mvdbeek** [comment]
Yay, all green with the new planemo release!

**Comment by davebx** [comment]
I agree with Björn.

**Comment by mvdbeek** [comment]
Corresponding mini-tuotiral here: https://github.com/galaxyproject/training-material/pull/1244

**Comment by bgruening** [comment]
Merci @mvdbeek!

**Pull request merged**
