### PR TITLE
skip test_repositories/ in CI

### PR DESCRIPTION
**Pull request by bernt-matthias**
alternatively:

- fix warnings
- move to deprecated

?

otherwise we will get in the future

```
test_repositories/golang_package
Linting repository /home/berntm/projects/tools-iuc/test_repositories/golang_package
Failed linting
Applying linter tool_dependencies_sha256sum... WARNING
.. WARNING: Missing checksum for https://github.com/erasche/bin-fasta/archive/415756dcd3573f330a39b073c9a314b840c189e0/master.zip
Applying linter shed_metadata... WARNING
.. WARNING: Missing shed metadata field [homepage_url] for repository
```

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by mvdbeek — APPROVED** [review]
Fine with me, but do they serve any purpose at all ? Can't we just delete them ?

**Comment by bernt-matthias** [comment]
@bgruening can you remember?

**Comment by bgruening** [comment]
Oh gosh, memories ... please remove them.

**Comment by nsoranzo** [comment]
I think these were never actually published to the ToolShed, can we remove them completely instead of moving them to `deprecated/` ?

**Pull request merged**
