### PR TITLE
avoid AUGUSTUS files copying when AUGUSTUS is not used

### PR DESCRIPTION
**Pull request by bgruening**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
@abretaud does this look ok for you?

**Review by abretaud — APPROVED** [review]
Good idea :+1:

**Comment by abretaud** [comment]
Do you prefer to merge it on this version or include it in https://github.com/galaxyproject/tools-iuc/pull/4819? (no preference for me)

**Comment by bgruening** [comment]
Oh haven't seen the other PR. If you have time please feel free to get it into the update. I don't care about commit history, so just take it over if you like :)

**Comment by abretaud** [comment]
Ok, I'm trying to finish the other PR quickly, adding your commits

**Comment by abretaud** [comment]
Added to #4819 :heavy_check_mark:

**Pull request closed without merging**
