### PR TITLE
hisat2: correctly assign datatype to output Fastq datasets when inputs are compressed

### PR DESCRIPTION
**Pull request by pjbriggs**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

PR which addresses an issue in the `hisat2` tool: when the input Fastqs are in a compressed format (e.g. `fastqsanger.gz` or `fastqsanger.bz`), the tool runs the `hisat2` program so that it produces output Fastqs with the same compression type as the input, but then incorrectly assigned the datatypes of those datasets to `fastqsanger`. This had implications for downstream tools, causing them to fail.

With this patch the correct datatype should be assigned to the output Fastq datasets based on that of the inputs (based on code which performs a similar job in the `bowtie2` tool).

### CODE REVIEW

**Comment by bgruening** [comment]
@pjbriggs I think the dbkeyactions are already actions: https://github.com/galaxyproject/tools-iuc/blob/b5944211a94ae2c83d4cc6d4f2d2d3a7649c7334/tools/hisat2/hisat2_macros.xml#L32

So you need to remove the action__s__ from the macro.

**Comment by pjbriggs** [comment]
@bgruening thanks - I just figured it out now myself! (Should have linted before initial push...)

**Comment by mvdbeek** [comment]
Thanks @pjbriggs! I changed the indentation to 4 spaces and bumped the tool version, thanks for fixing this!

**Comment by bgruening** [comment]
Thanks!

**Comment by pjbriggs** [comment]
Thanks @mvdbeek & @bgruening

**Pull request merged**
