### PR TITLE
Bug fix on qiime pick_open_reference xml

### PR DESCRIPTION
**Pull request by dsobral**
There seems to be a typo that's making one output (an important one) to always come out empty.

### CODE REVIEW

**Comment by bgruening** [comment]
@dsobral Can you please check why this was not catches by any test.
Great fix thanks!

**Comment by dsobral** [comment]
The tests do not contain any verifications for the file that was failing.

**Comment by bgruening** [comment]
Thanks! I tried to fix the one failing test ... Your fix looks great!

**Comment by bgruening** [comment]
Thanks @dsobral!

**Pull request merged**
