### PR TITLE
Clean up dotnet folder for space

### PR DESCRIPTION
**Pull request by mvdbeek**
I hope that helps with

```
 --
No space left on device : '/home/runner/runners/2.299.1/_diag/pages/7fa8a17c-a556-4235-9dfe-8e504f8053e6_fa5bf8d6-a3cd-598b-c37e-7051536e76dc_1.log'
```
in https://github.com/galaxyproject/tools-iuc/actions/runs/3510417129

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Can you explain a bit? What is in this folder? And why isn't it needed?

**Comment by mvdbeek** [comment]
dot net headers. don't need it -> https://github.com/galaxyproject/galaxy/blob/dev/.github/workflows/integration.yaml#L55-L56

**Comment by bernt-matthias** [comment]
The chunk processed in the job that is timing out contains: 

```
tools/poretools/poretools_times.xml tools/poretools/poretools_winner.xml tools/poretools/poretools_yield_plot.xml
tools/presto/presto_alignsets.xml tools/presto/presto_assemblepairs.xml tools/presto/presto_buildconsensus.xml tools/presto/presto_collapseseq.xml tools/presto/presto_filterseq.xml tools/presto/presto_maskprimers.xml tools/presto/presto_pairseq.xml tools/presto/presto_parseheaders.xml tools/presto/presto_parselog.xml tools/presto/presto_partition.xml tools/presto/prestor_abseq3.xml
```

Can't see anything suspicious on the first look.

**Comment by mvdbeek** [comment]
> timing out contains:

It's not timing out, it's running out of space

**Comment by bernt-matthias** [comment]
> it's running out of space

that's what I meant. Sorry.

**Comment by bernt-matthias** [comment]
Maybe we can also move https://github.com/galaxyproject/planemo-ci-action/blob/c3300c26221731c0e4ce15beb44b0bd9a0687cce/planemo_ci_actions.sh#L171 to the beginning of the loop. Then the first `planemo test` will get more space. .. but this seems not to be the problem here.

**Comment by mvdbeek** [comment]
> to the beginning of the loop. Then the first `planemo test` will get more space. .. but this seems not to be the problem here.

I would instead run this in a loop in the background (without `--force`), then you can test the entire chunk without restarting Galaxy for each tool.

**Comment by bernt-matthias** [comment]
Another thing I was wondering in the logs: could these calls use `mv` / `ln` instead of `cp`? 

```
if [ -f "/tmp/tmp6boj1ldz/job_working_directory/000/71/working/tmp-1_pair-pass.fastq" ] ; then cp "/tmp/tmp6boj1ldz/job_working_directory/000/71/working/tmp-1_pair-pass.fastq" "/tmp/tmp6boj1ldz/job_working_directory/000/71/outputs/galaxy_dataset_1b6c309f-7656-497b-88dc-df9919b7d7dd.dat" ; fi; 
if [ -f "/tmp/tmp6boj1ldz/job_working_directory/000/71/working/tmp-2_pair-pass.fastq" ] ; then cp "/tmp/tmp6boj1ldz/job_working_directory/000/71/working/tmp-2_pair-pass.fastq" "/tmp/tmp6boj1ldz/job_working_directory/000/71/outputs/galaxy_dataset_87bd34be-043d-4701-8ab3-17a4a178b159.dat" ; fi; cd '/tmp/tmp6boj1ldz/job_working_directory/000/71'; 
```

**Comment by mvdbeek** [comment]
That's a big change in Galaxy, let's go step by step here ?

**Comment by bernt-matthias** [comment]
> I would instead run this in a loop in the background

Might be an idea. Not sure about force `--force` according to the help this just does not ask for confirmation. I found the `--volumes` argument quite interesting (Prune volumes). Do we use volumes to persist data? 

I found the 1st answer [here](https://stackoverflow.com/questions/58755754/how-to-cleanup-docker-containers-and-images-on-linux-machines) quite interesting. 

Maybe a loop calling

```bash
docker container prune --force
docker image prune --all --force
docker volume prune --force
```

Might this be implemented like this

````bash
function cleanup_docker {
  while true
  do
    DOCKER COMMANDS
  done
}

cleanup_docker &
...
```

**Comment by bernt-matthias** [comment]
Noticed that `proteinortho: mulled-v2-6d4e828e735ac62c061c5cb349a2c8b1204224de:243f9312b74a5197b3345e348c6b684354036f9c` seems not to be at biocontainers, might be unrelated. But at least wastes time.

**Comment by mvdbeek** [comment]
We should have all the non-biocontainer tools listed in the lint section, probably worth checking what's missing.

**Comment by mvdbeek** [comment]
https://github.com/BioContainers/multi-package-containers/pull/2378 for proteinortho

**Comment by bernt-matthias** [comment]
Regarding blat: maybe it proteinortho should use a recent blat package, like here: https://github.com/galaxyproject/tools-iuc/pull/4928.

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
