### PR TITLE
Update snapatac2 to 2.6.4

### PR DESCRIPTION
**Pull request by pavanvidem**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
> Output anndata_out:  different than expected, difference (using sim_size):
( /tmp/tmpnl409ww9tl.macs3.pbmc_500_chr21.h5ad v. /tmp/tmp298vgu87tl.macs3.pbmc_500_chr21.h5ad )
Files /tmp/tmpnl409ww9tl.macs3.pbmc_500_chr21.h5ad=2667292b but /tmp/tmp298vgu87tl.macs3.pbmc_500_chr21.h5ad=1979950b - compare by size (delta=20000) failed

**Comment by pavanvidem** [comment]
yes, that's strange! There are different number of peaks compared to the previous version and both use the same version of macs3. Maybe some dependency or some hidden parameter is causing this. I'm investigating it.

**Comment by pavanvidem** [comment]
a new param was added which had hard coded value in the previous version. Now the tests should generate the same results as the previous version.

**Review by bgruening — APPROVED** [review]

**Comment by pavanvidem** [comment]
Thanks @bgruening

**Pull request merged**
