### PR TITLE
fixed input datatypes for lastz

### PR DESCRIPTION
**Pull request by nekrut**
Having `fasta.gz` and `fastq.gz` causes errors as these datatypes are not understood by `lastz`. The conversion will be taken care by implicit converted I previously added during lastz rewrite

### CODE REVIEW

**Comment by bgruening** [comment]
@nsoranzo do you think we need the version bump here?

**Comment by nsoranzo** [comment]
I don't think that's necessary, the tool would have failed for these datatypes before, so no reproducibility concerns.

**Comment by bgruening** [comment]
Same here. @nekrut can you revert the increased tool number?

**Comment by nsoranzo** [comment]
It seems we are missing permissions on the Test ToolShed: https://travis-ci.org/galaxyproject/tools-iuc/jobs/347987983

**Comment by bgruening** [comment]
ping @martenson

**Comment by martenson** [comment]
done

**Comment by nsoranzo** [comment]
Test TS is fixed, still some problem on the Main TS:
```
Unexpected HTTP status code: 403: {"err_msg": "You are not the owner of this repository, so you cannot administer it.", "err_code": 403005}
Repository contents updated but failed to update metadata for repository 'lastz' on the main Tool Shed.
```

**Comment by martenson** [comment]
@nsoranzo updated, sorry

**Comment by nsoranzo** [comment]
Success! Thanks @martenson!

**Comment by martenson** [comment]
@nsoranzo just to clarify upload to TTS happens on PR test success and upload to MTS on merge at master?

**Comment by nsoranzo** [comment]
No, both happen on merge at master.

**Pull request merged**
