### PR TITLE
Add wrapper for varVAMP

### PR DESCRIPTION
**Pull request by elischberg**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by elischberg** [comment]
Done:
- insertion of all possible outputs
- Add macros for parts which are similar for each mode
- add section for specified output of each mode (beauty feature) 
- a bit commando line, but not all of it

not Done:
- test section
- code generates always 19 outputfiles in history which is after a few times a lot
- final command

**Review by bgruening — COMMENTED** [review]
.shed.yml is missing

**Comment by elischberg** [comment]
test-data file is too large. Is there a possibility to compress the file?

**Comment by wm75** [comment]
@bgruening this one's ready I think.

**Comment by wm75** [comment]
well, now :-)

**Review by wm75 — APPROVED** [review]

**Pull request merged**
