### PR TITLE
Add biotools to CAT

### PR DESCRIPTION
**Pull request by bebatut**
FOR CONTRIBUTOR:
* [X] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [X] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by bebatut** [comment]
The remaining linting error comes from `cat_prepare.xml` which does not have any inputs, nor tests. This tool seems to be more like a DM

**Review by bernt-matthias — APPROVED** [review]

**Comment by bernt-matthias** [comment]
But we need to fix the tests for merging. If you prefer you can also undo the expect number of outputs. We can ignore linting warnings, but not tool test errors.

**Comment by bebatut** [comment]
The test errors are fixed. Only the linting error is left now

**Comment by bebatut** [comment]
Thanks @bernt-matthias !

**Pull request merged**
