### PR TITLE
RepeatMasker: update to 4.1.5

### PR DESCRIPTION
**Pull request by abretaud**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

First commit to check if non standard tool version is linted, xref https://github.com/galaxyproject/galaxy/issues/15945

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by abretaud** [comment]
Ah, green :) Except the test file size: I don't think we can reduce it more

**Comment by abretaud** [comment]
Hm, I'm tempted to merge it as is, but is it even possible with the file size check not passing?

**Comment by bgruening** [comment]
No, but I can push manually if you like.

**Comment by abretaud** [comment]
Ok yep, I'd like it :)

**Comment by bgruening** [comment]
done

**Pull request merged**
