### PR TITLE
Update TSEBRA

### PR DESCRIPTION
**Pull request by rlibouba**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Is this still a draft PR, or is it ready?

**Comment by rlibouba** [comment]
It's ready. I forgot to remove the draft mode

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @rlibouba

**Comment by mvdbeek** [comment]
```
Traceback (most recent call last):
  File "/home/runner/.planemo/gx_venv_3.7_release_23.1/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmpyft8_m10/galaxy-dev/lib/galaxy/tool_util/deps/containers.py", line 363, in find_best_container_description
    resolved_container_description = self.resolve(enabled_container_types, tool_info, **kwds)
  File "/tmp/tmpyft8_m10/galaxy-dev/lib/galaxy/tool_util/deps/containers.py", line 395, in resolve
    enabled_container_types, tool_info, install=install, resolution_cache=resolution_cache, session=session
  File "/tmp/tmpyft8_m10/galaxy-dev/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 624, in resolve
    session=session,
  File "/tmp/tmpyft8_m10/galaxy-dev/lib/galaxy/tool_util/deps/container_resolvers/mulled.py", line 405, in targets_to_mulled_name
    tags = mulled_tags_for(namespace, target.package, resolution_cache=resolution_cache, session=session)
  File "/tmp/tmpyft8_m10/galaxy-dev/lib/galaxy/tool_util/deps/mulled/util.py", line 152, in mulled_tags_for
    if not _namespace_has_repo_name(namespace, image, resolution_cache):
  File "/tmp/tmpyft8_m10/galaxy-dev/lib/galaxy/tool_util/deps/mulled/util.py", line 131, in _namespace_has_repo_name
    repo_names = _get_namespace(namespace)
  File "/tmp/tmpyft8_m10/galaxy-dev/lib/galaxy/tool_util/deps/mulled/util.py", line 106, in _get_namespace
    repos_response_json = repos_response.json()
  File "/home/runner/.planemo/gx_venv_3.7_release_23.1/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

quay.io is not happy, need to try again later.

**Comment by bgruening** [comment]
@rlibouba there is still some randomness in the tests.

> -anno1;g5.t1	1.0	0.0	0.5921945488250882	-1.0
+anno1;g5.t1	1.0	0.0	0.5921945488250879	-1.0

**Pull request merged**
