### PR TITLE
Update seqkit translate

### PR DESCRIPTION
**Pull request by hugolefeuvre**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Review by bernt-matthias — APPROVED** [review]
Do we want to, or should we bump the version?

**Comment by hugolefeuvre** [comment]
> Do we want to, or should we bump the version?

The seqkit version ? From 2.3 to 2.8 ?

**Comment by bernt-matthias** [comment]
I mean  the `VERSION_SUFFIX`

**Comment by hugolefeuvre** [comment]
I don't know what are the usual things to do in this case ? When do we have to change the version suffix ?

**Comment by bernt-matthias** [comment]
IMO not mandatory in this case. That's why I formulated it as a question in my 1st commen :)

**Review by bernt-matthias — APPROVED** [review]

**Comment by hugolefeuvre** [comment]
> IMO not mandatory in this case. That's why I formulated it as a question in my 1st commen :)

Same for me :)

**Pull request merged**
