### PR TITLE
Bedtools update

### PR DESCRIPTION
**Pull request by bgruening**
Update bedtools to the most recent version. Including a new tools, new parameters and documentation fixes.

### CODE REVIEW

**Comment by bgruening** [comment]
Anyone?

**Comment by erasche** [comment]
http://gx.hx42.org/job/IUC-Github/317/Planemo_HTML_Reports/bedtools.html#functional.test_toolbox.TestForTool_bedtools_spacingbed.test_tool_000000 is that ok? Otherwise happy to merge this.

**Comment by wtse168** [comment]
#docker-galaxy-stable after docker restarting, all files under /export/galaxy-central/conf will disappear,could you give me some advice on solving the issue?

**Comment by bgruening** [comment]
@erasche No this is not ok. Can you double check that you running the latest bedtools version? This was a bug in previous versions.

**Comment by bgruening** [comment]
@wtse168 wrong repository :)
I will respond to your mail in more detail.

**Comment by erasche** [comment]
@bgruening then it's an out of date bedtools, happy to merge.

**Comment by bgruening** [comment]
Thanks @erasche!

**Pull request merged**
