### PR TITLE
add Beacon2 BFF Validatior

### PR DESCRIPTION
**Pull request by khaled196**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by khaled196** [comment]
The tools fail in the testing for unspecified reasons. I suspect it is about the input [deref_schemas](https://github.com/galaxyproject/tools-iuc/tree/d85f39d5d4a77d87ca08020243700c0bd0dbb820/tools/beacon2/test-data/deref_schemas) or the way of the tools works. The same parameter works fine with the tool locally.

**Comment by bgruening** [comment]
Can you test with --biocontainers locally? Does it stll pass?

**Comment by khaled196** [comment]
Hi @bgruening 

I tested the tool with 

    conda create -n test_beacon  beacon2-ri-tools
    conda activate test_beacon
    bff-validator -i runs.json -i individuals.json -s deref_schemas/

The tool shows the results directly to the shell so I added > to the command

    ****************************************
    *  Beacon v2 Reference Implementation  *
    * - BEACON FRIENDLY FORMAT VALIDATOR - *
    *           Version: 2.0.0             *
    *   (C) 2021-2022 Manuel Rueda, PhD    *
    *    GNU General Public License v3     *
    ****************************************
    
    ==== SCHEMA: ANALYSES ====
    ==== SCHEMA: BIOSAMPLES ====
    ==== SCHEMA: COHORTS ====
    ==== SCHEMA: DATASETS ====
    ==== SCHEMA: INDIVIDUALS ====
    Hurray! No errors found
    ==== SCHEMA: RUNS ====
    Hurray! No errors found

**Comment by bgruening** [comment]
The tests here on CI are running in a container. If you run it locally with `planemo test --biocontainers` you will get a container that you can use for testing. Maybe a dependency is missing?

**Comment by khaled196** [comment]
Sorry for earlier, 

I tested the tools with 

    planemo test --biocontainers bff_validator.xml

 
     docker run -e "GALAXY_SLOTS=$GALAXY_SLOTS" -e "GALAXY_MEMORY_MB=$GALAXY_MEMORY_MB" -e "GALAXY_MEMORY_MB_PER_SLOT=$GALAXY_MEMORY_MB_PER_SLOT" -e "HOME=$HOME" -e "_GALAXY_JOB_HOME_DIR=$_GALAXY_JOB_HOME_DIR" -e "_GALAXY_JOB_TMP_DIR=$_GALAXY_JOB_TMP_DIR" -e "TMPDIR=$TMPDIR" -e "TMP=$TMP" -e "TEMP=$TEMP" --name 5e7cb986f9b6438bb2d4b390f3f45d38 -v "$_GALAXY_JOB_TMP_DIR:$_GALAXY_JOB_TMP_DIR:rw" -v "$TMPDIR:$TMPDIR:rw" -v "$TMP:$TMP:rw" -v "$TEMP:$TEMP:rw" -v /tmp/tmpzusa98g6/galaxy-dev:/tmp/tmpzusa98g6/galaxy-dev:ro -v /mnt/sdc/khaled/galaxy_beacon/tools-iuc/tools/beacon2:/mnt/sdc/khaled/galaxy_beacon/tools-iuc/tools/beacon2:ro -v /tmp/tmpzusa98g6/job_working_directory/000/4:/tmp/tmpzusa98g6/job_working_directory/000/4:ro -v /tmp/tmpzusa98g6/job_working_directory/000/4/outputs:/tmp/tmpzusa98g6/job_working_directory/000/4/outputs:rw -v "$_GALAXY_JOB_HOME_DIR:$_GALAXY_JOB_HOME_DIR:rw" -v /tmp/tmpzusa98g6/job_working_directory/000/4/working:/tmp/tmpzusa98g6/job_working_directory/000/4/working:rw -v /tmp/tmpzusa98g6/files:/tmp/tmpzusa98g6/files:ro -v /tmp/tmpzusa98g6/galaxy-dev/tool-data:/tmp/tmpzusa98g6/galaxy-dev/tool-data:ro -v /mnt/sdc/khaled/galaxy_beacon/tools-iuc/tools/beacon2/test-data:/mnt/sdc/khaled/galaxy_beacon/tools-iuc/tools/beacon2/test-data:ro --cpus ${GALAXY_SLOTS:-1} -w /tmp/tmpzusa98g6/job_working_directory/000/4/working --rm --user 1000:1000 quay.io/biocontainers/mulled-v2-c206a6f0d321a1f067051dbbfa14c9382274e6e1:ed91202b3c4d83d4360c42f67c2697bf0fd3f1cf-0 /bin/bash /tmp/tmpzusa98g6/job_working_directory/000/4/tool_script.sh > '../outputs/tool_stdout' 2> '../outputs/tool_stderr'; return_code=$?; echo $return_code > /tmp/tmpzusa98g6/job_working_directory/000/4/galaxy_4.ec;
    if [ -f "/tmp/tmpzusa98g6/job_working_directory/000/4/working/bff_validation.txt" ] ; then cp "/tmp/tmpzusa98g6/job_working_directory/000/4/working/bff_validation.txt" "/tmp/tmpzusa98g6/job_working_directory/000/4/outputs/dataset_f9672035-1413-4b67-b25f-f389da4fdb4a.dat" ; fi; cd '/tmp/tmpzusa98g6/job_working_directory/000/4';
    [ "$GALAXY_VIRTUAL_ENV" = "None" ] && GALAXY_VIRTUAL_ENV="$_GALAXY_VIRTUAL_ENV"; _galaxy_setup_environment True; python metadata/set.py; sh -c "exit $return_code"
    galaxy.jobs.runners.local DEBUG 2023-10-12 09:41:28,880 [pN:main.1,p:3832788,tN:LocalRunner.work_thread-2] (4) executing job script: /tmp/tmpzusa98g6/job_working_directory/000/4/galaxy_4.sh
    
    galaxy.jobs.runners.util.process_groups DEBUG 2023-10-12 09:41:35,661 [pN:main.1,p:3832788,tN:LocalRunner.work_thread-2] check_pg(): No process found in process group 3832944
    galaxy.jobs.runners.local DEBUG 2023-10-12 09:41:35,661 [pN:main.1,p:3832788,tN:LocalRunner.work_thread-2] execution finished: /tmp/tmpzusa98g6/job_working_directory/000/4/galaxy_4.sh
    galaxy.tool_util.output_checker INFO 2023-10-12 09:41:35,667 [pN:main.1,p:3832788,tN:LocalRunner.work_thread-2] Job error detected, failing job. Reasons are [{'type': 'exit_code', 'desc': 'Fatal error: Exit code 1 ()', 'exit_code': 1, 'code_desc': '', 'error_level': 3}]
    galaxy.jobs DEBUG 2023-10-12 09:41:35,695 [pN:main.1,p:3832788,tN:LocalRunner.work_thread-2] finish(): Moved /tmp/tmpzusa98g6/job_working_directory/000/4/outputs/dataset_f9672035-1413-4b67-b25f-f389da4fdb4a.dat to /tmp/tmpzusa98g6/files/f/9/6/dataset_f9672035-1413-4b67-b25f-f389da4fdb4a.dat
    galaxy.jobs DEBUG 2023-10-12 09:41:35,734 [pN:main.1,p:3832788,tN:LocalRunner.work_thread-2] (4) setting dataset 4 state to ERROR
    galaxy.jobs DEBUG 2023-10-12 09:41:35,844 [pN:main.1,p:3832788,tN:LocalRunner.work_thread-2] job_wrapper.finish for job 4 executed (159.368 ms)
    
    Shut down


      {
          "summary": {
              "num_errors": 0,
              "num_failures": 1,
              "num_skips": 0,
              "num_tests": 1
          },
          "tests": [
              {
                  "data": {
                      "inputs": {
                          "bff_input|input_bff_file": "json",
                          "input": [
                              {
                                  "id": "e0e0d0a2e08240d5",
                                  "src": "hda"
                              },
                              {
                                  "id": "5d8a40a94b066300",
                                  "src": "hda"
                              }
                          ],
                          "schema_dir": {
                              "id": "e702b7a5cfbd0d1a",
                              "src": "hda"
                          }
                      },
                      "job": {
                          "command_line": "ln -s '/tmp/tmpzusa98g6/files/c/0/1/dataset_c01beb50-e81a-432e-acb4-36d5571a75d6.dat' ./schema_dir && ln -s '/tmp/tmpzusa98g6/files/2/3/f/dataset_23f3b622-3377-4e98-ae6d-0ed80097058e.dat' runs.json  && ln -s '/tmp/tmpzusa98g6/files/6/1/b/dataset_61be013a-d75c-4cf2-befc-3c9554522c62.dat' individuals.json  && bff-validator --input runs.json --input individuals.json  --schema-dir ./schema_dir > '/tmp/tmpzusa98g6/job_working_directory/000/4/outputs/dataset_f9672035-1413-4b67-b25f-f389da4fdb4a.dat'",
                          "command_version": "",
                          "copied_from_job_id": null,
                          "create_time": "2023-10-12T09:37:50.879196",
                          "dependencies": [],
                          "exit_code": 1,
                          "external_id": "3832944",
                          "galaxy_version": "23.1",
                          "history_id": "e0e0d0a2e08240d5",
                          "id": "11d505a25fcda4c6",
                          "inputs": {
                              "input": {
                                  "id": "e0e0d0a2e08240d5",
                                  "src": "hda",
                                  "uuid": "23f3b622-3377-4e98-ae6d-0ed80097058e"
                              },
                              "input1": {
                                  "id": "e0e0d0a2e08240d5",
                                  "src": "hda",
                                  "uuid": "23f3b622-3377-4e98-ae6d-0ed80097058e"
                              },
                              "input2": {
                                  "id": "5d8a40a94b066300",
                                  "src": "hda",
                                  "uuid": "61be013a-d75c-4cf2-befc-3c9554522c62"
                              },
                              "schema_dir": {
                                  "id": "e702b7a5cfbd0d1a",
                                  "src": "hda",
                                  "uuid": "c01beb50-e81a-432e-acb4-36d5571a75d6"
                              }
                          },
                          "job_messages": [
                              {
                                  "code_desc": "",
                                  "desc": "Fatal error: Exit code 1 ()",
                                  "error_level": 3,
                                  "exit_code": 1,
                                  "type": "exit_code"
                              }
                          ],
                          "job_metrics": [],
                          "job_stderr": "",
                          "job_stdout": "",
                          "model_class": "Job",
                          "output_collections": {},
                          "outputs": {
                              "validate_bff_files": {
                                  "id": "11d505a25fcda4c6",
                                  "src": "hda",
                                  "uuid": "f9672035-1413-4b67-b25f-f389da4fdb4a"
                              }
                          },
                          "params": {
                              "__input_ext": "\"input\"",
                              "bff_input": "{\"__current_case__\": 1, \"genomicVariations\": {\"__current_case__\": 1, \"genomicVariations_avail\": \"no\"}, \"ignore_validation\": false, \"input_bff_file\": \"json\"}",
                              "chromInfo": "\"/tmp/tmpzusa98g6/galaxy-dev/tool-data/shared/ucsc/chrom/?.len\"",
                              "dbkey": "\"?\""
                          },
                          "state": "error",
                          "stderr": "",
                          "stdout": "",
                          "tool_id": "bff_validator",
                          "tool_stderr": "",
                          "tool_stdout": "",
                          "traceback": null,
                          "update_time": "2023-10-12T09:41:35.814333",
                          "user_email": "planemo@galaxyproject.org"
                      },
                      "output_problems": [
                          "Job in error state.. tool_id: bff_validator, exit_code: 1, stderr: .",
                          "Job in error state.. tool_id: bff_validator, exit_code: 1, stderr: ."
                      ],
                      "status": "failure",
                      "test_index": 0,
                      "time_seconds": 240.11632633209229,
                      "tool_id": "bff_validator",
                      "tool_version": "2.0.0+galaxy0"
                  },
                  "has_data": true,
                  "id": "bff_validator-0"
              }
          ],
          "version": "0.1"
      }

**Comment by khaled196** [comment]
@bgruening 

For missing dependences, I collected all the tool dependences in the pkg and added them to the wrapper but still failed. 

    use strict;
    use warnings;
    use feature qw(say);
    use autodie;
    use Getopt::Long;
    use Pod::Usage;
    use Data::Dumper;
    use FindBin qw($Bin);
    use Text::CSV_XS;
    use Text::Unidecode;
    use JSON::XS;
    use JSON::Validator;
    use File::Basename;
    use File::Spec::Functions qw(catdir catfile);
    use File::Which qw(which);
    use List::MoreUtils qw(any);
    use Scalar::Util qw(looks_like_number);
    use Path::Tiny;
    use Term::ANSIColor qw(:constants);
    $Data::Dumper::Sortkeys = 1;
    

    <requirement type="package" version="@TOOL_VERSION@">beacon2-ri-tools</requirement>
    <requirement type="package" version="1.12">gzip</requirement>
    <requirement type="package" version="2.3.0">termcolor</requirement>
    <requirement type="package" version="0.124">perl-path-tiny</requirement>
    <requirement type="package" version="0.40">perl-scalar-util-numeric</requirement>
    <requirement type="package" version="0.430">perl-list-moreutils</requirement>
    <requirement type="package" version="1.23">perl-file-which</requirement>
    <requirement type="package" version="3.48_01">perl-file-spec</requirement>
    <requirement type="package" version="2.16">perl-file-path</requirement>
    <requirement type="package" version="1.51">perl-findbin</requirement>
    <requirement type="package" version="2.54">perl-getopt-long</requirement>
    <requirement type="package" version="2.36">perl-autodie</requirement>

**Comment by bgruening** [comment]
@khaled196 anything we need to do here?

Happy new Year!

**Comment by khaled196** [comment]
Hello @bgruening 

Happy new year. 

I moved the fork into my personal repository so the pull request automatically closed, I will reopen it again, but the issue stands still with implementing the tool into galaxy

**Pull request closed without merging**
