### PR TITLE
Add missing tool dependencies for package_fontconfig_2_11_1

### PR DESCRIPTION
**Pull request by methylome**
package_zlib_1_2_8 and package_libpng_1_6_7 were added for tool dependencies.

### CODE REVIEW

**Comment by nsoranzo** [comment]
These are actually dependencies of `package_freetype_2_5_2`, so they should be installed anyway. What error are you trying to fix?

**Comment by methylome** [comment]
Without the dependencies, the following error occurred:
/tmp/fontconfig-2.11.1/fc-cache/.libs/lt-fc-cache: /lib64/libz.so.1: version `ZLIB_1.2.3.4' not found (required by /home/galaxy/dev/software/libpng/1.6.7/iuc/package_libpng_1_6_7/7da8c5e453cc/lib/libpng16.so.16)

Installation.log set the following variables.
FREETYPE_LIB_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib; export FREETYPE_LIB_PATH
PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/bin:$PATH; export PATH
LD_LIBRARY_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
DYLD_LIBRARY_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib:$DYLD_LIBRARY_PATH; export DYLD_LIBRARY_PATH
C_INCLUDE_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/include/freetype2:$C_INCLUDE_PATH; export C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/include/freetype2:$CPLUS_INCLUDE_PATH; export CPLUS_INCLUDE_PATH
PKG_CONFIG_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib/pkgconfig:$PKG_CONFIG_PATH; export PKG_CONFIG_PATH
FREETYPE_ROOT_DIR=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4; export FREETYPE_ROOT_DIR
PKG_CONFIG_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib/pkgconfig:$PKG_CONFIG_PATH; export PKG_CONFIG_PATH
PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/bin:$PATH; export PATH
LD_LIBRARY_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
DYLD_LIBRARY_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib:$DYLD_LIBRARY_PATH; export DYLD_LIBRARY_PATH
LIBRARY_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib:$LIBRARY_PATH; export LIBRARY_PATH
C_INCLUDE_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/include:$C_INCLUDE_PATH; export C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/include:$CPLUS_INCLUDE_PATH; export CPLUS_INCLUDE_PATH
LIBXML2_ROOT_DIR=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504; export LIBXML2_ROOT_DIR
./configure --prefix=/home/galaxy/dev/software/fontconfig/2.11.1/iuc/package_fontconfig_2_11_1/37b9109e489c --disable-docs --enable-libxml2 && make && make install

I think galaxy doesn't add the dependencies of the dependent packages.

**Comment by nsoranzo** [comment]
Your `package_libpng_1_6_7` is not at the latest revision, can you try to update it, Uninstall its `libpng` tool dependency and then Install it again?

**Comment by methylome** [comment]
I've uninstalled and installed package_libpng. However, I got the same error. As pointed in the previous post, I don't think galaxy addes the dependencies of the dependent packages unless changing env.sh of package_freetype_2_5_2.

**Comment by methylome** [comment]
I've reinstalled package_fontconfig_2_11_1 as well. However the error is the same.

**Comment by mvdbeek** [comment]
@methylome what version of galaxy are you using? In case you are still using release_15.10, could you try 16.01? There were numerous bugfixes related to the toolshed, I'm not sure all of them went into 15.10

**Comment by methylome** [comment]
Yes I can see the dependency to package_zlib_1_2_8. However no environment variables for zlib isn't set for installation of package_font_config as shown in INSTALLATION.log.
#############################################
FREETYPE_LIB_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib; export FREETYPE_LIB_PATH
PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/bin:$PATH; export PATH
LD_LIBRARY_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
DYLD_LIBRARY_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib:$DYLD_LIBRARY_PATH; export DYLD_LIBRARY_PATH
C_INCLUDE_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/include/freetype2:$C_INCLUDE_PATH; export C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/include/freetype2:$CPLUS_INCLUDE_PATH; export CPLUS_INCLUDE_PATH
PKG_CONFIG_PATH=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4/lib/pkgconfig:$PKG_CONFIG_PATH; export PKG_CONFIG_PATH
FREETYPE_ROOT_DIR=/home/galaxy/dev/software/freetype/2.5.2/iuc/package_freetype_2_5_2/1e86d1cf79a4; export FREETYPE_ROOT_DIR
PKG_CONFIG_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib/pkgconfig:$PKG_CONFIG_PATH; export PKG_CONFIG_PATH
PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/bin:$PATH; export PATH
LD_LIBRARY_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH
DYLD_LIBRARY_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib:$DYLD_LIBRARY_PATH; export DYLD_LIBRARY_PATH
LIBRARY_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/lib:$LIBRARY_PATH; export LIBRARY_PATH
C_INCLUDE_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/include:$C_INCLUDE_PATH; export C_INCLUDE_PATH
CPLUS_INCLUDE_PATH=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504/include:$CPLUS_INCLUDE_PATH; export CPLUS_INCLUDE_PATH
LIBXML2_ROOT_DIR=/home/galaxy/dev/software/libxml2/2.9.1/iuc/package_libxml2_2_9_1/45b16a3ab504; export LIBXML2_ROOT_DIR
./configure --prefix=/home/galaxy/dev/software/fontconfig/2.11.1/iuc/package_fontconfig_2_11_1/37b9109e489c --disable-docs --enable-libxml2 && make && make install
STDOUT

**Comment by methylome** [comment]
I'm using release_16_01.

**Comment by mvdbeek** [comment]
Hmm, I confirm that the recursive env sourcing doesn't work on a clean 16.01 installation either ... .
@bgruening is this a bug or a known limitation of the toolshed?

**Comment by bgruening** [comment]
This seems like a bug to me, wired.

**Pull request closed without merging**
