### PR TITLE
Add data manager for fetching PlantTribes scaffolds data

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by bgruening** [comment]
@blankenberg can you please took at this? Thanks.

**Comment by bgruening** [comment]
I'm not sure what to do with data managers :(
We can not test them easily but I feel they are important for Galaxy and an easy setup, also with Galaxy flavors.

@gregvonkuster you have tested this one locally?

**Comment by gregvonkuster** [comment]
Yes, I've tested it locally, and I've discussed it a bit with @blankenberg.  We can hold off a bit longer on merging it.  I've had agreement from @blankenberg that he will take a look at it, but I am not currently blocked in any way if this is not merged for a while.  I may also be adding another data manager tool that will complement this one fairly soon.

**Comment by gregvonkuster** [comment]
I'm going to merge this.  I've been using it in testing for some time now and I don't think @blankenberg will get a chance to take any additional looks.

**Pull request merged**
