### PR TITLE
raceid: parameter fix

### PR DESCRIPTION
**Pull request by bernt-matthias**
- clustering: rfseed is commented in the command file

also rename version tokens

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
ping @mtekman

**Comment by mtekman** [comment]
Looks good, I'm minifying the data as we speak

**Comment by bernt-matthias** [comment]
@mtekman can you approve the PR? Then we could merge.

**Review by mtekman — APPROVED** [review]
"Looks good!"  

this time, hitting the *Approve' button :-)

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
