### PR TITLE
reference data table columns consistently by name

### PR DESCRIPTION
**Pull request by bernt-matthias**
just for consistency .. none of these were wrong as far a I could tell .. except for gffcompare where the asserts are now actually considered (since we now use this https://github.com/galaxyproject/galaxy/pull/8395).

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by abretaud** [comment]
Thanks @bernt-matthias!

**Comment by abretaud** [comment]
so in both TS, there are 2 multigps repos:
- one owned by greg
- one owned by iuc, but marked as deprecated (don't know why)

.shed.yml is using the [iuc ones](https://github.com/galaxyproject/tools-iuc/blob/master/tools/multigps/.shed.yml#L2), that explains the messages we get

sooo... any idea what to do?

**Comment by bgruening** [comment]
@gregvonkuster please :)

**Comment by abretaud** [comment]
I manually updated all the tools except multigps

**Pull request merged**
