### PR TITLE
Fix for MD5-sum urls

### PR DESCRIPTION
**Pull request by yhoogstrate**
The 'download_by_url' tool-shed action supports MD5 and SHA256 checking by adding the suffix ```#md5#hexhexhexhex``` or ```#sha256#hexhex``` to the url.
You can find the implementation at the following link for confirmation:

https://github.com/galaxyproject/galaxy/blob/dev/lib/tool_shed/galaxy_install/tool_dependencies/recipe/step_handler.py#L170

None of the tools in tools-iuc has this implemented correctly, but use ```#md5=hexhexhex``` (= instead of hashtag) instead.
In this PR you can find the fixed URLs.

I think a cleaner solution would be to add an optional md5sum="hexhexhex.." XML tag, like:
```<action type="download_by_url" md5sum="hexhexhex">https://u.r.l/clean-get-url-without-a-hashtag<action>```

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by erasche** [comment]
Hey @yhoogstrate, don't know if you saw https://github.com/galaxy-iuc/standards/issues/14, but we were definitely planning to do this for ALL downloaded files.

**Comment by erasche** [comment]
Thanks for the contributions @yhoogstrate! 

I somewhat thing this is a Galaxy bug, since those are the default pypi URLs, I'm somewhat surprised that Galaxy didn't adopt that format when they implemented it.

**Comment by yhoogstrate** [comment]
Thanks. I didn't know you were working on this in parallel.

**Comment by erasche** [comment]
"working" - just realised we really needed to be doing it, no work done yet. Thanks for getting us started :)

**Pull request merged**
