### PR TITLE
STDIO catching 2 critical errors

### PR DESCRIPTION
**Pull request by yhoogstrate**
Added STDIO catching of two critical errors

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by bgruening** [comment]
ok to test

**Comment by yhoogstrate** [comment]
job standard error:
Warning: Some stderr/stdout text
/tmp/tmpsPi590/job_working_directory/000/3/galaxy_3.sh: 20: /tmp/tmpsPi590/job_working_directory/000/3/galaxy_3.sh: STAR: not found
/tmp/tmpsPi590/job_working_directory/000/3/galaxy_3.sh: 20: /tmp/tmpsPi590/job_working_directory/000/3/galaxy_3.sh: STAR: not found
[E::hts_open] fail to open file 'Aligned.out.sam'
samtools: failed to open "Aligned.out.sam" for reading: No such file or directory

I can't believe this is due to the patch?

**Comment by bgruening** [comment]
@yhoogstrate this is not due to your patch. I think this patch looks good. I haven't tested it and would like to wait another day if someone with STAR experiences will comment, otherwise I will merge it.

Thanks!
Bjoern

**Comment by bgruening** [comment]
Thanks @yhoogstrate!

**Pull request merged**
