### PR TITLE
Maker: update 2.31.10 + add support for mpi

### PR DESCRIPTION
**Pull request by abretaud**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

FOR REVIEWER:
* [ ] .shed.yml file ok
    - [ ] Toolshed user `iuc` has access to associated toolshed repo(s)
* [ ] Indentation is correct (4 spaces)
* [ ] Tool version/build ok
* [ ] `<command/>`
  - [ ] Text parameters, input and output files `'single quoted'`
  - [ ] Use of `<![CDATA[ ... ]]>` tags
  - [ ] Parameters of type `text` or having `optional="true"` attribute are checked with `if str($param)` before being used
* [ ] Data parameters have a `format` attribute containing datatypes recognised by Galaxy
* [ ] Tests
  - [ ] Parameters are reasonably covered
  - [ ] Test files are appropriate
* [ ] Help
  - [ ] Valid restructuredText and uses `<![CDATA[ ... ]]>` tags
* [ ] Complies with other best practice in [Best Practices Doc](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

A minor update for maker, and also added support for MPI (finally found a way to avoid systematic segfault).
I'm a little nervous with the MPI stuff, but tests are ok (= in a non-cluster environment) and it seems to work fine on our cluster with a properly configure job destination.

### CODE REVIEW

**Comment by abretaud** [comment]
(There's also this PR which should improve support for mpi on SGE cluster: https://github.com/conda-forge/openmpi-feedstock/pull/30)

**Comment by abretaud** [comment]
humpf. maybe mpi is not so simple. we should wait before merging

**Comment by abretaud** [comment]
ping @bgruening as we discussed: using maker in mpi mode would probably look like this
(but this pr is not yet ready I think)

**Comment by bgruening** [comment]
Thanks for sharing @abretaud! Have a save trip home!

**Comment by abretaud** [comment]
Hum, the error looks like https://github.com/bioconda/bioconda-recipes/issues/13562, I'll have a look next week

**Comment by abretaud** [comment]
Green!
I think it's ready to merge now. To sum up, it uses mpich now to run maker in mpi mode:
- if it runs on a destination which supports mpi, fantastic, it can use thousands of cpus on hundreds of compute nodes. e.g. running this on a slurm queue with option `-n`
- if the destination doesn't support mpi, it works too, it will be able to use GALAXY_SLOTS number of cpus on the compute node (or even a single one if there is only one available)

ping @erasche @shiltemann with this PR the maker tutorial should run much faster, so it could be useful for the Utrecht session. Do you think it would be possible to try it, or do you prefer to keep the current non-mpi version?

I can open a Galaxy issue to start a discussion on a better way to standardize mpi execution

**Comment by erasche** [comment]
@abretaud of course we want a faster version! :)

**Comment by abretaud** [comment]
@erasche cool!
I opened the galaxy issue: https://github.com/galaxyproject/galaxy/issues/7884

**Comment by bgruening** [comment]
Thanks for creating the issue and the update.

**Pull request merged**
