### PR TITLE
Fix ivar trim's amplicon info on the fly generation

### PR DESCRIPTION
**Pull request by wm75**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Due to an option name mismatch auto-generation of the amplicon info file never happened in previous versions.

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, BAM files are compared vis sim_size, but we can compare them natively afaik and probably should do that.

**Comment by wm75** [comment]
Yes, but for now I'm still totally puzzled why those unrelated tests are failing. There has been a new build of the bioconda package since the last update so maybe some unpinned dependency?

**Comment by bgruening** [comment]
> Yes, but for now I'm still totally puzzled why those unrelated tests are failing. There has been a new build of the bioconda package since the last update so maybe some unpinned dependency?

could be, we rolled out new htslib version

**Comment by wm75** [comment]
Yeah, so it seems that either the htslib or the samtools update in the new build of the ivar conda package are causing the slight difference in the variant call stats produced by ivar variants.
Now what is the proper way to avoid such surprises in the future. Put a fixed version of htslib in the requirements, or of htslib *and* samtools?

**Comment by mvdbeek** [comment]
Those tests should be running in a container, so differences there would be rather surprising (unless the container wasn't built on time)

**Comment by mvdbeek** [comment]
Oh, I'm sure this is https://github.com/galaxyproject/galaxy/issues/13460 as well.

**Comment by mvdbeek** [comment]
Yep, that was it, green after merging https://github.com/galaxyproject/galaxy/pull/13468

**Comment by wm75** [comment]
Thanks @mvdbeek!
I guess ivar variants still deserves an explicit samtools requirement since it uses `samtools mpileup` on the command line?
Would do this in a separate PR though since requiring the latest version would also reintroduce the diffs causing the tests to fail, and that isn't really the scope here.

**Comment by bgruening** [comment]
So add samtools?

**Review by bgruening — APPROVED** [review]

**Pull request merged**
