### PR TITLE
Add HISAT

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by bgruening** [comment]
LGTM!

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/90/
Test (probably) passed

**Comment by erasche** [comment]
+1, merging.

**Comment by erasche** [comment]
BTW, You might want to wrap the readme with CDATA in the future, you have:

```xml
<readme> ... HISAT is much faster >50 times than TopHat2 ... </readme>
```

I'll patch that on master now. Thanks for the package @davebx!

**Comment by erasche** [comment]
Reformats in https://github.com/galaxyproject/tools-iuc/commit/0e3e956a262f09a8002749c29e89b5d661d8cb90

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/91/
Test (probably) passed

**Pull request merged**
