### PR TITLE
fix star DM test

### PR DESCRIPTION
**Pull request by bernt-matthias**
Some test parameters were not existing in the inputs. 

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
I guess we skip deployment?

**Comment by bernt-matthias** [comment]
> I guess we skip deployment?

Guess so. Should we skip always if we do not bump?

**Comment by bgruening** [comment]
> Guess so. Should we skip always if we do not bump?

Yes.

**Comment by mvdbeek** [comment]
Attention: deployment cancelled!

https://github.com/galaxyproject/tools-iuc/actions/runs/11192894349

**Pull request merged**
