### PR TITLE
RNASTAR: Add --sjdbOverhang option for twopass mode and its test

### PR DESCRIPTION
**Pull request by ccedmendoza**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @ccedmendoza!

I was just looking into the STAR changelogs as there is 2.7.0 out already, but I guess we need to have a new indices for [STAR 2.7.0](https://github.com/alexdobin/STAR/blob/master/RELEASEnotes.md):

> Important: the genome index has to be re-generated with the latest 2.7.0x release.

So lets release this version as last for 2.6. and then do a bigger rework in the light of 2.7.

**Comment by ccedmendoza** [comment]
Hi,

I'm sorry but I don't understand the error in this PR, so I can't fix it to pass the tests.
Could someone help me?

**Comment by bgruening** [comment]
@ccedmendoza I tried to fix that. It was a linting issue as it seems that some metadata was missing. So not something in the tool that you changed.

Sorry for my late reply.

**Comment by nsoranzo** [comment]
Actually the error is another:
```
Error '404 Client Error: Not Found for url: https://bitbucket.org/jgoecks/jeremys-code/raw/fa1930a689b8e2f6b59cc1706e5ba0ed8ad357be/galaxy/tool-wrappers/star.xml' accessing https://bitbucket.org/jgoecks/jeremys-code/raw/fa1930a689b8e2f6b59cc1706e5ba0ed8ad357be/galaxy/tool-wrappers/star.xml
```

**Comment by nsoranzo** [comment]
Should be fixed now.

**Comment by bgruening** [comment]
Thanks @ccedmendoza!

**Comment by abretaud** [comment]
So ready to merge?

**Comment by bgruening** [comment]
@abretaud sure :) Please feel free to merge as well!

**Pull request merged**
