### PR TITLE
bakta 1.8.1 to pass github CI/CD

### PR DESCRIPTION
**Pull request by pimarin**
New bakta branch from the last main version

### CODE REVIEW

**Comment by pimarin** [comment]
test seem to be validated by the CI/CD @bernt-matthias

**Comment by bernt-matthias** [comment]
OK. Lets try/

**Review by bernt-matthias — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Seemed to work https://toolshed.g2.bx.psu.edu/repository?repository_id=bff6aef15285f2f5&changeset_revision=3f0aa1b3e816

**Comment by pimarin** [comment]
Great ! thank you @bernt-matthias  !

**Pull request merged**
