### PR TITLE
Add recipe for installing bwa version 0.7.12.

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by bgruening** [comment]
LGTM. Not sure if we want to have a binary for this one.
@gregvonkuster can you add this compile step for all other architectures also to the devteam repo?

**Comment by gregvonkuster** [comment]
@bgruening All the install recipes for the various versions of BWA do, in fact, include this installation from source with the exception of this one https://github.com/galaxyproject/tools-devteam/blob/master/packages/package_bwa_0_7_10_039ea20639/tool_dependencies.xml, which may be using a specific version of the code files rather than a tagged download.  I have no idea why this recipe was written this way, especially since it does not support OS X.  I will soon submit a PR to have a new version of these tools use the 0.7.12 recipe I just submitted.

**Comment by mvdbeek** [comment]
Okay, so let's merge it. Thanks @gregvonkuster

**Comment by gregvonkuster** [comment]
Thanks for merging!  ;)

**Pull request merged**
