### PR TITLE
Update wrapper

### PR DESCRIPTION
**Pull request by SantaMcCloud**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by SantaMcCloud** [comment]
Had trouble in a workflow since some file names can not be change and because of this I change the wrapper to handle such kind of things

**Comment by SantaMcCloud** [comment]
No, since you use label to label the column names in the output if not then you have numbered column names which then should be clear since it is the input order.

**Comment by bgruening** [comment]
Can you please bump the version.

**Comment by SantaMcCloud** [comment]
Done

**Pull request merged**
