### PR TITLE
fix error on building a pdf with no-model specified

### PR DESCRIPTION
**Pull request by scholtalbers**

### CODE REVIEW

**Comment by bgruening** [comment]
:+1:

**Comment by mvdbeek** [comment]
Perhaps a test for PDF creation would be nice? Not a must have, but should prevent breaking it in the future.

**Comment by peterjc** [comment]
e.g. https://github.com/peterjc/pico_galaxy/blob/master/tools/venn_list/venn_list.xml uses:

<output name="PDF" file="magic.pdf" ftype="pdf" compare="contains" />

with https://github.com/peterjc/pico_galaxy/blob/master/test-data/magic.pdf which is just the header from a v1.4 PDF file.

**Comment by yhoogstrate** [comment]
> Perhaps a test for PDF creation would be nice? Not a must have, but should prevent breaking it in the future.

I think this is a very good point (also because it helps testing)

**Comment by scholtalbers** [comment]
I guess this is what is called peer pressure :stuck_out_tongue_winking_eye:

**Comment by bgruening** [comment]
@scholtalbers we are getting better and better in this ;)
Can you please also add the missing file :)
Many thanks!

**Comment by scholtalbers** [comment]
missing file? its all there isn't it?

**Comment by bgruening** [comment]
Yes, great!  @peterjc, @mvdbeek can we merge this?

**Comment by mvdbeek** [comment]
I'll give it a quick spin, 5 minutes.

**Comment by mvdbeek** [comment]
Alright, the new test validates :+1:

**Comment by bgruening** [comment]
@yhoogstrate If you like you can merge your first PR :)
Thanks for reviewing and @scholtalbers for the patch!

**Comment by yhoogstrate** [comment]
Hi guys, but the PDF file is 8 bytes large and my computer can't view it. Can somebody confirm this before we merge?

**Comment by mvdbeek** [comment]
@yhoogstrate this is just the header of a PDF file, if I understood the well.
In this case we test that a PDF is being produced, not it's contents.
Which we could also do?!

**Comment by yhoogstrate** [comment]
The PDF is generated by a fixed version of R, so I think it should always produce the same pdf file? If someone thinks this is too tricky I'll merge it as it is now.

**Comment by peterjc** [comment]
Your ``magic.pdf`` looks wrong when downloaded via GitHub using browser:

```
$ hexdump -C ~/Desktop/magic.pdf 
00000000  25 50 44 46 2d 31 2e 0a                           |%PDF-1..|
00000008
```

Note the trailing new line (0x0a), I need to try this via ``git`` at the command line to confirm.

In comparison, mine checks PDF v1.4 which is more precise:

```
$ hexdump -C ~/repositories/pico_galaxy/test-data/magic.pdf 
00000000  25 50 44 46 2d 31 2e 34  0a                       |%PDF-1.4.|
00000009
```

**Comment by peterjc** [comment]
Given PDF files are so complex a 100% match will be hard to ensure across platforms (even if most of the dependencies are via the Tool Shed), so I would not encourage that.

**Comment by yhoogstrate** [comment]
Nice catch @peterjc. I can confirm this with the git pulled version of @scholtalbers macs2-pdf-fix branch:
```
00000000  25 50 44 46 2d 31 2e 0a                           |%PDF-1..|
00000008
```

**Comment by mvdbeek** [comment]
@yhoogstrate @peterjc in practice checking our PDFs produced by lattice in R works across different R versions on different versions of ubuntu ... we might also compare the full PDF file. Not sure what is best.

**Comment by blankenberg** [comment]
As stated, fully matching PDFs can be tough, not that I am trying to discourage trying to do it. Most of the time, you'll need to at least take into account metadata, such as the creation date/times that are often present. Much of this will depend on the program that created the PDF, however.

**Comment by peterjc** [comment]
Yes, confirmed with file fetched via git:

```
$ git checkout -t scholtalbers/macs2-pdf-fix
Branch macs2-pdf-fix set up to track remote branch macs2-pdf-fix from scholtalbers.
$ hexdump -C tools/macs2/test-data/magic.pdf
00000000  25 50 44 46 2d 31 2e 0a                           |%PDF-1..|
00000008
$ python -c 'print(repr(open("tools/macs2/test-data/magic.pdf").read()))'
'%PDF-1.\n'
```

As long as you can assume a v1.4 PDF, then there should be a new line after the four, e.g.

```
$ hexdump -C velvet_manual.pdf | head -n 1
00000000  25 50 44 46 2d 31 2e 34  0a 25 d0 d4 c5 d8 0a 35  |%PDF-1.4.%.....5|
```

You can copy the ``magic.pdf`` from ``pico_galaxy`` or recreate it in Python.

**Comment by yhoogstrate** [comment]
Or merge https://github.com/scholtalbers/tools-iuc/pull/1

Very solid arguments @blankenberg

**Comment by jmchilton** [comment]
Someone should add assertions for PDFs - https://github.com/galaxyproject/galaxy/tree/dev/test/base/asserts. The assertion testing framework is pretty easy to extend.

Also a new assertion for that just verifies the file sniffs appropriately to the specified ``ftype``, that is a little bit harder to implement though.

**Comment by peterjc** [comment]
Good idea @jmchilton - I wanted to use a ``compare="startswith"`` rather than ``compare="contains"`` here, but using the Galaxy datatype sniffers would be elegant.

**Comment by yhoogstrate** [comment]
Thanks everyone for working on this one!

**Pull request merged**
