### PR TITLE
Fix missed pRESTO version macro update

### PR DESCRIPTION
**Pull request by natefoo**
The tools were actually updated in #3747, but because this version macro wasn't updated, they do not appear as new versions in the Tool Shed.

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by aerijman — APPROVED** [review]
Good catch! Thanks!

**Review by bernt-matthias — COMMENTED** [review]
Can you use the token also on the requirement?

**Comment by natefoo** [comment]
@bernt-matthias Sure, does it work to use macros inside the macros file? I am not very familiar with how they work.

**Comment by bernt-matthias** [comment]
> does it work to use macros inside the macros file?

Yep, should work.

**Comment by natefoo** [comment]
@bernt-matthias ok, done, thanks!

**Review by bernt-matthias — APPROVED** [review]

**Comment by aerijman** [comment]
@natefoo and  @bernt-matthias, thank you very much!

**Pull request merged**
