### PR TITLE
Update varVAMP to 1.2.1

### PR DESCRIPTION
**Pull request by wm75**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

supersedes  #6372

### CODE REVIEW

**Comment by wm75** [comment]
@jonas-fuchs
https://github.com/jonas-fuchs/varVAMP/blob/ac4b1edb0f51965bc1116673f5cd1dcd2f600722/varvamp/command.py#L508-L509

@bgruening is right, I think, in https://github.com/galaxyproject/tools-iuc/pull/6372#issuecomment-2395003051 that this seems weird.
The consensus outputs are a property of the msa, not of the primer scheme, and it
 doesn't look helpful that these two files now have identical titles.
Is there an advantage to doing this that I'm not seeing?

**Comment by wm75** [comment]
Tests are now passing with the consensus output name adjusted, but lets wait for what Jonas says.

**Comment by jonas-fuchs** [comment]
Hi Wolfgang,

so from my side this was indeed intended as the type of consensus is still referenced in the name of the file. 'varVAMP_consensus' is also just the default name which you can adjust with the '--name' argument to something like 'HEV_consensus', which I think would make it more easy if you would like to differentiate between primer schemes. Might have not been that smart. So open to suggestions. We could also adjust it to something like 'varVAMP_consensus | ambig'.

Let me know ;)
Jonas

**Comment by wm75** [comment]
Ok, lets get this merged and think things over again before the next release :-)

**Pull request merged**
