### PR TITLE
Update meme and fix tests

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by gregvonkuster** [comment]
Is it best to keep tool suites like this all in the same repo, or should I move each tool to a separate repo?  I tend to prefer the latter, but I'll go with consensus.

**Comment by bgruening** [comment]
@gregvonkuster I'm not sure what you mean with repo. But a classical suite are many tools that are in __one__ folder, share one-or-many macro files and are demultiplexed into __many__ TS repos.

**Comment by gregvonkuster** [comment]
Ok, thanks, I'll keep it this way.  I'll add the fixes for the 2 additional tools - should have done that in the initial commit.  ;)

**Comment by bgruening** [comment]
Thanks @gregvonkuster!

**Pull request merged**
