### PR TITLE
Add gemini wrappers.

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by blankenberg** [comment]
I moved the datatype. 

Only other thing to think about is whether the data manager should be a repository dependency of this (as it currently is), or if there should be a tool suite instead that depends on the tools and the data manager.

However, I'm ok with merging this now.

**Comment by bgruening** [comment]
@blankenberg thanks!

Do you mean splitting up all tools into different repositories? I thinks this only increases complexity for no good reason. An admin can always hide tools.

**Comment by blankenberg** [comment]
Well, there are several technical reasons (revolving around updates/fixes to individual tools, where not every tool might have been updated) to split up the tools into individual repositories beyond not wanting to install each one. Which is why the: Suite (repository_dependencies.xml)--> individual tools and data managers, works well.

Right now we have: gemini tools (repository_dependencies.xml)--> gemini data manager, which doesn't seem correct, since you could use the tools without the data manager (manually curating your reference data). (also suffers from problems when updating only subset of tools)

**Comment by martenson** [comment]
I will merge this, remove the repository dependency, and then define a suite for it.

**Comment by bgruening** [comment]
True @blankenberg I'm just not sure this is worth the splitting overhead.
@martenson let me know if I can help you.

**Pull request merged**
