### PR TITLE
fix Circos preset option

### PR DESCRIPTION
**Pull request by gmauro**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This PR fixes a path composition in the Circos preset option.

### CODE REVIEW

**Review by hexylena — APPROVED** [review]
Thanks!

**Comment by hexylena** [comment]
@bgruening @bernt-matthias is the file size check now mandatory? I can reduce the size of the pngs at some point but I'd rather not do it right now since I don't have bandwidth.

I've checked all four of the test jobs and they all pass?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
No, its an optional check that we can overrule for old tools afaik.

**Comment by hexylena** [comment]
I thought as much but the required test is failing. Any idea why? The output is not helpful

image

**Comment by bgruening** [comment]
Does the linting takes 6h? Do we ran into a recursion?

**Comment by bernt-matthias** [comment]
> Does the linting takes 6h? Do we run into a recursion?

Works for me locally in a few secs. I restarted. Here is my local output: 

```
Linting repository /home/berntm/projects/tools-iuc/tools/circos
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/binlinks.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/stack-histogram.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/tiles-from-interval.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/bundlelinks.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/alignments-to-links.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/tableviewer.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/scatter-from-wiggle.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/resample.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/circos.xml
Applying linter xml_order... WARNING
.. WARNING: Best practice violation [stdio] elements should come before [version_command]
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/text-from-interval.xml
+Linting tool /home/berntm/projects/tools-iuc/tools/circos/gc_skew.xml
```

**Comment by hexylena** [comment]
well a new commit helps there, let's see if this gets stuck in a forever loop.

**Comment by hexylena** [comment]
Next time we start enforcing a specific ordering on elements can we just update all of the tools in IUC automatically? This felt like a lot of time to merge a 2 character underlying change because I had to solve all of the updated linting warnings which are fatal despite being mostly cosmetic.

**Comment by gmauro** [comment]
I thought the same. Thanks @hexylena for merging it

**Pull request merged**
