### PR TITLE
Fix R linting + lint dexseq

### PR DESCRIPTION
**Pull request by martenson**
GitHub workflows is being migrated to Ubuntu 20.04, which is breaking the R linting CI job with:
```
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/runner/work/_temp/Library/stringi/libs/stringi.so':
  libicui18n.so.60: cannot open shared object file: No such file or directory
Calls: lint_dir ... namespaceImport -> loadNamespace -> library.dynam -> dyn.load
Execution halted
```

This is due to R package cache, its key should depend also on the Ubuntu version.

Fix https://github.com/galaxyproject/tools-iuc/issues/3539

### CODE REVIEW

**Comment by martenson** [comment]
@nsoranzo That seems to have fixed it.

**Comment by nsoranzo** [comment]
OK, so I guess that the problem is the R package cache, its key should depend also on the ubuntu version. I'll change that here to test.

**Comment by nsoranzo** [comment]
Sorry, I've hijacked this pull request! It now fixes the R linting issue on CI, and dexseq linting issues since I was using it to test :)
Green and ready to review.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Cool, thanks!

**Comment by martenson** [comment]
@nsoranzo thanks for the hijack!

**Pull request merged**
