### PR TITLE
Fix deps for deseq2 1.10.0

### PR DESCRIPTION
**Pull request by abretaud**
Here's a fix for a missing package for deseq2 1.10.0 installation (and I consequently had to update other packages)

### CODE REVIEW

**Comment by abretaud** [comment]
It seems like my new intergalactic powers are operational: I updated TTS and MTS

**Comment by mvdbeek** [comment]
@abretaud indeed, thats nice, right? But ideally you would wait until you have one review and a 👍 .
@bgruening have we documented this somewhere? I know for galaxy-core that's in https://github.com/galaxyproject/galaxy/blob/dev/doc/source/project/organization.rst#handling-pull-requests

**Comment by abretaud** [comment]
Oops, sorry! @bgruening briefed me about these rules, and I thought it would fall in a quick-and-minor-fix category of PR that could exceptionally be just merged
I'll be more patient in future PRs :)

**Comment by mvdbeek** [comment]
No worries, IMO it does fall in that category :).

**Comment by bgruening** [comment]
@mvdbeek we do not have any guidelines currently. I felt we were to small for such strict rules but as we are growing this is maybe needed at some point.

**Pull request merged**
