### PR TITLE
Add "background motif regions parameter" to Homer

### PR DESCRIPTION
**Pull request by mtekman**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This is a small update to @lldelisle 's excellent Homer wrapper, where the `-bg` parameter is exposed in the wrapper.  (It's a small thing, but people in my lab requested it, and it will save me future headaches :P)

### CODE REVIEW

**Comment by bgruening** [comment]
please bump the tool version

**Comment by lldelisle** [comment]
Thanks @mtekman for this adding. In my lab they don't use `-bg` so I was not sure how to set it.

**Comment by bgruening** [comment]
@lldelisle is that one ready?

**Comment by lldelisle** [comment]
I think yes.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks everyone!

**Pull request merged**
