### PR TITLE
Add the data_manager_gtdbtk_database_installer tool

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Where is this data table used?

**Comment by gregvonkuster** [comment]
> Where is this data table used?
I've started a new suite of tools that will eventually consist of wrappers for each of these https://ecogenomics.github.io/GTDBTk/commands/index.html.  The first tool will be classify_wf  (https://ecogenomics.github.io/GTDBTk/commands/classify_wf.html).  I'm just wrapping up a few details on it, so I'll have it submitted soon.

**Comment by gregvonkuster** [comment]
Can this be merged?

**Review by bgruening — APPROVED** [review]

**Comment by gregvonkuster** [comment]
Thanks @bgruening !

**Pull request merged**
