### PR TITLE
Updating tools/pangolin from version 4.2 to 4.3

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/pangolin**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/pangolin from version 4.2 to 4.3.

**Project home page:** https://github.com/cov-lineages/pangolin/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Need to remove the pangolearn mode.. It seems.

Does this tool really need so many requirements?

**Comment by pvanheus** [comment]
I recall some of these requirements were added because of a problem with a certain bioconda build and can probably be removed - @wm75 do you remember the details?

We should definitely add a note to the effect that pangoLEARN mode is deprecated.

**Comment by wm75** [comment]
All those requirements are just pinning core dependencies of pangolin's lineage assignment logic. The bioconda recipe doesn't do that, but it means two pangolin environments created at different times with pangolin itself at the same version could produce rather different results. For the Galaxy wrapper we opted for more reproducibility though it means more maintenance effort: whenever you want to update the wrapper you should try a fresh conda install of pangolin to get the versions that would be installed of all requirements, then update them in the wrapper.

I have just updated the corresponding comment in the wrapper a bit to make the importance of the core dependencies clearer in #5398 .

**Comment by wm75** [comment]
Closing this now as completed in #5391 .

**Pull request closed without merging**
