### PR TITLE
Update bioext to 0.20.1

### PR DESCRIPTION
**Pull request by davebx**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR updates an existing tool or tool collection

This PR updates the wrapper to use BioExt 0.20.1, which includes built-in references for SARS-CoV-2 genes.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Can you integrate the commits from https://github.com/galaxyproject/tools-iuc/pull/3788/ ... I guess that this also fixes the test failures. 

Seems that I missed your PR when I opened the other one.

**Comment by davebx** [comment]
@bernt-matthias the branches should be in sync now

**Comment by bernt-matthias** [comment]
@davebx there are many commits that do do not belong here...

**Comment by davebx** [comment]
@bernt-matthias yeah, not sure what happened, I'm going to rebase and push -f

**Comment by bernt-matthias** [comment]
> I'm skeptical about putting @VERSION_SUFFIX@ in macros.xml, since that means any time it's updated for one tool, it's updated for all of them. Would it make more sense to have that as a token in each tool's XML file?

Fine with me.

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
