### PR TITLE
Bedtools update

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
Travis fails on this repository: https://github.com/galaxyproject/tools-iuc/blob/master/tools/tool_factory_2/tool_dependencies.xml

Anyone knows if the `readme` is valid?

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/141/
Test (probably) passed

**Comment by erasche** [comment]
Shouldn't that be 'help'?
24. apr. 2015 03.13 skrev "Björn Grüning" <notifications@github.com>:

**Comment by erasche** [comment]
http://gx.hx42.org/job/IUC-Github/141/Planemo_HTML_Reports/bedtools.html the first random test failed, is that OK @bgruening?

**Comment by jmchilton** [comment]
About the ``readme`` - it is listed as needing to be under ``package`` on https://wiki.galaxyproject.org/ToolDependenciesTagSets and it doesn't seem to appear in the UI anywhere https://toolshed.g2.bx.psu.edu/view/fubar/tool_factory_2. I would say it is not functional and planemo is correctly linting this.

**Comment by bgruening** [comment]
Ok, I will remove this. @erasche first error results from exactly this `readme` section.

**Comment by erasche** [comment]
@bgruening tracking travis found linting problems in #113 

@bgruening "first error results from exactly this readme section" - no, the Jenkins bot planemo test error. That comes from a different place, the first randomBed test. 

```
History item  different than expected, difference (using diff):
( /var/lib/jenkins/workspace/IUC-Github/tools/bedtools/test-data/randomBed_result1.bed v. /tmp/tmpYzvJih/tmp/tmpc6IAtgrandomBed_result1.bed )
--- local_file
+++ history_data
@@ -1,3 +1,3 @@
-chr1	163032793	163032798	1	5	+
-chr1	184253514	184253519	2	5	-
-chr1	41422918	41422923	3	5	+
+chr1	115594142	115594147	1	5	+
+chr1	167415497	167415502	2	5	-
+chr1	191692404	191692409	3	5	-
```

**Comment by erasche** [comment]
@bgruening don't bother with the travis problems in this PR, let's keep that to a separate one.

**Comment by bgruening** [comment]
@erasche this is a random BED wrapper, any idea how to fix this? Should I remove this one test? It's actually not needed.

**Comment by erasche** [comment]
@bgruening ahh, okay, no way to specify a seed then. That's unfortunate. I would say switch to an `<assert_contents/>` rather than a test file? Would that be an ok option?

**Comment by bgruening** [comment]
It should use a `seed` does not work. The second test is using the `assert_contents` already.

**Comment by erasche** [comment]
I feel like a second assert_contents test (if it's testing something different) is better than no test at all?

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/148/
Test (probably) passed

**Comment by erasche** [comment]
LGTM, tests corrected with latest commit.

**Pull request merged**
