### PR TITLE
Remove old hisat package, this was never used.

### PR DESCRIPTION
**Pull request by bgruening**
This can be removed as it was never used by the hisat wrapper.

### CODE REVIEW

**Comment by nsoranzo** [comment]
This has already landed on the MTS:  https://toolshed.g2.bx.psu.edu/view/iuc/package_hisat_0_1_5/141b1bb47203 . Should we at least deprecate it there before merging this?

**Comment by bgruening** [comment]
I deprecated it, thanks Nicola. Anyone know why this was pushed to the MTS?

**Comment by martenson** [comment]
I don't know but it was in the #master so it is not unexpected.

**Comment by erasche** [comment]
That's on me, I had multiple complaints of packages missing from the MTS that were available in the IUC repo, so to thwart future complaints I push everything in master that was missing on the MTS.

**Comment by bgruening** [comment]
Should I merge this or close it?

**Comment by nsoranzo** [comment]
+1 to merge.

**Pull request merged**
