### PR TITLE
Add package for ballgown 1.0.3

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by erasche** [comment]
:+1:

**Comment by bgruening** [comment]
Dave can you add a `.shed.yml` file and maybe a link to ballgown to the help section?

**Comment by erasche** [comment]
blocking on @davebx's PR for the tools

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/39/
Test (probably) passed

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/40/
Test (probably) passed

**Comment by davebx** [comment]
I'm going to put this on a branch, instead of committing to master.

**Pull request closed without merging**
