### PR TITLE
Updating tools/quast from version 5.0.2 to 5.2.0

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/quast**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/quast from version 5.0.2 to 5.2.0.

**Project home page:** http://quast.bioinf.spbau.ru

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by simonbray** [comment]
https://github.com/ablab/quast/blob/master/CHANGES.txt#L3

**Comment by gallardoalba** [comment]
Working on it https://github.com/planemo-autoupdate/tools-iuc/pull/9

**Comment by gallardoalba** [comment]
When using reads as input for mapping against the contigs/scaffolds, it shows that error:

```
File "/usr/local/opt/quast-5.2.0/quast_libs/qutils.py", line 886, in compile_tool
open(make_logs_basepath + '.log', 'w').close()
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/quast_libs/bwa/make.log'
```

**Comment by bebatut** [comment]
> When using reads as input for mapping against the contigs/scaffolds, it shows that error:
> 
> ```
> File "/usr/local/opt/quast-5.2.0/quast_libs/qutils.py", line 886, in compile_tool
> open(make_logs_basepath + '.log', 'w').close()
> PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/quast_libs/bwa/make.log'
> ```

This error was reported in quast Github too: https://github.com/ablab/quast/issues/217
 
By adding `bwa` and `bedtools` in the requirement, the tests pass.
I opened a PR to update the bioconda recipe and add `bwa` and `bedtools` as run requirements: https://github.com/bioconda/bioconda-recipes/pull/36236

**Comment by bebatut** [comment]
Until the bioconda PR is merged, this should fix all tests.
I also:
- Fix metagenomics reference, and retunr correct outputs
- Fix error when paired-end gz reads are given
- Support paired collection for reads

**Review by bgruening — APPROVED** [review]

**Comment by bebatut** [comment]
Thanks @gallardoalba for the work there! Let's try the update now :smile:

**Pull request merged**
