### PR TITLE
Scanpy1.10.2 update1

### PR DESCRIPTION
**Pull request by nilchia**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

This PR updates two things:
1. adds `get.rank_genes_groups_df` function so the user will get the ranked genes table as a tabular file.
2. adds missing `gene_symbols` to pl.pca, pl.umap, and pl.diffmap

Thank you @nomadscientist for your suggestion. I hope it helps.

### CODE REVIEW

**Comment by pavanvidem** [comment]
Please make sure that it will not break the GTA tutorials. Otherwise, we will merge this after the GTA.

**Comment by nilchia** [comment]
@pavanvidem I guess it'll conflict with GTA.

**Comment by pavanvidem** [comment]
Then please mark it as a draft and let it open at least until the end of next week.

**Comment by nilchia** [comment]
@pavanvidem @bgruening 
Thanks!

**Comment by bgruening** [comment]
@nilchia you need to bump the version number.

**Comment by nilchia** [comment]
@bgruening Is it OK now?

**Review by bgruening — APPROVED** [review]

**Pull request merged**
