### PR TITLE
Trinotate: Update v.3.2.2

### PR DESCRIPTION
**Pull request by gallardoalba**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Closes https://github.com/galaxyproject/tools-iuc/issues/4116

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
For unknown reasons the tests are not running here.

**Comment by gallardoalba** [comment]
> For unknown reasons the tests are not running here.

Strange because tests pass in local.

**Comment by nsoranzo** [comment]
You need to remove trinotate from `.tt_skip` and commit the change. For reference, it was added in https://github.com/galaxyproject/tools-iuc/pull/3304

**Comment by gallardoalba** [comment]
> You need to remove trinotate from `.tt_skip` and commit the change. For reference, it was added in https://github.com/galaxyproject/tools-iuc/pull/3304

Grazie.

**Review by bgruening — APPROVED** [review]

**Pull request merged**
