### PR TITLE
Update nextclade to 1.10.1

### PR DESCRIPTION
**Pull request by pvanheus**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by pvanheus** [comment]
Nextclade CLI 1.10.0 has been [released](https://github.com/nextstrain/nextclade/releases). Besides a version bump this introduces a new JSON configuration file (which is supported in the "advanced options")

**Comment by bgruening** [comment]
Failing the tests as it seems.

**Comment by pvanheus** [comment]
> Failing the tests as it seems.

Yes, that was a problem with nextalign. Passing now.

**Comment by pvanheus** [comment]
The latest change in this PR is switching how the Nextclade reference data is handled: instead of specifying each file individually, the dataset directory is specified and then individual files are specified if the user provides values for them. This change was made after the Nextclade team clarified that the semantics of the tool allow to "override" like this.

**Comment by wm75** [comment]
Thanks @pvanheus! Looks like a real simplification of things :)

Couple of remarks:
- 1.10.1 is available by now and while it shouldn't include any changes relevant for the wrapper you might just want to update to it to show that everything's up to date
- why the new more complicated checks like `#if $adv.input_root_seq and str($adv.input_root_seq).strip()`? When would the first condition be True, but not the second?
- I just noticed on re-reviewing the code that your
  ```
            #if str($adv.advanced_options) == "yes"
                $adv.include_reference
            #end if
  ```
  doesn't work since `include_reference` doesn't specify true/falsevalues.
  So this leads to literal `true` / `false` being included on the command line and the tool always failing when `output_fasta` is selected in `outputs`.

**Comment by pvanheus** [comment]
> Thanks @pvanheus! Looks like a real simplification of things :)
> 
> Couple of remarks:
> 
>     * 1.10.1 is available by now and while it shouldn't include any changes relevant for the wrapper you might just want to update to it to show that everything's up to date
> 
Good point. The main change on their side was w.r.t. error messages.
>     * why the new more complicated checks like `#if $adv.input_root_seq and str($adv.input_root_seq).strip()`? When would the first condition be True, but not the second?
> 
I'm reverting to a simpler form. I was confusing myself here.
>     * I just noticed on re-reviewing the code that your
>       ```
>                 #if str($adv.advanced_options) == "yes"
>                     $adv.include_reference
>                 #end if
>       ```
>       doesn't work since `include_reference` doesn't specify true/falsevalues.
>       So this leads to literal `true` / `false` being included on the command line and the tool always failing when `output_fasta` is selected in `outputs`.
Well spotted and now fixed, with a test added.

**Review by wm75 — APPROVED** [review]
Perfect. This looks good to go to me!

**Pull request merged**
