### PR TITLE
prokka: more flexible testing

### PR DESCRIPTION
**Pull request by bernt-matthias**
Testdata differences were due the installed version is nowadays 1.13.7 and the version used to create the test data was 1.13. We could fix this now.

Probably does not cover the original error:

```
[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
[22:27:37] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.13 from https://github.com/tseemann/prokka' -Z outdir\/prokka\.err -i outdir\/prokka\.fsa 2> /dev/null
```

which I don't get for local test. 

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by mvdbeek** [comment]
That's quite annoying building in a check like that, even if I understand you don't want to receive bug reports for old versions ... 😠(xref https://www.biostars.org/p/301365/). I think we probably just need to rebuild the image, not much we can do on the Galaxy / IUC side. We could perhaps use libfaketime, but that wouldn't work on other architectures.

**Comment by bernt-matthias** [comment]
Checking the tbl2asn recipe: the used URL is not stable. So I guess we can't rebuild the image.

**Comment by bgruening** [comment]
@bernt-matthias if we rebuild the tbl2ans pkg with the latest version and bump the build-number of prokka, we should be save for one more year isn't it?

**Comment by bernt-matthias** [comment]
Jep, but we can't rebuild the current version, because the download link is not stable. Guess we should build the current version (maybe with a detour via the depot .. even if this seems useless given that the tool stops working in 1yr).

**Comment by bgruening** [comment]
Yeah abondend all our hopes for tbl2asn and decided to care only about the latest verion and not about reproducibility in bioconda. We once discssued even to patch this behaviour out, but decided against this I think.

**Pull request merged**
