### PR TITLE
Updating tools/amrfinderplus from version 3.11.18 to 3.11.20

### PR DESCRIPTION
**Pull request by lldelisle**
Hello! This is an automated update of the following tool: **tools/amrfinderplus**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/amrfinderplus from version 3.11.18 to 3.11.20.

**Project home page:** https://github.com/ncbi/amr/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Ping @pimarin

**Comment by pimarin** [comment]
Update is to fix minor bugs, no changes in the tools. I think it's okay !

**Comment by bgruening** [comment]
Thanks for checking @pimarin

**Comment by bernt-matthias** [comment]
Deployed by restarting CI.

**Pull request merged**
