### PR TITLE
gffread: add -S option, a test for -S and bump to version 0.12.3

### PR DESCRIPTION
**Pull request by FredericBGA**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR updates an existing tool or tool collection

### CODE REVIEW

**Comment by bernt-matthias** [comment]
`gffread=0.12.3` seems not yet available.

**Comment by FredericBGA** [comment]
This is not this tool?
https://github.com/gpertea/gffread/releases/tag/v0.12.3

**Comment by bernt-matthias** [comment]
We need an update for the bioconda recipe first: https://github.com/bioconda/bioconda-recipes/blob/master/recipes/gffread/

**Comment by bernt-matthias** [comment]
@FredericBGA  

- 0.12.7 should be available soon https://github.com/bioconda/bioconda-recipes/pull/30689
- what do you think about the other "missing" options?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Merci!

**Pull request merged**
