### PR TITLE
Created tool-data directory to link all .loc.sample files to, to avoi…

### PR DESCRIPTION
**Pull request by yhoogstrate**
Hi Everyone,

When I was looking into some *.sample.loc files I realized some were out of sync within the tools-iuc repo. To inspect it a bit further I made a overview with checksums and I found some discrepancies:

```
6b6fe23b090014dd50249e3c51e09c21  ./tools/meme/all_fasta.loc.sample
6b6fe23b090014dd50249e3c51e09c21  ./tools/pilon/all_fasta.loc.sample
fbbecafba7191825d29a765f52975839  ./tools/transtermhp/all_fasta.loc.sample
fbbecafba7191825d29a765f52975839  ./data_managers/data_manager_bowtie_index_builder/tool-data/all_fasta.loc.sample
fbbecafba7191825d29a765f52975839  ./data_managers/data_manager_star_index_builder/tool-data/all_fasta.loc.sample
fbbecafba7191825d29a765f52975839  ./data_managers/data_manager_hisat2_index_builder/tool-data/all_fasta.loc.sample
=> 6b6fe23b090014dd50249e3c51e09c21 seems to be the best one

e6a40fd82e46bfc2529de0a472fa76e9  ./data_managers/data_manager_gemini_database_downloader/tool-data/gemini_databases.loc.sample
fca053c39c587f0ff8aecc96f094618c  ./tools/gemini/tool-data/gemini_databases.loc.sample
=> fca053c39c587f0ff8aecc96f094618c seems to be the best one

59f95b1e54e0a706997ee01531bcc262  ./data_managers/data_manager_hisat2_index_builder/tool-data/hisat2_indexes.loc.sample
e394611fbbac1c3158756e47d268b2a5  ./tools/hisat2/tool-data/hisat2_indexes.loc.sample
=> e394611fbbac1c3158756e47d268b2a5 seems to be the best one

5a427bc598cc18b18849607858a1aa5e  ./data_managers/data_manager_star_index_builder/tool-data/rnastar_index.loc.sample
b7f572fd138e913fddfabefc1ceabc07  ./tools/rgrnastar/tool-data/rnastar_index.loc.sample
=> 5a427bc598cc18b18849607858a1aa5e seems to be the best one

# Different files and columns, I don't know which is valid or whether could better be renamed to avoid confusion
13f6d453f33db021002b1af4f65e18b4  ./tool_collections/snpsift/snpsift_dbnsfp_generic/tool-data/snpsift_dbnsfp.loc.sample
368bcc5b58cae34bc74319f31b4cb025  ./tool_collections/snpsift/snpsift_dbnsfp/tool-data/snpsift_dbnsfp.loc.sample seems to be the best one
```

And of course those that are identical:

```
5a07f247b6bc6f3c25e46bc3fcb9dabf  ./data_managers/data_manager_mothur_toolsuite/tool-data/mothur_aligndb.loc.sample
5a07f247b6bc6f3c25e46bc3fcb9dabf  ./tools/mothur/tool-data/mothur_aligndb.loc.sample

1adaf09bec4ea2561e5718ae3456b740  ./data_managers/data_manager_mothur_toolsuite/tool-data/mothur_lookup.loc.sample
1adaf09bec4ea2561e5718ae3456b740  ./tools/mothur/tool-data/mothur_lookup.loc.sample

7dae80354fec4618149737d2b1dd81d5  ./data_managers/data_manager_mothur_toolsuite/tool-data/mothur_map.loc.sample
7dae80354fec4618149737d2b1dd81d5  ./tools/mothur/tool-data/mothur_map.loc.sample

a088fca2fea44ea956bffe627050a70d  ./data_managers/data_manager_mothur_toolsuite/tool-data/mothur_taxonomy.loc.sample
a088fca2fea44ea956bffe627050a70d  ./tools/mothur/tool-data/mothur_taxonomy.loc.sample

ce488f8f1b7c3a28d1372b7aed68011c  ./data_managers/data_manager_snpeff/tool-data/snpeffv_annotations.loc.sample
ce488f8f1b7c3a28d1372b7aed68011c  ./tool_collections/snpeff/tool-data/snpeffv_annotations.loc.sample

c22fa7185ea199a6db852f47678c862f  ./data_managers/data_manager_snpeff/tool-data/snpeffv_databases.loc.sample
c22fa7185ea199a6db852f47678c862f  ./tool_collections/snpeff/tool-data/snpeffv_databases.loc.sample

e07e4949a55b493f2f056372b6bdbf77  ./data_managers/data_manager_snpeff/tool-data/snpeffv_genomedb.loc.sample
e07e4949a55b493f2f056372b6bdbf77  ./tool_collections/snpeff/tool-data/snpeffv_genomedb.loc.sample

69bc49c744c831615d6310516d9455f3  ./data_managers/data_manager_snpeff/tool-data/snpeffv_regulationdb.loc.sample
69bc49c744c831615d6310516d9455f3  ./tool_collections/snpeff/tool-data/snpeffv_regulationdb.loc.sample

9a6e6fdff9f7a66c24499d2bbc07305c  ./data_managers/data_manager_snpsift_dbnsfp/tool-data/snpsift_dbnsfps.loc.sample
9a6e6fdff9f7a66c24499d2bbc07305c  ./tool_collections/snpsift/snpsift_dbnsfp/tool-data/snpsift_dbnsfps.loc.sample
```

And some that were not shared after all:

```
bowtie_indices_color    ./data_managers/data_manager_bowtie_index_builder/tool-data/bowtie_indices_color.loc.sample
bowtie_indices  ./data_managers/data_manager_bowtie_index_builder/tool-data/bowtie_indices.loc.sample
gatk2_picard_index  ./tools/gatk2/gatk2_picard_index.loc.sample
kraken_databases    ./tools/kraken_taxonomy_report/kraken_databases.loc.sample
snpeff_msigdb_database  ./tool_collections/snpsift/snpsift_genesets/tool-data/snpeff_msigdb_database.loc.sample
twobit  ./tools/extract_genomic_dna/twobit.loc.sample
```

To avoid more discrepancies in the future I would propose to add all *.sample.loc file to {tools-iuc}./tool-data and make symlinks to that (../../../tool-data/....loc.sample) so that only the files within {tools-iuc}./tool-data have to be maintained.

For `./tool_collections/snpsift/snpsift_dbnsfp_generic/tool-data/snpsift_dbnsfp.loc.sample` and `./tool_collections/snpsift/snpsift_dbnsfp/tool-data/snpsift_dbnsfp.loc.sample` I don't know what to do. Although the loc file names are identical the number of columns are different. If somebody knows what to do with these files, please give a comment.

Enjoy,

Youri

### CODE REVIEW

**Comment by bgruening** [comment]
@yhoogstrate thats a great idea!
I'm not so sure about the top-level directory called `tool-data`. Maybe `shared/tool-data`?

ping @galaxyproject/iuc

**Comment by peterjc** [comment]
Personally I like the top level ``tool-data/`` (and ``test-data/`` etc) rather than ``shared/tool-data``, but I am not particularly bothered either way.

The top level folder is how I have this setup for my repositories - and that convention works nicely for planemo to find the test files. This is probably irrelevant as here planemo would access the symlinks under each tool's own ``test-data/`` folder.

**Comment by yhoogstrate** [comment]
Very elegant, thanks @jmchilton. Ready to merge according to me

**Comment by yhoogstrate** [comment]
Would you mind to share you opinion @shiltemann @nsoranzo ?

**Comment by nsoranzo** [comment]
:+1: Nice idea! I don't have a strong preference between `tool-data/` and `shared/tool-data/` .

**Comment by bgruening** [comment]
I like the idea, but I would like to keep symlinks and the original structure of a repository. This is easier to get for newcomers.

**Pull request closed without merging**
