### PR TITLE
JQ tool

### PR DESCRIPTION
**Pull request by erasche**
`env -i` is to run jq without an environment. Otherwise you can just do the following which is kinda undesirable.

utvalg_224

### CODE REVIEW

**Comment by erasche** [comment]
(No idea why this is failing)

**Comment by bgruening** [comment]
I guess you already tried to rebase against lastest master?

**Comment by erasche** [comment]
yes. (But note that my [other PR](https://github.com/galaxyproject/tools-iuc/pull/1378) is failing with the same message.) Am I doing something wrong?

**Comment by bgruening** [comment]
Thanks Eric!

**Pull request merged**
