### PR TITLE
Test deseq2

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by yhoogstrate** [comment]
The right conda channels are added with the correct deseq2 package (` bioconductor-deseq2-1.8.2gx|       r==3.2.1_0        46.3 MB`). Installing this should also install R and Rscript. I don't understand why we get this failure:
```
---------------------- >> begin tool stdout << -----------------------
Error: no such directory: /tmp/tmp9A_Al_/job_working_directory/000/8/conda-env/bin
----------------------- >> end tool stdout << ------------------------
---------------------- >> begin tool stderr << -----------------------
/tmp/tmp9A_Al_/job_working_directory/000/8/tool_script.sh: line 9: R: command not found
/tmp/tmp9A_Al_/job_working_directory/000/8/tool_script.sh: line 9: Rscript: command not found
----------------------- >> end tool stderr << ------------------------
```

Shall we run the test one more time to see if then does pass?

**Comment by bgruening** [comment]
Interesting it is this line: `Error: Did not recognize version specification: '=1.8.2gx=r==3.2.1_0'`
This is a conda error, isn't it?

**Comment by yhoogstrate** [comment]
`conda install bioconductor-deseq2=1.10.0=r3.2.2_1` works, so yeah I think this is a bug. However, using `==` in `r==3.2.1_0` makes things unnecessary complicated i.m.o.. If we can still rename it to r3.2.1_0 it would be easier?

**Comment by bgruening** [comment]
Let's see if this works better: https://github.com/galaxyproject/conda-iuc/pull/3

**Comment by yhoogstrate** [comment]
@bgruening it's green :+1:

**Comment by bgruening** [comment]
It was green before, but let's see if this test will work. It will take 10-15min until it reaches the conda storage.

**Comment by yhoogstrate** [comment]
Does it automatically deploy by merging?

**Comment by bgruening** [comment]
@yhoogstrate you are talking about the iuc-conda repo? Yes it does. It's the same build and deploy machinery as in bioconda.

**Comment by yhoogstrate** [comment]
It's failing because of the latest travis PR. Please review and merge this PR: https://github.com/galaxyproject/tools-iuc/pull/711 and then we can merge 711 into 690 and then we're most likely happy again

**Comment by bgruening** [comment]
Arg, this other WIP deseq PR was merged yesterday :(

**Comment by bgruening** [comment]
Ok, I reverted the other WIP deseq2 changes and rebase everything. Hopefully I did not make it worse.

**Comment by yhoogstrate** [comment]
```
Fatal error: cannot open file '/DESeq2/script/deseq2.R': No such file or directory
```
I guess this is because `$DESEQ2_ROOT_PATH` is not being set by conda.

You could obtain it in a hacky way by:
```
if [ -z "\$DESEQ2_ROOT_PATH" ]; then
    export DESEQ2_ROOT_PATH=\$(conda list env | head -n 1 | sed -e "s/^# packages in environment at //g" | sed -e "s/:$//g")"/lib/R/library" ;
fi &&
```

But then the test outputs differ quite a lot.

**Comment by bgruening** [comment]
closing in favour of #714

**Pull request closed without merging**
