### PR TITLE
JSON Collect Data Source

### PR DESCRIPTION
**Pull request by fabio-cumbo**
Extension of the [json_data_source](https://github.com/mdshw5/galaxy-json-data-source) tool. 
It allows to handle archives (gz, bz2, tar, and zip) organizing their content in a collection.
Reference [https://github.com/fabio-cumbo/galaxy-json-collect-data-source](https://github.com/fabio-cumbo/galaxy-json-collect-data-source)

### CODE REVIEW

**Comment by bgruening** [comment]
@fabio-cumbo we don't want to maintain these old tool_dependency files if it not really needed. Can I convince you to create a BioConda package instead?

**Comment by fabio-cumbo** [comment]
@bgruening I can definitely create a BioConda package. Do I have create a pull request on [bioconda/bioconda-recipes/recipes](https://github.com/bioconda/bioconda-recipes/tree/master/recipes)?

**Comment by bgruening** [comment]
Yes, I can give you a hand if you need. Thanks.

**Comment by fabio-cumbo** [comment]
@bgruening I have just created a new BioConda package. Please refer to the following pull request [#4995](https://github.com/bioconda/bioconda-recipes/pull/4995)

**Pull request closed without merging**
