### PR TITLE
Removing max limit to bcftools max-depth parameter

### PR DESCRIPTION
**Pull request by profgiuseppe**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Removing an upper limit to a parameter of bcftools mpilup, as per #4322

### CODE REVIEW

**Review by nsoranzo — APPROVED** [review]

**Comment by wm75** [comment]
@nsoranzo do we want to bump the wrapper version?

**Comment by nsoranzo** [comment]
> @nsoranzo do we want to bump the wrapper version?

Doesn't seem needed to me.

**Comment by nsoranzo** [comment]
> The result is going to be different, it's a problem for the workflow state, this needs a version bump.

@mvdbeek Can you elaborate a bit please? I'd like to understand this well for future reviews.

**Comment by mvdbeek** [comment]
There's a problem that as a user you could define a workflow with the fixed tool version and set the value beyond the previous max. As a user you could reasonably expect that you can take the workflow to any server with the right tool version, except if the tool version is the non-fixed one the workflow won't run. If there's a version bump that's a clean and clear separation.

**Review by nsoranzo — APPROVED** [review]

**Comment by nsoranzo** [comment]
Thanks for taking the time to explain! I've bumped the tool version.

**Pull request merged**
