### PR TITLE
[TESTING, not for merge] Loaded in packages not available in R env

### PR DESCRIPTION
**Pull request by astrovsky01**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)
Loaded in packages not available in R env for me

Stdout: 
```
/galaxy/database/jobs_directory/000/28/conda-env/bin/Rscript
/galaxy/database/jobs_directory/000/28/conda-env/bin/R
 [1] "base"           "BH"             "BiocGenerics"   "BiocParallel"  
 [5] "compiler"       "datasets"       "DelayedArray"   "formatR"       
 [9] "futile.logger"  "futile.options" "graphics"       "grDevices"     
[13] "grid"           "IRanges"        "lambda.r"       "lattice"       
[17] "Matrix"         "matrixStats"    "methods"        "parallel"      
[21] "rjson"          "S4Vectors"      "snow"           "splines"       
[25] "stats"          "stats4"         "tcltk"          "tools"         
[29] "utils"         
```

Stderr:
```
Error in library("DESeq2") : there is no package called ‘DESeq2’
```

### CODE REVIEW

**Comment by mvdbeek** [comment]
Please just update the versions in the existing wrapper and let us know what you think the problem is.

**Comment by astrovsky01** [comment]
Ok, this was the result of breaking it down as far as I could. I'll put the original update in

**Comment by mvdbeek** [comment]
I've canceled the build, the tests won't run without a .shed.yml file anyway.

**Comment by mvdbeek** [comment]
This is going to fail again, you're missing `get_deseq_dataset.R`. Still, can you please just bump the original tools dependencies, in place ?

**Comment by astrovsky01** [comment]
https://github.com/galaxyproject/tools-iuc/pull/2883

**Pull request closed without merging**
