### PR TITLE
Updated busco data manager with new data tables.

### PR DESCRIPTION
**Pull request by Slugger70**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

This PR updates the busco data manager with the expanded odb10 versions of the data files.

### CODE REVIEW

**Comment by Slugger70** [comment]
Addresses #2872

**Comment by mvdbeek** [comment]
Awesome, but it looks like the constructed test URL doesn't exist ?

**Comment by abretaud** [comment]
I will try to update the busco tool during the cofest.
Not sure if a data manager is still needed as busco is now able to download them on demand

**Comment by abretaud** [comment]
No MD needed anymore

**Pull request closed without merging**
