### PR TITLE
Change vSNP processors

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by gregvonkuster** [comment]
This fix is per instruction from @natefoo

**Comment by gregvonkuster** [comment]
The linting error is due to the large files sizes required for testing.

**Review by bernt-matthias — CHANGES_REQUESTED** [review]
Please bump the tool version.

**Comment by gregvonkuster** [comment]
> Please bump the tool version.

No inputs and outputs change, so why the version bump?  Also, I'm the only user that has ever installed them.
```
Times cloned / installed: 2
```
If the version bump is required, we'll need to change the use of the macro to separate the version to each tool since only 2 our of the 5 vSNP tools are affected by this.

**Comment by bernt-matthias** [comment]
>  I'm the only user that has ever installed them.

In this case it might be OK. 

Note, in my experience Galaxy loads only one tool if there are multiple installed with the same version and unfortunately this seems to be the older one. 

I mentioned this somewhere here for data managers https://github.com/galaxyproject/galaxy/pull/12255 .. and also noted this behavior just yesterday on my instance. Guess I should open an issue for this.

**Review by bernt-matthias — APPROVED** [review]
Up to you :)

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/galaxy/issues/13030

**Comment by gregvonkuster** [comment]
> > I'm the only user that has ever installed them.
> 
> In this case it might be OK.
> 
> Note, in my experience Galaxy loads only one tool if there are multiple installed with the same version and unfortunately this seems to be the older one.
> 
> I mentioned this somewhere here for data managers [galaxyproject/galaxy#12255](https://github.com/galaxyproject/galaxy/pull/12255) .. and also noted this behavior just yesterday on my instance. Guess I should open an issue for this.

Hmm...this is a bit concerning.  If we merge this PR without bumping the version, the the Galaxy tool install / uninstall UI will show the tool as installed, but the Install button will be displayed instead of the Uninstall button since the currently installed revision has an update available in the Tool Shed.  

I've always clicked the Install button to get the update.  And after the update is installed, the Uninstall button is displayed for the installed version.

Are you saying that the update is not actually installed in this scenario, and that the original version of the tool (without the update) is used?

**Comment by bernt-matthias** [comment]
The admin UI is not the problem. All revisions are shown (independent of if they are bumped).

The problem is the user interface. If multiple tools with the same id and version are installed then Galaxy will show the tool with the oldest revision to the user (in my experience .. still need a way to verify this).

**Comment by gregvonkuster** [comment]
Can this be merged?

**Comment by gregvonkuster** [comment]
Thanks @bernt-matthias  :)

**Pull request merged**
