### PR TITLE
Fix malt_run code for pulsar

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
> The word 'path' has to be in the parameter template, so I eliminated the unnecessary variable $ref.

I like the simplification. But I also think that the two versions should be equivalent, or am I missing something?

What exactly is the problem that you see on pulsar?

Also "funny": If I execute the tests with conda requirement resolution the tests fail, because there is 1byte size difference. Maybe we can allow for this by using `delta`.

**Comment by bgruening** [comment]
@gregvonkuster you fixed that in Galaxy do you?

**Comment by gregvonkuster** [comment]
> @gregvonkuster you fixed that in Galaxy do you?

No, that fix was for tools that use chromosome lengths (e.g., bedtools), which use the path_len setting.  It was a similar fix for Pulsar though.

**Comment by bgruening** [comment]
But we can close this one isn't it?

**Comment by gregvonkuster** [comment]
> But we can close this one isn't it?

This PR should be merged to make sure the malt_run tool works with the Pulsar job runner.  Thanks!  :)

**Comment by mvdbeek** [comment]
> The word 'path' has to be in the parameter template, so I eliminated the unnecessary variable $ref.

Pulsar receives the templated command, so that comes as a surprise to me. It sounds like you know where that happens though, can you let us know where that is ? 

> This PR should be merged to make sure the malt_run tool works with the Pulsar job runner. Thanks! :)

I strongly disagree, we have to figure out the bugs or else we're playing eternal catch up and that makes it a trial-and-error game to write tools that work on pulsar.

**Comment by gregvonkuster** [comment]
> > The word 'path' has to be in the parameter template, so I eliminated the unnecessary variable $ref.
> 
> Pulsar receives the templated command, so that comes as a surprise to me. It sounds like you know where that happens though, can you let us know where that is ?
> 

I'm just making sure that the word 'path' is in the template to ensure this code works https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/wrappers.py#L54

> > This PR should be merged to make sure the malt_run tool works with the Pulsar job runner. Thanks! :)
> 
> I strongly disagree, we have to figure out the bugs or else we're playing eternal catch up and that makes it a trial-and-error game to write tools that work on pulsar.

Perhaps I've misunderstood at which point in the code the templated command is translated.  I thought that this component of the command line ```--index '$ref'``` would not properly be translated, but if ```'$ref'``` is changed to ```'$reference.fields.path'``` before this code https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/wrappers.py#L54 is reached, I'll close this PR.

**Pull request merged**
