### PR TITLE
Upgrade bandage tool to output tabular format

### PR DESCRIPTION
**Pull request by neoformit**
# Bandage tool upgrade

Bandage tool was configured to output a space-delimited text file, which made for poor compatability in workflows. Output format was changed from `txt` to `tabular` and space deliminations were replaced with single tabs in the output file by piping through `sed`. Tests updated and passed with `planemo test` and tested in the Galaxy UI with `planemo serve`.

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR updates an existing tool or tool collection

### CODE REVIEW

**Comment by bgruening** [comment]
Can you please bump the tool version. Thanks.

**Comment by neoformit** [comment]
@bgruening Is there an issue with the CI? The tests all failed with:
`/tmp/tmp4za_oqu0/job_working_directory/000/2/tool_script.sh: line 9: Bandage: command not found`

**Comment by bgruening** [comment]
Mh, in bioconda only 0.8.1 is available :( 

https://anaconda.org/bioconda/bandage

**Comment by neoformit** [comment]
Ahh ok, I bumped it to `@TOOL_VERSION@+galaxy2` instead. Is that ok @bgruening?

**Comment by bgruening** [comment]
Yes :-)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Merci! Congrats to your first contribution! Welcome to IUC

**Pull request merged**
