### PR TITLE
Update to Version 1.3, adding HiCExplorer support

### PR DESCRIPTION
**Pull request by joachimwolff**

### CODE REVIEW

**Comment by joachimwolff** [comment]
To be honest I do not know what is going on with the failing tools. I added the HiCExplorer support and checked it locally with planemo and it was working.

**Comment by bgruening** [comment]
@joachimwolff one error is that `tools/multiqc/test-data/hicexplorer1.log` is missing.

**Comment by joachimwolff** [comment]
For which reasons the test-data is in .gitignore?

**Comment by mvdbeek** [comment]
> For which reasons the test-data is in .gitignore?

https://github.com/galaxyproject/tools-iuc/blob/master/.gitignore#L48
it's the .log file that is in gitignore, not test-data.

**Comment by joachimwolff** [comment]
@mvdbeek Thanks, this makes sense. Maybe I rename my files even if they are log files.

**Pull request merged**
