### PR TITLE
pe_histogram: add freetype requirement

### PR DESCRIPTION
**Pull request by bernt-matthias**
https://github.com/galaxyproject/tools-iuc/issues/2701

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think the freetype issue has been fixed in openjdk-11.0.1 build 1017 thanks to https://github.com/conda-forge/openjdk-feedstock/pull/60. Not sure that can be used for pe_histogram though.

**Comment by bernt-matthias** [comment]
Let's try

**Comment by bernt-matthias** [comment]
Good news is that don't get the `freetype.so` error openjdk-11.0.1, but instead there is now the same error that indicates missing fonts (which is likely solved by adding fonts-conda-ecosystem)

**Comment by bernt-matthias** [comment]
I suggest to go for the newer JDK + fonts (the generated png files look better: fontwise).

**Pull request merged**
