### PR TITLE
update xml file and add binary

### PR DESCRIPTION
**Pull request by SalihaZ**
despite the validity of the planemo test, phyml does not work on all the instances of galaxy and on galaxy planemo as well.
I added the binary with the xml file.
Could you please check if it works?
Thanks in advance

### CODE REVIEW

**Comment by bernt-matthias** [comment]
What is the actual problem?

**Comment by bernt-matthias** [comment]
Dear @SalihaZ adding a binary is not an option (in my opinion). Feel free to open an issue describing the actual problem or make this an update of phyloseq wo adding a binary here (see also https://github.com/galaxyproject/tools-iuc/pull/4908).

**Comment by SalihaZ** [comment]
Thanks for your reply. Actually when running phyml (on galaxy planemo and on other servers), I got the error: "command not found". I had to specify on the xml file, the path to the binary and it worked.
Is there another solution then adding the binary?

**Comment by bernt-matthias** [comment]
`planemo test` on phyml works for me (see also  https://github.com/galaxyproject/tools-iuc/pull/5536 .. which proves this). Have you setup conda (or docker) correctly?

Can you share a link to the history where you observed an error on a public instance?

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/tools-iuc/issues/5535

**Comment by SalihaZ** [comment]
The `planemo test` worked on phyml but not when I've run the `planemo serve`. 
I've just checked and it's now working on both planemo and Fr instance. Many thanks for you help

**Comment by bernt-matthias** [comment]
In serve you may be able to install the dependencies manually in the admin interface....? 

Thanks for the update.

**Comment by SalihaZ** [comment]
I've been using Galaxy for not very long. Yes indeed, I just discovered that it is possible to manage dependencies on the admin interface.

**Pull request closed without merging**
