### PR TITLE
Update pgt 3.7

### PR DESCRIPTION
**Pull request by lldelisle**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
Awesome!

**Comment by lldelisle** [comment]
Thanks @bgruening 
Would you mind to put it on usegalaxy.eu so I can update my presentation for the European Galaxy days ;-) ?

**Comment by bgruening** [comment]
on it!

**Comment by bgruening** [comment]
https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/pygenometracks/pygenomeTracks/3.7+galaxy0

**Comment by lldelisle** [comment]
Thank you very much

**Pull request merged**
