### PR TITLE
Use threads in the samtools view step.

### PR DESCRIPTION
**Pull request by davebx**
Addresses #614

### CODE REVIEW

**Comment by mvdbeek** [comment]
Hmm, I would probably go for a combined sort and view (`samtools sort - -@2 -l 6 -o hsbam`), in my tests this gave the biggest speedups (and it's recommended in the samtools help). But I didn't test the memory consumption. Also giving it the same amount of GALAXY_SLOTS as hisat might be contraproductive.

**Comment by davebx** [comment]
Combining the steps makes sense, I'll add that. I'm not entirely convinced the potential performance hit for >2 GALAXY_SLOTS is major enough to hardcode a number, but I'm open to the possibility of _becoming_ convinced.

**Comment by mvdbeek** [comment]
I agree, but throwing more than ~ 2-3 threads at samtools doesn't make it faster either, though a combined sort and view alone already gives about a 2-fold speedup. We could try without threading, maybe samtools will not be trailing behind hisat anymore?

**Comment by davebx** [comment]
As it stands, using GALAXY_SLOTS with a default of 2 feels more elegant to me.

**Comment by mvdbeek** [comment]
Yeah, I'm up to testing this!

**Comment by mvdbeek** [comment]
So I tried the old wrapper, and the new wrapper with 1 thread, 2 threads and 8 threads (hardcoded in the wrapper):

old: 32 seconds
1 thread: 20 seconds
2 thread: 21 seconds
8 threads: 21 seconds

This is with GALAXY_SLOTS = 8, same input fastq (single unpaired, 1 million reads). It doesn't seem to hurt the performance, but it also doesn't make it faster, though with higher GALAXY_SLOTS it might actually be faster, so I'd say :+1:

**Comment by davebx** [comment]
I'd say a 35% performance increase is not too terrible.

**Comment by mvdbeek** [comment]
haha, yes, I knew it'd be pretty nice. Same will be true for the bowtie wrappers.

**Comment by mvdbeek** [comment]
@bgruening shouldn't we have hisat2 in testing?

**Comment by mvdbeek** [comment]
alright, thanks @davebx

**Comment by bgruening** [comment]
@mvdbeek yes we should. And because hisat is actually under conda testing I'm fine with pushing it automatically to both TS from travis ...

**Comment by davebx** [comment]
Oh, I was just about to manually update the toolsheds. Will that not be necessary?

**Comment by mvdbeek** [comment]
sorry, it is under testing and finished successfully, I was expecting a second test.

**Comment by mvdbeek** [comment]
I uploaded manually, I guess we would need an additional line in the .travis.yml

**Comment by bgruening** [comment]
@mvdbeek yes we need to tweak travis to make this happen. If you agree we are already two which support this idea. I know @erasche also is in favour of this so maybe we should go for it.

It's a little bit more complicated than just one line in travis. You need to ask if you are actually on the main branch, because you only want to push if we have merged it and we need to take care that it is only triggered if conda testing was done.

**Comment by mvdbeek** [comment]
Yes, I'd :+1: that. It looks pretty straightforward too:
https://docs.travis-ci.com/user/deployment/script/

**Pull request merged**
