### PR TITLE
Modify picard_CollectRnaSeqMetrics.xml to create correct refflat format

### PR DESCRIPTION
**Pull request by cpreviti**
Added only -genePredExt Parameter to picard_CollectRnaSeqMetrics.xml to create correct refflat format

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by nsoranzo** [comment]
@cpreviti The second test of `picard_CollectRnaSeqMetrics` is failing with this message:
```
2019-01-30 10:58:13,982 INFO  [galaxy.tools.verify] ## files diff on /tmp/tmpz0m9QYpicard_CollectRnaSeqMetrics_test2.tab and /tmp/tmppfbF3Ipicard_CollectRnaSeqMetrics_test2.tab lines_diff=4, found diff = 109
```

meaning that with your change the test output file `tools/picard/test-data/picard_CollectRnaSeqMetrics_test2.tab` needs to be updated.

**Comment by cpreviti** [comment]
oh. right. I think an update of the test-output file is in Order. I'll do that...and then do another pull? What would you suggest...?

**Comment by nsoranzo** [comment]
No, you should add the changes to a commit in the same branch (i.e. `master` in this case) and `git push`, which will add the commit to this pull request and restart the tests.

**Comment by nsoranzo** [comment]
If you are using [Planemo](https://planemo.readthedocs.io/) (very recommended!), you can easily update the test data with `planemo test PATH_TO_TOOL.XML --update_test_data` .

**Comment by cpreviti** [comment]
This is a lot more complicated than I thought, I don't know what output it expects...I gave it a new annotation file as input as well as the expected output (from our Galaxy). Nevertheless it finds differences. I'll try with planemo, but getting it up and running here might take a while.
Thanks for the tips!

**Comment by cpreviti** [comment]
The problem was that the version of Picard-tools that I have installed is older than the one in the repository. I adjusted the output to fit the newer version.

**Comment by nsoranzo** [comment]
Thanks @cpreviti and sorry for the late merge!

**Pull request merged**
