### PR TITLE
Updating tools/ena_upload from version 0.6.3 to 0.7.1

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following tool: **tools/ena_upload**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/ena_upload from version 0.6.3 to 0.7.0.

**Project home page:** https://github.com/usegalaxy-eu/ena-upload-cli/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @bedroesb ... this one needs a larger update, isn't it?

**Comment by bedroesb** [comment]
@bgruening correct! And we are working on it as we speak ;) I also want to improve the text inside the tool

**Comment by bgruening** [comment]
@bedroesb have you ever tried uploading larger submissions than viruses?

**Comment by bedroesb** [comment]
@bgruening yes from what I can see: https://www.ebi.ac.uk/ena/browser/text-search?query=ena-upload-cli Not tested by myself ;)

**Pull request closed without merging**
