### PR TITLE
Add Snapatac2 wrappers

### PR DESCRIPTION
**Pull request by y4nnick8**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
.shed.yml file is missing

**Comment by pavanvidem** [comment]
For datasets with larger than 1MB, I used `location` attribute with Zenodo links. All those tests resulted in the error message: `Input staging problem: Timed out after 1800.25 seconds waiting on tool test run`. The Zenodo links are public and accessible. With my local planemo test also I could see the data was fetched into the jwd.

**Comment by pavanvidem** [comment]
I'm using 23.0 profile in the macros. Is it fine or better to go down to 22.05?

**Comment by bgruening** [comment]
I guess its fine, we need to have an IUC rule here at some point.

**Review by bgruening — APPROVED** [review]

**Comment by pavanvidem** [comment]
Thanks a lot @bgruening

**Pull request merged**
