### PR TITLE
Update fastp to version 0.23.2

### PR DESCRIPTION
**Pull request by pvanheus**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]
No new options?

**Comment by pvanheus** [comment]
> No new options?

Do you mean, does the fastp command offer new options in this version? I don't know. What I *do* know is that the current version of fastp available in the toolshed (and on usegalaxy.eu) is broken because it load plotly from a http URL (http://opengene.org/plotly-1.2.0.min.js), and this loading gets blocked by modern web browsers (causing the fastp graphs to not be rendered). This impacts all Galaxy servers that are served over https. The latest version of fastp (0.23.2) doesn't have this problem (it loads plotly from a https URL).

**Comment by bgruening** [comment]
That is a good reason to merge it :)

**Comment by wm75** [comment]
Ah, just a bit late - there is in fact a new deduplication option in this version, but it's ok we don't need this urgently.
The new version is also supposed to be faster for compressed fastq input so that's relevant and the update comes just in time to include it in our next SARS-CoV-2 variation workflow version :)
Thanks @pvanheus !

**Pull request merged**
