### PR TITLE
Update read_group_name_default macro to be used in Python3

### PR DESCRIPTION
**Pull request by gallardoalba**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

This PR modifies the read_group_name_default macro in order to be used in Python3. It has been tested in Bowtie2, BWA-MEM and BWA-MEM2.

### CODE REVIEW

**Comment by gallardoalba** [comment]
Required for https://github.com/galaxyproject/tools-iuc/pull/3968

**Review by mvdbeek — APPROVED** [review]

**Review by bernt-matthias — COMMENTED** [review]
Can you bump a tool that uses this and covers it with a test, otherwise it's hard to know if it works.

**Comment by gallardoalba** [comment]
> Can you bump a tool that uses this and covers it with a test, otherwise it's hard to know if it works.

How can I create a test for it?

**Comment by bernt-matthias** [comment]
Maybe you can find a tool that uses this macro and sets values of params used in the macro in a test. If such a tool is available, then just bump it.

**Comment by gallardoalba** [comment]
> Maybe you can find a tool that uses this macro and sets values of params used in the macro in a test. If such a tool is available, then just bump it.

BWA-MEM is one of the tools that use it; I modified the TOOL_VERSION and SUFFIX_VERSION format in order to launch the tests @bernt-matthias.

**Review by bernt-matthias — APPROVED** [review]
Thanks @gallardoalba, I'm convinced.

Since `"+" < "."` in python the update of the version in bwa won't work. I'm fine if you revert the last two commits.

**Comment by gallardoalba** [comment]
> Thanks @gallardoalba, I'm convinced.
> 
> Since `"+" < "."` in python the update of the version in bwa won't work. I'm fine if you revert the last two commits.

Done @bernt-matthias

**Pull request merged**
