### PR TITLE
Htseq clean 2

### PR DESCRIPTION
**Pull request by yhoogstrate**
Trying to solve the `rm` mistake in https://github.com/galaxyproject/tools-iuc/pull/1102

ping @bgruening @lparsons

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks for fixing my mess.

**Comment by lparsons** [comment]
Hmmm... Seems travis wasn't able to push the update to the toolshed. To preserve the tool chain, I'm still the owner of the repo in the toolshed, but `iuc@galaxyproject.org` has write access.

```
Repository htseq_count updated successfully.
Unexpected HTTP status code: 403: {"err_msg": "You are not the owner of this repository, so you cannot administer it.", "err_code": 403005}
Repository metadata updated successfully for repository htseq_count.
Repo updated but metadata was not.
```

Is there a way we can fix this so Travis can update it, or does it need to be done manually.

**Comment by nsoranzo** [comment]
@lparsons Yes, you need to go to the repo page; in the "Repository Actions" menu on the top right click on "Manager repository administrators". In the page there is a textbox titled "Groups associated with 'htseq_count_admin'", add "Intergalactic Utilities Commission" from the box on its right.

**Comment by lparsons** [comment]
Thanks @nsoranzo. Done and restarted the build.

**Comment by lparsons** [comment]
OK, I'm not quite sure what's going on, but [htseq-count on the toolshed](https://toolshed.g2.bx.psu.edu/view/lparsons/htseq_count/6e5c95760ab1) doesn't seem updated to me.

```
Could not update htseq_count
Unexpected HTTP status code: 400: {"content_alert": "The file \"/srv/toolshed/test/var/data/repos/000/repo_134/static/images/count_modes.png\" contains image content.\n", "err_msg": "No changes to repository."}
Unexpected HTTP status code: 403: {"err_msg": "You are not the owner of this repository, so you cannot administer it.", "err_code": 403005}
Repository metadata updated successfully for repository htseq_count.
Failed to update a repository.
```

**Comment by lparsons** [comment]
Well, I even tried adding `iuc@galaxproject.org` to the admin list on the toolshed. No go. Advice on pushing this manually? Or should we try to fix the Travis issue? @bgruening @nsoranzo

**Comment by bgruening** [comment]
I uploaded it locally.

**Comment by lparsons** [comment]
Thanks @bgruening, I'd have been happy to do it, but wasn't sure if we wanted to fix the automation.

**Comment by nsoranzo** [comment]
@lparsons I suspect the problem is that iuc does not have admin permission on the test ToolShed.

**Pull request merged**
