### PR TITLE
change khmer description

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by mr-c** [comment]
:+1:

**Comment by mvdbeek** [comment]
:+1: 
awesome, thanks @mr-c @bgruening

**Comment by mvdbeek** [comment]
this is now uploaded on the TTS.

**Comment by bgruening** [comment]
@mvdbeek please feel free to upload it to TS if the demultiplexing worked out :)

**Comment by drosofff** [comment]
@mvdbeek can you push to the TS now that it is tested from the TTS ?

**Comment by bgruening** [comment]
@drosofff updated.

**Comment by drosofff** [comment]
@bgruening Thanks !

**Pull request merged**
