### PR TITLE
Sniffles: add test for optional reference history file

### PR DESCRIPTION
**Pull request by fubar2**
FOR CONTRIBUTOR:
* [x] This PR does something else (explain below)

Add a test for history reference

### CODE REVIEW

**Comment by bgruening** [comment]
It tries to create the fai index in the database and not in the working dir. `[E::fai_build3_core] Failed to open FASTA index /tmp/tmpsqavgukc/files/2/a/d/dataset_2ad2a911-6979-4313-aa57-963c7bed6c6a.dat.fai : Read-only file system`

**Comment by fubar2** [comment]
> It tries to create the fai index in the database and not in the working dir. `[E::fai_build3_core] Failed to open FASTA index /tmp/tmpsqavgukc/files/2/a/d/dataset_2ad2a911-6979-4313-aa57-963c7bed6c6a.dat.fai : Read-only file system`

Yep! Thanks - been testing a symlink to the reference so it can index it for itself and just pushed that.

**Review by bgruening — APPROVED** [review]

**Comment by fubar2** [comment]
@bgruening: Not deployed yet?  https://github.com/galaxyproject/tools-iuc/actions/runs/11050755897/job/30699479808 seems to have been skipped?

**Comment by bgruening** [comment]
The TS is updated. Do you have any problems?

**Pull request merged**
