### PR TITLE
Create combined markdown report in weekly CI

### PR DESCRIPTION
**Pull request by bernt-matthias**
I guess writing it to `GITHUB_STEP_SUMMARY` will still not work (because it's to large). But there is only one way to find out.

FOR CONTRIBUTOR:
* [ ] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by mvdbeek** [comment]
It will definitely not work :).
In the CI action we could have another option to just post the summary, without details, and/or an option to just report the failing tool ids.

**Comment by bernt-matthias** [comment]
@mvdbeek:  With https://github.com/galaxyproject/planemo-ci-action/pull/59 this should work now.

**Comment by bernt-matthias** [comment]
Actually https://github.com/galaxyproject/planemo-ci-action/pull/60 :)

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
Cool, thank you!

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/tools-iuc/actions/runs/12398034995

**Pull request merged**
