### PR TITLE
Krona: make wording for text input more generic

### PR DESCRIPTION
**Pull request by shiltemann**
I made a tool to convert mothur taxonomy files to krona text input format, so it is no longer restricted to MetaPhlAn output, changed wording to reflect this.

ping @bebatut

### CODE REVIEW

**Comment by bebatut** [comment]
Nice! Thanks @shiltemann !

**Comment by nsoranzo** [comment]
Maybe use `tabular` instead of `text`?

**Comment by bgruening** [comment]
@nsoranzo  http://www.crs4.it can not be accessed.

**Comment by nsoranzo** [comment]
@bgruening It's back.

**Pull request merged**
