### PR TITLE
datatable support in featureCounts

### PR DESCRIPTION
**Pull request by dpryan79**
This implements my request in #1016, namely that featureCounts support datatables, so people needn't keep uploading the same GTF file.

### CODE REVIEW

**Comment by bgruening** [comment]
Looks great to me.
ping @yhoogstrate

**Comment by bgruening** [comment]
I guess it would make sense to add the same patch to sailfish and salmon and deseq2 - opinions?

**Comment by dpryan79** [comment]
What is the DESeq2 wrapper doing with an annotation?

**Comment by bgruening** [comment]
More tximport before DESeq2: https://github.com/galaxyproject/tools-iuc/blob/master/tools/deseq2/deseq2.xml#L114

**Comment by dpryan79** [comment]
Ah tximport, that makes sense.

@yhoogstrate: I thought a bit about filtering by dbkey, but isn't it the case that dataset collections don't have one? I recall that being the main issue we're having with the non-IUC wrapper when using collections (we get an internal server error).

**Comment by yhoogstrate** [comment]
In that case we leave it as it is. Thanks @dpryan79 @bgruening ! If it turns out to be convenient to use `gene_sets.loc` you could make a PR to the galaxy core code as well.

**Pull request merged**
