### PR TITLE
Update samtools dependencies

### PR DESCRIPTION
**Pull request by davebx**
so they will resolve on install time.

### CODE REVIEW

**Comment by peterjc** [comment]
Nitpick: Overly long commit message (something that was common back when Galaxy was on bitbucket too). Good practice to have a single short line, blank line, then any details.

If you do edit the commit comment, there is also a typo in dependencies.

**Comment by davebx** [comment]
I hope that worked. Per @peterjc's suggestion, I amended the commit message.

**Comment by peterjc** [comment]
GitHub has updated the PR nicely with the replacement commit :)

**Comment by martenson** [comment]
I am not GitHub :)

**Comment by davebx** [comment]
Admit it, you totally are.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/45/
Test (probably) passed

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/46/
Test (probably) passed

**Pull request merged**
