### PR TITLE
allow gzipped fastq files

### PR DESCRIPTION
**Pull request by hrhotz**
In order to get this wrapper to work in our server, I had to add the "--readFilesCommand zcat" option to the STAR command. So, I would like to make this suggestion - Thanks for considering this pull request.

### CODE REVIEW

**Comment by yhoogstrate** [comment]
Hi @hrhotz,

Great to see this PR. I know compression of large files is an active discussion: https://trello.com/c/3RkTDnIn . Until progress on that issue has been made I think it is great to implement it within STAR because FASTQ files can be huge. (I suppose to make use of this auto-decompression must be disabled in Galaxy?)

```zcat``` is not part of https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList so I would like to see zcat as a dependency of STAR. I also think it is very easy to add a test-case.

Most tools have this functionality built-in (in the sense that they determine on the fly whether a file is compressed or not). So I am wondering whether it would be handy to check this within the <command /> tag rather than to use a select box? I'm happy to hear your thoughts on this.

**Comment by nsoranzo** [comment]
@yhoogstrate `zcat` is part of `gzip` (which is also not listed in https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList but is required by many of the listed ones) and is used in many `tools-devteam` tools (e.g. `tool_collections/fastx_toolkit/`) without defining a `requirement`.

**Comment by yhoogstrate** [comment]
@nsoranzo can I add ```gzip``` to the list?

**Comment by nsoranzo** [comment]
@yhoogstrate Not sure what is the process for this, I think @bgruening may know.

**Comment by bgruening** [comment]
There is no official procedure yet. We try to keep this list as short as possible and moving more and more deps into the Tool Shed. If gzip is a hard dependency of any of the listed deps, I don't see a problem in adding it to make this clear. Otherwise, I would prefer to build a package for gzip.

**Comment by nsoranzo** [comment]
Well, it looks like that on Ubuntu gzip is not a hard dependency for those packages, but trying to remove it will print:
```
WARNING: Performing this action will probably cause your system to break!
         Do NOT continue unless you know EXACTLY what you are doing!
To continue, type the phrase "I am aware that this is a very bad idea":
```

**Comment by hrhotz** [comment]
Please ignore my ignorance, but I don't understand why this is an issue:
As Nicola correctly stated: zcat is part of GZIP and is used and required by many instalation processes already. And, as far I understand, even the STAR code is downloaded as a gzipped file (<action type="download_by_url">https://github.com/alexdobin/STAR/archive/STAR_2.4.0d.tar.gz</action> ), so GZIP has already been used.

Hans-Rudolf

**Comment by yhoogstrate** [comment]
> As Nicola correctly stated: zcat is part of GZIP and is used and required by many instalation processes already. And, as far I understand, even the STAR code is downloaded as a gzipped file (https://github.com/alexdobin/STAR/archive/STAR_2.4.0d.tar.gz ), so GZIP has already been used.

Uncompressing RNA-STAR's tar.gz file is done using Python libraries within Galaxy, not using zcat. Installing galaxy does not guarentee zcat is also available on the system (although most systems have it as @nsoranzo pointed out). Different distro's may come with different versions of zcat, gunzip, gzip, uncompress etc. that might use with different command line arguments. It sounds hypothetical but I've seen a galaxy issue were a specific version of the GCC-compiler (https://github.com/galaxyproject/tools-iuc/pull/306) breaks a galaxy tool. Similarly the OSX version of ```sed``` requires ```-i.bak```.  If we include one version of gzip in the tool shed (as proposed in https://github.com/hrhotz/tools-iuc/pull/1) we enforce to use this consistent version of zcat and such issues should not pop-up.

**Comment by hrhotz** [comment]
Hi @yhoogstrate 

Thanks for the clarification. I have merged your pull request into mine

**Comment by bgruening** [comment]
@hrhotz +1 from me. Can you please increase the version number before we merge this?

**Comment by hrhotz** [comment]
you mean the version number of the tool? I don't wanna touch that, since it is set to the version of the STAR code i.e. "2.4.0d"

**Comment by bgruening** [comment]
Yes, just change it to "2.4.0d.1". Otherwise, users with old and new versions installed will find this tool twice but with the same version number.

**Comment by hrhotz** [comment]
done, Thanks

**Comment by bgruening** [comment]
I'm fine with merging this, but I'm not using this tool.
@yhoogstrate any more comments?
Is anyone ok with making the compressed file the default option?

**Comment by peterjc** [comment]
Does this work by forcing a gzipped FASTQ file under one of the existing (normally uncompressed) ``fastq`` Galaxy datatypes?

**Comment by hrhotz** [comment]
@peterjc 
yes, that's how I use it on our develeopment server

**Comment by yhoogstrate** [comment]
I did not test the following, but if you start the command with:

```
if file --mime-type "$singlePaired.input1" | grep -q /gzip$; then
  zcat="         --readFilesCommand zcat " ;
else
  zcat="" ;
fi ;
```

and include ```$zcat``` later on:
```
... truncated ...

     #if str($singlePaired.sPaired) == "paired"
             $singlePaired.input2
     #end if 

     \$zcat

	 --runThreadN \${GALAXY_SLOTS:-4}
```

I suppose you can solve this without using an extra select box:
```
        <param name="compressed" type="select" label="is the data gzipped">
              <option value="gzipped" selected="true">gzipped</option>
              <option value="">not compressed</option>
        </param>
```

**Comment by hrhotz** [comment]
yes, might work.
Though personally, for our local installation, I would prefer the extra select box. Our users should know what kind of data they are working with (in this case: is gzipped or not) and not just press the 'red' button and the analysis gets done for them. That is just our philosophy on how we use Galaxy at our institute.

**Comment by peterjc** [comment]
I would also prefer auto-detection of gzipped FASTQ from an end-user experience perspective (and really want Galaxy to track this itself rather than pushing it onto the tool authors/wrappers).

Many tools do support gzip input themselves, although sometimes via the filename extension which Galaxy undermines by using ``*.dat``. So something like the MIME type trick from @yhoogstrate ought to work.

**Comment by yhoogstrate** [comment]
@bgruening @mvdbeek Any suggestions on whether or not to use file/magic to determine compression on the fly or whether to do this as with a galaxy argument (and whether decompression should be default or not)?

**Comment by bgruening** [comment]
@yhoogstrate imho this should be an integral part of the framework. It should handle compressed files nicely and uncompress transparently, if a tool can not handle it. But this requires a lot of framework work :(

**Comment by yhoogstrate** [comment]
I totally agree that would be the most elegant solution. But if there are no plans to include this within the next year or so, I think we should make a decision on this PR.

**Comment by hrhotz** [comment]
@yhoogstrate  don't worry about the PR in it's current form. If time permits, I will make a new PRusing the latest version of STAR (STAR_2.5.0a) within the next few days/week. There are some nice new features in this version, which are especially usefull for our local set-up.

**Comment by yhoogstrate** [comment]
@hrhotz Awesome, indel realignment and built-in gene counting!

**Comment by hrhotz** [comment]
@yhoogstrate well, actually it is the new "--outSAMmultNmax parameter" to limit the number of output alignments for multimappers, which is of big interest to us

**Comment by zipho** [comment]
is there still work on this, I noticed there is also discussion on the same in:
https://github.com/bxlab/galaxy_hackathon/issues/2
https://github.com/bxlab/galaxy_hackathon/issues/38

Perhaps we should a combined effort around this.

**Comment by yhoogstrate** [comment]
I am closing this PR because these commits have been cherry-picked into the large STAR update.

**Pull request closed without merging**
