### PR TITLE
Additional includes for cairo fontconfig r os x

### PR DESCRIPTION
**Pull request by mvdbeek**
should fix the last issues discussed in http://dev.list.galaxyproject.org/gcc-error-during-pixman-0-32-4-installation-on-Mac-OS-X-10-11-td4668455.html

### CODE REVIEW

**Comment by nsoranzo** [comment]
I've never heard about `LD_INCLUDE_PATH` and also a Google search suggests that it does nothing. Is it really needed?

**Comment by mvdbeek** [comment]
Interesting ... I'll double-check, but I believe I had to set this to get the fontconfig includes ...

**Comment by mvdbeek** [comment]
http://stackoverflow.com/questions/5523545/does-ld-include-path-actually-do-anything

okay, learning something new every day ... I guess it wouldn't hurt to know the basics of C.
This leaves the question ... why did it help? Are some compilers anticipating confused users to supply LD_INCLUDE_PATH ?
In any case LD_INCLUDE_PATH shouldn't be necessary, since we got the C_INCLUDE_PATH ( on github, but not in the toolshed (for fontconfig ).

**Comment by nsoranzo** [comment]
LGTM

**Pull request merged**
