### PR TITLE
Update StringTie to wrap version 1.0.1, add tests for ballgown output.

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/35/
Test (probably) passed

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/36/
Test (probably) passed

**Comment by bgruening** [comment]
I like this in general, not sure about the normalization. It does not improve readability.

**Comment by jmchilton** [comment]
Yeah - lets say ``planemo normalize`` is not for actually modifying tools -  that was a mistake on my part.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/37/
Test (probably) passed

**Comment by erasche** [comment]
Yikes, this shouldn't have triggered four builds. wtf.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/38/
Test (probably) passed

**Comment by jmchilton** [comment]
:+1:

**Comment by erasche** [comment]
+1 from me.

**Comment by erasche** [comment]
@bgruening merge if you're happy!

**Comment by bgruening** [comment]
Done!

**Pull request merged**
