### PR TITLE
Update to include newest SILVA reference files

### PR DESCRIPTION
**Pull request by pmpcosta**
Update includes SILVA reference files versions 132 and 138.

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by pmpcosta** [comment]
outdated by a different PR

**Comment by bgruening** [comment]
@pmpcosta can we help you here? Or did I miss the other PR, that looks like a nice improvement!

**Comment by nsoranzo** [comment]
@bgruening I think it's now included in #1721 .

**Comment by bgruening** [comment]
I see, great. Thanks for pointing out!

**Pull request closed without merging**
