### PR TITLE
Requested rename made. Fixed typo causing linter to fail

### PR DESCRIPTION
**Pull request by KyleL1998**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Shortened the output names as It was causing problems in some pipelines

### CODE REVIEW

**Comment by bgruening** [comment]
@KyleL1998 can you explain what the issue with the output names is? The names should not influence anything and I would favor more descriptive ones.

**Comment by KyleL1998** [comment]
Keeping the name as ‘Simulated of Illumina sequencing of ‘. It makes it so that read lengths are so long that they no longer work with downstream pipelines.

**Comment by bgruening** [comment]
Which tools does not work @KyleL1998 downstream? Maybe this tool should be changed instead?

**Comment by Takadonet** [comment]
@bgruening a good portion of  tools we use cannot handle having '(' ')' or white-spaces in their file name. We are in the process of converting them to use collection identifier instead but this fix allows my users to move forward with their work.

**Comment by nsoranzo** [comment]
I agree with @bgruening, the changes to `tools/art/art_illumina.xml` are a workaround that is not in line with IUC goals of providing "best practice" tools.
If you really needs them, I'd suggest to patch the labels in your installed copy of the tool.

The fix to `tools/art/art_solid.xml` should be merged though.

Sorry for the hindrance.

**Comment by KyleL1998** [comment]
One of those git disasters...

**Pull request merged**
