### PR TITLE
Fix to Raceid 

### PR DESCRIPTION
**Pull request by mtekman**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This provides fixes for diffgene testing, and also now provides a normalised matrix as output as per user request.

A mass tidy up of macros is also underway.

Features to be included in this PR are plotting of specific clusters, and using custom gene names.

### CODE REVIEW

**Comment by mtekman** [comment]
I did :-)

https://github.com/galaxyproject/tools-iuc/pull/2528/files/ee3ad6116c29db417c70a616ffee559423573c99#diff-d979b0d3f042e962ec4a55e48548e4efR29

**Comment by bgruening** [comment]
https://github.com/galaxyproject/tools-iuc/pull/2528/files/ee3ad6116c29db417c70a616ffee559423573c99#diff-4cb07ec886a5748f5cb7627b253545aaR1 --> still ends on .1 this can go away?

**Comment by mtekman** [comment]
oh good point, didn't see that

**Comment by bgruening** [comment]
Merci!

**Pull request merged**
