### PR TITLE
update readgroup macros

### PR DESCRIPTION
**Pull request by bernt-matthias**
was originally suggested here https://github.com/galaxyproject/tools-iuc/pull/5963 but better done separately .. with bumping all tools using the macros

Just noticed that `bowtie2` uses more or less the same macros. Should we work toward that also bowtie2 uses these macros? Or the other way round?

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by wm75** [comment]
So if there are no changes required to any tool to adjust for the macros update, then why not do it as part of the bwa PR?

Other tools would get the changes on their next update naturally, and we don't create additional wrapper versions.

**Comment by wm75** [comment]
I see, the picard tools are a single repo so we would need to make sure  that #5963 gets merged before #5297 and that the latter bumps the add or replace rg tool.

**Comment by bernt-matthias** [comment]
> So if there are no changes required to any tool 

It's a change to the tool :) But alongside with https://github.com/galaxyproject/tools-iuc/pull/5297#issuecomment-2095433475 I will refrain from this here.

**Comment by wm75** [comment]
Sorry @bernt-matthias if that came across wrong. I'm also not entirely sure which is the better way to go here,I'd just like to get the bwa update merged this week and, if possible without breaking other stuff :-)

**Comment by wm75** [comment]
> > So if there are no changes required to any tool
> 
> It's a change to the tool :) But alongside with [#5297 (comment)](https://github.com/galaxyproject/tools-iuc/pull/5297#issuecomment-2095433475) I will refrain from this here.

Sure, what I meant is none of the tools here will require additional work in a separate PR to make it compatible with the new macro version.

**Comment by bernt-matthias** [comment]
> that came across wrong

no worries :) .. all good. 

IMO Best would be to just revert the changes to the macro and ignore the linter warnings. Deployment will ignore all warnings.

**Pull request closed without merging**
