### PR TITLE
Updating tools/king from version 2.2.4 to 2.2.7

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/king**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/king from version 2.2.4 to 2.2.7.

**Project home page:** http://people.virginia.edu/~wc9c/KING

### CODE REVIEW

**Comment by bernt-matthias** [comment]
2.2.6 seems to contain a few new parameters: https://www.kingrelatedness.com/history.shtml

**Comment by simonbray** [comment]
@mtekman maybe interesting for you? (just ignore the ping if not)

**Comment by mtekman** [comment]
Cheers, I'll add the missing pca parameter

**Comment by bernt-matthias** [comment]
Superseded by https://github.com/galaxyproject/tools-iuc/pull/4498

**Pull request closed without merging**
