### PR TITLE
Fix .shed.yml for pbgcpp

### PR DESCRIPTION
**Pull request by mvdbeek**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bernt-matthias — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Thanks @mvdbeek

**Comment by mvdbeek** [comment]
```
{"err_msg": "Metadata may have been defined for some items in revision '29eec6c7bab2'.  Correct the following problems if necessary and reset metadata.<br/><b>pbmm2.xml<\/b> - This file requires an entry in the tool_data_table_conf.xml file.  Upload a file named tool_data_table_conf.xml.sample to the repository that includes the required entry to correct this error.<br/><br/>"}
```
same old stuff ;)

**Comment by bernt-matthias** [comment]
Those error messages are really not helpful. I still have no idea what this means :(

**Comment by mvdbeek** [comment]
What are you referring to ? The error message is pretty clear here.

**Comment by bernt-matthias** [comment]
> Metadata may have been defined for some items in revision '29eec6c7bab2'. 

- Not sure if this is refering to an error. Does not sound like.
- What kind of revision is this. Seems not to be git / hg? 
- What kind of metadata is meant. Completely unclear.

To me this sentence seems only to be misleading and not helpful in any way.

> pbmm2.xml: This file requires an entry in the tool_data_table_conf.xml file. Upload a file named tool_data_table_conf.xml.sample to the repository that includes the required entry to correct this error

This seems completely new to me. What kind of entry is needed here. But maybe I missed something in the last years :)

**Comment by mvdbeek** [comment]
> This seems completely new to me.

Always been there, and it has always been necessary to include the necessary sample files for tools that use data tables. I really don't know how this could be any clearer, it says exactly what to do to fix this.

> * What kind of metadata is meant. Completely unclear.

Repository metadata, what else could it be ?

**Comment by bernt-matthias** [comment]
But `tool_data_table_conf.xml.sample` is inlcuded, isn't it?

And I do not see which _required entry_ is missing. Also if planemo finds out that an entry is missing. Couldn't it be more specific in the error message, e.g. entry "XYZ" is missing?

Is it `tool-data/all_fasta.loc` that is missing?

**Comment by mvdbeek** [comment]
It is not included (https://github.com/galaxyproject/tools-iuc/tree/main/tools/pbmm2), and it is the tool shed that does the check.

**Comment by bernt-matthias** [comment]
Ah :) Was looking at `pbgcpp` .. thanks for pointing this out.

**Pull request merged**
