### PR TITLE
change defaults for spliced alignments

### PR DESCRIPTION
**Pull request by bgruening**
Is this ok?
It was pretty confusing for a few of our users to have spliced alignments deactivated by default.

### CODE REVIEW

**Comment by bgruening** [comment]
I don't think so. Rerun should not be affected as you said.

**Comment by bgruening** [comment]
@mblue9 not your fault. This was included also in old version, just wanted to have your feedback here as you touched the code last time.

**Comment by bgruening** [comment]
@yhoogstrate please merge :)

**Comment by mblue9** [comment]
Ah I see and phew!... all good so :smile:

**Pull request merged**
