### PR TITLE
--window_size does not exists in stacks_population

### PR DESCRIPTION
**Pull request by bgruening**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Good one. 

Tests are failing because Galaxy gets the data set names from the relative paths given in the tests .. which makes liking fail. I had suggested a fix https://github.com/galaxyproject/galaxy/pull/7372 here which was not merged for various (valid) reasons. 

Currently I don't see a simple solution for this problem... but I'm wondering when this broke. 

I'm quite sure that the tests build on each other and assume that the data set names are the sample names (ie the file's basenames). So if you replace the `/` in the file name its not the sample anymore. 

I guess on the long run it might be a good idea to have an `id="..."` attribute for all collections and data sets allowing to name everything explicitly...

**Comment by nsoranzo** [comment]
> Currently I don't see a simple solution for this problem... but I'm wondering when this broke.

@bernt-matthias @mvdbeek I've bisected this issue and it was broken by https://github.com/galaxyproject/galaxy/commit/6791f3b99905ac0db0a8e2c23f38a4bce8b1d3c8

**Comment by bernt-matthias** [comment]
@nsoranzo I'm not understanding what is done in the commit. my guess would have been that some `basename` calls need to be distributed in this this function

https://github.com/galaxyproject/galaxy/blob/6791f3b99905ac0db0a8e2c23f38a4bce8b1d3c8/lib/galaxy/tools/verify/interactor.py#L280

**Comment by nsoranzo** [comment]
Rebased, it's green now.

**Comment by bernt-matthias** [comment]
I integrated this here: https://github.com/galaxyproject/tools-iuc/pull/4194

**Comment by bernt-matthias** [comment]
My bad... this is not stacks2...

**Comment by bernt-matthias** [comment]
@bgruening good to merge?

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
