### PR TITLE
Updating tools/bwameth from version 0.2.2 to 0.2.3

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/bwameth**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/bwameth from version 0.2.2 to 0.2.3.

**Project home page:** https://github.com/brentp/bwa-meth/releases

### CODE REVIEW

**Comment by bgruening** [comment]
The new version added support for BWA2 indices, nothing we need here strictly.

**Review by bgruening — APPROVED** [review]

**Comment by bernt-matthias** [comment]
So we could use `bwa_mem2_indexes` here: https://github.com/galaxyproject/tools-iuc/blob/5275667f1a59335340e07f7633a56821fb73f407/tools/bwameth/bwameth.xml#L94

in addition / as alternative?

**Comment by bgruening** [comment]
I would decide for one and since BWA is more common and we all have indices for that one already I would keep it like it is for the time being. Or is it really worth the pain of creating new indices and maintaining them?

**Comment by bernt-matthias** [comment]
> since BWA is more common and we all have indices for that one already I would keep it like it is for the time being

Just to be sure: its not the bwa data data table, but the bwameth data table.

Currently there are 3 data data tables:

- bwa_mem_indexes
- bwa_mem2_indexes
- bwameth_indexes

(where the second has apparently no data manager). So I thought that it might be a possibility to drop one? Or create a unifying data table that also stores the creation method in an extra column.

But we can merge for now .. and maybe open an issue.

**Comment by bgruening** [comment]
> But we can merge for now .. and maybe open an issue.

I like that.

**Comment by bernt-matthias** [comment]
Opened an issue https://github.com/galaxyproject/tools-iuc/issues/4319

**Pull request merged**
