### PR TITLE
Heatmap2: uncouple from ggplot2

### PR DESCRIPTION
**Pull request by mblue9**
- Remove heatmap2 from ggplot2 and make it a separate tool xref https://github.com/galaxyproject/tools-iuc/issues/2275
- Make Euclidean distance the default (same as heatmap.2 default)
- Add parameters for Distance and Clustering (just added two options for each, could add others later)

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by nsoranzo** [comment]
@mblue9 Thanks for working on this! I've pushed a commit, can you check the changes are OK for you?

**Comment by mblue9** [comment]
Looks great @nsoranzo 👍 thanks for improving it!

**Comment by mblue9** [comment]
I've just had a request from a user to add an option to only cluster rows not columns, so could be good to add a parameter to enable clustering of rows, columns or both. I could add that to this PR tonight/tomorrow or after this is merged?

**Comment by nsoranzo** [comment]
@mblue9 I think it would be good to add to this PR, there's no rush.

**Comment by mblue9** [comment]
Great! Thanks for merging @nsoranzo

**Pull request merged**
