### PR TITLE
cleanups of htseq-count

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
This explains why this tool was never really tested and fixes https://github.com/galaxyproject/tools-iuc/issues/1072
ping @lparsons

**Comment by lparsons** [comment]
Thanks for the detective work @bgruening, but something's fishy here. The conda env can't be built due to conflicting samtools versions, yet these tests seem to pass...

**Comment by lparsons** [comment]
I'm not sure, but the version of htseq-count should probably be bumped to `0.6.1galaxy3`.

**Comment by nsoranzo** [comment]
@bgruening Why move only the `.shed.yml` to `deprecated/`? I'd say move everything there or just remove everything.

**Comment by nsoranzo** [comment]
Superseded by #1126.

**Pull request closed without merging**
