### PR TITLE
Updating tools/pretext tool version(s)

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/pretext**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

Please see https://github.com/planemo-autoupdate/autoupdate for more information.

### CODE REVIEW

**Comment by bgruening** [comment]
@gallardoalba can you please check for param changes?

**Review by bernt-matthias — APPROVED** [review]

**Comment by gallardoalba** [comment]
No changes at all https://github.com/wtsi-hpag/PretextMap/compare/0.1.7...0.1.8

**Comment by bgruening** [comment]
@simonbray do you think we can include such a link from Cristobal in the bot message?

**Comment by simonbray** [comment]
Maybe we can do something with the `homepage_url` entry in the shed.yaml file

https://github.com/planemo-autoupdate/autoupdate/issues/11

**Pull request merged**
