### PR TITLE
Update ENA upload tool to latest version

### PR DESCRIPTION
**Pull request by bedroesb**
Functionally, nothing has changed to the tool, except updated support for the templates it uses as input

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bedroesb** [comment]
Not sure if I understand what is going wrong in the logs :thinking:

**Comment by bgruening** [comment]
We made the linting stricter and now all Warnings needs to be fixed.

```
 Applying linter tests... WARNING
.. WARNING: Test should specify 'expect_num_outputs' if outputs have filters
.. WARNING: Test should specify 'expect_num_outputs' if outputs have filters
.. WARNING: Test should specify 'expect_num_outputs' if outputs have filters
.. WARNING: Test should specify 'expect_num_outputs' if outputs have filters
.. WARNING: Test should specify 'expect_num_outputs' if outputs have filters
.. WARNING: Test should specify 'expect_num_outputs' if outputs have filters
.. WARNING: Test should specify 'expect_num_outputs' if outputs have filters
.. CHECK: 10 test(s) found.
Applying linter inputs... WARNING
.. WARNING: Conditional [conditional_viral_metadata] first param of type="boolean" is discouraged, use a select
.. WARNING: Conditional [conditional_viral_metadata] first param of type="boolean" is discouraged, use a select
.. INFO: Found 146 input parameters.
Applying linter command... CHECK
.. INFO: Tool contains a command.
Applying linter citations... WARNING
.. WARNING: Found no valid citations.
```

**Comment by bedroesb** [comment]
I think I figured it out. I took out the non-viral sample submission for interactive submissions out, but I will test this further and update the training about this. Reason: No metadata can be given in the non-viral one, making this option useless

**Comment by bedroesb** [comment]
@bgruening The only error that I still am having is `WARNING: Tool Shed doesn't render markdown, README.md is invalid readme.` This makes me wonder how this readme got in this repo in the first place, since the lint check exists already since 8 years I see.

**Comment by bedroesb** [comment]
TO DO: update instruments used in interface

**Comment by bedroesb** [comment]
@bgruening I think I finally made it working :) All the dropdowns are updated too. Will also update the training.

**Comment by bgruening** [comment]
Thanks @bedroesb! Looks good to me. I don't fully understand, however, why you removed the `non-viral sample submission`. Can you explain that more? Or what is the new way of submitting non-viral samples?

@neoformit this might be interesting for you.

**Comment by bedroesb** [comment]
The non-viral sample submission is still supported when using spreadsheets, but would be taken out from the interactive submissions. This is a function we noticed was not really used anyway + it does not allow you to add checklist specific sample attributes, making such submissions quite bad in quality.

**Comment by bedroesb** [comment]
@bgruening you think I should keep the minimal sample option in for the interactive submition?

**Comment by bgruening** [comment]
I think it would be nice to offer this option for users who really just want to submit 1-2 samples. But I understand that the maintenance overhead might be too large. Your call.

**Comment by bedroesb** [comment]
@bgruening  I brought back the minimal interactive submission but wrote a help text to advice that one is better of using checklist specific sample attributes through the spreadsheets when doing a non-viral submission.

I just don't understand the error of the last test:
```
(text 10): parameter 'upload_files': specify a dataset of the required format / build for parameter
```

I use the exact same syntax in other tests who do not fail...

**Comment by bedroesb** [comment]
the line where it fails: https://github.com/bedroesb/tools-iuc/blob/96204e08697e34cf68fd4b03ba304cd68d2a7c8c/tools/ena_upload/ena_upload.xml#L877

**Comment by bedroesb** [comment]
@bgruening It took longer than expected but we are now in good shape I think! It would be nice to get this one live before the biohackathon :)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Very cool, thanks a lot @bedroesb

**Pull request merged**
