### PR TITLE
Idr update modify

### PR DESCRIPTION
**Pull request by lldelisle**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [X] - This PR updates an existing tool or tool collection

This PR:
- change omero-py version from 5.7.1 to 5.10.1.
- add `.vscode` to gitignore (I hope you don't mind)
- add an option which will download all images of a dataset

### CODE REVIEW

**Comment by lldelisle** [comment]
It looks like the github actions has not been launched...

**Comment by lldelisle** [comment]
Youpi. I finally managed.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
merci!

**Comment by lldelisle** [comment]
Thanks for your reactivity in all the github repositories.

**Pull request merged**
