### PR TITLE
Add ncbi_accession2taxid data table sample

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by gregvonkuster** [comment]
I'm hoping this will fix this https://github.com/galaxyproject/tools-iuc/issues/4277

**Comment by bernt-matthias** [comment]
> I'm hoping this will fix this #4277

Any idea if this can be tested before merging? Maybe push to the TTS?

**Comment by gregvonkuster** [comment]
> > I'm hoping this will fix this #4277
> 
> Any idea if this can be tested before merging? Maybe push to the TTS?

Are you referring to planemo?  If so, I've never used plaemo to upload to TS or TTS.  Please feel free if you want to though.

**Comment by bgruening** [comment]
You should try `planemo shed_upload` is cool :)
But that looks good to me.

**Comment by bernt-matthias** [comment]
Bump needed? Maybe we should remove the DM version, because it has been deprecated https://github.com/galaxyproject/galaxy/pull/12255

**Comment by gregvonkuster** [comment]
> You should try `planemo shed_upload` is cool :)
> But that looks good to me.

Yeah, but it's also a bit dangerous, isn't it?  No reviews at the TS end after a planemo shed_upload can result in broken repositories like this one for the diamond DM and this one for the freebayes tool https://github.com/galaxyproject/tools-iuc/issues/4270.

**Comment by bgruening** [comment]
> > You should try `planemo shed_upload` is cool :)
> > But that looks good to me.
> 
> Yeah, but it's also a bit dangerous, isn't it? No reviews at the TS end after a planemo shed_upload can result in broken repositories like this one for the diamond DM and this one for the freebayes tool #4270.

Only test on the TTS :) But yes, these missing files should be linted by planemo, so those test uploads are not necessary.

**Comment by gregvonkuster** [comment]
> Bump needed? Maybe we should remove the DM version, because it has been deprecated [galaxyproject/galaxy#12255](https://github.com/galaxyproject/galaxy/pull/12255)

Done, tanks!  Can we get this merged asap?  I've got customers waiting for new diamond tools I've installed, and I need to get some references built.

**Review by bgruening — APPROVED** [review]

**Comment by gregvonkuster** [comment]
Hmm..still broken:
```
Metadata may have been defined for some items in revision '431198ad8a09'. Correct the following problems if necessary and reset metadata.
data_manager_diamond_database_builder.xml - This file refers to a file named ncbi_accession2taxid.loc. Upload a file named ncbi_accession2taxid.loc.sample to the repository to correct this error.
data_manager_diamond_database_builder.xml - The tool diamond_database_builder targets version 21.05 of Galaxy, you should upgrade Galaxy to ensure proper functioning of this tool.
```
The first error should have been resolved with this PR - no idea what's going on there.  For the second one, it seems the profile version has to be lowered.  What should it be?  Maybe if we correct that one,  the first one will go away?

Does anyone have this tool installed and working in a Galaxy instance?

**Pull request merged**
