### PR TITLE
Datamanager bowtie update

### PR DESCRIPTION
**Pull request by mvdbeek**
This uses bowtie 1.1.2, which is also available in conda.

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek the database is compatible with the older versions? Aka we can leave the old data_table entry?

**Comment by mvdbeek** [comment]
That is my understanding, but I will check this.

**Comment by mvdbeek** [comment]
Yes, all is well. Indexes generated with bowtie-1.1.2 continue to work with 0.12.7 (both colorspace and regular fastqsanger), and 0.12.7 indexes work with bowtie-1.1.2.

**Comment by mvdbeek** [comment]
@bgruening ready?

**Comment by bgruening** [comment]
Oh yes, thanks for checking!

**Pull request merged**
