### PR TITLE
fixed some arguments(biom-convert)

### PR DESCRIPTION
**Pull request by RZ9082**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

The `--collapsed-observations` and `--collapsed-samples` arguments were mixed up.

### CODE REVIEW

**Review by bernt-matthias — CHANGES_REQUESTED** [review]
Good fix. We need to bump the tool version.

Let me know if you plan to fix the linter warnings or if I should just ~fix~ merge

**Comment by RZ9082** [comment]
@bernt-matthias Do you mean to 2.1.15? this would result in a linter warning 
`Applying linter biocontainer_registered... WARNING
.. WARNING: Failed to find a BioContainer registered for these requirements.`

**Comment by bernt-matthias** [comment]
Just increase the `VERSION_SUFFIX` to `1`: https://github.com/galaxyproject/tools-iuc/blob/26ac2727c364e23b4bdd37f6ea2c0a475992e506/tools/biom_format/macros.xml#L9

**Review by bernt-matthias — APPROVED** [review]

**Comment by bernt-matthias** [comment]
I restarted CI. It's now deployed.

**Comment by RZ9082** [comment]
Thanks:)

**Pull request merged**
