### PR TITLE
Update anndata

### PR DESCRIPTION
**Pull request by mvdbeek**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by mvdbeek** [comment]
Locally I managed to run this against the tutorial data without crashing (as opposed to 0.74), let's see if this also passes tests.

**Comment by bgruening** [comment]
@mtekman can you have a look please?

Thanks @mvdbeek

**Comment by mtekman** [comment]
@bgruening  it's known, but I'm hesitant to work on it because it's likely it will have to be *completely* rewritten when the ScanPy tools are upgraded to latest.

I will look for an easy patch, but I doubt I can fix it before tomorrow

**Comment by mvdbeek** [comment]
I am updating them now, despite me not being associated with the tutorial. As it is now, users cannot run it, unless they remember to change each version individually. Please also see the slack channel where someone has already run into this. The tests are passing here, and the scanpy differences are minimal.

**Comment by mtekman** [comment]
Thanks Marius, I welcome any help -- I've struggled to update with patching this many times so I felt that a rewrite was in order. When I last patched it, it was working with the materials, but now it's not, for reasons I do not know.

For now, shall we disable the latest version?

**Comment by mvdbeek** [comment]
Maybe removing is the right thing, but let me see if I can fix up the failing scanpy tests.

**Comment by mtekman** [comment]
I'm going to change the tutorial links for now to point to `0.6.22.post1+galaxy4`

**Review by mtekman — APPROVED** [review]

**Review by bgruening — APPROVED** [review]

**Pull request merged**
