### PR TITLE
limma-voom tool: upgrade conda env and fix xml file

### PR DESCRIPTION
**Pull request by drosofff**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

limma's conda environment has been broken for several versions. Nobody uses limma anymore?

### CODE REVIEW

**Comment by drosofff** [comment]
Am I stupid or has `lintr` lost his mind?

**Comment by bernt-matthias** [comment]
We are now using styler via https://github.com/galaxyproject/tools-iuc/blob/main/.github/styler.R. You may also use this script to fix the "problems" automatically.  But we can as well ignore r lint problems.

**Review by bernt-matthias — APPROVED** [review]
Don't know anything about the tool. But tests pass and the changes are mostly just changing style (except for the bump). Fine for me.

Thanks

**Comment by drosofff** [comment]
> We are now using styler via https://github.com/galaxyproject/tools-iuc/blob/main/.github/styler.R. You may also use this script to fix the "problems" automatically. But we can as well ignore r lint problems.

Ah ! I have lost my mind yesterday because my local lintr was happy ! It make sense now.

I will have a look to styler.R in local, why not. I hope it will be a bit more verbose than in the actions workflow...

But I will not pass another night on this tool, I need to move my neuroses onto something else 😉

**Comment by bernt-matthias** [comment]
Can you merge: https://github.com/ARTbio/tools-iuc/pull/3

I did: 

```
conda create --strict-channel-priority --solver libmamba --override-channels --channel conda-forge --channel bioconda --channel defaults --name r-styler r-styler r-argparse
./.github/styler.R --dry off tools/limma_voom/limma_voom.R
```

Btw: the solution for problems with conda envs is in most cases to switch to containers.

**Pull request merged**
