### PR TITLE
Update GECKO to 1.1.b fixes important error

### PR DESCRIPTION
**Pull request by estebanpw**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
@estebanpw is it possible to include a test so that the error that you now fixed is tested?

**Comment by estebanpw** [comment]
> @estebanpw is it possible to include a test so that the error that you now fixed is tested?

That is a great idea! Actually the error only happened in usegalaxy and I was kind of baffled with it. Let me add it to the test

**Comment by estebanpw** [comment]
Although on second thought, there is already a test that passes (both in my local machines and in the tool testing). I was somewhat surprised that it failed on usegalaxy.eu

It is this test:
```
<test expect_num_outputs="2">
            <param name="query" value="hyopneumoniae_16S.fasta"/>
            <param name="db" value="flocculare_16S.fasta"/>
            <param name="kmer" value="8"/>
            <param name="minlen" value="20"/>
            <param name="similarity" value="50"/>
            <param name="selection_mode" value="alignments"/>
            <output name="csv_output1" ftype="csv">
                <assert_contents>
                    <has_n_lines n="20"/>
                </assert_contents>
            </output>
            <output name="alignments2" ftype="txt">
                <assert_contents>
                    <has_n_lines n="96"/>
                </assert_contents>
            </output>
        </test>

```

However I think its OK now because I found two *small* memory leaks in valgrind that I was able to fix. Any thoughts?

**Comment by estebanpw** [comment]
A test is already available and passes, but this was the case as well in the previous version and it only failed in the usegalaxy machines

Not sure if there is a way I can try this directly on the usegalaxy machines? is there a container I can work with? Thanks a lot @bgruening

**Comment by bgruening** [comment]
@estebanpw if you use planemo you can test it in a local Galaxy instance with `planemo serve ...`

**Comment by estebanpw** [comment]
> 
> 
> @estebanpw if you use planemo you can test it in a local Galaxy instance with `planemo serve ...`

First, I have included the exact test that I ran on usegalaxy.eu (same files, they are 1 MB each thou, let me know if you want me to remove them after you can see that the tests pass OK) 

Then I ran `planemo test` and all tests are successful.

Last, I also created a disposable galaxy instance with `planemo serve` and manuall ran the experiment that I did on usegalaxy.eu and it has also succeeded.

Lets see if CI runs OK as well

planemo output:
```
All 3 test(s) executed passed.
gecko[0]: passed
gecko[1]: passed
gecko[2]: passed

```

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Merci!

**Comment by estebanpw** [comment]
> 
> 
> Merci!

Thanks to you for all the help & knowledge!

**Pull request merged**
