### PR TITLE
Require Python 2 for genetrack

### PR DESCRIPTION
**Pull request by gregvonkuster**
and apply recent standards to command line.  It turns out the default numpy install now uses Python 3 but the genetrack code currently supports only Python 2.

### CODE REVIEW

**Comment by yhoogstrate** [comment]
The changes look good to me :+1: .

**Comment by nsoranzo** [comment]
I can try to add Python3 support alternatively, should be easy enough.

**Comment by gregvonkuster** [comment]
Sounds great - thanks!

**Comment by nsoranzo** [comment]
@gregvonkuster Done, merging as soon as tests pass.

**Comment by gregvonkuster** [comment]
Awesome!  Thanks a bunch!

**Comment by gregvonkuster** [comment]
Thanks so much for everything @nsoranzo !!

**Pull request merged**
