### PR TITLE
add rptools suite v5.13.1

### PR DESCRIPTION
**Pull request by kenza12**
Create **rptools suite v5.13.1** as requested.

This suite include the following tools:

- rpviz: https://github.com/galaxyproject/tools-iuc/pull/4897
- rpreport: https://github.com/galaxyproject/tools-iuc/pull/4898
- rpranker: https://github.com/galaxyproject/tools-iuc/pull/4856
- rpextractsink: https://github.com/galaxyproject/tools-iuc/pull/4314
- rpfba

**rpcompletion** (https://github.com/galaxyproject/tools-iuc/pull/4797) will be also integrated into the rptools suite once a bug in the source code is fixed.

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Regarding the `TMPDIR` problem. Can you try to test locally against 22.01, ie `--galaxy_branch release_22.01` or with a 0.74 release of planemo (you may install it with conda).

**Comment by bernt-matthias** [comment]
Alternatively debugging like described here https://planemo.readthedocs.io/en/latest/writing_how_do_i.html#interactively-debug-tool-tests might help.

**Comment by nsoranzo** [comment]
Actually I've also come across this issue with TMPDIR yesterday, see https://matrix.to/#/!NhNWKNcgINoFZdbUbY:gitter.im/$zePB4VtI47XoCdEAO7JqUVj1hpJHrpHSbpC1fo5kAmU?via=gitter.im&via=matrix.org
Not sure if it's a new thing, but we need to fix it at the Galaxy level, I think.

**Comment by kenza12** [comment]
Hi, Unfortunately I have trouble using `--biocontainers` option. The Galaxy admin installed docker so I can run planemo with docker but I keep having this error:

```
galaxy.datatypes.display_applications.application ERROR 2022-11-29 13:51:40,781 [pN:main,p:2449,tN:MainThread] Error loading a set of Dynamic Display Application links: A format or a metadata can be defined for a DisplayApplicationParameter, but not both.
galaxy.tool_util.output_checker INFO 2022-11-29 13:52:23,774 [pN:main,p:2449,tN:LocalRunner.work_thread-0] Job error detected, failing job. Reasons are [{'type': 'exit_code', 'desc': 'Fatal error: Exit code 127 ()', 'exit_code': 127, 'code_desc': '', 'error_level': 3}]
```

I already use `planemo mull`, the image 'rptools' was created here:

```
root@b0b1e5f9778e:/galaxy# docker image ls
REPOSITORY                                 TAG                 IMAGE ID            CREATED             SIZE
quay.io/biocontainers/sbol-utilities       1.0a16              6e13bb6d3f5e        4 hours ago         1.01GB
quay.io/biocontainers/rptools              6.0.1               65d1d19cf7bc        5 hours ago         1.32GB
continuumio/miniconda3                     latest              ce7d119281a1        5 months ago        403MB
quay.io/bioconda/base-glibc-busybox-bash   latest              9c9215c03820        19 months ago       11MB
involucro/tool                             latest              1ed8c6d13028        3 years ago         6.98MB
```
I also run this command: `docker container run -it 65d1d19cf7bc /bin/bash` to see if rptools is working.

So, the tool is working good without `--biocontainers` option. @nsoranzo, I was wondering if you found a solution about this TMPDIR issue.

**Comment by nsoranzo** [comment]
@kenza12 This was solved yesterday for Galaxy 22.05 and dev by merging https://github.com/galaxyproject/galaxy/pull/15039 .

**Comment by kenza12** [comment]
Ok nice @nsoranzo ! Is it possible to rerun the tests (checks) please ? to see if it's work for me. Thanks.

**Comment by kenza12** [comment]
Oh nice ! Happy to see that ! Thank you @nsoranzo

**Review by gallardoalba — APPROVED** [review]

**Comment by gallardoalba** [comment]
I would like to review it, tomorrow I'll check it @kenza12.

**Comment by kenza12** [comment]
Thank you for you work !!

**Pull request merged**
