### PR TITLE
Update TB-Profiler to version 4.1.1

### PR DESCRIPTION
**Pull request by pvanheus**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
```
Checking the headers and starting positions of 2 files
[E::bcf_hdr_read] Input is not detected as bcf or vcf format
Failed to parse header: 20cb5d53-e138-4431-89eb-d1a890c5942b.vcf
```

**Comment by pvanheus** [comment]
> ```
> Checking the headers and starting positions of 2 files
> [E::bcf_hdr_read] Input is not detected as bcf or vcf format
> Failed to parse header: 20cb5d53-e138-4431-89eb-d1a890c5942b.vcf
> ```

Yep. I noticed this. It runs fine on my local machine though.

**Comment by bgruening** [comment]
Do you test with the --biocontainers option? maybe some zlib missing or so?

**Comment by pvanheus** [comment]
> Do you test with the --biocontainers option? maybe some zlib missing or so?

Thanks for the hint. It turned out to be a permissions issue as described [here](https://github.com/jodyphelan/pathogen-profiler/issues/5).

**Comment by pvanheus** [comment]
A [fix](https://github.com/bioconda/bioconda-recipes/pull/33737) on the bioconda side solved the problem that was causing this tool to fail when using containers. Yay!

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks!

**Pull request merged**
