### PR TITLE
Change the validator for set_id, add test, bump version

### PR DESCRIPTION
**Pull request by FredericBGA**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [X] - This PR updates an existing tool or tool collection

Regex modified to allow backslash (`\_` between tags for command line) and underscores in tags (for `%FIRST_ALT`) for the `--set-id` option. The example given on the interface works (used in the test: `%CHROM\_%POS\_%REF\_%FIRST_ALT`)
I've modified the second test (add an assert_contents: `<has_text text="1_3062915_GTTT_G" />`

### CODE REVIEW

**Comment by nsoranzo** [comment]
@FredericBGA I've added a couple of commits, hope you are OK with the changes.

**Comment by FredericBGA** [comment]
> @FredericBGA I've added a couple of commits, hope you are OK with the changes.

yes, it's nice to lint the file.
By the way are you sure about the `unnecessary backslash in regex`?


I've tested with:
```
reg = '^([+]?(%[A-Z]+)(\\_%[A-Z_]+)*)?$'
set_id = "%CHROM\_%POS\_%REF\_%FIRST_ALT"
print(re.match(reg, set_id), 'set_id', set_id)
# None set_id %CHROM\_%POS\_%REF\_%FIRST_ALT
```
and
```
reg = '^([+]?(%[A-Z]+)(\\\_%[A-Z_]+)*)?$'
set_id = "%CHROM\_%POS\_%REF\_%FIRST_ALT"
print(re.match(reg, set_id), 'set_id', set_id)
# <_sre.SRE_Match object; span=(0, 30), match='%CHROM\\_%POS\\_%REF\\_%FIRST_ALT'> set_id %CHROM\_%POS\_%REF\_%FIRST_ALT
```
It does not match with only two backslash. I've opened an issue here: https://github.com/galaxyproject/tools-iuc/issues/4438 to discuss about that. I'm not an expert in regex! I didn't know about raw string notation before I had to dig in this issue. Any help and explanations are welcomed.

**Comment by nsoranzo** [comment]
The tests pass though. And also in the UI it works for me with 2 slashes, no?

**Review by nsoranzo — APPROVED** [review]

**Comment by FredericBGA** [comment]
indeed ^^ it works with only two. But I don't yet really understand how. And sorry for the mistake, I've tested with a python script without trying then with two in the XML.

I've looked at `https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/parameters/validation.py` and I've tried to reproduce (with a python shell from the .venv of Galaxy) what we have in the docstring of `RegexValidator`. And here again I need three. Nevermind, it's perfect as it works but if somebody can explain me what I miss, I will be happy.
```
>>> from galaxy.util import XML
>>> from galaxy.tools.parameters.basic import ToolParameter
>>> p = ToolParameter.build(None, XML('''<param name="blah" type="text" value="%CHROM\_%POS\_%REF\_%FIRST_ALT"><validator type="regex" message="Nope" >^([+]?(%[A-Z]+)(\\\_%[A-Z_]+)*)?$</validator></param>'''))
>>> t = p.validate("%CHROM\_%POS\_%REF\_%FIRST_ALT")
>>>
>>>
>>> p = ToolParameter.build(None, XML('''<param name="blah" type="text" value="%CHROM\_%POS\_%REF\_%FIRST_ALT"><validator type="regex" message="Nope" >^([+]?(%[A-Z]+)(\\_%[A-Z_]+)*)?$</validator></param>'''))
>>> t = p.validate("%CHROM\_%POS\_%REF\_%FIRST_ALT")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/softs/bioinfo/galaxy-dev/lib/galaxy/tools/parameters/basic.py", line 295, in validate
    return super(TextToolParameter, self).validate(value, trans)
  File "/softs/bioinfo/galaxy-dev/lib/galaxy/tools/parameters/basic.py", line 233, in validate
    validator.validate(value, trans)
  File "/softs/bioinfo/galaxy-dev/lib/galaxy/tools/parameters/validation.py", line 91, in validate
    raise ValueError(self.message)
ValueError: Nope
```

**Comment by nsoranzo** [comment]
@FredericBGA The issue with your Python code is that if you want to write a literal `\` inside a Python string you need to escape it as `\\`. The regular expression in the tool XML doesn't need that though because it's read from the file by Galaxy.

**Pull request merged**
