### PR TITLE
Fix Snippy Paired Collection Handling

### LINKED ISSUE #2161: Snippy wrapper fails with Collection of Paired dataset
#set $dir_name = re.sub('[^\w_]', '_', $fastq_input.fastq_input1.element_identifier) this line of code will fail when the input is  collection of paired datasets

### PR DESCRIPTION
**Pull request by dfornika**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Fixes #2161

### CODE REVIEW

**Comment by dfornika** [comment]
There seems to be a bit of non-determinism in the test output, maybe introduced by some of the dependencies(?). I'll try to generate new test outputs.

**Comment by dfornika** [comment]
I guess I should add a `+galaxy#` string onto the version:

```xml
<tool id="snippy" name="snippy" version="@VERSION@+galaxy0">
```
...but should it be `+galaxy0`, `+galaxy1` or some other value?

**Comment by nsoranzo** [comment]
I'd use `+galaxy1` .

**Comment by dfornika** [comment]
@bgruening I'm not sure why the tests are producing different output now, but I did purposely re-generate the test outputs to get the tests to pass.

I haven't changed any parameters or input files for the tests, so my best guess is that some of the dependencies aren't tightly pinned, resulting slightly different output compared to last time the test data was generated. Maybe a default parameter or something was changed in one of the dependencies? 

But it shouldn't be necessary to get to the root of that problem here, should it? Those new output files are consistent with what the tests produce.

**Comment by bgruening** [comment]
Ok! Thanks @dfornika!

**Pull request merged**
