### PR TITLE
Fix broken URLs

### PR DESCRIPTION
**Pull request by bernt-matthias**
Requires: https://github.com/galaxyproject/tools-iuc/pull/6184

TODO: 

- [ ] bump tools versions

FOR CONTRIBUTOR:
* [ ] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by mvdbeek** [comment]
I wouldn't bump the version or deploy the tools, I think it's fine to just do that when there is a relevant change on the next update ?

**Comment by bernt-matthias** [comment]
> I wouldn't bump the version or deploy the tools, I think it's fine to just do that when there is a relevant change on the next update ?

Would be fine for me. But I have the feeling that we should document the rules when to bump / not. Sometimes people say always. Sometimes there are exceptions.

**Comment by bgruening** [comment]
I would not bump if we do not deploy. If we deploy we bump.

I would not deploy and not bump this PR. We just want to fix the linters and I think it fine to deploy with the next proper release.

**Comment by bernt-matthias** [comment]
OK. Let's merge and skip deployment.

**Comment by bgruening** [comment]
Lint is green!

**Comment by mvdbeek** [comment]
Attention: deployment cancelled!

https://github.com/galaxyproject/tools-iuc/actions/runs/10869685320

**Pull request merged**
