### PR TITLE
Demultiplex the hmmer tools

### PR DESCRIPTION
**Pull request by erasche**
Depends on 

- [x] https://github.com/galaxyproject/planemo/issues/313

In support of (todo: find issue where we were all talking about demultiplexing and I volunteered to do it on my repository.)

### CODE REVIEW

**Comment by erasche** [comment]
This is ready for review.

**Comment by erasche** [comment]
And visible here: https://testtoolshed.g2.bx.psu.edu/repository/browse_repositories?sort=name&advanced_search=false&show_item_checkboxes=false&async=false&f-free-text-search=hmmer&page=1

**Comment by bgruening** [comment]
:+1: this looks fantastic!

**Comment by bgruening** [comment]
Thanks @erasche! The year of demultiplexing has started ...

**Pull request merged**
