### PR TITLE
package_ncurses_5_9: Fixes critical compilation error for GCC5.1+

### PR DESCRIPTION
**Pull request by yhoogstrate**
A fix for issue https://github.com/galaxyproject/tools-iuc/issues/477
Could testers report their GCC version as well?

### CODE REVIEW

**Comment by mvdbeek** [comment]
works fine on os x:
```
(.venv)mariuss-MacBook-Pro:~ marius$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

But we should perhaps "sedify" the patch, so that we don't rely on a github download.
Also CDATA is probably a good idea the shell command.

**Comment by bgruening** [comment]
@mvdbeek what do you mean with sedify?
xref: https://github.com/galaxyproject/cargo-port/pull/35

**Comment by mvdbeek** [comment]
@bgruening 
rewrite the diff into sed commands, but the cargo solution is good. 
Is it possible to download the patch using a `download_file` action (in addition to `download_by_url`)?
wget is not present on default os x installations, this way we could get around it.

**Comment by bgruening** [comment]
`https://depot.galaxyproject.org/software/ncurses_patch/ncurses_patch_5.9p_src_all.patch` with `c9033021022979a02621af43883e6ca5a4df14d2c3a5a821e4c67923d13d5e78`
@mvdbeek download_file would be great!

**Comment by yhoogstrate** [comment]
@mvdbeek My PR is only fixing this for linux. Do you think I should copy the code to `<actions os="darwin" architecture="x86_64">` as well? I don't have a mac and I don't know which compiler it uses.

I'm fixing both your suggestions, thanks for that and thanks for the update in the cargo @bgruening !

**Comment by mvdbeek** [comment]
It is compiling fine with the patch manually applied.
On OS X you can get the gcc compiler either with the CommandLine tools package, with XCode or through homebrew, so I guess there are quite a few different gcc versions out there on OS X. I think we should include it also for darwin, since at some point a more recent gcc will be the default, and it doesn't break current installations.

**Comment by bgruening** [comment]
Awesome! Thanks a lot guys!

**Pull request merged**
