### PR TITLE
Enhance the ncurses 5.9 recipe to work with OSX.

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by mvdbeek** [comment]
This looks good to me, not sure why travis is complaining.
@bgruening you'd be ok for merging? planemo shed_lint passes locally ...

**Comment by bgruening** [comment]
I think this is looks good. Actually I think planemo 0.20 is borken: https://github.com/galaxyproject/planemo/issues/385
Haven’t had time to look at it :(
Do you have 0.19 installed?
Maybe we should fix the planemo version to 0.19 for the hackathon on Monday,

**Comment by bgruening** [comment]
@mvdbeek can you please upload it? I'm on a conference right now :(

**Comment by mvdbeek** [comment]
@bgruening yes, it's 0.19, I will upload it.

**Comment by gregvonkuster** [comment]
Thanks for merging!  ;)

**Pull request merged**
