### PR TITLE
Add art BioConda dependency

### PR DESCRIPTION
**Pull request by remimarenco**

### CODE REVIEW

**Comment by yhoogstrate** [comment]
This one passes on my local instance... The travis test is now rerunning

**Comment by remimarenco** [comment]
@bgruening I guess the test-data would need to be upgraded? Do you want me to change them?

**Comment by bgruening** [comment]
On some conferences the next weeks. Feel free to do it otherwise I will look at it in May.

**Comment by yhoogstrate** [comment]
Any progress on the test data @remimarenco  ?

**Comment by remimarenco** [comment]
Hrmm I am a bit far from this dependency work. Not sure if I have the time right now, but I will be happy to help if somebody wants to take the ownership of this :)

**Comment by yhoogstrate** [comment]
@remimarenco I think the dependency in conda should work:
```
art                          3.11.14                       0  bioconda        
                             3.19.15                       1  bioconda 
```
Test data can be updated with `planemo test --update_test_data`

**Comment by bgruening** [comment]
Can anyone help here?

**Comment by bgruening** [comment]
Already done.

**Pull request closed without merging**
