### PR TITLE
add new tools rp2biosensor v 3.1.0

### PR DESCRIPTION
**Pull request by kenza12**
Add new tool **rp2biosensor v 3.1.0** : https://github.com/brsynth/rp2biosensor

Thank you !!

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
LGTM, if the test pass :)

**Comment by bgruening** [comment]
Anything how we can help here?

**Comment by kenza12** [comment]
> Anything how we can help here?

No, Thank you @bgruening . It's a known problem where the tool is trying to download some files in the installation directory which is forbidden here. I asked the developer to add an option in the source code in order to download these files in another directory like TMPDIR.

**Review by yorgomoubayed — APPROVED** [review]

**Comment by yorgomoubayed** [comment]
@bgruening Hi, review is done, is it possible to look into it again please? Thank you.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
cool, thanks a lot!

**Pull request merged**
