### PR TITLE
use planemo ci_find_repos+ci_find_tools

### PR DESCRIPTION
**Pull request by bernt-matthias**
for counting tools and computing chunks.

- [ ] we should think about removing `-exclude packages --exclude deprecated` in favor of including these directories in `.tt_skip` (here and in the PR workflow). Advantage would be that the workflow would also run if those dirs do not exist in other repos. So all exclusions would be controlled in `.tt_skip`

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by nsoranzo** [comment]
> we should think about removing -exclude packages --exclude deprecated in favor of including these directories in .tt_skip (here and in the PR workflow). Advantage would be that the workflow would also run if those dirs do not exist in other repos.

That's already the case, planemo works fine if the directories passed explicitly with `--exclude` do not exist. I'd drop this point.

**Review by nsoranzo — APPROVED** [review]
I haven't tested the changes (or my follow-up commit), but they look good to me.

**Comment by bernt-matthias** [comment]
> I haven't tested the changes (or my follow-up commit), but they look good to me.

Me neither. I guess we should. How is the easiest way? What happens if we call the slash command in this PR?

**Comment by bernt-matthias** [comment]
Seems to run https://github.com/bernt-matthias/tools-iuc/runs/1687636152

**Comment by nsoranzo** [comment]
> Seems to run https://github.com/bernt-matthias/tools-iuc/runs/1687636152

Yes, I also just looked at it and it looks fine. I can merge if you rebase out the spurious changes.

**Comment by nsoranzo** [comment]
Thanks! I'll open a PR with file renaming to pr.yaml for consistency.

**Pull request merged**
