### PR TITLE
Mothur: fixed issues with chimera tools

### PR DESCRIPTION
**Pull request by oxyko**
Issue described in #419. Also, added test data and test for chimera.slayer. But test is commented out, because planemo wasn't able to run it. Will need to revisit it once mothur wrapper tests are in good shape.

### CODE REVIEW

**Comment by martenson** [comment]
Thanks for the contribution @oxyko
Is it possible to trim the testing dataset to be less than 25k lines? It would help preventing this repo from growing too big.

**Comment by oxyko** [comment]
Will do.

**Comment by bgruening** [comment]
@oxyko this file is still 17.000 lines, is this correct? 
tools/mothur/tools/mothur/test-data/chimera_test_in.fasta

**Comment by bgruening** [comment]
Can you please rebase/squash against master to get rid of the large file from the git history? Thanks!

Let me know if you need help with squasching commits.

**Comment by martenson** [comment]
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by oxyko** [comment]
I've removed the test files and tried the rebase/squash, but I'm afraid I'm in a bit of a mess and my HEAD is now detached. Could you see if you can bring in the current pull as it is? If not, I'll do the hard reset on mothur branch, redo the changes and do a new pull request.

**Comment by bgruening** [comment]
I guess we can merge this branch and ry to rebase the master mothur branch before merging into main. @martenson does this sound reasonable? If so please feel free to merge.

**Comment by oxyko** [comment]
Thanks guys! I'll try and be more careful with rebasing and test data size next time.

**Comment by martenson** [comment]
@bgruening I tried to do the rebase locally and it is not easy. If you see the diff in GitHub you will notice that only one or two commits are actually being shown - all other changes are both commited and then reverted (e.g. all the whitespace changes are missing). This needs some handwork :/

**Comment by oxyko** [comment]
OK, doing a hard reset on mothur and re-applying the changes.

**Comment by bgruening** [comment]
@oxyko thanks. Just to explain the mess. We try to keep this repository as small as possible, hence we try to keep test data small.
@martenson thanks for investing!

**Pull request closed without merging**
