### PR TITLE
Renamed package to correct name for version

### PR DESCRIPTION
**Pull request by erasche**
- Follow up to #147 in which I switched package version and forgot to rename the folder/change versions elsewhere.
- CC @bgruening @peterjc 
- Thanks to @yhoogstrate for reporting.

### CODE REVIEW

**Comment by peterjc** [comment]
Looks sensible, but might it be better to keep both ``packages/package_r_limma_3_9_9/`` and ``packages/package_r_limma_3_25_3/`` here on GitHub? If so then reverting the 3.9.9 to 3.25.3 changes and adding a new folder seems better.

**Comment by erasche** [comment]
@peterjc I'll be happy to do that...if anyone's actually going to use 3_9_9 ever.  It isn't on main yet, and missing lots of the functionality of the latest package, so I have fewer qualms just renaming it and pretending 3.9.9 wasn't ever used.

**Comment by peterjc** [comment]
Given 3.9.9 never made it to the main Tool Shed, then we can deprecate it on the Test Tool Shed and pretend it never happened ;)

+1 on this PR.

**Comment by erasche** [comment]
Great, thanks :)

**Comment by bgruening** [comment]
Only main counts ;)

**Pull request merged**
