### PR TITLE
update star to version 2.7.6a

### PR DESCRIPTION
**Pull request by pavanvidem**
This should hopefully fix this issue from the tutorial https://github.com/galaxyproject/training-material/issues/2103

### CODE REVIEW

**Comment by bgruening** [comment]
Hu, it simply passes all tests? How unexpeceted. @mtekman @wm75 is it ok to merge?

**Review by bgruening — APPROVED** [review]

**Comment by wm75** [comment]
Surprising indeed :) Let me check ...

**Review by wm75 — APPROVED** [review]
Seems plausible. Apparently there have been only bug-fixes since 2.7.5b.

Maybe the profile version of the wrappers could be updated, but fine otherwise.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @pavanvidem

**Pull request merged**
