### PR TITLE
Set allow_duplicate_entries="False" for Tool Data Tables.

### PR DESCRIPTION
**Pull request by blankenberg**
Prevents duplicate entries from appearing in data table when they exist in the files. Prevents cases where a duplicate entry occurs and is then passed as a comma separated list onto the command line (which breaks most tools).

I just did all of the data tables here, if folks could review and check if any of these tables actually should allow duplicate entries, that would be a big help.

### CODE REVIEW

**Comment by bgruening** [comment]
```
snpEff[0]: failed
snpEff_databases[0]: failed
snpEff_download[0]: failed
```
I guess they should be added to the tool-testing blacklist or fixed.

**Comment by yhoogstrate** [comment]
SnpEff is failing because it has issues independent of this PR. @blankenberg I don't know how duplicate entries are checked exactly, is this done on `dbkey` or on the entire entry? In case of the second, let's merge :+1:

**Comment by mvdbeek** [comment]
@yhoogstrate It should be on all fields: https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/data/__init__.py#L642

:+1:, already had that issue.
@blankenberg 
Just for my understanding: What's the point of allowing duplicate data table entries in galaxy?

**Comment by blankenberg** [comment]
It checks across all fields. Restricting the check to optionally only check specific field(s) is a future enhancement.

Keeping duplicates is a backwards compatibility issue, there maybe a datatable that expects it, although I do not know of one off the top of my head.

**Comment by mvdbeek** [comment]
Alright, thanks @blankenberg!

**Pull request merged**
