### PR TITLE
Spades fixes

### PR DESCRIPTION
**Pull request by bernt-matthias**
f37ce4136944e04dc14952bbfdca489ceda88d7d fixes current CI failure

Instead of 879ce2ee31c993faf0183f27d6d13bb1458c1e20 we could also define the `operation_mode` parameter in all tools?

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
ping @gallardoalba and @bebatut

**Review by bgruening — APPROVED** [review]
Its holiday time, not sure @bebatut and @gallardoalba will be able to answer in time.

If you want to get it in feel free to merge.

**Comment by bernt-matthias** [comment]
No need to hurry.

**Comment by gallardoalba** [comment]
> No need to hurry.

Looks good to me.

**Review by gallardoalba — APPROVED** [review]

**Pull request merged**
