### PR TITLE
Genometools package

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I would need genometools for reago. Bjorn suggests to integrate the package as an iuc package.

Bérénice

### CODE REVIEW

**Comment by peterjc** [comment]
This should be useful :)

I'm currently using the genometools Python bindings (``import gt``), which right now are Python 2.7 only.

Installing them requires an extra step after the make install - probably something like this (untested):

```
cd gtpython
python2.7 setup.py install --prefix=$INSTALL_DIR
```

@bgruening does that look right? Should this be part of ``package_genometools`` and declare a Python 2.7 dependency? Or should it be a separate package just for the Python bindings?

Note when I was installing this locally under $HOME without using root, I had to set ``$LD_LIBRARY_PATH`` in order that Python could find the compiled code:

```
$ export LD_LIBRARY_PATH=$HOME/lib/
```

Quick sanity test (we don't yet have an official test section in the installation recipes):

```
$ python2.7 -c "import gt; print(gt.__file__)"
```

See also https://github.com/genometools/genometools/issues/712

**Comment by yhoogstrate** [comment]
This package contains some awesome tools. I really want to play with some of them.

When I compiled it locally and in Docker, it terminated with the following error:

```
[compile mg_xmlparser.o]
[compile mg_reverse.o]
[compile mg_computepath.o]
[compile layout.o]
In file included from /tmp/genometools-1.5.7/src/annotationsketch/text_width_calculator_cairo.h:21:0,
                 from src/annotationsketch/layout.c:26:
/tmp/genometools-1.5.7/src/annotationsketch/text_width_calculator_cairo_api.h:21:19: fatal error: cairo.h: No such file or directory
compilation terminated.
```

This can probably be fixed by depending on:
https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_cairo_1_14_2/tool_dependencies.xml

Otherwise `make cairo=no` should solve it as well according to the manual. But this won't compile AnnotationSketch.

**Comment by peterjc** [comment]
Good point. Locally I've been using ``make cairo=no prefix=$HOME`` and ``make cairo=no prefix=$HOME install``, not sure the XML ``make_install`` action would handle this repetition of the options...

Probably AnnotationSketch is not going to be important for Galaxy use.

**Comment by bgruening** [comment]
@peterjc good point to install the python bindings as well. I think this is a more portable solution:
`python setup.py install --install-lib $INSTALL_DIR/lib/python --install-scripts $INSTALL_DIR/bin`
And you need to create the $INSTALL_DIR/lib/python beforehand with `<action type="make_directory">$INSTALL_DIR/lib/python</action>`.

@bebatut can you please add this and depend on package_cairo_1_14_2 as @yhoogstrate suggested. Hopefully everything also plotting from python will work then!

Thanks,
Bjoern

**Comment by yhoogstrate** [comment]
@bebatut Thanks for the changes!

```
<environment_variable name="GENOMETOOLS_DIR" action="set_to">$INSTALL_DIR/</environment_variable>
```
I know that as of the latest versions of Galaxy this is not necessary anymore. Do we want to keep this in and for how long do we want to support this?

I think something like this needs to be added to get the python bindings working:
```
<environment_variable action="prepend_to" name="PYTHONPATH">$INSTALL_DIR</environment_variable>
```

Also the cairo package should be loaded to the installation environment like this:
```
<action type="set_environment_for_install">
	<repository name="package_cairo_1_14_2" owner="iuc">
		<package name="cairo" version="1.14.2" />
	</repository>
</action>
```

(example: https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_gnuplot_4_6/tool_dependencies.xml#L20 )
Further it looks good to me and ready for the testtoolshed for testing.

**Comment by bgruening** [comment]
@yhoogstrate I will merge this now and add you comments post merge to help @bebatut a little bit.

**Comment by yhoogstrate** [comment]
@bgruening Can I push this to the main tool shed?

**Comment by bgruening** [comment]
Yes please!

**Pull request merged**
