### PR TITLE
put datamash under testing

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Is the Travis build failure expected?

**Comment by bgruening** [comment]
@nsoranzo no ... the log is not really useful. I could not spot the error, this needs more love.

**Comment by bgruening** [comment]
Retrigger the test, let's see if it was an sqlite issue.

**Comment by nsoranzo** [comment]
I already tried that yesterday from the Travis interface (Restart Build button), no luck.

**Comment by mvdbeek** [comment]
@bgruening 
I have re-triggered the (previously) successfull push build.
if this fails, something outside of this PR has changed, for example in conda, availablle pip modules or galaxy or in travis' build environment or ... also I remember they had docker images of their build environemnts, for interactive trouble-shooting.

**Comment by bgruening** [comment]
Why should this be a conda or pypy problem. My assumption is a random planemo locking issue.
1 out of 3 was successful, I guess this is too bad to be merged ....

**Comment by mvdbeek** [comment]
> Why should this be a conda or pypy problem. My assumption is a random planemo locking issue.
> 1 out of 3 was successful, I guess this is too bad to be merged ....

true, could also be planemo. I wasn't aware that this is a stochastic process, I thought it broke right after the first push build finished. It's a curious problem though. can we reproduce this behaviour locally?

**Comment by peterjc** [comment]
I didn't see anything about SQLite locking in the TravisCI log, just:

```
RunToolException: Error creating a job for these tool inputs - Unknown error occurred while processing request.
```

Not much to go on. :(

We could click the re-test button on TravisCI to try it again and see if it fixes itself (often works with SQLite locking issues in my own tool testing under Travis)?

**Comment by nsoranzo** [comment]
I've restarted the Travis build for the 3rd time now, but `datamash_ops` tool seems to always fail.

**Comment by peterjc** [comment]
That does suggest this is not a stochastic failure... but something that looks hard to debug. Reproducing it locally would be idea.

**Comment by bgruening** [comment]
I think I found it. It is a regression in Galaxy as far as I know, or two regressions I have described here: https://github.com/galaxyproject/galaxy/issues/1818

**Comment by bgruening** [comment]
Tests are passing, anyone willing to merge?

**Comment by peterjc** [comment]
Merged, should we delete the ``datamash_testing`` branch now?

**Comment by bgruening** [comment]
Yes, please feel free to delete all old branches.

**Comment by bgruening** [comment]
Thanks Peter!

**Pull request merged**
