### PR TITLE
Update Jbrowse to 1.12.3

### PR DESCRIPTION
**Pull request by abretaud**
Updating to the latest jbrowse version 
@erasche do you prefer to merge it before or after gcc? the "name store" error message should be gone with this new version, but I haven't tested all the options

### CODE REVIEW

**Comment by erasche** [comment]
Before :)

**Comment by bgruening** [comment]
@erasche the test is failing?

**Comment by erasche** [comment]
deploy task failed because github deleted the branch due to the merge. my fault :( Importantly, the tests passed.

**Comment by erasche** [comment]
I'll merge some other jbrowse work soon and will do it properly / wait for tests to finish next time.

**Pull request merged**
