### PR TITLE
Force full-length ivar consensus builds

### PR DESCRIPTION
**Pull request by wm75**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by wm75** [comment]
@pvanheus not quite sure how this one could go unnoticed until now.

**Review by bgruening — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Please also check in the help section and report upstream https://github.com/andersen-lab/ivar/blob/d0e2ad0e6be69307771a5d36c573ffba578f4ce0/pipeline_consensus/Snakefile#L34

**Comment by wm75** [comment]
@bernt-matthias oh no, don't make me look into too much detail - only unearthing more bugs :exploding_head:

**Comment by wm75** [comment]
> and report upstream

done in https://github.com/andersen-lab/ivar/pull/144

**Comment by wm75** [comment]
integer overflow issue reported, too: https://github.com/andersen-lab/ivar/issues/145

**Comment by bernt-matthias** [comment]
Then lets merge?

**Comment by wm75** [comment]
Yes, I think so. Thanks for the review @bernt-matthias !

**Pull request merged**
