### PR TITLE
update rasusa with default values to subsmaple

### PR DESCRIPTION
**Pull request by pavanvidem**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by pavanvidem** [comment]
There is no defaults in the tool. Now I set the Galaxy tool default to the fraction of reads which is easier. Other params need genome size.

**Comment by pavanvidem** [comment]
I don't think it is required to bump the `VERSION_SUFFIX`, or? The initial version failed anyway.

**Comment by bgruening** [comment]
Since the TS repo is busted I think you don't need to bump the version number.

**Review by bgruening — APPROVED** [review]

**Comment by pavanvidem** [comment]
Strange. Same error message. The param `genome_size` is not default anymore. Does it still need to have a value or `optional="true"`?

**Pull request merged**
