### PR TITLE
Update tb_variant_filter to version 0.4.0

### PR DESCRIPTION
**Pull request by pvanheus**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by pvanheus** [comment]
The upstream changes in version 0.4.0 are:
* better support for parsing the variety of ways that people represent allele frequency in VCF (this specifically should work with `bcftools call` output)
* update of drug resistances regions as specified by MTBSeq

None of this changes the interface from a Galaxy point of view, so this should be a drop-in replacement in any workflows.

**Comment by pvanheus** [comment]
The current error causing check failures is a [linting failure](https://github.com/galaxyproject/tools-iuc/actions/runs/5823828369/job/15801396360?pr=5440#step:7:437) where a URL cannot be retrieved.

**Comment by bgruening** [comment]
Can you change the URL?

**Comment by pvanheus** [comment]
> Can you change the URL?

Yep - works when I use an archive.org URL to point to the paper. So Wiley (even when mentioned as a DOI) doesn't like our linting.

**Comment by bgruening** [comment]
Cool thanks

**Comment by pvanheus** [comment]
> Attention: deployment skipped!
> 
> https://github.com/galaxyproject/tools-iuc/actions/runs/5843298213

At deployment time there was another URL error and deployment did not succeed. I have raised the URL error with the owner of the website in question (its an expired SSL certificate).

**Comment by mvdbeek** [comment]
thanks @pvanheus, I've uploaded this manually.

Now that we've raised the error level to warning for IUC tools we could consider lowering
`Applying linter tool_urls... FAIL` to warning, so that deployments will still work for invalid urls.

**Pull request merged**
