### PR TITLE
get abyss under testing

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by nsoranzo** [comment]
@bgruening I actually prefer the original indentation (i.e. no initial indentation for the commands), any particular reason for this change? We usually do the same in the `<help>` section.

**Comment by bgruening** [comment]
The main reason is that I need to change something to trigger the test ;)
The secondary reason I like this indentation more as you can separate from the main program call and the parameters. For the help we are restricted to keep the indentation because rst is very picky.

But this was just because I needed to change something.

**Comment by nsoranzo** [comment]
@bgruening It didn't work on Travis for some reason:
```
$ git diff --name-only $TRAVIS_COMMIT_RANGE | xargs -n1 dirname | ./filter_directories.py | sort -u > changed_repositories.list
dirname: missing operand
Try `dirname --help' for more information.
```

**Comment by bgruening** [comment]
@nsoranzo from where do you get this error? Travis is happy and shows everything from conda installation to planemo test.

**Comment by bgruening** [comment]
Ah I see, look at the other test.
Not sure why the second runs at all.

**Comment by martenson** [comment]
@bgruening if you talk about the two travis tests it is because you have it set up in a way it builds every PR & every push - so given you develop in main repo branches you trigger them both

**Pull request merged**
