### PR TITLE
Remove dependencies on openssl.

### PR DESCRIPTION
**Pull request by bgruening**
openssl should be installed by the system package manager.

### CODE REVIEW

**Comment by erasche** [comment]
:+1:

**Comment by bgruening** [comment]
Thanks @erasche!

**Comment by yhoogstrate** [comment]
Thanks @bgruening @erasche . Does openssl need to be listed down here:
https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList ?

**Comment by bgruening** [comment]
Yes, good catch, I added it.

**Pull request merged**
