### PR TITLE
Add bio.tools for qiime_core

### PR DESCRIPTION
**Pull request by clsiguret**
Hi all,

This PR links the tools to its bio.tools entry: https://bio.tools/qiime_core
It will be useful to get EDAM ontology annotations

The linting seems ok, I don't know for the tests.. 
However, the tool must be deprecated because we are using Qiime2 now.

Thanks!

### CODE REVIEW

**Comment by bernt-matthias** [comment]
I added an issue for qiime2 https://github.com/qiime2/galaxy-tools/issues/66

Should we merge this or deprecated directly?

**Comment by bernt-matthias** [comment]
Ha https://github.com/qiime2/q2galaxy/pull/54 ;)

**Comment by bebatut** [comment]
Here the idea was mostly to add bio.tools so it appears in the Galaxy Tool Metadata Extractor table. We will also add a deprecated status there

**Comment by bgruening** [comment]
So let's merge it?

@shiltemann ?

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
