### PR TITLE
STAR: Add two pass mode

### PR DESCRIPTION
**Pull request by TorHou**
This feature is now available in STAR 2.5 and I would really like to use it.

### CODE REVIEW

**Comment by bgruening** [comment]
@TorHou version needs to be bumped and a test would be nice.
@yhoogstrate can you look at this?

**Comment by TorHou** [comment]
I just realized that all tests that use the star-fusion setting will probably fail now, because I have changed those settings. Twopass mode for star-fusion makes perfect sense however and is the default setting, so I think the test data output should be updated.

**Comment by TorHou** [comment]
ok. I checked the ouput of the tests, they are all as expected (it's a simple case, as should be). So I think this change is all good.

**Comment by yhoogstrate** [comment]
@TorHou Indeed twopass makes also sense for fusion analysis. I don't see any reason why this implementation would fail and given that the test passes it's an OK from my side.

Thanks everyone :+1:

**Comment by bgruening** [comment]
Thanks @TorHou and @yhoogstrate!

**Pull request merged**
