### PR TITLE
stacks2: fix tests, output format and filter, and bump

### PR DESCRIPTION
**Pull request by bernt-matthias**
xref https://github.com/galaxyproject/galaxy/pull/11313
fixes https://github.com/galaxyproject/tools-iuc/issues/3526

also improving some tests by using `diff` instead of `sim_size`

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
There seem to be empty files in this PR and the files ending with gz are visible? I suspect they are not really compressed?

**Comment by bernt-matthias** [comment]
> There seem to be empty files in this PR and the files ending with gz are visible?

Output type was wrong (should have been fastq). But they are empty -- could be replaced with an assertion if you like. 

Wondering why the tool linting step already worked. I expected it to pass only with https://github.com/galaxyproject/galaxy/pull/11536 .. and I do not understand how this change affects planemo that fast. 

But maybe it just fine and I should be happy :)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
> Wondering why the tool linting step already worked. I expected it to pass only with galaxyproject/galaxy#11536 .. and I do not understand how this change affects planemo that fast.

That is indeed strange. Does the lint fail locally?
Feel free to merge, that seems to be an unrelated problem.

**Comment by bernt-matthias** [comment]
Problem seems to be that the repo_list file has no new line at the end: https://github.com/galaxyproject/planemo-ci-action/blob/a7fb2018f8283c28232f794c80f4c1e38c3c5a0a/planemo_ci_actions.sh#L96

I remember that I did this on purpose .. but I can not remember. 

Ultimately this leads to 

```
while read DIR
do
...
done
```
skipping the last line. The only thing I would so far is to check if $DIR is not empty after the loop and execute the loop body again if necessary. 

Or we remove the `-n` from the echo.


maybe @mvdbeek or @nsoranzo have an idea?

**Comment by bernt-matthias** [comment]
tata .. looks good for me

**Review by bgruening — APPROVED** [review]

**Pull request merged**
