### PR TITLE
Bump vsnp_determine_ref_from_data requirements

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Review by bernt-matthias — COMMENTED** [review]
@gregvonkuster can you merge the 3 PR and introduce version tokens. Then its easier to have consistent requirements. Alternatively macros might be an option.

**Comment by gregvonkuster** [comment]
> @gregvonkuster can you merge the 3 PR and introduce version tokens. Then its easier to have consistent requirements. Alternatively macros might be an option.

I can merge the PRs myself even though I submitted them?  I'll certainly introduce version tokens.

**Comment by bernt-matthias** [comment]
> I can merge the PRs myself even though I submitted them?

I meant to put the commits in a single PR :) and to introduce the tokens.

I cancelled the workflows, so the changes to the other 2 PR will not be deployed to the TS. Can you add the commits of these PRs here?

**Comment by gregvonkuster** [comment]
Hmm..sorry for the confusion - this is why I don't merge.  :).

**Comment by gregvonkuster** [comment]
Since this one is now merged, what would you like me to do next?

**Comment by bernt-matthias** [comment]
> Since this one is now merged, what would you like me to do next?

Just cherry pick the commit to the open PR.

**Pull request merged**
