### PR TITLE
Update .travis.yml for latest Galaxy and Planemo enhancements.

### PR DESCRIPTION
**Pull request by jmchilton**
Worked for a devteam PR at https://github.com/galaxyproject/tools-devteam/pull/386 thanks to @mvdbeek.

### CODE REVIEW

**Comment by bgruening** [comment]
Can you maybe trigger one test? Bedtools is always a good example.

**Comment by jmchilton** [comment]
How do I do that?

**Comment by bgruening** [comment]
Some changes, can be whitespace changes to the tool.xml file. Thanks.
On Sep 2, 2016 2:52 PM, John Chilton <notifications@github.com> wrote:How do I do that?

**Comment by bgruening** [comment]
Seems to fail with:
```
bedtools_annotatebed[0]: [32m[1mpassed[0m
bedtools_bamtobed[0]: [32m[1mpassed[0m
bedtools_bamtobed[1]: [32m[1mpassed[0m
bedtools_bed12tobed6[0]: [31m[1mfailed[0m
bedtools_bedpetobam[0]: [32m[1mpassed[0m
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/bin/planemo", line 11, in <module>
    sys.exit(planemo())
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/cli.py", line 175, in handle_profile_options
    return f(*args, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/commands/cmd_test.py", line 77, in cli
    return_value = run_in_config(ctx, config, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 115, in run_in_config
    kwds=kwds
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 129, in handle_reports_and_summary
    **kwds
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 220, in _handle_summary
    **kwds
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 232, in _summarize_tests_full
    _summarize_test_case(test_case_data, **kwds)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/galaxy/test/actions.py", line 250, in _summarize_test_case
    get_dict_value("data", structured_data)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/planemo/test/results.py", line 113, in get_dict_value
    raise KeyError("No key [%s] in [%s]" % (key, data))
KeyError: 'No key [status] in [None]'
```

**Comment by jmchilton** [comment]
Looks like the database was locked - that old gem :(.

**Pull request merged**
