### PR TITLE
LASTZ: added differences output option. Incremented version

### PR DESCRIPTION
**Pull request by nekrut**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This commit adds [differences](http://www.bx.psu.edu/miller_lab/dist/README.lastz-1.02.00/README.lastz-1.02.00a.html#fmt_diffs) output option to lastz tools. It is necessary for recombination analysis in SARS-CoV-2

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
The produced file is an interval format left? Should we add this to the output converts?

**Comment by bernt-matthias** [comment]
Can you add fastq.gz as input type to lastz_d? See https://github.com/galaxyproject/tools-iuc/issues/2312#issuecomment-803041663

**Comment by nekrut** [comment]
@bgruening / @bernt-matthias - can you merge?

**Review by bernt-matthias — APPROVED** [review]

**Comment by bernt-matthias** [comment]
Ready from my side: Linter shows some warnings.. maybe they are easy to fix:

```
Applying linter tool_urls... FAIL
.. ERROR: Error '404 Client Error: Not Found for url: http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.00.html#adv_inference' accessing http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.00.html#adv_inference
.. ERROR: Error '404 Client Error: Not Found for url: http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.00.html#fmt_inference' accessing http://www.bx.psu.edu/~rsharris/lastz/README.lastz-1.04.00.html#fmt_inference
```

**Pull request merged**
