### PR TITLE
Update (Fix) Cutadapt when used with pe collections which are gz or bz

### PR DESCRIPTION
**Pull request by lldelisle**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Do we need a test for this case? Have you also seen https://github.com/galaxyproject/tools-iuc/pull/4393

**Comment by lldelisle** [comment]
I missed the PR...
So funny that we discovered together a bug which exists since 10 months

**Comment by lldelisle** [comment]
I don't know how to make a test for this. The problem was that the datasets where of datatype "fastqsanger.gz" but were not gzipped...

**Comment by lldelisle** [comment]
See https://usegalaxy.eu/u/ldelisle/h/test-cutadapt for example (History Content API ID | 11ac94870d0bb33a1bec1dc3ba5506a1)

**Comment by lldelisle** [comment]
I just checked and their PR is better. Please merge https://github.com/galaxyproject/tools-iuc/pull/4393

**Pull request closed without merging**
