### PR TITLE
add tools nugen_nudup and join_files_by_id

### PR DESCRIPTION
**Pull request by bimbam23**

### CODE REVIEW

**Comment by bgruening** [comment]
@bimbam23 now I see what you mean. You have to many changes in this branch, back to 2016. Can you merge master into your branch? Let us know if you need help.

**Comment by bimbam23** [comment]
Hmm, yes I think I need some help. So I obviously forgot to update the old branch. I tried to reset the branch and update it... some how it does not work.  
git fetch --all
git reset --hard origin/master

but maybe its easier to start from the beginning? Get a new folk and add the new tools?

Cheers Jochen

**Comment by shiltemann** [comment]
Hi @bimbam23 :)

ah yes, `origin` points to your own fork (see `git remote -v`) ..you can add the upstream repo with 

`git remote add upstream https://github.com/galaxyproject/tools-iuc.git ` 

merging/rebasing seems to lead to a large number of conflicts, so I would suggest starting fresh by creating a new branch and resetting this to the master branch of the upstream tools-iuc repo:

```
git checkout -b add-tools 
git fetch upstream
git reset --hard upstream/master
```

and then adding your changes there. I think you'll have to open a new PR if you are using a new branch 

(you *could* also do this without switching to a new branch, but then make sure you have your changes backed up somewhere first because they will be overwritten by the reset, and you will have to do a force-push after you've re-added your changes `git push -f ` )

hope this was a bit clear, feel free to contact me on gitter for more help if you like

**Comment by shiltemann** [comment]
@bimbam23 great, closing this in favour of your new PR: #1332

**Pull request closed without merging**
