### PR TITLE
Add deepTools-2.5.0

### PR DESCRIPTION
**Pull request by dpryan79**
This adds deepTools-2.5.0, which should be available in bioconda shortly.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @dpryan79

**Comment by dpryan79** [comment]
Thanks @bgruening! Do you have time to push the wrapper versions for 2.5.0 to the toolshed? It sounds like Galaxy main wants some of the wrapper updates from @mvdbeek.

**Comment by bgruening** [comment]
Pushing to test at the moment with: https://github.com/fidelram/deepTools/pull/502

**Comment by bgruening** [comment]
Btw. everything should be updated. @martenson

**Comment by dpryan79** [comment]
@bgruening It looks like there's still some mismatch in version numbers somewhere in the wrappers. In the toolshed I see the following warning: "The settings for name, version and type from a contained tool configuration file's requirement tag does not match the information for the following tool dependency definitions in the tool_dependencies.xml file, so these tool dependencies have no relationship with any tools within this repository."

I assume that's related to the PR I merged.

**Comment by bgruening** [comment]
image

Can we skip tool_depenencies please :)
I will look into it, the Conda function should not be affected.

**Pull request merged**
