### PR TITLE
Add linter exceptions for all linters that are currently failing

### PR DESCRIPTION
**Pull request by bernt-matthias**
And re-enable warn as linter fail level. 

It's like a TODO list :) 

```
      1 HelpMissing
      1 InputsDataFormat
      1 InputsDataOptionsFiltersType
      1 InputsSelectDynamicOptions
      1 InputsSelectOptionsDeprecatedAttr
      1 RequirementVersionMissing
      1 ValidatorExpression
      1 ValidatorExpressionFuture
      2 InputsDataOptionsFilterAttribFiltersType
      2 InputsDataOptionsFiltersRef
      2 InputsNameDuplicateOutput
      2 InputsSelectOptionDuplicateValue
      2 OutputsNameDuplicated
      2 OutputsNameInvalidCheetah
      2 TestsOutputCompareAttrib
      2 ToolIDWhitespace
      2 XSD
      3 CommandTODO
      3 EDAMTermsValid
      3 InputsMissing
      3 TestsExpectNumOutputsFailing
      4 ConditionalWhenMissing
      4 InputsBoolDistinctValues
      4 InputsNameDuplicate
      4 InputsSelectOptionDuplicateText
      5 HelpInvalidRST
      6 HelpEmpty
      9 OutputsLabelDuplicatedNoFilter
     13 ConditionalParamTypeBool
     14 TestsMissing
     15 ToolVersionPEP404
     18 OutputsLabelDuplicatedFilter
     19 TestsParamInInputs
     29 CitationsNoValid
     32 CitationsMissing
     41 InputsNameRedundantArgument
     73 TestsExpectNumOutputs
    103 XMLOrder
```

Should replace https://github.com/galaxyproject/tools-iuc/pull/5650

FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [x] This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
The remaining tool linter errors are all die to linters defined in planemo (working in it: https://github.com/galaxyproject/planemo/pull/1472)

Tool tests won't finish with 4 chunks (and likely there fill be failing tests anyway).

I will fix the python linter problems.

**Comment by bgruening** [comment]
Do you want me to fix a few other stuff here or should we merge that and fix other stuff later?

If we merge this PR, so we cancel the CI or do we deploy?

**Comment by bernt-matthias** [comment]
> If we merge this PR, so we cancel the CI or do we deploy?

I would not deploy. Since we do not change any tools (I should undo the changes to py and xml files and but them in a separate PR)

> Do you want me to fix a few other stuff here or should we merge that and fix other stuff later?

I would put any other changes to a separate PRs.

**Comment by bernt-matthias** [comment]
The `XSD` errors are maybe due to a bug: https://github.com/galaxyproject/galaxy/pull/18605

**Comment by bgruening** [comment]
@bernt-matthias please also have a look at https://github.com/bernt-matthias/tools-iuc/pull/107  ... not sure where it should go. Please let me know how you want to have those fixes.

**Review by mvdbeek — APPROVED** [review]
Awesome, thanks a lot!

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/tools-iuc/actions/runs/10719699458

**Pull request merged**
