### PR TITLE
Update ivar suite of tools to v1.4

### PR DESCRIPTION
**Pull request by wm75**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

- implements new -m default in ivar trim
- removes max value restriction on -m option in ivar consensus after upstream fix
- works around messed up ivar trim stdout/stderr in new version

### CODE REVIEW

**Review by bernt-matthias — APPROVED** [review]
Looks good to me. Was just wondering if instead of the hidden parameters some logic should be added to the command. Potential problem with the hidden parameters is that they might accidentally be overwritten in tests. 

But I'm totally fine with either way

**Comment by wm75** [comment]
Thanks @bernt-matthias, that's fairly trivial. I'm still hopeful that ivar 1.4.1 will get released rather soon and fix SAM output piping. So for me it's ok to have this PR here remain open for a couple of days.
I'll either bump to the next release then, or just implement your suggestion.

**Comment by wm75** [comment]
@cmaceves no rush at all, but what's your approximate timeline for a 1.4.1 release with https://github.com/andersen-lab/ivar/issues/157 fixed?

**Comment by cmaceves** [comment]
> @cmaceves no rush at all, but what's your approximate timeline for a 1.4.1 release with [andersen-lab/ivar#157](https://github.com/andersen-lab/ivar/issues/157) fixed?

hi! we're looking for a push to 1.4.1 no later than next week.

**Comment by bgruening** [comment]
@cmaceves any news about version 1.4.1? Thanks :)

**Comment by cmaceves** [comment]
hi @bgruening! we just pushed a new release, it might be a bit until it goes through bioconda release but the master branch has the piping bug addressed and is functional for streaming!

**Comment by bgruening** [comment]
We automatized the bioconda thing to a [large degree](http://m.genome.cshlp.org/content/early/2023/02/23/gr.276963.122.full.pdf) so we can probably take care of that - create packages, containers and get this PR here in.

Thanks a lot @cmaceves!

**Comment by wm75** [comment]
nad I guess it's due to your changes around https://github.com/andersen-lab/ivar/blob/2e982a8383c9ef0b3ccdbe04ae5a23a89b713a28/src/trim_primer_quality.cpp#L659

where the continue now causes an endless loop.

**Comment by cmaceves** [comment]
Okay, @wm75 thanks for pointing this out, I'll dig into it!

**Comment by wm75** [comment]
> Looks good to me. Was just wondering if instead of the hidden parameters some logic should be added to the command. Potential problem with the hidden parameters is that they might accidentally be overwritten in tests.
> 
> But I'm totally fine with either way

@bernt-matthias I've implemented your suggestion now.
Let's get this in with v1.4 for now.

**Comment by wm75** [comment]
@bgruening looks a bit as if 1.4.1 gets chosen when requirement is 1.4. Can I somehow require 1.4 exactly?

**Comment by wm75** [comment]
> @bgruening looks a bit as if 1.4.1 gets chosen when requirement is 1.4. Can I somehow require 1.4 exactly?

Aha, specifying 1.4.0 seems to have done the trick.

**Comment by bernt-matthias** [comment]
> Aha, specifying 1.4.0 seems to have done the trick.

This is surprising, isn't it? I always assumed that the specified version is exact...
The xml doc defines: `For requirements of type package this value defines a specific version of the tool dependency.`

@wm75 how did you find out which version is installed?

**Comment by bgruening** [comment]
Not really, if we specify python=3 we also want the latest Python version.
The package was called 1.4.0, so specifying the exact version is fixing it. Or did I understand something wrong.

**Comment by wm75** [comment]
The package version is just 1.4 with no minor version. I found yesterday that conda accepts also 1.4.0.
The confusing aspect is imo that 1.4 *is* an exact version id and the resolver still goes looking for newer minor releases. Maybe this particular edge-case behavior should be considered a bug?

**Comment by wm75** [comment]
@bernt-matthias I was diagnosing the version only by behavior of the tests, which hang again with 1.4 as the requirement, but passed with 1.4.0.

**Comment by bgruening** [comment]
Oh there is no https://anaconda.org/bioconda/ivar/files 1.4.0 ... I guess it's at least worth talking to the conda people if that is what it should be.

**Pull request merged**
