### PR TITLE
Optional RData output file for DESeq2

### PR DESCRIPTION
**Pull request by yhoogstrate**
solves https://github.com/galaxyproject/tools-iuc/issues/975

### CODE REVIEW

**Comment by bgruening** [comment]
@yhoogstrate thanks for the enhancement. Do you know if a RData object is persistent between different R version? Which promises are we doing by offering this option?

**Comment by yhoogstrate** [comment]
I saw an issue on the Galaxy biostar where someone requested the possibility to get *publishable figures* (https://biostar.usegalaxy.org/p/19742/#19752). The figures currently produced are detailed but I can imagine someone like to customize them e.g. by changing the axes or naming the samples in the PCA plot. I don't know to what extend this is a problem especially as PDFs are vector based figures, but having an R object would give enless options. You are also right that there is backwards incompatibility as far as I read in the manual:

*Although the default version has not changed since R 1.4.0, this does not mean that saved files are necessarily backwards compatible. You will be able to load a saved image into an earlier version of R unless use is made of later additions (for example, raw vectors, external pointers and some S4 objects).*
*One such ‘later addition’ was long vectors, introduced in R 3.0.0 and loadable only on 64-bit platforms.*

I don't know what the best choice would be, and thanks for reviewing this @bgruening

**Comment by bgruening** [comment]
Ok, let's do the following. Can we create a macro which we can share between all R tools that contains an advanced section with this option, hided by default and with an explicit statement that the backward compat is not guaranteed between different R versions?

This way we can add this feature to all our R tools in a consistent way.

**Comment by bgruening** [comment]
@yhoogstrate what do you think about the macro idea? 
Can you also please look at https://github.com/galaxyproject/tools-iuc/pull/714 - new generation of DESeq2

**Comment by yhoogstrate** [comment]
Thanks @bgruening, I like the macro idea. I will look at your PR in the beginning of next week.

**Comment by bgruening** [comment]
So this needs to be rebased on the new DESeq2 wrapper :)

**Pull request closed without merging**
