### PR TITLE
ci.yaml and pr.yaml update

### PR DESCRIPTION
**Pull request by heylf**
FOR CONTRIBUTOR:
* [X] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [X] This PR does something else (explain below)

### CODE REVIEW

**Comment by heylf** [comment]
This is in connection with #6191

**Comment by bgruening** [comment]
@mvdbeek is this ok, or can we get a new planemo release: https://github.com/galaxyproject/tools-iuc/pull/6191#issuecomment-2269763625

It could be that Leonid meant a new release of galaxy-tool

**Comment by mvdbeek** [comment]
I don't see any related changes in galaxy-tool-util ? I've created a new planemo release which updates the galaxy package pins.

**Comment by kostrykin** [comment]
> I don't see any related changes in galaxy-tool-util ? I've created a new planemo release which updates the galaxy package pins.

Not sure whether this is already clear here or not, but the new planemo release is required to have these changes: https://github.com/galaxyproject/planemo/pull/1471 @mvdbeek

**Review by bgruening — APPROVED** [review]
Ok, this has not helped. Lets add it for the time being.

**Comment by bgruening** [comment]
Thanks @mvdbeek!

**Comment by mvdbeek** [comment]
Attention: deployment skipped!

https://github.com/galaxyproject/tools-iuc/actions/runs/10342483720

**Comment by mvdbeek** [comment]
What I'm seeing in @heylf's PR is https://github.com/galaxyproject/tools-iuc/pull/6191/files#r1713360682. I do see pillow and tifffile getting installed, so I think galaxy-tool-util or planemo is not at fault.

**Pull request merged**
