### PR TITLE
SPAdes: fix memory allocation variable

### PR DESCRIPTION
**Pull request by gallardoalba**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Review by bernt-matthias — APPROVED** [review]
Looks good to me, but it could also go to a macro token.

**Comment by bgruening** [comment]
I had another idea, lets wait before merging.

**Comment by gallardoalba** [comment]
Now it is fine I think.

**Comment by bgruening** [comment]
@bernt-matthias does this look good for you?

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
