### PR TITLE
Add DESeq2 wrapper

### PR DESCRIPTION
**Pull request by bgruening**
This will add a DESeq2 wrapper with unit-test and hopefully a most convenient UI.
@fubar2 can you please review this :)

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by erasche** [comment]
(sorry, jenkins bot auto-commented on all of the open PRs)

**Comment by bgruening** [comment]
Updated the wrapper and the script. @mikelove did an awesome job in cleaning up the R script. I'm waiting for a new DESeq2 version that should have this script integrated. At this point we can remove our script.

**Comment by mikelove** [comment]
hi Bjoern,

yeah, how to best coordinate. The deseq2.R script is in the Bioc trunk which is always accessible here:

https://hedgehog.fhcrc.org/bioconductor/trunk/madman/Rpacks/DESeq2/inst/script/deseq2.R

u/p: readonly/readonly

the good thing about getting from the trunk is that I can immediately fix bugs. otherwise if you go with the release package it will take up to 6 months to wait for fixes.

**Comment by bgruening** [comment]
Ah, do you plan to release every six month now a new version? I remember times with every 2 weeks or so :)

I'm actually fine with shipping it in the wrappers (synced from hedgehog) until you get out a proper release with this script. Does this sound reasonable?

**Comment by mikelove** [comment]
Bioconductor has releases on an April/October schedule. 

And then we try not to bump the release version too much (users will get an annoying message to update for each version bump). So I wouldn't want to tweak the script in the release branch.

The deseq2.R script will be in the April release (DESeq2 version 1.8).

I didn't yet write unit tests for the script but I will add that to my todo list.

**Comment by bgruening** [comment]
Ok, makes sense. Let's ship this script next to the wrappers until April and DESeq2 1.8. I will ping Vipin to join our testing.

**Comment by erasche** [comment]
@fubar2 assigned this issue to you since @bgruening mentioned in opening commit.

**Comment by erasche** [comment]
Bumping this thread now that april is halfway done

**Comment by mikelove** [comment]
DESeq2 v1.8 with galaxy-friendly script will be available on April 17 
http://www.bioconductor.org/developers/release-schedule/

**Comment by erasche** [comment]
@bgruening

**Comment by bgruening** [comment]
@mikelove has 1.20 our script included? 
http://www.bioconductor.org/packages/release/bioc/html/DESeq.html I can not find it.

**Comment by mikelove** [comment]
that's the old DESeq package, the new one is DESeq2 (we have both existing on Bioc, because some users needed access to the old version, but the new version is recommended for all users now).

http://www.bioconductor.org/packages/release/bioc/html/DESeq2.html

the script is here:

https://hedgehog.fhcrc.org/bioconductor/branches/RELEASE_3_1/madman/Rpacks/DESeq2/inst/script/deseq2.R

u/p: readonly/readonly

**Comment by bgruening** [comment]
Oh ok, I thought this would be integrated into the new release. Never mind will try to get this issue resolved tomorrow. Thanks!

**Comment by mikelove** [comment]
hi Bjorn,

I'm confused. DESeq2 version 1.8 is the current release (Bioc 3.1 is the latest release in April 2015), and the script deseq2.R is included in the package source, DESeq2_1.8.1.tar.gz, if you download it from Bioc. It's also available at the URL i posted above.

**Comment by bgruening** [comment]
@mikelove sorry for the confusion. I finally found everything :) Thanks for the link!

**Comment by mikelove** [comment]
hows it going with the testing? is anything more needed from me?

**Comment by yhoogstrate** [comment]
Maybe you could add:
```<version_command>echo $(R --version | grep version | grep -v GNU)", DESeq2 version" $(R --vanilla --slave -e "library(DESeq2) ; cat(sessionInfo()\$otherPkgs\$DESeq2\$Version)" 2&gt; /dev/null | grep -v -i "WARNING: ")</version_command>```

**Comment by bgruening** [comment]
@yhoogstrate can you please test the latest version? Does the tool_dependency installation works for you as well?
I moved finally over to the deseq2.R script shipped in the DESeq2 tarball. Unfortunately, I was some serious issues with the installation of R, atlas and DESeq2.

**Comment by yhoogstrate** [comment]
Hi @bgruening ,

I checked a few things and the following things made me happy:
* The installation works like a charm.
* The HTSeq specific annotations "no_feature", "ambiguous", "too_low_aQual", "not_aligned", "alignment_not_unique" are properly removed.
* Samplenames are properly checked for being unique.
* Extensive plots

There were also a few small issues:
* When the newline between line 11 and 12 is removed, the version command will work again.
* Using ```planemo server DESeq2.xml```, I get the following output:
```Fatal error: cannot open file '...tools-iuc/tools/deseq2//script/deseq2.R': No such file or directory```
The history box turns green. I think it's safe to capture all errors starting with "Fatal error:", and add this to stdio.
* The output files have no column names (P-values, logFC and FDR), it's only in the tools readme.
* The samples/factors are not being checked for being mutually exclusive. If I add the same sample to multiple conditions (especially in a 2 factor design) I would like to receive at least a warning. It sound very silly to make this mistake, but they do happen very frequently. It's not very important, but might be worth thinking about.
* A feature request that I got for a similar tool is an opt-in option to export the RData object so people can continue with it in their own R instance (or Galaxy RStudio).

I saw that there were some lines in the results that had NA values for the FDR while there was a P-value. I think those FDRs should be set to 1, but probably I'm overseeing something. I will try to get more into the results a.s.a.p


Great work again!

**Comment by mikelove** [comment]
hi @yhoogstrate 

the FDR set to NA when there is a p-value is normal DESeq2 behavior. It indicates that a gene was excluded from p-value correction for having too low of mean normalized count (independent filtering). See vignette for more details (section on independent filtering and FAQ on p-values / adjusted p-value NA).

**Comment by bgruening** [comment]
@yhoogstrate I was able to solve my build problems with this patch: https://github.com/galaxyproject/docker-build/pull/29

> 
* When the newline between line 11 and 12 is removed, the version command will work again.

Fixed!

> * Using ```planemo server DESeq2.xml```, I get the following output:
```Fatal error: cannot open file '...tools-iuc/tools/deseq2//script/deseq2.R': No such file or directory```
The history box turns green. I think it's safe to capture all errors starting with "Fatal error:", and add this to stdio.

Fixed.

> * The output files have no column names (P-values, logFC and FDR), it's only in the tools readme.

This is intentionally, because sorting and filtering with header can be unintuitive, my preferred solution here is that we can set table-header metadata in a tool, so the headers are not part of the file, but part of the visualization. 

> * The samples/factors are not being checked for being mutually exclusive. If I add the same sample to multiple conditions (especially in a 2 factor design) I would like to receive at least a warning. It sound very silly to make this mistake, but they do happen very frequently. It's not very important, but might be worth thinking about.

I had this in earlier version with a custom code file, but removed it because we simplified the UI a lot. I will add this back in a later version. Is this ok?

> * A feature request that I got for a similar tool is an opt-in option to export the RData object so people can continue with it in their own R instance (or Galaxy RStudio).

Ah, yes, makes sense. Can we add this in a later version, I really would like to get this release out. I have promised so many people a proper DESeq2 release since month :)

@mikelove the diff of your test data is a little bit scary large, is this change expected from one version to the other?

**Comment by mikelove** [comment]
If your previous version was 1.0 or 1.2, yes expected. Those were the first two releases (from 2013) , and v1.4 incorporated a lot of good suggestions from early user feedback. 

There have been only small changes to methods  since v1.4 (April 2014).

**Comment by yhoogstrate** [comment]
Hi @bgruening,

Great to see the changes.

I guess I'm a bit stubborn but I still prefer real columns. For example, if you would print out the table for a lab meeting, you first need to add column headers. The same accounts for using the files in spreadsheet programs outside galaxy. (The filter in galaxy has the builtin option to skip lines, but indeed the defeault is to skip 0 lines.) Anyway, it's not a big  deal.

I plotted the results on a public dataset against results of edgeR, and I believe this correlates nice:
correlation
This confirms that it behaves as expected.

I saw that the wrapper accepts designs with 1 replicate per condition. Because this doesn't allow to estimate dispersion properly, you could mention something about the pitfalls and risks in the readme.

I hope DESeq2 gets into the main tool shed asap

**Comment by bgruening** [comment]
Sorry, I did not updated the test toolshed with this latest version. But the actual problem is, and this is blogging a merge, the R 3.2.1 has some error with lapack and atlas. I hope @davebx is back next week and can have a look at it: https://github.com/galaxyproject/docker-build/pull/29

**Comment by bgruening** [comment]
@yhoogstrate we have a new R version in the TTS and for me know everything works. Tested with the galaxy-deseq2 Docker image. If you can confirm that everything works as expected I will merge and push everything to the TSs :)

One thing I realised is that I still use a repeat in the XML file. But DESeq2 does not support 3 factor levels as far as I know ( @mikelove is this correct? ). So this should be replace by just two input fields without a repeat in the next release.

**Comment by mikelove** [comment]
DESeq2 does support any number of factors, and any complex design which can be constructed with R's formula function.

Multiple comparisons can be extracted using:

```{r}
results(dds, contrast=c("condition","B","A"))
results(dds, contrast=c("condition","C","A"))
results(dds, contrast=c("condition","C","B"))
```

etc.

**Comment by bgruening** [comment]
But this is more or less a pair-wise comparison. I think we just have a usability issue here. If the user can specify 2+ factor levels you would expect one output and not 3 or more with pairwise comparisons.

We could think about to output multiple files, depending on the user input in the next version I guess. Currently, you can archive the same result if you run DESeq2 3 times.

**Comment by mikelove** [comment]
earlier like around Dec/Jan we had the script actually doing that: producing multiple results tables by cycling through all the combinations of factor levels. But then we realized that it was easier in Galaxy to just have one analysis produce one results table per run. So it's def possible in DESeq2/R just the question of how the UX would work in Galaxy. For now I agree let's push out the version we have. thanks again Bjoern.

**Comment by yhoogstrate** [comment]
I figured out why I had the previous error, which is probably also the reason why I can't find *deseq2.R*, and testing fails. I didn't notice it because galaxy indicated that the installation status of deseq 1.8.1 was 	"Installed"

For installing DESeq2_1.8.1.tar.gz, the INSTALLATION log says:

```
STDERR
* installing *source* package ‘DESeq2’ ...
** libs
installing to /usr/local/src/galaxy/tool-dependencies/deseq2/1.8.1/iuc/package_deseq2_1_8_1/dcfbf1f4611f/DESeq2/libs
** R
** inst
** preparing package for lazy loading
Error in setMethod("plotPCA", signature(object = "DESeqTransform"), plotPCA.DESeqTransform) :
  no existing definition for function ‘plotPCA’
Error : unable to load R code in package ‘DESeq2’
ERROR: lazy loading failed for package ‘DESeq2’
* removing ‘/usr/local/src/galaxy/tool-dependencies/deseq2/1.8.1/iuc/package_deseq2_1_8_1/dcfbf1f4611f/DESeq2’
Warning message:
In install.packages(c("DESeq2_1.8.1.tar.gz"), lib = "/usr/local/src/galaxy/tool-dependencies/deseq2/1.8.1/iuc/package_deseq2_1_8_1/dcfbf1f4611f",  :
  installation of package ‘DESeq2_1.8.1.tar.gz’ had non-zero exit status
```

**Comment by bgruening** [comment]
Ok, I was able to find the error in our R installation and now it is working in `docker pull bgruening/galaxy-deseq2`. Ready to merge!

**Comment by bgruening** [comment]
@yhoogstrate @mikelove sorry that it took me so long.
This may make you happy: https://github.com/galaxyproject/tools-iuc/pull/281

**Comment by mikelove** [comment]
Thank you for all your efforts Björn and others!

I learned a lot about Galaxy in the process.

**Comment by yhoogstrate** [comment]
Hi Guys,

Great work! The latest update of the wrapper works here. I was able to install and run it, and also the latest revision of the docker image works:

rplot

Maybe it's handy, when the tools gets updated, to add the sample labels to the samples in the PCA and the cluster plot:

labels

In the left (current) situation you only see dots. When you have an outlier in the data, you would like to see at first glance which sample it is (like in the right situation).

I think it's ready to go into the toolshed.

**Comment by bgruening** [comment]
Awesome, we did it! Thanks a lot to all involved.
@yhoogstrate yes please add this with a next PR, I will now upload these wrappers to all Tool Sheds.

**Comment by mikelove** [comment]
hi @bgruening,

someone just reported a small bug in 1.8.1, wherein if the betaPrior is turned off (not the default), for some datasets there may be high standard errors for certain rows. so it's a non-critical bug for the majority of users. I fixed this in 1.8.2 which i just pushed to Bioconductor. If it's not a huge hassle, it would only involve pulling DESeq2 v1.8.2 to replace 1.8.1 (no other dependencies need to change). I won't be making any more commits to the 1.8 branch as Bioc moves this week to 1.10 (but Galaxy can stay on the 1.8 branch).

**Comment by bgruening** [comment]
@mikelove definitely thanks for letting me now.
I had a look at http://www.bioconductor.org/packages/release/bioc/html/DESeq2.html but could not see a release. I suppose BioC needs some time to update the page. I will care about this tm.

Are you also involved in DEXseq? https://github.com/galaxyproject/tools-iuc/pull/281

Thanks Michael!

**Pull request merged**
