### PR TITLE
samtools stats: remove plot_bamstats call

### PR DESCRIPTION
**Pull request by bernt-matthias**
To get rid of the gnuplot and perl dependency

advantage: no additional mulled environment needed

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Is the additional mulled env problematic? I think bioconda will not like it. There was recently a discussion about adding R to Picard and this was shut down. https://github.com/bioconda/bioconda-recipes/issues/3859

What you can do is create a samtools-full packages or similar, but then again you have an additional environment.

**Comment by bernt-matthias** [comment]
No real problem, the extra env just takes more memory which is not really necessary.

Interesting discussion. I'm pro adding the extra dependency to the package. Lets see what the community thinks.

After finding out that multiqc can plot the stats I kind of regret that I added the plot_bamstats call... we might as well remove it .. it would not remove any functionality from Galaxy.

**Comment by bgruening** [comment]
Thank remove it :)

> No real problem, the extra env just takes more memory which is not really necessary.

If you mean storage here, think about it the other way, everyone that just needs samtools, including all our other tools that include samtools, will get now R and gnuplot as well - in their mulled-env.

**Comment by bernt-matthias** [comment]
Would it be OK to keep the version. For me it would be fine if the change goes to the TS with the next mayor improvement of the tools.

**Comment by bgruening** [comment]
Not sure how? Do you mean not merging this PR, or merge and kill travis to not upload the recipes?

**Comment by bernt-matthias** [comment]
Ahh .. lets just bump :) .. 

Maybe it would be an option not to upload to the TS if the version is already present in the TS anyway?

**Comment by mvdbeek** [comment]
Can you bump the version ? I don't see the point of holding back releases ? The smaller the release the better IMO.

**Comment by bernt-matthias** [comment]
sure. done

**Pull request merged**
