### PR TITLE
Updating tools/spyboat from version 0.1.1 to 0.1.2

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following tool: **tools/spyboat**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/spyboat from version 0.1.1 to 0.1.2.

**Project home page:** http://github.com/tensionhead/spyboat/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bgruening** [comment]
ping @tensionhead ... Good to go? :-)

**Comment by bernt-matthias** [comment]
Probably we should bump version suffix. Versioning was messed up already.. An we made it even worse over here https://github.com/galaxyproject/tools-iuc/pull/5572/files... I just realized.

**Comment by bgruening** [comment]
Outch, yes I see ... Ok lets try this one.

**Review by bernt-matthias — APPROVED** [review]

**Comment by tensionhead** [comment]
Looks like all is good @bgruening @bernt-matthias ?!

**Pull request merged**
