### PR TITLE
[WIP] Dockerized Testing.

### PR DESCRIPTION
**Pull request by jmchilton**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

The goal of this PR is to enable testing inside of containers to catch more tool problems in container environments as quickly as possible.

Added a test I expect to fail to debug this actually working.

### CODE REVIEW

**Comment by jmchilton** [comment]
Shockingly easy! It even somehow found another issue with another tool.

**Comment by nsoranzo** [comment]
> Shockingly easy! It even somehow found another issue with another tool.

1) For the `snippy` tool, the Travis logs for the snippy tool test contains this line:

```
/tmp/tmpvlqBmk/job_working_directory/000/17/tool_script.sh: line 9: /tmp/tmpvlqBmk/job_working_directory/000/17/COMMAND_VERSION: Read-only file system
```

which is caused by `<version_command><![CDATA[snippy --version]]></version_command>` being translated by Galaxy into `snippy --version > /tmp/tmpvlqBmk/job_working_directory/000/17/COMMAND_VERSION 2>&1;` in the `tool_script.sh` : this looks like a (non-fatal) Galaxy bug.

2) For the `snippy_core` tool, the error is:

```
tar: unrecognized option '--strip-components=1'
```

which is due to this part of the `<command/>`:

```
tar -xf '$indir' -C '$sample_name' --strip-components=1
```

I think this can only be fixed by adding a requirement for GNU tar.

**Comment by jmchilton** [comment]
The version problem should be fixed with something like: https://github.com/galaxyproject/galaxy/pull/8997. I'm not sure we should fix it in 19.09.

**Comment by nsoranzo** [comment]
We are doing this for a while.

**Pull request closed without merging**
