### PR TITLE
Condafy data_manager_gemini_download tool

### PR DESCRIPTION
**Pull request by gregvonkuster**
And update the gemini version to 0.19.1.  This is the first step for this issue: https://github.com/galaxyproject/tools-iuc/issues/1130

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks @gregvonkuster for working on this. Are you planning to put the tool in here as well? I don't think it makes sense to update the data manager without the tools.

**Comment by gregvonkuster** [comment]
Yes, I am taking look.  Regarding the tabix requirement for the current tool, I'm wondering if I should create a conda recipe based on this: http://wiki.wubrowse.org/How_to_install_tabix (this is my current approach).  However, it is also a component of htslib (https://github.com/samtools/htslib) but that package includes a lot more stuff.  Let me know if you'd rather have me use it though.

**Comment by bgruening** [comment]
Depending on htslib is ok, I think.

**Comment by yhoogstrate** [comment]
This should be pending on: https://github.com/galaxyproject/galaxy/pull/3686

**Comment by bgruening** [comment]
Thanks @gregvonkuster!

**Pull request merged**
