### PR TITLE
Added wrappers for cmake-3.2.3

### PR DESCRIPTION
**Pull request by yhoogstrate**
CMake and git are tools that are not by default shipped with all linux
distributions. CMake has some time ago changed from version 2 to version
3 where certain CMake 2 features have been deprecated. To ensure galaxy
users won't suffer from compiliation problems due to versioning or
missing cmake or git as system dependency, I have packaged both of them.

I have added them as dependencies to the wrappers of:
 - package_bedtools_2_18 (git)
 - package_lapack_3_4 (cmake)

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by blankenberg** [comment]
ok to test

**Comment by blankenberg** [comment]
Personally, xml tags broken into lines by attributes looks goofy to me. Additionally, we have listed cmake as one of those "must have installed" dependencies, but the note about incompatibilities between versions makes this seem quite useful, and it should be more reproducible anyway to have it pinned to an exact version.

**Comment by erasche** [comment]
This weirds me out a bit. Is there any reason to use git over downloading a github packaged version of the codebase at that point in time?

**Comment by erasche** [comment]
We (the IUC) is being a bit more relaxed about the split XML tags. Agreed, they always look a bit goofy, but a good point was raised that it's still technically correct, and it's intended to be consumed by computers AND humans doing the code review. E.g. https://github.com/galaxyproject/tools-iuc/pull/80/files#diff-3fd6f2603dfcba6d1a642a3be0d57e2eR39

**Comment by erasche** [comment]
Apologies for all the comments. `git clone --recursive` is arguably a reason...however bedtools doesn't actually require a recursive clone. There are no submodules, and there weren't at that point in time either. Arguably that is a problem with the bedtools' wrapper author, not with your new packages.

**Comment by bgruening** [comment]
I'm in favour of getting cmake it, where it makes sense. https://wiki.galaxyproject.org/Admin/Config/ToolDependenciesList lists it as ok to require but I'm with @blankenberg here. If it is easy to compile and failure proof, let's get it in.
I wouldn't offer git as package. Git is also mentioned on this wiki site as dependency and actually all installations should (now) have git installed to get the latest updates.

**Comment by blankenberg** [comment]
Split lines will definitely still parse, and I agree it may make it easier to read in some cases. I'm totally fine if we want to allow it (encourage it?) where it makes things easier to understand -- still think it looks goofy, but my brain can adjust ;) [this is totally an aside, and not at all really related to this particular PR]

**Comment by yhoogstrate** [comment]
I had chosen to split the lines because this was mentioned in https://github.com/galaxy-iuc/standards/blob/master/docs/best_practices/tool_xml.rst ("large XML tags should be broken into several lines"). But yeah, what's large :no_mouth: ?

**Comment by bgruening** [comment]
This is how I do this usually: https://github.com/galaxyproject/tools-iuc/blob/master/tools/bedtools/bedToBam.xml#L20

Not sure if this is better.

**Comment by erasche** [comment]
Huh, didn't know that was actually part of the IUC standards. Neat. Go Us! :laughing: 

+1 for cmake, -1 for git

**Comment by bgruening** [comment]
LGTM, no clue why the test is failing, but I'm ok merging this.

**Comment by erasche** [comment]
builds are failing because I *still* haven't set up proper dependency/package installation for the jenkins build bot, please just ignore it.

**Pull request merged**
