### PR TITLE
Trinity: better output for run_DE_analysis

### PR DESCRIPTION
**Pull request by abretaud**
A small PR:
-better regex to avoid mixing datasets in data collections
-make datasets non visible outside data collections

### CODE REVIEW

**Comment by abretaud** [comment]
Hum, maybe I should bump the version?

**Comment by nsoranzo** [comment]
No strong opinion about the version bump.

**Comment by nsoranzo** [comment]
With latest change, you need to increase version of tools/trinity/abundance_estimates_to_matrix.xml

**Comment by abretaud** [comment]
Done :)

**Comment by abretaud** [comment]
No objection to merge this?

**Comment by bgruening** [comment]
Thanks @abretaud!

**Pull request merged**
