### PR TITLE
Added ucsc_blat tool

### PR DESCRIPTION
**Pull request by Yating-L**
Galaxy wrapper for UCSC BLAT alignment tool
===========================================
BLAT (http://genome.ucsc.edu/goldenPath/help/blatSpec.html) is a bioinformatics software a tool which performs rapid mRNA/DNA and cross-species protein alignments. 

Features
--------
1. Perform rapid mRNA/DNA and cross-species protein alignments using blat 
2. Sort the output file
3. The output file can be filtered using UCSC pslCDnaFilter

Licence
-------
Please note that commercial download and installation of the Blat and In-Silico PCR software may be licensed through Kent Informatics (http://www.kentinformatics.com).

### CODE REVIEW

**Comment by bgruening** [comment]
@Yating-L do you mind to add the source here directly without a submodule, so we can help you maintaining it?

**Comment by yhoogstrate** [comment]
This came on my request and happy to review

**Comment by Yating-L** [comment]
I added the tool as a submodule by accident. So I create a new pull request with the source code. @bgruening .

**Comment by Yating-L** [comment]
Hi, @yhoogstrate . I created a new pull request for ucsc_blat #1310. Please let me know if you have any comments. Thank you for reviewing it!

**Pull request closed without merging**
