### PR TITLE
Add table compute (for general-purpose) table operations

### PR DESCRIPTION
**Pull request by mtekman**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [X] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

FOR REVIEWER:
* [ ] .shed.yml file ok
    - [ ] Toolshed user `iuc` has access to associated toolshed repo(s)
* [ ] Indentation is correct (4 spaces)
* [ ] Tool version/build ok
* [ ] `<command/>`
  - [ ] Text parameters, input and output files `'single quoted'`
  - [ ] Use of `<![CDATA[ ... ]]>` tags
  - [ ] Parameters of type `text` or having `optional="true"` attribute are checked with `if str($param)` before being used
* [ ] Data parameters have a `format` attribute containing datatypes recognised by Galaxy
* [ ] Tests
  - [ ] Parameters are reasonably covered
  - [ ] Test files are appropriate
* [ ] Help
  - [ ] Valid restructuredText and uses `<![CDATA[ ... ]]>` tags
* [ ] Complies with other best practice in [Best Practices Doc](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

******

This tool performs simple and custom table operations in a safe R environment

The PR is a continuation of https://github.com/galaxyproject/tools-iuc/pull/1960 which was mistakenly closed due to an error during a force push.

### CODE REVIEW

**Comment by mtekman** [comment]
@erasche do you have time to check this for vulnerabilities?

**Comment by erasche** [comment]
Absolutely I'll poke around.

**Comment by mblue9** [comment]
Hi @mtekman, was wondering if this could be used to calculate the variance for rows and add the output a column eg add a column with output of`apply(x, 1, var)` ?

**Comment by mtekman** [comment]
Hi @mblue9, yep I think so.

I would envision that as a two step operation, one where the variance is calculated, and two where the output vector is joined column-wise to the input table using the paste tool in Galaxy.

**Pull request closed without merging**
