### PR TITLE
fixed bug where unaligned and aligned fastqs would be empty

### PR DESCRIPTION
**Pull request by Takadonet**
fixed bug where unaligned and aligned fastqs would be empty when using a paired_collection

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by Takadonet** [comment]
Note that the wrapper version is slightly decoupled from the bioconda version from previous commit.
Bioconda version : **2.3.4.1**
wrapper version    : **2.3.4.3**
So just appended '+galaxy0' to Galaxy wrapper version.

Any suggestions moving forward?

**Comment by bgruening** [comment]
Just found this here: https://github.com/galaxyproject/tools-iuc/pull/2510

Could you integrate that one as well? Thanks!

**Comment by Takadonet** [comment]
added changes from #2510 and update test.

**Comment by bgruening** [comment]
Merci! :)

**Pull request merged**
