### PR TITLE
Enable meme_chip to run Centrimo

### PR DESCRIPTION
**Pull request by gregvonkuster**
Since https://github.com/galaxyproject/galaxy/pull/6374 was merged, tools will once again render multiple dependent dynamic select lists, where selecting an option in the first will render the options in the second.

With this fix, we can now include the option to run Centrimo here in the meme_chip tool, which requires installation of the ```meme motif databases downloader``` data manager tool.  This https://github.com/galaxyproject/tools-iuc/pull/1772 will have to be merged and made available in the MTS to enable this.

### CODE REVIEW

**Comment by bgruening** [comment]
@gregvonkuster can you increase the tool version number and maybe include a profile to indicate from which Galaxy version this tool is supposed to work?

**Comment by gregvonkuster** [comment]
@bgruening I've increased the tool version string.  Can you let me know what profile string you'd like to use?  It's difficult to know when support for this tool feature was broken in the Galaxy framework since I haven't messed around with the only other tool that uses it for a couple of years, so past profiles are probably not useful, and it should probably be the next release version.  Will that be 18.09?

**Comment by bgruening** [comment]
Good question @gregvonkuster. When was it fixed? I think 18.09 is a save bet. But maybe the fix is already in 18.05? Can you check? Thanks.

**Comment by gregvonkuster** [comment]
Here is the tag, so I set it to 18.09.  Thanks @bgruening 

```Fix for rendering multiple dependent dynamic select lists  kind/bug status/review
#6374 by gregvonkuster was merged 28 days ago • Approved    18.09```

**Pull request closed without merging**
