### PR TITLE
Updating tools/amrfinderplus from version 3.11.26 to 3.12.8

### PR DESCRIPTION
**Pull request by gxydevbot**
Hello! This is an automated update of the following tool: **tools/amrfinderplus**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/amrfinderplus from version 3.11.26 to 3.12.8.

**Project home page:** https://github.com/ncbi/amr/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bgruening** [comment]
> AMRFinderPlus v3.12.8 includes a new database format version. Because this version is incompatible with AMRFinderPlus databases from previous versions, amrfinder -u must be run once the software update is installed to get the latest version of the database.

Arg!

**Comment by bernt-matthias** [comment]
Note to ourself: always version datatable entries. Can we make this a rule (or strong suggestion)?

**Comment by bgruening** [comment]
Yes, we can make that an IUC guideline. https://galaxy-iuc-standards.readthedocs.io

**Comment by bebatut** [comment]
AMRFinderPlus is already in version 3.12.8: https://github.com/galaxyproject/tools-iuc/blob/main/tools/amrfinderplus/macro.xml#L2

**Pull request closed without merging**
