### PR TITLE
Add mummer package created by James Johnson.

### PR DESCRIPTION
**Pull request by bgruening**
Fix for: https://github.com/galaxyproject/tools-iuc/issues/9#issuecomment-75721174

### CODE REVIEW

**Comment by peterjc** [comment]
Looks good, just add a ``.shed.yml`` file too?

**Comment by bgruening** [comment]
Done.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/29/
Test PASSed.

**Comment by peterjc** [comment]
+1 on merging assuming no problems from the tests...

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/30/
Test PASSed.

**Comment by bgruening** [comment]
Great, thanks!

**Pull request merged**
