### PR TITLE
Updating tools/funannotate from version 1.8.9 to1.8.15

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/funannotate**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/funannotate from version 1.8.9 to 1.8.11.

**Project home page:** https://funannotate.readthedocs.io

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by abretaud** [comment]
I can have a look some time soon :crossed_fingers:

**Comment by bernt-matthias** [comment]
> I can have a look some time soon crossed_fingers

This would be awesome, since the current version fails CI. This is because the tool writes to the input dir (which seems to be solved https://github.com/nextgenusfs/funannotate/commit/7743ccffa57afe0a53f8221d57bb4857c40eaff7 .. https://github.com/nextgenusfs/funannotate/issues/722)

**Comment by abretaud** [comment]
Ok, the error comes from a strange augustus error, maybe related to gcc version.
I'll try to investigate more but I think it will be long and painful :(

**Comment by bernt-matthias** [comment]
In a recent CI test for compare I have seen 

```
[Nov 28 08:49 AM]: Running GO enrichment for each genome
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/funannotate/aux_scripts/enrichment_parallel.py", line 76, in <module>
    lib.runMultiNoProgress(GO_safe_run, file_list, procs)
  File "/usr/local/lib/python3.8/site-packages/funannotate/library.py", line 1303, in runMultiNoProgress
    p = multiprocessing.Pool(cpus)
  File "/usr/local/lib/python3.8/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
  File "/usr/local/lib/python3.8/multiprocessing/pool.py", line 205, in __init__
    raise ValueError("Number of processes must be at least 1")
ValueError: Number of processes must be at least 1
```

**Comment by abretaud** [comment]
Still failing, but I think the to-be-released 1.8.14 should fix the current error

**Review by abretaud — APPROVED** [review]

**Comment by abretaud** [comment]
Thanks @nextgenusfs for the new release!
Green now! Anyone else wants to review? I'll merge in a moment otherwise

**Review by bernt-matthias — APPROVED** [review]

**Pull request merged**
