### PR TITLE
new minimap release

### PR DESCRIPTION
**Pull request by bgruening**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by wm75** [comment]
Puh, the failing tests are the ones testing PE input, and alignment of PE reads is exactly what was changed in this new release so presumably that's ok.
Since lh3 calls the new behavior a fix of a regression introduced in 2.18, you would expect kind of a mirror image change in the test data when the tool was updated to 2.18. Something to investigate, but not today for me.

**Review by bernt-matthias — COMMENTED** [review]
The diff in the bam files is likely due to https://github.com/galaxyproject/tools-iuc/issues/3699

Maybe just add `--no-PG` to the `samtools sort` calls in the wrapper 

https://github.com/galaxyproject/tools-iuc/blob/2c96bcee8728afb9e108ee942097af5ead75faa8/tools/minimap2/minimap2.xml#L153

and a few lines below. 

If necessary add lines_diff to the bam outputs.

**Comment by wm75** [comment]
@bernt-matthias I guess this is *not* the explanation here. This wrapper has been updated twice since #3699 got merged.
It's also not the header changes that we need to think about, but there are real alignment record changes, too.

**Comment by bernt-matthias** [comment]
Maybe https://github.com/galaxyproject/tools-iuc/issues/2432

**Comment by bernt-matthias** [comment]
Another open minimap issue

**Comment by bernt-matthias** [comment]
Seems outdated now, or?

**Comment by bgruening** [comment]
Oh yes :)

My attempt to play a bot before no bot was available ;)

**Pull request closed without merging**
