### PR TITLE
Attempt to fix Gene Body Coverage output for MultiQC by adding element.identifier to HISAT2

### PR DESCRIPTION
**Pull request by mblue9**
I don't know if this PR is necessary (I think I may have just wasted a chunk of time) but what I was trying to do was...

The Gene body coverage tool has the element_identifier in the wrapper but for some reason the "Tool on data N" dataset name is used in the txt output file, which is what's used by MultiQC, so you currently get the hard-to-interpret ("Tool on data N") names like below.

screen shot 2018-09-18 at 9 46 41 am

e.g. gene body coverage runs this:

ln -sf '/private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpa_yOOf/files/000/dataset_28.dat' 'HISAT2_on_data_2_and_data_3__aligned_reads__BAM_.bam' && ln -sf '/private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpa_yOOf/files/_metadata_files/000/metadata_4.dat' 'HISAT2_on_data_2_and_data_3__aligned_reads__BAM_.bam.bai' && geneBody_coverage.py -i 'HISAT2_on_data_2_and_data_3__aligned_reads__BAM_.bam' -r '/private/var/folders/zn/m_qvr9zd7tq0wdtsbq255f8xypj_zg/T/tmpa_yOOf/files/000/dataset_14.dat' --minimum_length 100 -o output

I thought maybe the "name" field was being used because there was no element.identifier associated with the hisat bam in the hisat wrapper so I tried changing the bam file output in the hisat2 wrapper to use the element.identifier (the changes in this PR, modelled on cutadapt) but the gene body coverage wrapper is still using the "HISAT on data N" name. If anyone knows why that is happening and if it can be fixed please let me know.

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

FOR REVIEWER:
* [ ] .shed.yml file ok
    - [ ] Toolshed user `iuc` has access to associated toolshed repo(s)
* [ ] Indentation is correct (4 spaces)
* [ ] Tool version/build ok
* [ ] `<command/>`
  - [ ] Text parameters, input and output files `'single quoted'`
  - [ ] Use of `<![CDATA[ ... ]]>` tags
  - [ ] Parameters of type `text` or having `optional="true"` attribute are checked with `if str($param)` before being used
* [ ] Data parameters have a `format` attribute containing datatypes recognised by Galaxy
* [ ] Tests
  - [ ] Parameters are reasonably covered
  - [ ] Test files are appropriate
* [ ] Help
  - [ ] Valid restructuredText and uses `<![CDATA[ ... ]]>` tags
* [ ] Complies with other best practice in [Best Practices Doc](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

### CODE REVIEW

**Comment by mblue9** [comment]
hmm don't know how I ended up with this messy-looking PR :(

**Comment by mvdbeek** [comment]
You have to fetch and rebase against the current dev. Assuming https://github.com/galaxyproject/tools-iuc is your current origin 
```
git fetch origin
git rebase origin/dev
```
I think that should probably run without conflicts

**Comment by mblue9** [comment]
Thanks for the help @mvdbeek !

I tried what you suggested and I get below. Do I go through the files fixing any merge conflicts and git adding them?

```
First, rewinding head to replay your work on top of it...
Applying: Fix tool Structure output file names so that they can be used in the downstream tool StructureHarvest (using a regex to get the input files)
Using index info to reconstruct a base tree...
M	tools/structure/structure.xml
Falling back to patching base and 3-way merge...
No changes -- Patch already applied.
Applying: trinity 2.8.1 is available
Using index info to reconstruct a base tree...
M	tools/trinity/macros.xml
Falling back to patching base and 3-way merge...
Auto-merging tools/trinity/macros.xml
CONFLICT (content): Merge conflict in tools/trinity/macros.xml
error: Failed to merge in the changes.
Patch failed at 0002 trinity 2.8.1 is available
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

**Comment by lparsons** [comment]
BTW, I believe @mvdbeek fixed this issue by helping me with this patch: #2107.

See https://github.com/galaxyproject/galaxy/issues/6182 for discussion and #2108 for linting fix that will (hopefully) allow me to get this fix pushed out.

**Comment by lparsons** [comment]
@mblue9 I can confirm that the latest version of Gene Body Coverage now outputs using the element_identifier and thus the MultiQC reports also use the correct element_identifier.

**Comment by mblue9** [comment]
Excellent!!  🎉Thanks a lot @lparsons and @mvdbeek ! This was the last thing not working in the otherwise lovely MultiQC report I had (oops @lparsons I didn't realise you'd already filed an issue on the gene body coverage naming).

Not sure what to do here with this PR but I'm going to close it for the moment. The only reason for keeping the changes here I think is that it makes hisat more consistent with cutadapt but I don't know if that's necessary.

**Pull request closed without merging**
