### PR TITLE
Deepvariant

### PR DESCRIPTION
**Pull request by HassanAmr**

### CODE REVIEW

**Comment by mblue9** [comment]
Hi @HassanAmr thanks for contributing this tool!

Travis is giving an error because it can't find the `ucsc.hg19.chr20.unittest.fasta` file as in the deepvariant test-data directory it's `ucsc.hg19.chr20.unittest.fasta.gz`. I tried unzipping it and it moves past that Travis error onto this one (for me anyway):

`parallel: Error: Command line too long (481 >= 0) at input 0: 0`

**Comment by HassanAmr** [comment]
Hi @mblue9,
Thanks. I was working on producing a smaller test-case. Didn't know galaxy can work with zipped files.

**Comment by bgruening** [comment]
Ok, this is as far as we can get for the moment. The bioconda package needs to either compile deepvariant or use more compliant binaries. Nothing we can do about this last error :(

Thanks all for your help!

**Comment by gallardoalba** [comment]
It can be closed I think @bernt-matthias.

**Comment by bgruening** [comment]
Tool is available here: https://usegalaxy.eu/root?tool_id=toolshed.g2.bx.psu.edu/repos/iuc/deepvariant/deepvariant/1.2.0+galaxy1

**Pull request closed without merging**
