### PR TITLE
Fix bctools_remove_spurious_events test, run containerized tests

### PR DESCRIPTION
**Pull request by mvdbeek**
Allows for this diff:
```
--- local_file
+++ history_data
@@ -1,6 +1,6 @@
+chr1	10	20	AAAAA	100	+
 chr1	10	20	AAAAA	5	-
 chr1	10	20	AAAAA	5	-
 chr1	10	20	AAAAA	4	-
 chr1	10	20	AAAAA	3	-
-chr1	10	20	AAAAA	100	+
 chrX	20	30	TTTTT	7	+
```

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Would "sort" work here? Marius do we need the version bump?

**Comment by mvdbeek** [comment]
Meh, we're not super consistent with the version bumps. Yeah, sorting should work

**Comment by mvdbeek** [comment]
I've cherry-picked John's dockerized testing commit to make sure this works in the container and bumped to 20.01. I guess now wouldn't be a bad time to start using this?

**Comment by mvdbeek** [comment]
Nice, all green 😎

**Comment by mvdbeek** [comment]
Right. I know the on-the-fly building works well in the GitHub workflow, I don't think we need an additional test for that before merging?

**Comment by bgruening** [comment]
Agreed, lets see how this works on master :)

Thanks a lot Marius!

**Pull request merged**
