### PR TITLE
kraken2 data manager: Allow cleanup to be optional

### LINKED ISSUE #2511: Kraken2 Data Manager: Make cleanup optional
`kraken2-build` provides a `clean` operation that removes the `library` and `taxonomy` directories to minimize kraken database storage. It is currently run by default in the `data_manager_build_kraken2_database` tool.

But some tools (notably `bracken`) require some of the data that is removed by the cleanup process for their functionality.

It would be good to allow the user to decide whether or not to clean the kraken2 database. Cleanup should probably be enabled by default.

### PR DESCRIPTION
**Pull request by dfornika**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Fixes #2511

### CODE REVIEW

**Comment by dfornika** [comment]
I've updated the version string from `2.0.8_beta` to `2.0.8_beta+galaxy1`.

**Comment by dfornika** [comment]
It looks like the most recent TravisCI build failed due to a network issue. The `kraken2-build` downloads taxonomy info from NCBI and that failed. Could it be re-started @bgruening?

**Comment by nsoranzo** [comment]
@dfornika Done.

**Comment by bgruening** [comment]
Merci!

**Pull request merged**
