### PR TITLE
Fix chromeister tests

### PR DESCRIPTION
**Pull request by cat-bro**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Fix tests for this tool (it appears to be OK from planemo results but this is because the tests do not run, see https://github.com/galaxyproject/tools-iuc/runs/1727263758#step:11:100)

This PR reverts a commit from a few months ago that removed a number of output files, replaces one of the the test files, fixes assumptions about the number of outputs and removes some `<output/>`s from the 4th test.

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Ping @estebanpw

**Comment by estebanpw** [comment]
I am guessing the output number of files refers to the total number of produced files and not the ones that get marked as actual outputs in the xml file, my bad.

I have inspected the output of the testing and it seems it fails with the following error in all tests:

```
Dataset Job Standard Error:
|  /usr/local/env-execute: 5: /usr/local/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: \"(\" unexpected
```

Do you know where that is coming from? Could it be linked to the virtualenv and the packages that are required for the python script?

**Comment by cat-bro** [comment]
Tests are passing locally with planemo.  Could the errors here have to do with cached environments used in the CI script?

**Review by estebanpw — APPROVED** [review]

**Comment by bgruening** [comment]
@cat-bro have you run the test locally with `planemo test --docker`?

**Comment by cat-bro** [comment]
@bgruening I did not use the `--docker` flag.  I'll try that.

**Comment by cat-bro** [comment]
with `planemo test --docker` I get the exact same error as occurs in the linting process.  `/usr/local/env-execute: 5: /usr/local/etc/conda/activate.d/activate-binutils_linux-64.sh: Syntax error: \"(\" unexpected\n`.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
It was the container that was broken ... urgs. I fixed that. Sorry @cat-bro!

**Pull request merged**
