### PR TITLE
mothur: allow fastq.gz

### PR DESCRIPTION
**Pull request by bernt-matthias**
- in make.contigs all cases are now treated with `combo_fastq.dat`. this changed the output slightly. if this is undesireable I can revert this
- we could also remove all fastq test files .. or leave some tests for the fastq case
- some tools did not accept gz natively -> then unzip them
- did not apply to [fr]index in make.contigs since untested
  and I have no idea how this works

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
@shiltemann can you please have a look at this one?

**Comment by bgruening** [comment]
maybe we can get a fix for https://github.com/galaxyproject/tools-iuc/issues/3663 into this one as well.

**Review by shiltemann — APPROVED** [review]

**Comment by shiltemann** [comment]
Thanks @bernt-matthias, looks good to me!

**Comment by bernt-matthias** [comment]
@bgruening do we want to merge and not deploy .. in case we want to merge multiple PRs we might save some updates to the TS?

**Comment by mvdbeek** [comment]
The version bumps are a must IMO, the inputs are changing.

**Comment by bernt-matthias** [comment]
Now covered by https://github.com/galaxyproject/tools-iuc/pull/3765

**Pull request closed without merging**
