### PR TITLE
Receive R's transferred dependencies.

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by martenson** [comment]
xref: https://github.com/galaxyproject/tools-devteam/pull/204

**Comment by erasche** [comment]
lgtm.

**Comment by martenson** [comment]
:+1:

**Comment by erasche** [comment]
@martenson before we merge this, would you mind responding to:

> Would y'all accept a PR version of 204/240 which retains edit history [in lieu of a legacy/ folder]?

**Pull request merged**
