### PR TITLE
Fix snpeffdb output to not contain broken symlinks

### LINKED ISSUE #5647: Staging out composite dataset files fails due to security check ("Attempt to read or write file outside an authorized directory.") on subdirectory of `outputs/`
From a test snpEff job that Jen ran:
```
2023-11-16 20:13:47,581 INFO  [pulsar.client.staging.down][[manager=jetstream2]-[action=postprocess]-[job=53733643]] collecting output dataset_780f791e-0118-430f-a6b3-0947d06e6c43_files/salmonella/sequences.fa with action FileAction[path=/corral4/main/objects/7/8/0/dataset_780f791e-0118-430f-a6b3-0947d06e6c43_files/salmonella/sequences.fa,action_type=remote_transfer,url=https://galaxy-web-03.galaxyproject.org/_job_files?job_id=bbd44e69cb8906b57616901504efc56d&job_key=c0ffee&path=%2Fcorral4%2Fmain%2Fobjects%2F7%2F8%2F0%2Fdataset_780f791e-0118-430f-a6b3-0947d06e6c43_files%2Fsalmonella%2Fsequences.fa&file_type=output]
2023-11-16 20:13:47,626 WARNI [pulsar.client.job_directory][[manager=jetstream2]-[action=postprocess]-[job=53733643]] Attempt to read or write file outside an authorized directory. Attempted path: /jetstream2/scratch/main/jobs/53733643/outputs/dataset_780f791e-0118-430f-a6b3-0947d06e6c43_files/salmonella/sequences.fa, valid directory: /jetstream2/scratch/main/jobs/53733643/outputs
2023-11-16 20:13:57,571 WARNI [pulsar.managers.staging.post][[manager=jetstream2]-[action=postprocess]-[job=53733643]] Failures collecting results [Exception('Attempt to read or write file outside an authorized directory.'), Exception('Attempt to read or write file outside an authorized directory.')]
```

### PR DESCRIPTION
**Pull request by mvdbeek**
Instead just copy out the actual .bin files.

We have no test coverage for snpeffdb files since those are composite files in disguise, I can test this manually.

Fixes #5647 

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by natefoo — APPROVED** [review]

**Comment by mvdbeek** [comment]
Tested this manually by downloading https://www.ncbi.nlm.nih.gov/nuccore/KJ660346, building a database for it and then running snpeff on this and input.vcf from the test data folder

**Comment by mvdbeek** [comment]
linting seems to be false positive for the somewhat odd add_value filter type

**Comment by nsoranzo** [comment]
> linting seems to be false positive for the somewhat odd add_value filter type

This needs to be uploaded manually to the TS then, as reported by the bot.

**Comment by mvdbeek** [comment]
I thought we had skipped that rule ?

**Comment by mvdbeek** [comment]
apparently not: https://github.com/galaxyproject/tools-iuc/pull/5650

**Comment by mvdbeek** [comment]
uploaded manually

**Comment by bernt-matthias** [comment]
> linting seems to be false positive for the somewhat odd add_value filter type

Independent of that (I don't know if this is true since `options_filter_attribute` is undocumented) I think that the `options` and `validator` tag are redundant.

Also `options_filter_attribute` is super inefficient and has been marked deprecated.

**Pull request merged**
