### PR TITLE
Enables user to set gene_symbol column name in .var for various plots.

### PR DESCRIPTION
**Pull request by pcm32**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

This PR exposes the existing gene_symbol parameter for more plotting types, so that the user can choose the column within .var where the gene symbols are located if these are not the main index of var. Not sure if you want me to bump the +galaxy number given that this is mostly reusing existing elements.

### CODE REVIEW

**Comment by bgruening** [comment]
@pcm32 thanks. Should we add a test for this?

Can you please also bump the tool version of this wrapper. Thanks!

**Comment by pcm32** [comment]
No problem in bumping. I have tried some of the existing reduced datasets there, and none of them lend themselves nicely for the test; they either do not have .var or they store the gene symbols in the .var index (and you are not allowed to specify the index as a column). It would require modifying and duplicating one of the small h5ad. The same functionality already existed in some of the other plotting functions and is currently not covered in the tests (besides a case where the means are used which doesn't extrapolate well to all plots).

**Comment by pcm32** [comment]
Ok, I have modified one of the reduced datasets, let me see if it works nicely with all the plots I modified.

**Comment by pcm32** [comment]
I'm struggling to modify `tl.rank_genes_groups.krumsiek11.h5ad` for the rank gene examples.

**Comment by pcm32** [comment]
I had to remove the changes for `pl.rank_genes_groups_*` becuase they don't play nicely with symbols in different columns of var (not being the index elsewhere), see https://github.com/theislab/scanpy/issues/1796.

**Comment by pcm32** [comment]
Now tests added cover all new functionality @bgruening .

**Comment by bgruening** [comment]
@pcm32 can you give me edit access to your fork please?

**Comment by pcm32** [comment]
I have added you to our fork with write access. I couldn't find any other option that would allow you to write easily.

**Comment by nsoranzo** [comment]
> I have added you to our fork with write access. I couldn't find any other option that would allow you to write easily.

Unfortunately it's not possible to use the normal "Allow edits by maintainers" for PRs opened from a fork owned by an organisation.

**Comment by bgruening** [comment]
Thanks @pcm32. If that turns green I will merge. I did the last commit just because we only want to have this tool updated and not all the other tools as well. We should reset the version as soon as a new scanpy version is out.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
merci!

**Comment by pcm32** [comment]
Thanks @bgruening !

**Pull request merged**
