### PR TITLE
Update ivar to version 1.2.2

### PR DESCRIPTION
**Pull request by wm75**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by wm75** [comment]
@bernt-matthias yes, you can pass unpaired reads to ivar, why?
why and where do you think bed input is optional?

Stricter handling of primer detection (only at 5' end of reads seems to be the only relevant change in 1.2.2 (see https://github.com/andersen-lab/ivar/compare/v1.2.1...v1.2.2), but that's an important one for Illumina data.

**Comment by bernt-matthias** [comment]
According to the 1.2.1 release notes: 

> BED file (-b) now optional for ivar trim. In absence of BED file, ivar trim just does quality trimming and writes all reads that pass min length threshold (-m) to file. 

and 

> ivar trim now supports unpaired reads

(just wanted to make sure that this is possible).

**Comment by wm75** [comment]
> According to the 1.2.1 release notes:
> 
> > BED file (-b) now optional for ivar trim. In absence of BED file, ivar trim just does quality trimming and writes all reads that pass min length threshold (-m) to file.
> 

Ah, this thing. Nobody thought about that so the wrapper requires the BED input I think, but to be honest we have plenty of trimming options in Galaxy and without the BED input ivar doesn't add much to that.

The unpaired input works also with the wrapper.

**Comment by bgruening** [comment]
@bernt-matthias upps ... I have not seen you comment before merging :( Sorry.

**Comment by bernt-matthias** [comment]
@bgruening fine with me. I'm completely convinced by the reasoning of @wm75 .

**Pull request merged**
