### PR TITLE
rpy2 2.2.7.8 package

### PR DESCRIPTION
**Pull request by mvdbeek**
This matches what is available in conda.

### CODE REVIEW

**Comment by yhoogstrate** [comment]
Hey @mvdbeek, could you fix the URL? I get:
```wget https://depot.galaxyproject.org/software/rpy2/rpy2_2.7.8_src_all.tar.gz 
--2016-09-01 14:42:57--  https://depot.galaxyproject.org/software/rpy2/rpy2_2.7.8_src_all.tar.gz
Resolving depot.galaxyproject.org (depot.galaxyproject.org)... 128.118.250.14
Connecting to depot.galaxyproject.org (depot.galaxyproject.org)|128.118.250.14|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-09-01 14:42:58 ERROR 404: Not Found.```

**Comment by mvdbeek** [comment]
Actually this depends on https://github.com/galaxyproject/cargo-port/pull/97.
I guess I can just merge that on my own.

**Comment by mvdbeek** [comment]
OK, I guess this will still take a moment.

**Comment by yhoogstrate** [comment]
We're online, looks good to me @mvdbeek thanks!! :+1:

**Comment by mvdbeek** [comment]
OK, this is ready, tested from TTS and works.

**Comment by bgruening** [comment]
LGTM!

**Pull request merged**
