### PR TITLE
Update name2taxid wrapper

### PR DESCRIPTION
**Pull request by SantaMcCloud**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [ ] This PR adds a new tool or tool collection
* [x] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Comment by SantaMcCloud** [comment]
I change the select column from data_ref to integer, since it can happen that you have multiple files as input and all files share the same column as input. With data_ref it can not work since my workflow generate a collection which stop it there since it has now data as reference for the column or at least it still throws an error if you try to use it this way.

**Comment by SantaMcCloud** [comment]
@bgruening could you merge this quick to have this in the bot update scope?

**Comment by bgruening** [comment]
Same here, please explain us what is the motivation and what is the error that you are seeing. Maybe share the workflow/history.

**Comment by SantaMcCloud** [comment]
I found a way to handle this error here, so I will close the PR since it is not needed anymore

**Pull request closed without merging**
