### PR TITLE
bump ncbi datasets

### PR DESCRIPTION
**Pull request by bernt-matthias**
Failing CI. Lets see if this helps

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Is the autobump bot not working anymore? Haven't seen it anymore.

**Comment by bernt-matthias** [comment]
> Is the autobump bot not working anymore? Haven't seen it anymore.

I also noticed that...

**Comment by nsoranzo** [comment]
It seems the last scheduled action ran 2 months ago: https://github.com/planemo-autoupdate/autoupdate/actions . Maybe the planemo-autupdate bot was blocked by GitHub?

**Comment by bernt-matthias** [comment]
It says: `This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. `

**Comment by nsoranzo** [comment]
Ping @simonbray 
Not sure if anyone else has the necessary privileges on that repository, it would be good to increase the bus factor if it's only Simon.

**Comment by simonbray** [comment]
I believe Cristo has access, I'll add a few more people when I'm back in
front of a computer (in a tent right now)

**Comment by gallardoalba** [comment]
Yes, I have access too.

**Pull request merged**
