### PR TITLE
Fix error to plasmidfinder data manager

### PR DESCRIPTION
**Pull request by pimarin**
from this issue [5409](https://github.com/galaxyproject/tools-iuc/issues/5409), i checked the data manager.
The database was downloaded but the path giver to store database was no well completed it missing the `db_name` info to allow galaxy to manage the folder.

Tested and pass test to make the json and the .loc file but also to moove database

### CODE REVIEW

**Review by bernt-matthias — COMMENTED** [review]
Can you bump the VERSION_SUFFIX of the data manager tool?

**Comment by pimarin** [comment]
I don't understand the error :

```
Job in error state.. tool_id: data_manager_fetch_plasmidfinder, exit_code: 125, stderr: docker: invalid spec: ::rw: empty section between colons.
See 'docker run --help'.
```

**Comment by pimarin** [comment]
Thank's @bernt-matthias  !

**Review by bernt-matthias — APPROVED** [review]

**Comment by pimarin** [comment]
thank's a lot @bernt-matthias  !

**Pull request merged**
