### PR TITLE
update get_length_and_gc_content

### PR DESCRIPTION
**Pull request by lldelisle**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

My chages are:
- Do not request fasta if only interested in length.
- Use single letter with single hyphen.
- Update the test to get multiple exons and multiple genes

### CODE REVIEW

**Comment by lldelisle** [comment]
Good idea

**Comment by lldelisle** [comment]
I don't know what is the policy, should I update the dependencies? Or is it better to keep the old ones?

**Comment by lldelisle** [comment]
" [Mar 10 13:57:28] SERR UnsatisfiableError: The following specifications were found to be incompatible with each other:"
...
I don't understand how it is possible...

**Comment by lldelisle** [comment]
Pfiou, it passes...

**Comment by lldelisle** [comment]
@wm75 do you need more changes?

**Review by wm75 — APPROVED** [review]
No, nothing to add @lldelisle - very nice work, thank you!

**Comment by lldelisle** [comment]
@wm75 Thanks for the review and the merge

**Pull request merged**
