### PR TITLE
Update ncbi datasets

### PR DESCRIPTION
**Pull request by bernt-matthias**
Recover https://github.com/galaxyproject/tools-iuc/pull/4886 (which was deleted for some reason .. I only marked it as draft while working on it).

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
I guess this removes the "virus-functionality". Since I removed the `excludes_virus_protein` macro (and all the include/exclude arguments which are now covered by `--include`

Downloading virus data seems now to work with `datasets download virus [genome|protein]`

**Comment by mvdbeek** [comment]
This is awesome, thanks @bernt-matthias!

**Comment by bernt-matthias** [comment]
Two questions @mvdbeek: 

- is the removal of the virus functionality fine (it moved to a separate subcommand)? Or should I consider to readd it as separate tool? 
- To download the data of multiple `taxon` I created an auxiliary workflow using an expression tool. This will then create a parallel download job for each genome. Might this be sanctioned by NCBI (aborted downloads)? I see two alternatives
  - is it possible to limit the number of parallel jobs in galaxy thereby I could serialize the processing of the downloads
  - I could change the tool such that it uses a bash for loop for downloading multiple `taxon` (eg given in a file)

**Comment by mvdbeek** [comment]
> * is the removal of the virus functionality fine (it moved to a separate subcommand)? Or should I consider to readd it as separate tool?

That's fine I think. It used to be a separate tool (I had implemented everything, but it was decided to go one tool at a time), and we only kept the macro. I guess at this point the options have changed; starting from scratch is probably easier than picking this back up.

I think the batch/parallel question is something we can't really answer, let's keep it as it is for now ?

**Review by mvdbeek — APPROVED** [review]

**Comment by bernt-matthias** [comment]
> let's keep it as it is for now ?

Fine with me. 

Unsure about the test failures. All tests pass locally for me.

**Comment by mvdbeek** [comment]
> All tests pass locally for me.

Same, could be the container again ... although then I'd expect everything to fail.

**Pull request merged**
