### PR TITLE
Updating tools/bwameth from version 0.2.3 to 0.2.4

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/bwameth**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/bwameth from version 0.2.3 to 0.2.4.

**Project home page:** https://github.com/brentp/bwa-meth/releases

### CODE REVIEW

**Comment by bgruening** [comment]
Is there a way to skip the release? This one only contains fixes for bwa2 that we do not support.

**Comment by bernt-matthias** [comment]
I would suggest that we simply close PRs which we want to skip. Or will the autoupdater open a new PR?

**Comment by simonbray** [comment]
It will reopen them, as for BiocondaBot, which I followed quite closely for the implementation.

Bioconda are dealing with this situation using the `do-not-close` tag: https://github.com/bioconda/bioconda-recipes/pulls?q=is%3Aopen+is%3Apr+label%3Ado-not-close

Maybe that could be an option here as well?

**Comment by simonbray** [comment]
Hm, maybe

**Comment by planemo-autoupdate** [comment]
let's test

**Pull request closed without merging**
