### PR TITLE
Metaphlan2

### PR DESCRIPTION
**Pull request by yuanbit**
FOR CONTRIBUTOR:
* [X ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

FOR REVIEWER:
* [ ] .shed.yml file ok
    - [ ] Toolshed user `iuc` has access to associated toolshed repo(s)
* [ ] Indentation is correct (4 spaces)
* [ ] Tool version/build ok
* [ ] `<command/>`
  - [ ] Text parameters, input and output files `'single quoted'`
  - [ ] Use of `<![CDATA[ ... ]]>` tags
  - [ ] Parameters of type `text` or having `optional="true"` attribute are checked with `if str($param)` before being used
* [ ] Data parameters have a `format` attribute containing datatypes recognised by Galaxy
* [ ] Tests
  - [ ] Parameters are reasonably covered
  - [ ] Test files are appropriate
* [ ] Help
  - [ ] Valid restructuredText and uses `<![CDATA[ ... ]]>` tags
* [ ] Complies with other best practice in [Best Practices Doc](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

### CODE REVIEW

**Comment by bwlang** [comment]
This looks good to me... just need to re-trigger travis since he timed out.

**Comment by bebatut** [comment]
The database was downloaded given if you give to MetaPhlAn an already existing database. I added something to trick MetaPhlAn to make it use the local database and not downloading it.
Will see if it fixes the tests

**Comment by nsoranzo** [comment]
Maybe the conda envs creation takes a long time?

**Comment by bwlang** [comment]
I wonder if travis would work now ... worth a retry?
I don't know how to trigger that...

**Comment by nsoranzo** [comment]
Restarted the Travis build.

**Comment by nsoranzo** [comment]
Unfortunately this PR needs a rebase.

**Comment by bernt-matthias** [comment]
Metaphlan2 is now deprecated. Newer versions are in metaphlan.

**Pull request closed without merging**
