### PR TITLE
Updating tools/metaphlan from version 4.0.5 to 4.0.6

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/metaphlan**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/metaphlan from version 4.0.5 to 4.0.6.

**Project home page:** https://github.com/biobakery/MetaPhlAn/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Probably something for the data manager:  The GTDB taxonomic assignment for the vOct22 database is now available.

**Comment by bgruening** [comment]
Do you think we need to update the DM?

**Comment by bernt-matthias** [comment]
> Do you think we need to update the DM?

Seems so.

**Comment by tuncK** [comment]
> Probably something for the data manager: The GTDB taxonomic assignment for the vOct22 database is now available.

It was actually released in Dec 2022 but the .tar was broken. We had already addressed it in the past DM revision, it seems to work as is, as far as I can tell.

Can you please merge this or https://github.com/galaxyproject/tools-iuc/pull/5218 ?

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/tools-iuc/pull/5218

**Pull request merged**
