### PR TITLE
Add Velvetoptimiser to the IUC repo

### PR DESCRIPTION
**Pull request by Slugger70**

### CODE REVIEW

**Comment by abretaud** [comment]
Nice!
If it's possible could you try to reduce the size of the test data?
Also, I don't know if you have control on this but I've made a [tiny PR for velvetoptimiser](https://github.com/tseemann/VelvetOptimiser/pull/20)
Apart from that, it's 👍 for me

**Comment by Slugger70** [comment]
I merged your PR for Velvet Optimiser and will include it in the next release version.. The test data is that shipped with Velvet itself and is already pretty tiny..

**Comment by abretaud** [comment]
Great, thanks @Slugger70 !

**Comment by abretaud** [comment]
The upload to TS [failed](https://travis-ci.org/galaxyproject/tools-iuc/jobs/319604833)
I don't understand why on TTS it created [a repo with owner=iuc ](https://testtoolshed.g2.bx.psu.edu/view/iuc/velvetoptimiser/e27fc7443e0a) instead of [simon-gladman](https://github.com/galaxyproject/tools-iuc/pull/1641/files#diff-43127e7e02fa813998ea43a25890a237R7)
On MTS did you give permission to iuc user to upload to your velvetoptimiser repo?

**Comment by bgruening** [comment]
@Slugger70 can you add IUC (the group) to the repo to the Admin permissions.

**Comment by Slugger70** [comment]
Done

**Pull request merged**
