### PR TITLE
Add picrust

### PR DESCRIPTION
**Pull request by shiltemann**
addresses #1015, work in progress, help welcome ;)
package already in conda, test data can be found here: https://github.com/picrust/picrust/tree/master/picrust_test_data

update existing tools:
- [x] normalize_by_copynumber
- [x] predict_metagenomes
- [x] categorize_by_function

add new tools (some? all?)
- [ ] predict_traits
- [ ] metagenome_contributions
- [ ] ancestral_state_reconstruction
- [ ] compare_biom
- [ ] format_tree_and_trait_table
- [ ] run_genome_evaluations
- [ ] scale_metagenome

### CODE REVIEW

**Comment by bgruening** [comment]
Great work @shiltemann! I triggered a rebuild let's see if it passing now, if not can you please rebase against master.

It would be nice to have the other tools as well, but this is a great start and hopefully someone else will pick them up.

Thanks!

**Comment by shiltemann** [comment]
yep, will rebase :)

**Comment by bgruening** [comment]
Great! Is this ready to merge or still WIP?
Release early, release often ;)

**Comment by shiltemann** [comment]
nope, what's there is good to go I think, and we can add additional tools later :)

**Pull request merged**
