### PR TITLE
Updates and fixes to the "clustering" tool in the vsearch suite

### PR DESCRIPTION
**Pull request by pjbriggs**
This PR makes the following fixes to the `vsearch` `clustering` tool:

 1. Fix the original test case (remove specification of `--sizeout` as reference output appears to have been generated without this option)
 2. Fix the generation of the `--sizein` and `--sizeout` options in the command template.
 3. Fix the `--qmask` macro in `vsearch_macros.xml` (was broken if "No masking" was selected), and add a test case. I haven't explicitly tested this change for other tools that use this macro however existing test cases still pass for me.

In addition the PR implements support for the following options of `vsearch` (with test cases):

 - `--cluster_smallmem` (this change incorporates a fix to the `--usersort` option, to make it consistent with the output from `vsearch --help`)
 - `--uc`
 - `--iddef`

The text in the `help` section has also been updated to make it consistent with the output from `vsearch --help`.

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by bgruening** [comment]
@pjbriggs sorry I had forgotten about this one. Mea culpa!
This looks really nice! Can you please increase the tool version number and check your test files?
`tools/vsearch/test-data/clustering_uc_result3.fasta` is not a FASTA file as far as I can see.

Thanks!
Bjoern

**Comment by pjbriggs** [comment]
@bgruening thanks for picking this up again, and also for checking - you're right, in fact it is a tabular format file that mimics the output from UCLUST. This is now fixed (and version bumped).

**Comment by bgruening** [comment]
Really nice! These tools shaping up nicely!
Thanks @pjbriggs!

**Comment by bgruening** [comment]
TTS is updated! If you can test, this would be awesome, otherwise I will do and update the MTS this evening.

**Comment by pjbriggs** [comment]
@bgruening Thanks - I've just tried installing the TTS version here but it looks like these changes didn't make it in e.g. the clustering tool is still at `.0` and doesn't have the `--uc` or other options :(

**Comment by bgruening** [comment]
@pjbriggs it's now on both Sheds!
Hope its working for you as well and thanks again!

**Pull request merged**
