### PR TITLE
Fixes 3 bugs

### PR DESCRIPTION
**Pull request by cgirardot**
The tool was : 
- not passing the `min_mean_count` option from web form 
- not filtering on any `min_mean_count` (as it was always NULL) in the `create_seq_expression_set()` function
- not using the filtered data to create the `newSeqExpressionSet` in the `create_seq_expression_set()` function
- I also add trouble to actually deploy the tool at first and had to manually deploy a conda env. I reflected it by bumping up the packages versions and adding the needed getup for cmd line option parsing

I doubt the tool actually ever worked :-/

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by abretaud** [comment]
Hi @cgirardot and thanks for the PR!
Looks ilke the [tests are failing](https://travis-ci.org/galaxyproject/tools-iuc/jobs/509520367#L3292), do you know where this could come from? (the new version or the changes you've made?)

**Comment by cgirardot** [comment]
we are looking into this. First 2 issues are most likely because the test expects some precise value that should now be different. And the third one, we are not sure yet. Otherwise the code works on our installation.

**Comment by cgirardot** [comment]
The `get_deseq_dataset()` routine was : 
- 1. Using a command line variable instead of the one passed to the method
- 2. Blindly setting header=FALSE instead of using the passed argument

The sailfish test needs `min_mean_count=0` to run

**Comment by cgirardot** [comment]
@abretaud the last test still fails despite the additional fixes. The plugin executes correctly (did it interactively in my planemo). The problem is that we do not understand the error. Could you have a look please ?

**Comment by cgirardot** [comment]
@abretaud ok finally found "by trying" what the problem was. The tests' tests were also incorrect. How this could previously pass the tests is a mystery to me !

**Comment by abretaud** [comment]
Cool, thanks @cgirardot!

**Pull request merged**
