### PR TITLE
Update hisat to version 2.0.2

### PR DESCRIPTION
**Pull request by bgruening**
Labelled as WIP, because we need to add a traditional tool dependency.

### CODE REVIEW

**Comment by bgruening** [comment]
Awesome @yhoogstrate. I had forgotten about this one.
If you like https://github.com/galaxyproject/tools-iuc/pull/708 we can merge it before this one here and have our first test :)

**Comment by bgruening** [comment]
Oh wait is was labelled WIP because we need a new tool_dependency.xml as well. Arg.

**Comment by yhoogstrate** [comment]
Is the long term plan to keep supporting both conda and tool shed, or at some point only conda?

**Comment by bgruening** [comment]
We as IUC need to decide this. Galaxy needs to support tool_dependencies for old tools, but this does not mean that we as IUC can decide we only support conda and docker from timepoint X onwards.

**Comment by bgruening** [comment]
@yhoogstrate what do you think, ready to go? I have not tested the tool_dependency.xml yet ...

**Comment by yhoogstrate** [comment]
LGTM :+1:

**Comment by bgruening** [comment]
Thanks for the merge! If everything works as expected it should be on the TTS automatically.

**Pull request merged**
