### PR TITLE
Bakta 1.8.1 not available after first merging

### PR DESCRIPTION
**Pull request by pimarin**
After merging the [PR5354](#5354), the bot locked the deployment and bakta 1.8.1 is not available on toolshed.
I re-test using planemo and all test seem to pass but on github the test_6 seem to failed

### CODE REVIEW

**Comment by pimarin** [comment]
@bernt-matthias seem to pass as previously when you validated it.

**Comment by bernt-matthias** [comment]
I see no changed files here...

**Comment by bernt-matthias** [comment]
Can you create a branch from an up to date master branch where you bump the version token, ie the `+galaxyX` part. Then we can have a new look on the tests.

**Comment by pimarin** [comment]
I make a new branch `bakta_1.8.1` and a new [PR5408](https://github.com/galaxyproject/tools-iuc/pull/5408)

**Comment by bgruening** [comment]
Should this one be closed?

**Comment by bernt-matthias** [comment]
Ping @pimarin  https://github.com/galaxyproject/tools-iuc/pull/5460

**Comment by pimarin** [comment]
Oh ! a new version I made a new PR with 1.8.2

**Pull request closed without merging**
