### PR TITLE
Updating tools/dexseq from version 1.28.1 to 1.48.0

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/dexseq**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/dexseq from version 1.28.1 to 1.40.0.

**Project home page:** https://www.bioconductor.org/packages/release/bioc/html/DEXSeq.html

### CODE REVIEW

**Comment by simonbray** [comment]
No release notes: https://www.bioconductor.org/packages/release/bioc/news/DEXSeq/NEWS

Tests are failing with `dexseq_count.py: command not found` - is that a recurring issue? https://github.com/bioconda/bioconda-recipes/pull/13806

**Comment by TomHarrop** [comment]
The bioconda recipe might be broken - some dependencies were removed in commit [25494d8ab5b1380a3e69445a1bb7e1d251cb3d2f](https://github.com/bioconda/bioconda-recipes/commit/25494d8ab5b1380a3e69445a1bb7e1d251cb3d2f)

(e.g. `git diff 25494d8ab5b1380a3e69445a1bb7e1d251cb3d2f recipes/bioconductor-dexseq/meta.yaml`)

**Comment by TomHarrop** [comment]
Super quick attempted fix: https://github.com/bioconda/bioconda-recipes/pull/46916

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/tools-iuc/pull/5926

**Pull request closed without merging**
