### PR TITLE
yahs: bioconda version bump, add `--no-mem-check`

### PR DESCRIPTION
**Pull request by abueg**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by abueg** [comment]
test 3 & test 4 are failing with segfault -- tried it on CLI after compiling tag 1.2a-2 and that also segfaulted even without the `--no-mem-check` flag, hmm... 

```
 [I::main] dump hic links (BAM) to binary file yahs_out.bin
/tmp/tmp_7k1lcpp/job_working_directory/000/11/tool_script.sh: line 22:    11 Segmentation fault      (core dumped) yahs input.fasta input.bam -e 'GATC,GANT' -l 20 --no-mem-check -o yahs_out
```

**Comment by bgruening** [comment]
Puh, again a segmentation fault ...

> /tmp/tmp_7k1lcpp/job_working_directory/000/11/tool_script.sh: line 22:    11 Segmentation fault      (core dumped) yahs input.fasta input.bam -e 'GATC,GANT' -l 20 --no-mem-check -o yahs_out

**Comment by abueg** [comment]
i subsetted some of the LYZE test data used in the new yahs test script on the yahs repo; i'm using this subsetted data now for test 3 & 4 (the ones that were failing previously), test 3 checks the log to make sure yahs is reading the test input correctly, and test 4 checks against expected output that i've updated. i also added --no-mem-check hardcoded for yahs (not for agp_to_fasta because it doesn't take that parameter)
🤞🏼

**Comment by abueg** [comment]
ah the BED made it go over 😭 gimme a bit I'll try to subset that....

**Comment by abueg** [comment]
seventeenth time is the charm?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks a lot!

**Pull request merged**
