### PR TITLE
Goseq update v1.44->1.50

### PR DESCRIPTION
**Pull request by tuncK**
Everything else are re-arrangements due to linting requirements.

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Hey @gallardoalba I really don't like https://github.com/galaxyproject/tools-iuc/pull/5036/commits/45e648ce2dd2ccd51e744952dbd9b1544bd544bc .. :(

 Makes no sense without increasing the timeout in the weekly CI test .. which I would like to avoid. 

Any chance to revert this?

**Comment by tuncK** [comment]
Hey @bernt-matthias

Do you happen to have a way to monitor the instance behind Github tests? After a version upgrade, the test1 of this tool times out on Github and we dont know whats really happening as it works fine on our own PCs. Maybe RAM is out and switches swap disc etc? Is there a way to somehow know at what step it gets stuck before timing out?

**Comment by bernt-matthias** [comment]
You could use [tmate](https://tmate.io/) to ssh into the machine running the action.

For this you would need to add a step in the beginning of the test job of the PR workflow. You can do this in a fork.

**Comment by bernt-matthias** [comment]
My best guess for the timeout is that the construction of the container takes very long. The container is only constructed once for the first test. Locally this happens only once in the first run of `planemo test`, for github actions this happens every time, since we have a new machine every time. 

You may try to reproduce by purging all docker images from your system, e.g. by `docker system prune --all --force --volumes`. I guess the first test will need more than 900s then. 

For the CI this should not be a problem because the multi package container (mulled-v2-a363682a95427ff51dddd9ac3110099eb1069b4d:14721b9daa3e3a72e3b400a32eef6dfa2e4a2313 in this case) should be added at some point via https://github.com/BioContainers/multi-package-containers .. @bgruening seems not yet to be the case, does this just need time or might there be a problem .. could someone remind me how new combinations from IUC are added automatically. 

@tuncK would be cool if you could verify that I'm right. Then I would revert the timeout.

**Comment by tuncK** [comment]
The container generation was also my guess, but then I was told the stopwatch starts ticking after the env is ready. We ran into a similar timeout issue on another update a month or so ago. Will get back to you about this, I am trying out a few things.

**Comment by bernt-matthias** [comment]
Interestingly there is also a stacktrace in the raw logs which might indicate another problem:

```
galaxy.tool_util.deps.mulled.mulled_build WARNING 2023-01-09 15:50:04,985 [pN:main.1,p:2465,tN:LocalRunner.work_thread-1] Could not load metadata.yaml for 'r-ggplot2', version '3.4.0'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1674, in bz2open
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/bz2.py", line 178, in read
    return self._buffer.read(size)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmpiakfy04e/galaxy-dev/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 161, in base_image_for_targets
    tarball = get_file_from_recipe_url(hit["url"])
  File "/tmp/tmpiakfy04e/galaxy-dev/lib/galaxy/tool_util/deps/mulled/util.py", line 355, in get_file_from_recipe_url
    return tarfile.open(mode="r:bz2", fileobj=BytesIO(r.content))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1593, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1678, in bz2open
    raise ReadError("not a bzip2 file")
tarfile.ReadError: not a bzip2 file
galaxy.tool_util.deps.mulled.mulled_build WARNING 2023-01-09 15:50:05,552 [pN:main.1,p:2465,tN:LocalRunner.work_thread-1] Could not load metadata.yaml for 'openssl', version '1.1.1s'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1674, in bz2open
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/bz2.py", line 178, in read
    return self._buffer.read(size)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/_compression.py", line 103, in read
    data = self._decompressor.decompress(rawblock, size)
OSError: Invalid data stream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmpiakfy04e/galaxy-dev/lib/galaxy/tool_util/deps/mulled/mulled_build.py", line 161, in base_image_for_targets
    tarball = get_file_from_recipe_url(hit["url"])
  File "/tmp/tmpiakfy04e/galaxy-dev/lib/galaxy/tool_util/deps/mulled/util.py", line 355, in get_file_from_recipe_url
    return tarfile.open(mode="r:bz2", fileobj=BytesIO(r.content))
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1593, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/tarfile.py", line 1678, in bz2open
    raise ReadError("not a bzip2 file")
tarfile.ReadError: not a bzip2 file
```

**Comment by tuncK** [comment]
I still dont know what counts towards the 15min cutoff what does not, but only the test at the first index fails. Here I can reproduce this problem by duplicating the failing test (i.e. now test1 = test2) and I restored the timeout to 15 min. Only test1 times out, test2 succeeds test2 does not. So nothing is particularly wrong with any particular test, something else is troubling their execution: https://github.com/tuncK/tools-iuc/actions/runs/3884119821

What does the above error excerpt you sent mean? That the mulled container could not be pulled successfully? Simply because it does not exist or a more real error?

**Comment by gallardoalba** [comment]
> Hey @gallardoalba I really don't like [45e648c](https://github.com/galaxyproject/tools-iuc/commit/45e648ce2dd2ccd51e744952dbd9b1544bd544bc) .. :(
> 
> Makes no sense without increasing the timeout in the weekly CI test .. which I would like to avoid.
> 
> Any chance to revert this?

Hi, yes sorry, I think I should wait for other additional review. Should I revert the timeout?

**Comment by bernt-matthias** [comment]
> Should I revert the timeout?

@gallardoalba would be great. 

> I think 15min is really too low.

Its 15min per test... and we have to make sure that the CI workflow can test all tools within the time constraints given by the github runner. 

But the answer may also depend if the time to build the container is counted or not.

**Comment by gallardoalba** [comment]
> > Should I revert the timeout?
> 
> @gallardoalba would be great.
> 
> > I think 15min is really too low.
> 
> Its 15min per test... and we have to make sure that the CI workflow can test all tools within the time constraints given by the github runner.
> 
> But the answer may also depend if the time to build the container is counted or not.

Here is the PR https://github.com/galaxyproject/tools-iuc/pull/5051

**Pull request merged**
