### PR TITLE
Add fasta regex finder

### PR DESCRIPTION
**Pull request by bernt-matthias**
Tool was requested.. moved from https://github.com/bernt-matthias/mb-galaxy-tools/tree/master/tools/fasta_regex_finder 

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
Can you push the script through black maybe?

**Comment by bernt-matthias** [comment]
Do you know if we need to deposit the MIT licence here? The original repo seems to be MIT.

Also wondering if we want to start this as a suite .. there seem to be quite some scripts that might be of inetrest in the future.

**Comment by bgruening** [comment]
A suite never hurts :)

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks a lot, did you add IUC as admin to both TSs?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
It could be that TTS is failing because there is no repo and IUC can not create an mbernt repo. Lets see.

**Comment by bernt-matthias** [comment]
Cool. I really like this new bit of the PR workflow.

**Comment by bernt-matthias** [comment]
@bgruening write access for `iuc` is not sufficient? How make `iuc` the owner?

**Comment by bgruening** [comment]
I haven't looked at it, but its failing for the TTS, correct? You need to create a repo with owner mbernt and then give IUC admin permission. Write permission are not sufficient.

grafik

**Comment by bernt-matthias** [comment]
OK. I was wrong .. seems that write is sufficient. The tool has been deployed: [fasta_regex_finder](https://toolshed.g2.bx.psu.edu/repository/browse_repositories?f-free-text-search=regex&sort=name&operation=view_or_manage_repository&id=e7eb9226011a1ef3)

Its the suite that failed because of the `-` in the name.

**Comment by bernt-matthias** [comment]
https://github.com/galaxyproject/tools-iuc/pull/5096

**Comment by bernt-matthias** [comment]
TTS worked :)

TS failed for the suite .. apparently over the dash

**Comment by nsoranzo** [comment]
Failure to deploy on the TTS are simply ignored.

**Comment by bernt-matthias** [comment]
Thanks @nsoranzo .. Just checked the output for the TTS .. no idea what this means (the errors and success messages seem to make no sense at all):

```
 Repository fasta_regex_finder updated successfully.
Unexpected HTTP status code: 400: {"err_msg": "You already own a repository named <b>fasta_regex_finder<\/b>, please choose a different name.", "err_code": 400008}
Repository [fasta_regex_finder] does not exist in the targeted Tool Shed.
Failed to update metadata for repository 'fasta_regex_finder' on the test Tool Shed.
```

**Comment by bernt-matthias** [comment]
`planemo` generated a TTS repo with owner `iuc` .. also odd.

**Comment by bernt-matthias** [comment]
Ahh. I used a different identity on the TTS in the past ..

**Pull request merged**
