### PR TITLE
QIIME: fix flake8

### PR DESCRIPTION
**Pull request by bebatut**
Hi,

I fixed flake8 linting for 2 python scripts.

Bérénice

### CODE REVIEW

**Comment by bgruening** [comment]
:) Sorry for being nitpicking.

**Comment by bebatut** [comment]
No it is good for me :)

**Comment by nsoranzo** [comment]
I think it would be better to use functions from the [shutil](https://docs.python.org/2/library/shutil.html#directory-and-files-operations) Python standard library module instead of `cp`.

**Comment by bgruening** [comment]
This and subprocess when needed are on the todo list.

**Pull request merged**
