### PR TITLE
Updating tools/interproscan from version 5.52-86.0 to
5.54_87.0

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/interproscan**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/interproscan from version 5.52-86.0 to 5.52_86.0.

**Project home page:** http://www.ebi.ac.uk/Tools/pfa/iprscan5

### CODE REVIEW

**Comment by abretaud** [comment]
I'll have a look at the failing tests in the coming days

**Review by bgruening — APPROVED** [review]
Thanks

**Comment by abretaud** [comment]
Strange, the TS says the tool is invalid now, with this error:
`interproscan.xml - This file refers to a file named interproscan.loc. Upload a file named interproscan.loc.sample to the repository to correct this error.`
But the file is there, in tool-data, and was not touched by this PR...
Any clue?

**Comment by nsoranzo** [comment]
@abretaud I've reset the repository metadata and it seems fine now, let us know if that's not the case. Thanks for the heads up!

**Comment by abretaud** [comment]
Thanks @nsoranzo!
The error is gone indeed, but now my usegalaxy is confused with the revisions: 
image
Ephemeris did not catch the new revision either
Odd!

**Pull request merged**
