### PR TITLE
Add mash package

### PR DESCRIPTION
**Pull request by bgruening**
This PR adds the mash package as part of the [2nd IUC hackathon](
https://github.com/galaxyproject/tools-iuc/issues/299).

Mash: https://github.com/marbl/Mash

### CODE REVIEW

**Comment by blankenberg** [comment]
The download URLs and everything else says 1.0.2, but when run, it says 1.0.1. This might just be an error on the mash dev's part though.
```
dan-1:bin dan$ ./mash 

Mash version 1.0.1

Type 'mash --license' for license and copyright information.

Usage:

  mash <command> [options] [arguments ...]

Commands:

  dist    Estimate the distance of query sequences to references.

  info    Display information about sketch files.

  paste   Create a single sketch file from multiple sketch files.

  sketch  Create sketches (reduced representations for fast operations).
```

**Comment by blankenberg** [comment]
xref https://github.com/marbl/Mash/pull/19

**Comment by bgruening** [comment]
Can we merge this nevertheless?

**Comment by blankenberg** [comment]
This got buried in my inbox, sorry for the delay @bgruening

**Comment by bgruening** [comment]
Thanks Dan!

**Pull request merged**
