### PR TITLE
Anndata Fix

### PR DESCRIPTION
**Pull request by mtekman**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Yet another fix to anndata. The previous fix worked with a wider range of anndata and scanpy datasets, but was still failing for some scanpy 1.4.1 datasets.

This fix enables it to work with older 1.4.1 datasets too (by upgrading some of the other libraries, oddly enough)

### CODE REVIEW

**Comment by mtekman** [comment]
This should fix @nomadscientist's issue, but I'm having issues with NUMBA, which I know is something that has been tackled before

ping @gmauro  ?

**Comment by gmauro** [comment]
Which issue? and which tool?

**Comment by mtekman** [comment]
I remember in a previous meeting you and B talked about a Numba issue related to ScanPy tools.

I'm seeing this issue in some of the AnnData tests, import.xml for example. 

Do you know of an easy fix here?

**Comment by pcm32** [comment]
Anything I can help with here @mtekman? This look like a version pinning problem to me. At least locally for me pining to 2.10 on h5py, which is probably what our scanpy-scripts bioconda module is using, seems to work.

**Comment by pcm32** [comment]
Can this be closed given #3485 ? Or does this include anything in addition?

**Comment by pcm32** [comment]
I think that this was superseded by #3483 , correct? Should we close this then @mtekman ?

**Comment by mtekman** [comment]
@pcm32 Yes :-)

**Pull request closed without merging**
