### PR TITLE
Fix r dependencies xml

### PR DESCRIPTION
**Pull request by mvdbeek**
This should address https://github.com/galaxyproject/tools-iuc/issues/325#issuecomment-147960356
@yhoogstrate @bgruening @davebx  can you check this PR?
Did I miss why the package requirements were within the install tag?
And why does it seem to work on the TTS but not the main toolshed?

### CODE REVIEW

**Comment by bgruening** [comment]
@mvdbeek as far as I remember @davebx moved the dependencies within the install tag to not depend on these packages if you are only installing binaries.
If you can use binaries you don't need the dependencies at all.

TTS vs. MTS no clue. Metadata? Can you regenerate metadata on the MTS?

**Comment by martenson** [comment]
I believe this is relevant and also a reason why TTS does it correctly: https://github.com/galaxyproject/galaxy/pull/637

**Comment by davebx** [comment]
@bgruening is right, that is why I put the dependencies there.

**Comment by mvdbeek** [comment]
@martenson @davebx 
That does make sense and is a nice solution, can we get this on the MTS as well?
Else it breaks installs on OSX for example.

**Comment by martenson** [comment]
@mvdbeek I will update MTS now.

**Comment by mvdbeek** [comment]
Alright, thanks all, and closing this then.

**Comment by martenson** [comment]
@mvdbeek care to join #galaxyproject on irc? :)

**Comment by mvdbeek** [comment]
@martenson 
Sure, will try to remember. Problem is the university blocks IRC traffice,
I'll have to keep the tab open.

**Pull request closed without merging**
