### PR TITLE
edgeR: update to v3.24.1 and handle single quotes if present in input annotation

### PR DESCRIPTION
**Pull request by mblue9**
- updates edgeR to v3.24.1 and limma dependency to v3.38.3
- plus a couple of minor changes for more robust handling of potential issues with inputs

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by nsoranzo** [comment]
It seems tests are failing.

**Comment by mblue9** [comment]
Thanks @nsoranzo, I just noticed that too. Is it a conda issue? 
The error I see is ` libgfortran.so.3: cannot open shared object file: No such file or directory`

**Comment by nsoranzo** [comment]
That seems indeed a conda issue.

**Comment by bgruening** [comment]
The error indicates that limma is linked to libgfortran? The bioconda package does not depend on gfortran, so we should fix this I think and probably for this older version as well.

**Comment by bgruening** [comment]
Uh awesome. I think this means our new R stack works :)

Merci @mblue9!

**Comment by mblue9** [comment]
That was quick! yep looks like it works 👍  😄 Thanks @bgruening!

**Pull request merged**
