### PR TITLE
Updating tools/spyboat from version 0.1.2 to 0.1.1

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/spyboat**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/spyboat from version 0.1.2 to 0.1.1.

**Project home page:** http://github.com/tensionhead/spyboat/releases

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by bernt-matthias** [comment]
@tensionhead.. Any idea why there could be a downgrade?

**Comment by bgruening** [comment]
Because the conda packages does not exist: https://anaconda.org/conda-forge/spyboat

Don't ask me how it could pass the tests ... I guess it pulled the older container?

**Comment by bgruening** [comment]
xref: https://github.com/conda-forge/spyboat-feedstock

**Comment by tensionhead** [comment]
So I bumbed the tool version (from 0.1.1 to 0.1.2) but the `spyboat` package itself got no new release. Could that be the issue here?

**Pull request closed without merging**
