### PR TITLE
Condafy krona

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Can you remove `taxonomy_krona_chart` from `.tt_blacklist`, so that it's properly tested?

**Comment by bgruening** [comment]
No clue, can we get a rebase @davebx?

**Comment by nsoranzo** [comment]
I think it's a Planemo bug.

**Comment by davebx** [comment]
@bgruening Done. Let's see if that changes anything.

**Comment by nsoranzo** [comment]
Nope, it was not tested. I actually expect this tool to fail at `planemo shed_lint` because the MIT license link usually fails to validate. I started debugging `planemo find_ci_repos`, but I had to leave.

**Comment by nsoranzo** [comment]
Fix for Planemo: https://github.com/galaxyproject/planemo/pull/665

**Comment by davebx** [comment]
Oh, silly of me, I need to wait for the new version of planemo to be on travis, don't I?

**Comment by nsoranzo** [comment]
@davebx Yes, need to wait for the updated `planemo` to be on PyPI, then restarting the tests on Travis should be enough.

**Comment by bgruening** [comment]
Thanks @nsoranzo for unpinning. Now planemo was able to test it!

**Comment by bgruening** [comment]
Thanks @davebx!

**Comment by bgruening** [comment]
@davebx @martenson: we can not update this repo: https://travis-ci.org/galaxyproject/tools-iuc/jobs/228504731

**Comment by nsoranzo** [comment]
@bgruening Actually this tool is under `crs4` owner. `iuc@galaxyproject.org` user was missing from the list of repository administrators, I've fixed that and uploaded to the TTS and MTS.

**Comment by bgruening** [comment]
Thanks @nsoranzo!

**Pull request merged**
