### PR TITLE
Add LUMPY

### PR DESCRIPTION
**Pull request by npinter**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [X] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Part of the ELIXIR BioHackathon-Europe 2020 - Project 7 "CNV detection software containerization and benchmark"

Part of the ELIXIR BioHackathon.

### CODE REVIEW

**Comment by wm75** [comment]
@npinter still not finished, but getting closer.
Remaining issue is that a user may want to set PE options per RG (and SR options per sample). I think we will have to add repeats to each of these two sections, where each repeat's settings would apply to a user-specified RG ID or Sample Name.
Plus the current section, which would apply to all other RG/samples not specifically configured, but found in any of the BAMs.

**Comment by wm75** [comment]
An illustration of what this should look like. Needs to be wired still.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @npinter and @wm75!

**Comment by hexylena** [comment]
@wm75 do y'all have a workflow using lumpy?

**Pull request merged**
