### PR TITLE
Crisprseek dependencies

### PR DESCRIPTION
**Pull request by nephantes**
I generated dependencies with Bjorn's get_galaxy_tool_dependencies.py code.

### CODE REVIEW

**Comment by bgruening** [comment]
I updated https://testtoolshed.g2.bx.psu.edu/view/iuc/package_r_crisprseek_1_11_0/
If anyone has a chance to test ....
@nephantes thanks for updating.

**Comment by nephantes** [comment]
Thanks for the update Bjorn. After I tested, realized that the versions are wrong somehow in the latest push. I will correct them and push again.
Thanks,
Alper

On Nov 15, 2015, at 5:16 PM, Björn Grüning <notifications@github.com<mailto:notifications@github.com>> wrote:


I updated https://testtoolshed.g2.bx.psu.edu/view/iuc/package_r_crisprseek_1_11_0/
If anyone has a chance to test ....
@nephantes<https://github.com/nephantes> thanks for updating.

**Comment by nephantes** [comment]
I fixed the versions and pushed. Could you please check if everything is fine or not. Thanks.
Alper

**Comment by bgruening** [comment]
Done! Sorry for taking to long.

**Comment by nephantes** [comment]
Thanks Bjorn,
I still get this error.
ERROR: dependencies ‘Biostrings’, ‘BSgenome’, ‘data.table’ are not available for package ‘CRISPRseek’

There is no any trace of installing Biostrings and BSgenome in the INSTALLATION.log file. What would be wrong?
data.table wasn’t in the list. I added that one. Biostrings and BSgenome were in the package list but they weren’t installed. I thought they might require data.table. So, I added that for a new trial but I am not sure, if that’s the case for it.
Let me know, after you updated testtoolshed I will try with data.table addition.
Thanks
Alper

On Nov 17, 2015, at 10:48 AM, Björn Grüning <notifications@github.com<mailto:notifications@github.com>> wrote:


Done! Sorry for taking to long.

**Comment by bgruening** [comment]
@nephantes I can spend more today evening.
Just as a hint, you can try to modify the local version `tool_dependencies.xml` and so you don't need us to update it.

**Comment by nephantes** [comment]
I am updating local tool_dependencies.xml but when I test, I need to re-install this package. Doesn’t it re-downloading the tool_dependencies.xml file from testtoolshed site every time I do uninstall and install for this package and overwrite to the local version? How can I reinstall local tool_dependecies.xml file without downloading from testtoolshed?
Thanks,
Alper

On Nov 17, 2015, at 11:48 AM, Björn Grüning <notifications@github.com<mailto:notifications@github.com>> wrote:


@nephantes<https://github.com/nephantes> I can spend more today evening.
Just as a hint, you can try to modify the local version tool_dependencies.xml and so you don't need us to update it.

**Comment by bgruening** [comment]
Do not reinstall the package, but go to 'Manage package dependencies' and reinstall only the dependency.

**Comment by yhoogstrate** [comment]
I'm getting the following error:

```
Error downloading from URL
http://cran.rstudio.com/src/contrib/ade4_1.7-2.tar.gz:
HTTP Error 404: Not Found
```

Can we use persistent mirrors for all cran.rstudio.org URLs? (If you can't find it at e.g. bioarchive.galaxyproject.org please use https://github.com/galaxyproject/cargo-port)

**Comment by blankenberg** [comment]
@nephantes have you had a chance to look at https://github.com/galaxyproject/tools-iuc/pull/390#issuecomment-164062813?

**Comment by yhoogstrate** [comment]
ping @nephantes

**Pull request closed without merging**
