### PR TITLE
fix test of strelka germline

### PR DESCRIPTION
**Pull request by bernt-matthias**
xref galaxyproject/galaxy#11313

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Seems that the content of `out_genome` is non-deterministic. Does one of the contributors know if this is expected? Ping @bgruening @stephanflemming @wm75

**Comment by wm75** [comment]
Does using
```
<section name="expert_settings">
    <param name="s_e_e" value="--disableSequenceErrorEstimation" />
</section>
```

in that test help? That's the trick I used in other tests to get reproducible results, but apparently I forgot to add it to this one (cause it never triggered an error before you fixed the bug with collection testing).

**Comment by bernt-matthias** [comment]
@wm75 unfortunately this does not help. reason seems to be that the assertions work on the compressed output. https://github.com/galaxyproject/galaxy/issues/11521

**Comment by wm75** [comment]
Ah, of course! That's why here: https://github.com/galaxyproject/tools-iuc/pull/2534/commits/d1dec9494a64d73ff264b5a387a35fd3e996bf9b
I changed the first two tests to use *diff* and the `--disableSequenceErrorEstimation` option.
Maybe the later wouldn't even have been necessary - don't remember anymore.
Let me check whether comparing to any of the existing test datasets would work.

**Comment by bernt-matthias** [comment]
I disabled the assertion for now. I guess for the tool its sufficient to know that there are two elements in the collection. 

Feel free to extend the test or merge.

**Comment by wm75** [comment]
Was about to suggest the same. Seems totally fine for now.

**Review by wm75 — APPROVED** [review]

**Pull request merged**
