### PR TITLE
Requirements Fix

### PR DESCRIPTION
**Pull request by Kurt-Hanel**
Changes:
  - Remove version field from "perl-bioperl" requirement. For some
  reason it caused the environment to become unsolvable.
  - Add requirement for blast

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by Kurt-Hanel** [comment]
Tests fail because berokka db is not included in current bioconda recipe. Once they are [included](https://github.com/bioconda/bioconda-recipes/pull/14044), things should be good.

```
2418 |  ERROR: Missing database file '/home/travis/conda/envs/mulled-v1 c09de651a9cc79b77d7f3065f6c98189ec09a7e9242cbfa21d920192ebe61de6/db/dnaA.fna'
```

**Comment by bernt-matthias** [comment]
In my opinion `perl-bioperl` and `blast` should be removed from the tool requirements. Both requirements should be handled in the bioconda recipe.

**Comment by Kurt-Hanel** [comment]
@bernt-matthias Ah yes, that makes sense to me.

**Comment by bgruening** [comment]
@Kurt-Hanel merci! Also for the round-trip to bioconda, very much appreciated!

**Comment by Kurt-Hanel** [comment]
No problem, learned a lot along the way!

**Pull request merged**
