### PR TITLE
tool_factory_2 ownership

### PR DESCRIPTION
**Pull request by erasche**
Hi @fubar2, currently tool_factory_2 is owned by the IUC in the TTS, and you in the MTS, without cross-permissions. Can you please grant IUC permissions on your tool_factory_2 repository in the MTS? 

This PR is made for notification/converation purposes. Additionally the `owner` was changed to `IUC` as currently we're only automating the push to the TTS; it's more important for that to be correct w/r/t TTS.

### CODE REVIEW

**Comment by erasche** [comment]
Fixes #88

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/104/
Test (probably) passed

**Comment by fubar2** [comment]
Hi Eric - I just checked - it looks like the permissions are set - I thought I'd already done that but it seems ok now? Thanks!

Grant authority to make changes
fubar	owner	 
iuc	write	remove
devteam	write	remove

**Comment by erasche** [comment]
Great, thanks!
7. apr. 2015 7.59 p.m. skrev "Ross" <notifications@github.com>:

**Pull request closed without merging**
