### PR TITLE
Various fixes to the vsearch dereplication tool

### PR DESCRIPTION
**Pull request by pjbriggs**
This PR attempts to address a number of issues with the dereplication tool in the vsearch tool suite, and adds two new test cases.

Specifically the issues are:

1. The existing test case was broken: the test specified --sizeout but the reference output wasn't generated using this option. Fixed by removing --sizeout from the test case.

2. Tool fails if no value is supplied for the number of top sequences to output (--topn).
Added a test case for this, and fixed by omitting --topn option if no value was supplied.

3. There is an ambiguity when UCLUST-like output is requested (--uc), as both the 'uclust_like_output' macro and the tool define params called 'uc'. Added a test case for this and fixed by renaming the second 'uc' parameter to 'uc_outfile'.

4. The generation of the --sizein and --sizeout options in the <command> section was incorrect (it resulted in e.g. '--sizein --sizein' rather than '--sizein'), although vsearch still appears to operate correctly. However this has been fixed.

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by bgruening** [comment]
Hi Peter;
can you please increase the tool version?
Also can you please double check your test outputs. The newly created files are identical with https://github.com/galaxyproject/tools-iuc/blob/master/tools/vsearch/test-data/dereplication_result1.fasta isn't?

I suspect this all happens because of a recent regression where you can not use booleans like we did here, but you need to write something like this:

`<param name="sizeout" value="True"/>`

**Comment by nsoranzo** [comment]
ok to test

**Comment by pjbriggs** [comment]
Hello Bjoern

Re the tool version, I can do this - do you have a preferred format? (e.g. I would use 1.1.3-1 as the vsearch version is 1.1.3, and the tool version is the bit after the hyphen.)

Re the outputs, I don't quite understand your comments - doing md5sum gives me:

    $ md5sum test-data/dereplication_result*.fasta | sort
    4a2e74809f8c9a14e0f06950cc578a3a  test-data/dereplication_result2.fasta
    4a2e74809f8c9a14e0f06950cc578a3a  test-data/dereplication_result3.fasta
    85a49071e9b5dd00abec31d994ebebde  test-data/dereplication_result1.fasta

i.e. my two new files are identical to each other but different from the first, which on reflection is what I should have expected. So I could remove one of them and use the other for both the new tests.

However I do expect a difference compared with the first (existing) reference file:

    $ diff test-data/dereplication_result1.fasta test-data/dereplication_result2.fasta 
    1c1
    < >97485665bcded44c4d86c131ca714848
    ---
    > >97485665bcded44c4d86c131ca714848;size=4;

Here `size=4` comes from the use of `--sizeout` for generating the second file. So it looks to me as if the existing reference file was generated *without* using `--sizeout`, and this was breaking the first test case.

My "fix" to this test case was to remove the setting of `--sizeout` in the initial test, however it is correctly applied in the new test cases. A (better?) alternative would be to reinstate `--sizeout` in the test case and update the reference ouptut fasta file to be the same for all three tests.

Hopefully this makes sense - please let me know what you think.

**Comment by bgruening** [comment]
> Re the tool version, I can do this - do you have a preferred format? (e.g. I would use 1.1.3-1 as the vsearch version is 1.1.3, and the tool version is the bit after the hyphen.)

I guess we have added a `.1` for your small fixes.

> My "fix" to this test case was to remove the setting of `--sizeout` in the initial test, however it is correctly applied in the new test cases. A (better?) alternative would be to reinstate `--sizeout` in the test case and update the reference ouptut fasta file to be the same for all three tests.

> Hopefully this makes sense - please let me know what you think.

Oh yes it does. Thanks. If you increase the version I'm ready to merge this :)

**Comment by pjbriggs** [comment]
Thanks Bjoern - I've now bumped the version to 1.1.3.1 and removed one of the duplicated reference files for the new tests.

**Comment by pjbriggs** [comment]
Looks like I changed the package requirement version number and not the tool version - now fixed in 3a1759f. Apologies for the traffic.

**Comment by pjbriggs** [comment]
Ack - now I **finally** understand how the versioning works for these tools ("major" version defined in macros file, & individual tools append a point version). Commit 07ce1b2 should sort this out properly.

**Comment by bgruening** [comment]
@pjbriggs thanks a lot!

**Pull request merged**
