### PR TITLE
Enhance functionality of the varscan somatic tool

### PR DESCRIPTION
**Pull request by wm75**
Turns varscan_somatic into a higher-level wrapper for running
the

- samtools mpileup
- varscan somatic and
- varscan fpfilter

command line tools combined to provide a much enhanced
user experience.

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

FOR REVIEWER:
* [ ] .shed.yml file ok
    - [ ] Toolshed user `iuc` has access to associated toolshed repo(s)
* [ ] Indentation is correct (4 spaces)
* [ ] Tool version/build ok
* [ ] `<command/>`
  - [ ] Text parameters, input and output files `'single quoted'`
  - [ ] Use of `<![CDATA[ ... ]]>` tags
  - [ ] Parameters of type `text` or having `optional="true"` attribute are checked with `if str($param)` before being used
* [ ] Data parameters have a `format` attribute containing datatypes recognised by Galaxy
* [ ] Tests
  - [ ] Parameters are reasonably covered
  - [ ] Test files are appropriate
* [ ] Help
  - [ ] Valid restructuredText and uses `<![CDATA[ ... ]]>` tags
* [ ] Complies with other best practice in [Best Practices Doc](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

### CODE REVIEW

**Comment by bgruening** [comment]
@wm75 you need to pep8 your python file :)

**Comment by wm75** [comment]
huh, strict rules here :) I'll revise it asap

**Comment by wm75** [comment]
Ok, so the delay was a good thing because it allowed me to include quite a number of fixes for issues found in an initial round of testing by prospective users :sweat_smile:

**Comment by wm75** [comment]
Could it be, however, that this gets linted using python2? The script used by this tool is Python3 only and the xml wrapper says so in the requirements, but how do I tell Travis?

**Comment by wm75** [comment]
Surprisingly few changes! Thanks, @nsoranzo, for looking over it. Looks good to me.

**Pull request merged**
