### PR TITLE
seqtk conda dependency addition

### PR DESCRIPTION
**Pull request by nturaga**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Is it ok having different (minor) release versions as dependencies for TS and conda resolution?

**Comment by nitesh1989** [comment]
@bgruening @jmchilton You might be able to answer better.

**Comment by bgruening** [comment]
I would say it's not ok. We should try hard to have the some version no matter what dependency resolver we will use.
@nitesh1989 is currently trying to build an older version of seqtk for bioconda.

**Comment by jmchilton** [comment]
Yeah - I'd avoid duplicating requirements when there exists the possibility to do so.

**Comment by erasche** [comment]
@nturaga did you eve rmake progress on that seqtk version?

**Pull request merged**
