### PR TITLE
Testing latest Planemo update.

### PR DESCRIPTION
**Pull request by jmchilton**

### CODE REVIEW

**Comment by jmchilton** [comment]
Ping @bgruening - is this pilon problem a tool problem - do these test results say anything about whether https://github.com/galaxyproject/galaxy/pull/3391 and the latest planemo update is working or not?

**Comment by bgruening** [comment]
John, this does not look like a Planemo error. @nekrut what is Pilon? Is it needed or not?

**Comment by bgruening** [comment]
@jmchilton looks better now. But we have a 'Unicode Character 'LEFTWARDS ARROW' (U+2190)' somewhere and this crashes Galaxy/Planemo.
One test is passing.

**Comment by bgruening** [comment]
@nekrut can you look at this error please: https://travis-ci.org/galaxyproject/tools-iuc/jobs/196144935#L3085

**Comment by bgruening** [comment]
@nekrut with the new version the generated command seems to be wrong: https://travis-ci.org/galaxyproject/tools-iuc/jobs/197856590#L3140

This tool is changing so frequently ... can you please use this conda package for local testing and make it just working with this particular version.

**Comment by bgruening** [comment]
@nekrut what is this status of this? Would be nice to get it in!

**Comment by mvdbeek** [comment]
That's in for quite some time now, I think

**Pull request closed without merging**
