### PR TITLE
Sratools 2.8.11 -->3.0.0 + changes to IO

### PR DESCRIPTION
**Pull request by tuncK**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [x] - This PR does something else (explain below)

In addition to the usual version update, I want to be able to use the output of this tool for some quick checks, so I propose reorganizing the wrapper to make it possible to provide multiple SRRs at once.

*If I were to shorten the headers returned by fasterq-dump from:*
@SRR922139.1 1 length=202
AGTCGCCGTCCTGCAGCGCGGGGGCGGGCGCGGGAAAAAAGCCGCGCGGGGCGGGCCGCGGGGAAGAGGGCCAACCGCTCGTGGGCGCATGGGCGGCGTGCCCGCCCCTCCCCCAGCGCCCCGCGGGCGCGTTTCCCCGGGGCGGCCGCCGCGCGGCATTTTTGCCGCGTCCGCCACTGCGGGGCAGGAAGGTGTCTTGATT
+SRR922139.1 1 length=202
#####################################################################################################1+:=;ADDH+<@#########################################################################################

*to:*
@1/2
AGTCGCCGTCCTGCAGCGCGGGGGCGGGCGCGGGAAAAAAGCCGCGCGGGGCGGGCCGCGGGGAAGAGGGCCAACCGCTCGTGGGCGCATGGGCGGCGTGCCCGCCCCTCCCCCAGCGCCCCGCGGGCGCGTTTCCCCGGGGCGGCCGCCGCGCGGCATTTTTGCCGCGTCCGCCACTGCGGGGCAGGAAGGTGTCTTGATT
+
#####################################################################################################1+:=;ADDH+<@#########################################################################################

*we seem to save some storage. Would this break any downstream tool (current fastq-dump wrapper already does it)?*
-rw-rw-r--  1 ubuntu ubuntu 1208922140 Jan 18 14:43 SRR922139_lh.fastq
-rw-rw-r--  1 ubuntu ubuntu  331032960 Jan 18 14:44 SRR922139_lh.fastq.gz
-rw-rw-r--  1 ubuntu ubuntu 1053661898 Jan 18 14:57 SRR922139_sh.fastq
-rw-rw-r--  1 ubuntu ubuntu  308844166 Jan 18 14:51 SRR922139_sh.fastq.gz

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
Looks good to me. @mvdbeek any comments from your side?

@nekrut are you using this tool? The single outputs are gone, it's now always a collection.

**Review by mvdbeek — APPROVED** [review]

**Comment by mvdbeek** [comment]
> _If I were to shorten the headers returned by fasterq-dump from:_

Those headers are pretty useless, so that would be ok. I guess there's still no option to get the headers from the files as they were submitted ? Those do contain sequencer and flowcell information for illumina data, which can be useful.

**Comment by tuncK** [comment]
In the current way (the NCBI developers' default), it is reporting SRR#s # read ID, but not the original headers. Let me see if I can bring those original ones in, else I will truncate the headers to preserve storage space.

Then please DO NOT MERGE yet, I will get back to you.

**Comment by mvdbeek** [comment]
Sure. You can also turn a PR back into draft to signal this:

Screenshot 2023-01-19 at 13 05 34

**Comment by tuncK** [comment]
Deja vu: This time no timeout, rather an executable from the container contents not usable for 1st test only (sam-dump not found).

**Comment by bgruening** [comment]
Green!

**Review by bgruening — APPROVED** [review]

**Pull request merged**
