### PR TITLE
Deseq2 update

### PR DESCRIPTION
**Pull request by bgruening**
New release of DESeq2 requested by @mikelove in https://github.com/galaxyproject/tools-iuc/pull/20

### CODE REVIEW

**Comment by yhoogstrate** [comment]
Great to see that @mikelove is actively involved in updating his tool in galaxy!

@bgruening, could you replace ```/master/``` for ```/1cff0e7f7793cbfc26dcf7fa1b62bdb08047396b/```? This should ensure that the files should never change.

```rjson_0.2.14.tar.gz``` doesn't have a revision in it's url and it also comes from a non secure connection, could you at the MD5 or sha256 sum:

md5sum: ```1fd5245205b8f3d649fc84b898cb9a2b```
sha256sum ```93d417f4eddb6fb7d679fbabb934b155de3965cf3d3e5ab03af69af5a0123357```

**Comment by bgruening** [comment]
> @bgruening, could you replace ```/master/``` for ```/1cff0e7f7793cbfc26dcf7fa1b62bdb08047396b/```? This should ensure that the files should never change.

I don't think this is needed. I will not touch these tarballs :)
I uploaded rjson to github as well and added the checksum. At some point we should add these checksums automatically.

**Comment by bgruening** [comment]
@yhoogstrate is this ready to go?

**Comment by yhoogstrate** [comment]
I don't know how to test a package installer when it's not available in a (test)toolshed. How should I do this?

**Comment by bgruening** [comment]
`package_deseq2_1_8_2` is now in the TTS.

**Comment by mvdbeek** [comment]
I'm about to test this as well. Note that the tool (not the package) is missing a .shed.yml!

**Comment by bgruening** [comment]
@mvdbeek upps, sorry I missed the `git add` step :) Thanks.

**Comment by yhoogstrate** [comment]
I am figuring out how to compile cairo (err: ```test.c:1618: more undefined references to `cairo_boilerplate_content_name' follow```). This wrapper seems to depend on 1.12.14 and the previous time I was testing it was 1.14.2. I'll keep you posted if there is any progress. It might be my machine again, so don't wait on me.

There is a small typo in the DESeq2 wrapper /intput/input/.

**Comment by mvdbeek** [comment]
@bgruening same as for youri, i'm also using gcc 4.9.2 and cairo breaks with the same error.
I can open a PR for an updated R and cairo, if you want.

**Comment by bgruening** [comment]
@mvdbeek please go ahead, much appreciated. I'm going to merge this now. We can merge the cairo deps afterwards into R.

**Comment by bgruening** [comment]
Thanks for reviewing!

**Pull request merged**
