### PR TITLE
Add HAPO-G: assembly polishing

### PR DESCRIPTION
**Pull request by abretaud**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Adding HAPO-G, a tool from Genoscope to polish genome assemblies.
Paper: https://academic.oup.com/nargab/article/3/2/lqab034/6262629?login=true
GitHub repo: https://github.com/institut-de-genomique/HAPO-G

The tests are probably failing for now due to https://github.com/institut-de-genomique/HAPO-G/issues/21

### CODE REVIEW

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
The ordering of attributes is wrong or not IUC like. Have you used the VSC extension, is there a bug that we need to fix?

**Comment by abretaud** [comment]
> The ordering of attributes is wrong or not IUC like. Have you used the VSC extension, is there a bug that we need to fix?

Using vscode with the extension, but it must be a copy/paste accident, just fixed it

**Comment by abretaud** [comment]
@bgruening do you want to review my last changes or do I go ahead and merge?

**Comment by bgruening** [comment]
Thanks @abretaud

**Pull request merged**
