### PR TITLE
Mothur version update

### LINKED ISSUE #1688: Mothur screen.seqs with a contigs report
Hello everyone,

One of my colleague that uses Mothur for her analysis recently show me that there are two issues with the current Screen.seqs wrapper when you execute it with an input contigs report file (generated by Make.contigs).

The first one is that the option displayed in the help of the contigsreport parameter (Ie. minoverlap, ostart, oend and mismatches) can't be set with the current Screen.seqs wrapper.

The second one is that, in these conditions, Mothur generates a modified contigsreport (as displayed in its log) that is not recovered by the wrapper.

It would be nice if these parameters could be made available (and the output file recovered) in the next iteration of the screen.seqs wrapper.

This is not a major issue so it can probably wait for the major update of the wrapper (migration to Mothur 1.39.5).

Thanks in advance for the enhancements :)

ping @shiltemann

### PR DESCRIPTION
**Pull request by shiltemann**
started at GCC with @Takadonet and @ValentinChCloud, this updates mothur to the latest version, 1.39.5, and does some general cleanup etc of wrappers

should also fix #1688, #1644, #1643, #1472 and incorporates changes from #1569 (thanks @arbernard!) 
I have not encountered #1625, #1572 locally,  let's see if travis agrees
I could not reproduce #1621, let me know if you're still running into this with new wrappers @bernt-matthias 

ping @arbernard @Takadonet @bernt-matthias @jennaj thanks for all the help and bugreports, maybe you would like to test/review this? :)

### CODE REVIEW

**Comment by Takadonet** [comment]
Will for sure take a look! Awesome work.

**Comment by shiltemann** [comment]
@bernt-matthias am pushing to the testtoolshed now, thanks!

**Comment by bernt-matthias** [comment]
@shiltemann I guess you have an answer to my latest question in https://github.com/galaxyproject/tools-iuc/pull/1721 on the integration of the UNITE DB in the mothur data manager...?

**Comment by bernt-matthias** [comment]
@shiltemann will you also update suite_mothur in the testtoolshed?

**Comment by shiltemann** [comment]
@bernt-matthias ah yeah, something went wrong the first time, but should be good to go now :)

**Comment by shiltemann** [comment]
@nsoranzo the last tool I added seems to have just pushed this over the max time limit for travis again, shall I make a 4th chunk?

**Comment by nsoranzo** [comment]
I guess there's no other choice!

**Comment by bgruening** [comment]
@shiltemann @bernt-matthias @abretaud @Takadonet ready to go?

**Comment by bernt-matthias** [comment]
I forgot about this one. Sorry. I will test this afternoon.

Some quick comments (see https://github.com/galaxyproject/tools-iuc/issues/1472): 
- I still think that the 3x log output (as data set, in the stdio/stderr, and in the data set preview) is very redundant. I my opinion the stdio/stderr in the data set information page plus an **optional** log data set  would be great.
- have you tried to add the -q switch to mothur (to remove unnecessary log output)
- are citations now automatically added (command(help))?

**Comment by shiltemann** [comment]
@bernt-matthias oh yeah, I have made the logfile an optional output now, which is off by default, remembering your comment (but maybe only after I pushed to the test toolshed), is that ok for you?

I will look into the citations thing, but it may be nicer to just add that the "Galaxy way" ..I will have a look at which tools are missing citations and add those

**Comment by bernt-matthias** [comment]
Currently redoing http://galaxyproject.github.io/training-material/topics/metagenomics/tutorials/general-tutorial/tutorial.html with the new tools.

One first comment: 

Unique.seqs set "output format" needs to be changed to "Name file" (expected as input for count.seqs)
- maybe the default changed / the tutorial was buggy
- alternatively: can the tool output both: Name file and count table at the same time

**Comment by jennaj** [comment]
@bernt-matthias This is a new issue for Unique.seqs afaik -- I haven't rerun the tutorial again at https://usegalaxy.org since late Dec. Open issues I am tracking to run the tutorial on that server are here and includes some issues that probably impact usage anywhere: https://github.com/galaxyproject/usegalaxy-playbook/issues/74

@shiltemann Thanks the updates!

**Comment by shiltemann** [comment]
@bernt-matthias ah yes, they changed the default here. Thanks a lot for testing the training materials, I will update the tutorial accordingly :)

**Comment by bernt-matthias** [comment]
Screen.seqs: The minlength default is 10. For all other parameters its -1. Does -1 (probably ignore) also work here?

Cluster.split  seems to have more options. is Opticlust the Clustering Method of choice

**Comment by shiltemann** [comment]
@bernt-matthias mothur uses a default minlength of 10, so I did same in wrapper. Same for Cluster.split, opti is indeed the new default in this version. 

We will need to update both the mothur tutorials to explicitly set any parameters that are no longer the default. I started this here: https://github.com/galaxyproject/training-material/pull/715

**Comment by bernt-matthias** [comment]
Otherwise everything seems fine.

**Comment by shiltemann** [comment]
@bernt-matthias thanks a lot! I suspect that is due to the new clustering method (if different clustering levels give same results, mothur only reports biggest) I changed the tutorial to set the method back to the previous default of `average neighbour`

**Comment by bernt-matthias** [comment]
@shiltemann you are right average neighbour gives the usual results

**Comment by bgruening** [comment]
Thanks all this is an amazing team work!

**Pull request merged**
