### PR TITLE
Fix Docutils errors in Mothur tools

### PR DESCRIPTION
**Pull request by arbernard**
Hi everyone,

I recently updated one of my Galaxy instance from Galaxy 17.05 (master) to Galaxy 17.09 (master) and, as I a consequence, I paid more attention to warnings and error messages that could appear at the instance startup.

I quickly noticed that several warnings were popping up in the log files and were triggering Docutils error messages visible on the parameter selection pages of several Mothur wrappers.

All those warnings are generated because some links are missing in the Help sections of a few Mothur wrappers.

The first part of this PR is therefore a commit that add all the missing links in the appropriate files.

Please note that in some cases I've been forced to use the URL of a search result on the official Mothur wiki instead of a direct link to the page of the corresponding tool.

The reason behind this behavior is that the maintainer of the official Mothur wiki has fully deleted the pages of tools that have been removed in the lastest versions of Mothur itself (instead of just marking them as deprecated).

The current IUC wrappers for Mothur were made for Mothur 1.36.1 and since this version the following tools have been removed from Mothur:

- get.otulabels removed since v1.37
- remove.otulabels removed since v1.37
- hcluster removed since v1.38
- clear.memory removed since v1.38
- pds.pipeline removed since v1.38

I've created an Issue on Mothur's Github to ask its creator if he can restore the deleted pages and just mark/tag them as deprecated/obsolete so that users can still access all the informations about the Mothur version they are currently running:

https://github.com/mothur/mothur/issues/401

Unfortunatly, the answer is not positive at the moment so we might expect some links to become dead after the release of the next Mothur versions.

In addition, when I was fixing the links in the Mimarks.attributes wrapper I also noticed that the wrapper name was incorrect so I fixed it in the second commit of this PR.

I've used planemo lint/serve/test locally to check that the wrappers were still Ok after the updates and Travis did not issued any error when it run on the branch of my fork of the galaxyproject/tools-iuc repo.

Have a nice day :)

ping @shiltemann

### CODE REVIEW

**Comment by bgruening** [comment]
@arbernard thanks for all your efforts and fixing these things. Its nice to know that tests pass at your side. We see some errors since a month in mothur testing. I have restarted on of your tests, lets see if this gets better now.

Thanks again!

**Comment by arbernard** [comment]
@bgruening The tests have failed again. I've looked into the Travis log and the majority of the failed tests have failed because Mothur can't find the Blast-legacy executables. The bioconda recipe for Mothur 1.36.1 and blast-legacy haven't changed for months though.

**Comment by arbernard** [comment]
For the test of the Mothur primer.design wrapper that is failing in the .4 part of the Travis build, it's an issue with a drop-down menu that is no longer populated in Galaxy 17.09 like it used to be in 17.05 (when the user select the same input files in both case). It seems that the `filter` rule of the **otulabel** param is no longer returning anything now.

**Comment by arbernard** [comment]
I gave a look at the history of commits of the [lib/galaxy/datatypes/mothur.py](https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/datatypes/mothur.py) lib and I think that the https://github.com/galaxyproject/galaxy/commit/43702ccacdbfe925d921dac413c02bb7f65b9c4f commit is responsible for this empty "otulabel" drop-down menu in the primer.design wrapper. I also suspect that it can cause the incorrect addition of the "label" entry in the other auto-filled drop-down menu (which is common to several wrappers because it's defined in the macros.xml file) at least when the metadata are collected from a mothur.list file (where the "title" line does not start with a special character).

**Comment by mvdbeek** [comment]
@arbernard Thanks for the detective work, indeed, even if you request a header with `count` 1 you'll get a list of lists, where the outer list items are lines ... duh. I'll open a PR in a second.

**Comment by arbernard** [comment]
You're welcome @mvdbeek :) and thanks for the https://github.com/galaxyproject/galaxy/pull/5072 PR (even if you have referenced the wrong detective in it lol)

I didn't found the precise reason of the failure of all the other tests though...

**Comment by mvdbeek** [comment]
There are still loads of `Deprecated interpeter attribute on command element is now ignored.`, those are probably worth fixing.

**Comment by arbernard** [comment]
> There are still loads of Deprecated interpeter attribute on command element is now ignored., those are probably worth fixing.

There are indeed a bunch of these warnings that are displayed in the test report. A few are emitted for wrappers directly provided with Galaxy and some for wrappers of the tools-iuc repo. However, it seems that Mothur wrappers does not contain any interpreter attribute.

**Comment by bgruening** [comment]
@shiltemann do you know why a few tools complain about

```
|  Generating search database...    [ERROR]: /tmp/tmpBfZKRL/job_working_directory/000/112/working/blast/bin/formatdb file does not exist. mothur requires formatdb.exe.
```
The directory looks especially wired.

**Comment by shiltemann** [comment]
hmm, yes, seen that before, mothur is very particular about where it expects certain executables in relation to others etc, will have a look why this isnt working anymore

**Comment by arbernard** [comment]
This PR can be closed since the modifications it was applying have been included in @shiltemann's PR for Mothur 1.39.5 (https://github.com/galaxyproject/tools-iuc/pull/1722)

**Pull request closed without merging**
