### PR TITLE
Fix broken package in ONTO-PERL

### PR DESCRIPTION
**Pull request by erasche**
For #6 @bgruening

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks for fixing. I'm a little bit disappointed by cran. I thought they will not remove old version. Now I need to backup the tarballs on my own.

**Comment by erasche** [comment]
Agreed, CPAN should be storing versions forever...

On that note, look, I'm already running gx.hx42.org, I'm happy to add a
CPAN mirror that never removes old packages, we can just mirror the galaxy
relevant stuff there. You know, as an IUC alternative to the galaxyproject
files depot. Thoughts?

2015-02-10 12:56 GMT-06:00 Björn Grüning <notifications@github.com>:

> Thanks for fixing. I'm a little bit disappointed by cran. I thought they
> will not remove old version. Now I need to backup the tarballs on my own.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/pull/40#issuecomment-73759681>
> .
>



-- 
Eric Rasche

**Comment by erasche** [comment]
Rather, also as an alternative to putting tarballs in a git repo like with
you do on your account.

2015-02-10 13:01 GMT-06:00 Eric Rasche <rasche.eric@gmail.com>:

> Agreed, CPAN should be storing versions forever...
>
> On that note, look, I'm already running gx.hx42.org, I'm happy to add a
> CPAN mirror that never removes old packages, we can just mirror the galaxy
> relevant stuff there. You know, as an IUC alternative to the galaxyproject
> files depot. Thoughts?
>
> 2015-02-10 12:56 GMT-06:00 Björn Grüning <notifications@github.com>:
>
>> Thanks for fixing. I'm a little bit disappointed by cran. I thought they
>> will not remove old version. Now I need to backup the tarballs on my own.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/galaxyproject/tools-iuc/pull/40#issuecomment-73759681>
>> .
>>
>
>
>
> --
> Eric Rasche
>



-- 
Eric Rasche

**Comment by bgruening** [comment]
@erasche this is a really great/gentle offer. But this needs to be discussed with your PI and with the scientific community in general. This is a general problem and we need a solution that will last longer than your PhD position :)

I was more thinking like an NCBI storage or the new google scientific drive with TB of free storage.

**Comment by erasche** [comment]
Hah, it's my own digitalocean VM that I'm going to use to (eventually) host
a toolshed with my wrappers for audio processing/scanning (nmap)/pdf
processing/etc.

Personal funds, not university, and I see myself continuing to run that VM
in one location or another (e.g. might migrate to a private server
eventually, but that hostname will always point to the same thing)

That said, I definitely agree, we need a permanent solution to this problem
(DOIs! :P)

2015-02-10 13:07 GMT-06:00 Björn Grüning <notifications@github.com>:

> @erasche <https://github.com/erasche> this is a really great/gentle
> offer. But this needs to be discussed with your PI and with the scientific
> community in general. This is a general problem and we need a solution that
> will last longer than your PhD position :)
>
> I was more thinking like an NCBI storage or the new google scientific
> drive with TB of free storage.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/galaxyproject/tools-iuc/pull/40#issuecomment-73761740>
> .
>



-- 
Eric Rasche

**Pull request merged**
