### PR TITLE
add phyloseq bar chart

### PR DESCRIPTION
**Pull request by MaraBesemer**
FOR CONTRIBUTOR:
* [x] I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] License permits unrestricted use (educational + commercial)
* [x] This PR adds a new tool or tool collection
* [ ] This PR updates an existing tool or tool collection
* [ ] This PR does something else (explain below)

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
LGTM! Can you plese fix the Rscript linting? Thanks

**Comment by MaraBesemer** [comment]
Which version of lintr is used in the test, bc on my local environment the tests pass?

**Comment by paulzierep** [comment]
Fix: https://github.com/MaraBesemer/tools-iuc/pull/1
Could you maybe add one or two more test, that check for empty parameter input and different parameters ?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
Thanks @MaraBesemer !

**Pull request merged**
