### PR TITLE
WIP: Add the fimo_gff_to_gff tool.

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by bgruening** [comment]
LGTM and tests are passing. I always wonder if it's worth to create such tools or simply fix the fimo tool to create correct gff files.

**Comment by gregvonkuster** [comment]
How should the 1-based input data requirement be handled?

**Comment by gregvonkuster** [comment]
I've marked this WIP for a bit - I believe we've come up with a better solution for this.  Be back shortly...

**Comment by gregvonkuster** [comment]
I'm closing this because I have a new version of the FIMO tool that I will be submitting that eliminates the need for this tool.  This new version is under review in my lab, and I will be away for a few days so I will submit it when I return.

**Pull request closed without merging**
