### PR TITLE
Fix python linting errors for table_compute

### PR DESCRIPTION
**Pull request by bernt-matthias**
- tests 20 and 21 were suddenly failing in CI 
  - failure is legit, but I don't know which galaxy change triggered it
- not sure what triggers the failing test 41 (it appears that the test is supposed to fail, but it is not recognized)

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by wm75** [comment]
Tests 20 and 21 are also *supposed* to fail since `[]:` are indeed not allowed in expressions.
So in fact all tests (and only those) of this tool that expect failure are behaving differently from before. My guess is that it's because of the combination `expect_num_outputs="1" expect_failure="true"`, which doesn't make much sense but probably hasn't always been checked for?

**Comment by bernt-matthias** [comment]
Thanks for pointing this out @wm75 .. overlooked this. 

Let me bisect this.

**Comment by mvdbeek** [comment]
Alright, it's green again! Thanks for the report and fix @bernt-matthias!

**Comment by bernt-matthias** [comment]
Cool. Then lets just merge the python linter fixes?

**Review by mvdbeek — APPROVED** [review]

**Pull request merged**
