### PR TITLE
Update heatmap2 tool

### PR DESCRIPTION
**Pull request by lldelisle**
FOR CONTRIBUTOR:
* [X] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Hi,
This PR contains multiple improvement of the current heatmap2 tool:
- I updated the version of the tool + dependency (should I add a `+galaxy0`?
- The z-score can be computed prior to clustering
- Multiple distance methods and clustering methods propsed. In addition I added the 'correlation' method similar to what is proposed in `pheatmap`.
- I proposed much more colormaps.
- The output can be either png or pdf

### CODE REVIEW

**Review by gallardoalba — APPROVED** [review]

**Comment by lldelisle** [comment]
Thanks

**Comment by lldelisle** [comment]
@bgruening would it be possible to put it in usegalaxy.eu before the automatic push on Saturday?

**Comment by bgruening** [comment]
Done.

**Comment by lldelisle** [comment]
Thank you so much

**Pull request merged**
