### PR TITLE
xz dependencies update

### PR DESCRIPTION
**Pull request by bgruening**
fixes: https://github.com/galaxyproject/tools-iuc/issues/363

### CODE REVIEW

**Comment by mvdbeek** [comment]
:+1:

**Comment by bgruening** [comment]
Thanks, updated the repositories.

**Comment by erasche** [comment]
@bgruening can you add to CPC as well please?

**Comment by bgruening** [comment]
@erasche I did that (hopefully) ... Oo https://github.com/erasche/community-package-cache/pull/18

**Comment by erasche** [comment]
Yep! saw that, thanks so much! :)

**Comment by yhoogstrate** [comment]
Do we have to shed_update each of the python packages that make use of xz as well?

**Comment by bgruening** [comment]
No.

**Pull request merged**
