### PR TITLE
hmmer3: update and nhmmer test fixes

### PR DESCRIPTION
**Pull request by bernt-matthias**
remaining problems seem due to the fact that nowadays v3.2.1 is used instead of 3.2. Could we fix this? Or better update test data?

since so far only tests changed I did not bump the tool version .. just kidding (I forgot it) .. 

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
I think the tests fail because now 3.2.1 is used instead of 3.2. 

`--update_test_data` ?

**Comment by bernt-matthias** [comment]
Also upgraded to 3.3. .. according to the changelog there seem to be no changes in the CLI.

aliscore output in nhmmer scan creates segfault (reported here https://github.com/EddyRivasLab/hmmer/issues/190). So I enabled it for testing in nhmmer search... still keeping the test file for scan for when it works again. 

Needed to update quite a bit of the test data since numeric values changed.

**Comment by bernt-matthias** [comment]
Also added some `expect_num_outputs` for tools with filters ... I was a bit lazy and just added tests instead of introducing macros for the outputs and testing filters just once... :(

**Comment by bgruening** [comment]
Still failing ... :(

**Pull request merged**
