### PR TITLE
vegan docker support

### PR DESCRIPTION
**Pull request by bgruening**
Anyone wants to test this?

### CODE REVIEW

**Comment by erasche** [comment]
```console
$ docker run "GALAXY_SLOTS=$GALAXY_SLOTS" -v /home/hxr/work/galaxy:/home/hxr/work/galaxy:ro -v /home/hxr/work/galaxy/tools/tools-iuc/tools/vegan/vegan_diversity:/home/hxr/work/galaxy/tools/tools-iuc/tools/vegan/vegan_diversity:ro -v /home/hxr/work/galaxy/database/jobs_directory/000/94:/home/hxr/work/galaxy/database/jobs_directory/000/94:rw -v /home/hxr/work/galaxy/database/files:/home/hxr/work/galaxy/database/files:rw -w /home/hxr/work/galaxy/database/jobs_directory/000/94 --net none --rm -u 1000 quay.io/mulled/r-vegan:2.3_4--r3.2.2_1 /home/hxr/work/galaxy/database/jobs_directory/000/94/tool_script.sh
no such file or directory
docker: Error response from daemon: Container command not found or does not exist..
```

this is because the tool script uses `/bin/bash`, and that isn't available in the container. We should probably make it available, or switch script to use `sh`.

Running the tool script under `sh` produces the following:

```console
/home/hxr/work/galaxy/database/jobs_directory/000/94 $ sh tool_script.sh 
tool_script.sh: line 9: can't create /home/hxr/work/galaxy/database/tmp/GALAXY_VERSION_STRING_94: Read-only file system
Loading required package: permute
Loading required package: lattice
This is vegan 2.3-4
/home/hxr/work/galaxy/database/jobs_directory/000/94 $ 
```

it looks like it would work though:

```console
/home/hxr/work/galaxy/database/jobs_directory/000/94 $ cat tmpfIidue 
options(bitmapType='cairo')
library(vegan)
input_abundance <- read.delim("/home/hxr/work/galaxy/database/files/000/dataset_120.dat", header=FALSE, sep="\t", row.names=6)
input_abundance <- t( input_abundance[ c( 2 )] )
write.table( diversity(input_abundance, index = "shannon", MARGIN = 1, base = exp(1)), "/home/hxr/work/galaxy/database/files/000/dataset_123.dat", quote=FALSE, col.names=NA, sep = "\t")
```

then

```console
/hxr/work/galaxy/database/jobs_directory/000/94 $ cat /home/hxr/work/galaxy/database/files/000/dataset_123.dat
        x
1       1.020620870138
```

**Comment by erasche** [comment]
Sorry for the two week delay @bgruening

**Comment by bgruening** [comment]
@erasche great! I have only tested it with an older version of Galaxy that did not require bash. Good to know. Would it make sense to have `sh` as default for Docker. One aim for these images was to make them really really small. Usually these images are only 10MB in size ...
ping @jmchilton

**Comment by bgruening** [comment]
@erasche thanks for testing!!!!

**Comment by jmchilton** [comment]
Since we are ignoring requirements, I guess it could make sense to fallback to sh if we are inside a Docker container - it does mean subtly different behavior inside and outside of the container :disappointed: - but I guess this is fine. sh respects ``set -e`` right?

**Comment by bgruening** [comment]
@jmchilton if you are concerned I try to change the containers. I don't think it matters. About the `set -e` I'm not sure - but I'm also not a fan of it. You are here the experts. Afaik `set -e` is not recommended, but who knows. 
See for example here: http://mywiki.wooledge.org/BashFAQ/105

**Comment by nsoranzo** [comment]
@jmchilton Yes, see http://pubs.opengroup.org/onlinepubs/009696799/utilities/set.html

**Comment by jmchilton** [comment]
@nsoranzo Thanks.
@bgruening It is the new default for 16.04+ tools, this should eliminate the need for the ``&&`` pattern right - which is a good thing.

**Comment by bgruening** [comment]
@jmchilton I know. I'm not an admin enough to make a qualified decision on this. All I know is what I read so far about `set -e` and this is not always good. For example see here: http://wiki.bash-hackers.org/scripting/obsolete

But I trust you and @nsoranzo  with this.

If `sh` works we only need to fix this one warning from above and can annotate our tools with conda and Docker! Wonderful times!

**Comment by bgruening** [comment]
With mulled we have a mechanism in place where we do not need to annotate all tools with containers, we will find them automatically so I will close this one.

**Pull request closed without merging**
