### PR TITLE
Hotifx for pooled tgreatement and control files

### PR DESCRIPTION
**Pull request by heylf**
FOR CONTRIBUTOR:
* [X ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [X] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [X] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Bug was fixed for Genrich wrapper.

### CODE REVIEW

**Comment by bgruening** [comment]
It would be nice to add a test case for this. We can probably give the tool the same file twice?

**Comment by heylf** [comment]
Ok I will create a test case. Lets see if that is possible with the same file.

**Comment by heylf** [comment]
@bgruening test alright. Hotfix finished.

**Comment by bgruening** [comment]
Merci!

**Pull request merged**
