### PR TITLE
Seqcomplexity

### PR DESCRIPTION
**Pull request by stevenweaver**
FOR CONTRIBUTOR:
* [ x ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ x ] - License permits unrestricted use (educational + commercial)
* [ x ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by stevenweaver** [comment]
Bump

**Comment by bgruening** [comment]
Does it need the file extension to detect the gz?

**Comment by bgruening** [comment]
Or can you please add a small gz file and a test for they?

**Comment by stevenweaver** [comment]
@bgruening -- I can add a test.

**Comment by stevenweaver** [comment]
Added tests for `fastq.gz` and a gzipped file with an abnormal file extension.

**Comment by bgruening** [comment]
Thanks @stevenweaver!

**Pull request merged**
