### PR TITLE
Trinity: bump version forgotten

### PR DESCRIPTION
**Pull request by loraine-gueguen**
I have forgotten to bump the wrapper version of tool run_de_analysis in #1178
Fixed.

### CODE REVIEW

**Comment by nsoranzo** [comment]
This can be solved as part of #1177, which also removes `tool_dependencies.xml` . I'm working on a commit which increases the version number of all tools.

**Comment by bgruening** [comment]
Is this solved now?
Thanks @loraine-gueguen for working on Trinity!

**Comment by nsoranzo** [comment]
Yes, it's fixed in #1177.

**Comment by loraine-gueguen** [comment]
@nsoranzo Thanks!

**Pull request closed without merging**
