### PR TITLE
Semi-automatic EDAM-annotation of tools with partial descriptions at macros.xml

### PR DESCRIPTION
**Pull request by inkuzmin**
This is the second part of the work on [cross-referencing the tools from Galaxy with their counterparts at bio.tools to assign them EDAM terms](https://github.com/galaxyproject/tools-iuc/pull/1897) started during the ELIXIR Workshop for Galaxy training material and skills improvement in Norwich.

This Pull Request covers the tools with descriptions split between `macro.xml` and individual XML files.

As those cases are trickier to be handled automatically they are potentially more vulnerable to inaccuracies.

### CODE REVIEW

**Comment by bgruening** [comment]
@hmenager this PR is getting out of data. Do you see any change we can merge this soonish? 

xref: https://github.com/galaxyproject/tools-iuc/pull/1897

**Comment by mr-c** [comment]
@nsoranzo did you close this manually, or is that the result of deleting the "master" branch?

**Comment by nsoranzo** [comment]
@mr-c Not me manually, it looks like that GitHub closed 6 PRs were either the source repository or branch was deleted.

**Comment by mr-c** [comment]
@nsoranzo Okay, that's what I thought. I would re-open this one, but I lack the permissions.

**Comment by nsoranzo** [comment]
The button to reopen it is disabled for the same reason. Any way I think we are now preferring bio.tools annotations (if available) over using EDAM directly.

**Comment by mr-c** [comment]
Yeah, you'd need to click `edit` at the top of the PR to change the target branch to something that exists (since `master` was deleted), and then you can re-open this, if that still makes sense

**Pull request closed without merging**
