### PR TITLE
conda for transdecoder

### PR DESCRIPTION
**Pull request by lecorguille**

### CODE REVIEW

**Comment by bgruening** [comment]
Yeah!

**Comment by nsoranzo** [comment]
`tools/transdecoder/tool_dependencies.xml` was not updated here, fixed in a1c67fe236be4c3c26c077ce86b9b19adf2dfb86.

**Comment by nsoranzo** [comment]
MTS and TTS manually updated.

**Comment by lecorguille** [comment]
Oups!
Thanks @nsoranzo

**Pull request merged**
