### PR TITLE
Increase version numbers of tools affected by pull request #2133

### PR DESCRIPTION
**Pull request by wm75**
FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

FOR REVIEWER:
* [ ] .shed.yml file ok
    - [ ] Toolshed user `iuc` has access to associated toolshed repo(s)
* [ ] Indentation is correct (4 spaces)
* [ ] Tool version/build ok
* [ ] `<command/>`
  - [ ] Text parameters, input and output files `'single quoted'`
  - [ ] Use of `<![CDATA[ ... ]]>` tags
  - [ ] Parameters of type `text` or having `optional="true"` attribute are checked with `if str($param)` before being used
* [ ] Data parameters have a `format` attribute containing datatypes recognised by Galaxy
* [ ] Tests
  - [ ] Parameters are reasonably covered
  - [ ] Test files are appropriate
* [ ] Help
  - [ ] Valid restructuredText and uses `<![CDATA[ ... ]]>` tags
* [ ] Complies with other best practice in [Best Practices Doc](http://galaxy-iuc-standards.readthedocs.io/en/latest/best_practices/tool_xml.html)

### CODE REVIEW

**Comment by martenson** [comment]
should we bump `gemini_gene_wise` too, since it uses the sanitize_query macro?

**Comment by wm75** [comment]
or not :(
to make this work we also need to put the parameter in single quotes in the commands section.

Looks like I have to create another PR just for this.

**Comment by wm75** [comment]
Means you have to wait with merging this one until the gene_wise fix got merged (without a version increase). Sorry for that oversight.

**Comment by martenson** [comment]
No worries at all. There is no rush with security.

**Comment by wm75** [comment]
the iqtree test timeout strikes again :(

**Comment by nsoranzo** [comment]
@wm75 We need to wait for https://github.com/galaxyproject/tools-iuc/pull/2147 anyway.

**Comment by bgruening** [comment]
Thanks @wm75!

**Pull request merged**
