### PR TITLE
Correct syntax error in snpeff datatype file

### PR DESCRIPTION
**Pull request by Unode**

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by bgruening** [comment]
Hi @Unode thanks for the patch I will merge it, but please note that the SNPeff datatypes are now integrated into Galaxy: https://github.com/galaxyproject/galaxy/blob/dev/config/datatypes_conf.xml.sample#L183

**Comment by erasche** [comment]
@bgruening let's just deprecate/remove the datatypes then? Does this change need to be mirrored to galaxy?

**Comment by Unode** [comment]
@bgruening Thanks. I just bumped into this upon checking the logs.
The toolshed snpeff package should probably be updated then as it still depends on this snpeff_datatypes.

**Comment by erasche** [comment]
If the toolshed package depends on it, and they're in Galaxy, can we just remove that dependency?

**Comment by Unode** [comment]
Referencing #133 after an accidental push --force that overwrote the master branch.

**Pull request merged**
