### PR TITLE
Try find maybe?

### PR DESCRIPTION
**Pull request by nitesh1989**
Hi Ross,

Try find, I tried it on my machine, and the code seems to work. It gives the same result, I think. But i'm dong more digging. This pull request might keep changing ...haha!

### CODE REVIEW

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by nitesh1989** [comment]
I've had a really hard time trying to get "locate" to work on OSX Yosemite. Its been a big pain, and i'm yet to figure out the problem. This whole problem disappears if we can use "locate".

**Comment by erasche** [comment]
Can one of the admins verify this patch?

**Comment by erasche** [comment]
Tagging @fubar2 as the reviewer because he was mentioned in the post, but never notified directly.

**Comment by fubar2** [comment]
This was done in a more complex way to try to get the right root for the find

**Pull request closed without merging**
