### PR TITLE
Updating tools/read_it_and_keep from version 0.2.2 to 0.3.0

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/read_it_and_keep**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/read_it_and_keep from version 0.2.2 to 0.3.0.

**Project home page:** https://github.com/GenomePathogenAnalysisService/read-it-and-keep/releases

### CODE REVIEW

**Comment by wm75** [comment]
v0.3.0 looks like a really trivial new release, which shouldn't change anything results-wise and doesn't offer anything new on the Galaxy side.
No idea why all tests are failing.

**Comment by mira-miracoli** [comment]
> v0.3.0 looks like a really trivial new release, which shouldn't change anything results-wise and doesn't offer anything new on the Galaxy side. No idea why all tests are failing.

I ran the tests and Conda said there would be no version 0.3.0 in bioconda, despite that, all tests "passed". However when I take a look at the conda [site](https://anaconda.org/bioconda/read-it-and-keep/files) the Version is displayed there (bioconda/linux64).
When I run the tests using --docker, it seems to find nothing, either.

**Comment by bgruening** [comment]
its now available and I restarted the tests

**Comment by wm75** [comment]
Cool, that solved it! Thanks @mira-miracoli & @bgruening!

A more general question: What's the strategy with tool updates like this one?
There are no functional changes in this release that would impact the Galaxy wrapper in any way. Do we still want to have an accompanying wrapper release just to be up to date, or are too many insignificant version choices just a burden for admins and users?

**Comment by bgruening** [comment]
> A more general question: What's the strategy with tool updates like this one?
> There are no functional changes in this release that would impact the Galaxy wrapper in any way. Do we still want to have an accompanying wrapper release just to be up to date, or are too many insignificant version choices just a burden for admins and users?

I think @simonbray had a plan :)

**Comment by simonbray** [comment]
> I think @simonbray had a plan :)

We can close this if you like.

**Pull request closed without merging**
