### PR TITLE
Fix readline related compilation failure

### PR DESCRIPTION
**Pull request by Unode**
The readline errors reported in #101 turned out to be due to ncurses not being in the list of linked libraries.

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by martenson** [comment]
ok to test

**Comment by erasche** [comment]
Nice catch @Unode. This will be automatically pushed to the TTS in ~8 hours.

**Comment by Unode** [comment]
Cool, thanks. Btw @erasche this only fixes the darwin build.
The prebuilt package for linux is still the same and suffers from #101. Different issue though.

**Comment by erasche** [comment]
Well, step in the right direction if nothing else. @galaxyproject/iuc should we port this change to the rest of the R packages?

**Comment by nsoranzo** [comment]
@erasche It seems most of the other `package_r` use precompiled binaries for Linux and/or Darwin. It's kind of a mess.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/120/
Test (probably) passed

**Comment by erasche** [comment]
@nsoranzo yeah...Hopefully https://github.com/galaxyproject/docker-build/issues/10 will get done soon and we can rebuild all of the R packages with correct linking.

**Comment by yhoogstrate** [comment]
Great you were able to track it down! Gracias, Youri

**Comment by erasche** [comment]
ping @davebx 

(you were pinged on this issue in two other places (https://github.com/galaxyproject/tools-devteam/issues/100, https://github.com/galaxyproject/tools-iuc/issues/101), figured doing so a third time might summon you :P)

**Pull request merged**
