### PR TITLE
rgrnastar restore IDX_VERSION_SUFFIX

### PR DESCRIPTION
**Pull request by TomHarrop**
Sorry @lldelisle @bgruening I didn't mean to change this.

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [x] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by lldelisle** [comment]
In fact it is the contrary you should have increased it:
```
    <!-- REMEMBER to bump the version of @IDX_VERSION_SUFFIX@
    whenever you make changes to the @TOOL_VERSION@ token!
    The data manager uses a symlink to this macro file to keep the STAR and
    the index versions in sync, but you should manually update @IDX_VERSION_SUFFIX@ -->
```
Because if you use the idx at this version you will use star version 2.7.11a and if you want to get trace of this you need to change the IDX_VERSION_SUFFIX.

**Comment by lldelisle** [comment]
Also, I do not know if it is relevant but STAR has a new version.

**Comment by TomHarrop** [comment]
Thanks @lldelisle, is this correct now? I'm not sure I get it 100% :)

There's a UI change in [2.7.11b](https://github.com/alexdobin/STAR/releases/tag/2.7.11b) that causes some tests to fail, maybe we want a separate PR for that.

**Comment by lldelisle** [comment]
Perfect

**Comment by bgruening** [comment]
Thanks for following up here!

**Pull request merged**
