### PR TITLE
Bedtools update

### PR DESCRIPTION
**Pull request by bgruening**
Time to get a serious review! This PR will update bedtools to the latest version, adds a lot of tests and style fixes.

### CODE REVIEW

**Comment by nsoranzo** [comment]
Amazing contribution, thanks Björn!

**Comment by bgruening** [comment]
@nsoranzo I hope I have addressed every issue. Thanks for pointing me to the text fields. I have fixed a few more and fixed a few tests.
Can we merge it and deploy them to the TTS?

**Comment by nsoranzo** [comment]
I've added some fixes, now all tests pass for me except for 1 randomBed and 3 shuffleBed, which end with segmentation fault on my machine (so not related to the wrappers).

Last thing for me is fisherBed.xml does not have any test.

**Comment by bgruening** [comment]
Added a test for the fisherBed tool.

**Pull request merged**
