### PR TITLE
Nested contrasts comparisons for complex designs

### PR DESCRIPTION
**Pull request by pcm32**
This is to allow contrasts as the ones explained in page 36 of https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

Simply updates the validator used for contrasts so that parenthesis `()` can also be allowed in the construction of more complex contrasts such as those explained in page 36 of edgeR vignettes: https://bioconductor.org/packages/release/bioc/vignettes/edgeR/inst/doc/edgeRUsersGuide.pdf

### CODE REVIEW

**Comment by bgruening** [comment]
@pcm32 do you mind adding a test for this or changing one of the existing ones to use a bracket?

**Comment by pcm32** [comment]
Do tests here run the tool test?

**Comment by nsoranzo** [comment]
Can you please rebase the pull request? Unfortunately we had to do a force-push on the master branch.

Please let us know if you have issues and we can do it for you.

**Comment by pcm32** [comment]
Sorry @nsoranzo I was on leave. When I tried to rebase I get some merge conflicts that I cannot resolve easily, maybe you would know what to pick?

**Comment by pcm32** [comment]
@nsoranzo @mblue9 @bgruening please review #2504 instead, that is from the latest iuc master, thanks! Will close this one.

**Pull request closed without merging**
