### PR TITLE
pygenometracks: use labels in the config file when off

### PR DESCRIPTION
**Pull request by lldelisle**
Hi,
Sorry, I just noticed that the option plot labels for bed and genes was not written in the config file when set to off whereas the default is on...

### CODE REVIEW

**Comment by bgruening** [comment]
Danke!

**Comment by lldelisle** [comment]
Thank you for the reactivity.

**Comment by lldelisle** [comment]
It looks like it did not updated in usegalaxy.eu (I was expecting to see version 3.1.2)...
image
Do you know why?

**Comment by bgruening** [comment]
The automatic update only happens on Saturdays, I will do a semi-manual round today and get @bebatut's new tools also in.

**Comment by lldelisle** [comment]
Ah I did not know. Thanks.

**Comment by bgruening** [comment]
Should be installed by now.

**Comment by lldelisle** [comment]
Yes many thanks

**Pull request merged**
