### PR TITLE
Revert diamond_database_builder profile version to the one that worked

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bgruening** [comment]
is that related to https://github.com/galaxyproject/galaxy/issues/13008 ?

**Comment by gregvonkuster** [comment]
> is that related to [galaxyproject/galaxy#13008](https://github.com/galaxyproject/galaxy/issues/13008) ?

Yes. :)

**Comment by gregvonkuster** [comment]
Can this be merged?

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
ping @natefoo

**Comment by natefoo** [comment]
> ping @natefoo

Thanks for the reminder, I was waiting for galaxyproject/galaxy#13010 to update the MTS. Will do that now...

**Pull request merged**
