### PR TITLE
dada: update and document the collection need sorting before

### PR DESCRIPTION
**Pull request by bernt-matthias**
- fixes: https://github.com/galaxyproject/tools-iuc/issues/2996
- updates to 1.16

FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Just pinging a few that were interested in the last dada tool iterations: @loraine-gueguen @gregvonkuster @yvanlebras .. has anyone of you affected by this?

**Comment by loraine-gueguen** [comment]
@bernt-matthias The 1.12 dada2 galaxy suite was used last December during a 5 days metabarcoding training in Roscoff, France, and there was no problem.

**Comment by yvanlebras** [comment]
Testing the 1.12 version was ok for me too, but maybe I don't use these paired parameters... Or don't see the error... Thank You Matthias for this amazing work !!!!

**Comment by bernt-matthias** [comment]
Just to clarify, the problem only occurs if 

- the dada tool is used in default (non-batch) mode and
- sample names have mixed case 

In this case I'm quite sure that also 1.12 is affected and also if paired data is given separately.

**Comment by bernt-matthias** [comment]
@loraine-gueguen 

> The 1.12 dada2 galaxy suite was used last December during a 5 days 

Is there some training material that I could use .. and the ultimately could go to the GTN?

**Comment by yvanlebras** [comment]
Dear Matthias, 

Thank you so much (for your work + detecting this issue and asking info from us) !

So I created a Galaxy history to reproduce the dada1.12 tuto using the default mode and sample name with mix cases (if I am right) https://ecology.usegalaxy.eu/u/ylebras/h/test-dada2 and it appears to have a difference in sorting files into "orignal" raw reads collections compared to "dada2: dada" output collections so the mergePairs tool try to merge unrelated reads. Is this the issue ?

As a GTN tuto we can maybe use the Dada2 official tutorial https://benjjneb.github.io/dada2/tutorial.html ?

**Comment by bernt-matthias** [comment]
> So I created a Galaxy history to reproduce the dada1.12 tuto using the default mode and sample name with mix cases (if I am right) https://ecology.usegalaxy.eu/u/ylebras/h/test-dada2 and it appears to have a difference in sorting files into "orignal" raw reads collections compared to "dada2: dada" output collections so the mergePairs tool try to merge unrelated reads. Is this the issue ?

Exactly. 

I like the colorful header of this Galaxy instance .. how is this implemented? 

> As a GTN tuto we can maybe use the Dada2 official tutorial https://benjjneb.github.io/dada2/tutorial.html ?

This sounds like the best idea. The question is if its necessary to create an extra text? Because the dada2 tutorial is already very nice IMO. Maybe its sufficient to augment it with additional Galaxy related infos (like the sorting issue / the two possibilities to run call the dada tool, ...) and workflow, tour, ....

**Comment by yvanlebras** [comment]
colorful header is a magic work by wonder @hexylena ;)

Your proposal around a GTN dada2 tuto is exactly what I was thinking about. Reusing the original Dada tuto with Galaxy dedicated enrichment.

**Comment by hexylena** [comment]
@bernt-matthias 

> I like the colorful header of this Galaxy instance .. how is this implemented?

we have [an ansible role](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/roles/usegalaxy-eu.subdomain-themes/tasks/main.yml) that sets up several 'override' CSS files, one per subdomain. Each of these [can add custom CSS content](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/group_vars/custom-sites.yml) on top of the base.css that galaxy ships. [NGINX checks if the CSS is there](https://github.com/usegalaxy-eu/infrastructure-playbook/blob/master/templates/nginx/galaxy-main.j2#L134), and shows that, otherwise, the 'base.css' that's symlinked into that folder.

at first I just wanted some [pretty colors](https://test.usegalaxy.eu/) for the test server, since I really liked travis-ci's configurable themes, but, then it expanded it some sillier things (e.g. [live](https://live.usegalaxy.eu) or [hicexplorer](https://hicexplorer.usegalaxy.eu))

**Comment by yvanlebras** [comment]
hmmm, even if I sort the collection (it appears to me the collections are ok now, files on the same order) mergePairs doesn't work... same error

**Comment by bernt-matthias** [comment]
Hrm. Can you share the history or the workflow? I have a (as far as I know) working workflow for 1.14.

**Comment by bernt-matthias** [comment]
@yvanlebras you should upgrade to 1.14 : there was a bug in dada in 1.12 https://github.com/galaxyproject/tools-iuc/pull/2918

**Comment by yvanlebras** [comment]
Thank you Matthias for your help, unfortunately, I am using the 1.14 version.

image

History link: https://ecology.usegalaxy.eu/u/ylebras/h/test-dada2

**Comment by bernt-matthias** [comment]
The read collections are sorted lexical in **reverse** order :)

**Comment by yvanlebras** [comment]
I used the Galaxy sort collection tool https://ecology.usegalaxy.eu/root?tool_id=__SORTLIST__ to sort alphabetically. There is no option to sort in reverse order on this tool... And as the dada2-data output collection elements were displayed the same order I was thinking this was ok.... So I miss something apparently ;) This is not "just" the output collection of "filterAndTrim" to sort so the collection elements are in the same order than the dada2-dada tool? or maybe I have to first sort "filterAndTrim" output collection before executing further steps like dada2-dada ? thank you for your help, will try several things this evening!

**Comment by bernt-matthias** [comment]
in https://ecology.usegalaxy.eu/u/ylebras/h/test-dada2 there is no sort step .. or?

**Comment by yvanlebras** [comment]
there is, resulting "just" in a new data collection with name finishing by (sorted)

**Comment by loraine-gueguen** [comment]
@bernt-matthias The dada2 workflow used during the december training (thanks Olivier Rué from the Migale platform, INRAE) was based on some public samples found at https://benjjneb.github.io/dada2/tutorial.html Unfortunaltely, the workflow history is currently not publicly available because it is on our access restricted galaxy instance http://galaxy4metab.sb-roscoff.fr

**Comment by bernt-matthias** [comment]
Just noticed 1.16 is out. Since there seem to be no user facing changed I suggest to bump the version.

**Comment by bernt-matthias** [comment]
@yvanlebras any success with your experiments?

**Comment by yvanlebras** [comment]
Sorry difficult to find some time to retry the steps, will try next week I hooe

**Comment by bernt-matthias** [comment]
Ready for review / merge.

**Comment by bgruening** [comment]
Merci!

**Comment by bernt-matthias** [comment]
Probably by mistake I downgraded the version of the data manager and dropped `profile="18.09" `. Should I open a PR fixing this.

**Pull request merged**
