### PR TITLE
Add .shed.yml for all packages

### PR DESCRIPTION
**Pull request by erasche**
I'll change the title and ping people when this is actually desired to be tested, but for the moment I'm going to use this PR to test the jenkins PR builder.

For the future:

- I'm adding `.shed.yml` files to everything in this repo so...
- jenkins will be able to push everything to the test toolshed on every successful build.

E.g. #29 has been done for ~20 days, and it wasn't on the TTS nor the MTS. We had a user on IRC who was encountering problems as a result of the delay for this fix, so we need to be better about pushing things to the TTS, and when they're built successfully there, to the MTS.

### CODE REVIEW

**Comment by erasche** [comment]
jenkins: test this please

**Comment by jmchilton** [comment]
This is awesome - you should be sure to open source the Jenkins stuff so we can steal it and run it for every repository :).

**Comment by nsoranzo** [comment]
That would be really cool, I hate pushing stuff to the Tool Sheds ;)

**Comment by erasche** [comment]
Of course! It'll all be published with extensive how-tos. These are easily automated tasks that *must* happen automatically since we're all rubbish about pushing to toolsheds. :)

**Comment by erasche** [comment]
jenkins: test this please

**Comment by erasche** [comment]
jenkins: for the love of all that is good and holy, test this please

**Comment by saketkc** [comment]
@erasche I think jenkins is too specific when it comes to comments on PRs.
"test this please" it should be, and nothing else.

**Comment by erasche** [comment]
@saketc of course. I'm using the default config so "test this please" is how it's configured, I was mostly prefixing with "jenkins:" so everyone getting these dozens of spam emails from me would know it's not to them :)

**Comment by erasche** [comment]
test this please

**Comment by erasche** [comment]
AWESOME.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/19/
Test FAILed.

**Comment by erasche** [comment]
test this please

**Comment by erasche** [comment]
FYI: comments will appear as me, I might create a separate "bot" account later.

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/20/
Test failed.

**Comment by erasche** [comment]
@galaxyproject/iuc okay, this PR is ready to be reviewed as I'm done playing around with jenkins. Please ignore the build failure notification as that was a misconfiguration (looked for xunit reports in `/reports/*.xml` not `reports/*.xml`, whoops!).

If anyone wants to look over this and sign off on a merge, that'd be great, thanks!

**Comment by bgruening** [comment]
Looks good to me!

**Comment by erasche** [comment]
Great, I'm calling that "good enough". Thanks @bgruening

**Comment by fubar2** [comment]
test this please

**Comment by erasche** [comment]
fubar2: also, it works on and off, I haven't really figured out the small details of the github PR plugin in jenkins. E.g. it works on new PRs, it sometimes works when you use the phrase/sometimes it doesn't test things when you ask. So, I don't know. Sorry for lack of clarity on that.

**Comment by fubar2** [comment]
Sounds like maybe Jenkins is so complex it has begun to exhibit infantile petulance as an emergent behaviour :(

**Comment by erasche** [comment]
hah! I hope not. 
That said, the github plugin is fairly complex, so there'll definitely be an infantile teething period getting things working.

**Pull request merged**
