### PR TITLE
Updating tools/bowtie2 from version 2.4.5 to 2.5.0

### PR DESCRIPTION
**Pull request by planemo-autoupdate**
Hello! This is an automated update of the following tool: **tools/bowtie2**. I created this PR because I think the tool's main dependency is out of date, i.e. there is a newer version available through conda.

I have updated tools/bowtie2 from version 2.4.5 to 2.5.0.

**Project home page:** http://bowtie-bio.sourceforge.net/bowtie2

For any comments, queries or criticism about the bot, not related to the tool being updated in this PR, please create an issue [here](https://github.com/planemo-autoupdate/autoupdate/issues/new).

### CODE REVIEW

**Comment by gallardoalba** [comment]
Improvements:
- Overall improvements in the use of prefetch instructions. (contribution by Igor Sfiligoi)
- Made input/output fully asynchronous by using a dedicated thread. (contribution by Igor Sfiligoi)
- Added support for AVX2 256-bit instructions with can be enabled by setting the SSE_AXV2 environment variable at compile time. (contribution by Igor Sfiligoi)
- Fixed an issue causing bowtie2 to crash when processing ZSTD files with high compression ratios.
- Changed the way that unique alignments are counted in summary message to better match up with filters on SAM output

**Review by gallardoalba — APPROVED** [review]

**Comment by bgruening** [comment]
Are we concerned that the resulting test data is reduced by 98%?

**Comment by gallardoalba** [comment]
> Are we concerned that the resulting test data is reduced by 98%?

I checked the content of some of them and seem to be fine; for example, the SAM file from bowtie2-test1.bam contains 204 lines, so not sure what can be the problem.

**Comment by gallardoalba** [comment]
> Are we concerned that the resulting test data is reduced by 98%?

The content of the SAM files seems to be the same https://gist.github.com/gallardoalba/bdc465327f9947d50f3b80df0089d36c

**Pull request merged**
