### PR TITLE
data_managers: create dirs with 755 instead of 777

### PR DESCRIPTION
**Pull request by bernt-matthias**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by bernt-matthias** [comment]
Maybe one should also post on the admin mailing list that dir permissions of existing data sets should be changed.

**Comment by bernt-matthias** [comment]
Didn't understand the first one. So I fixed the first .. hoping that the first is related .. lets see

**Comment by nsoranzo** [comment]
> Maybe one should also post on the admin mailing list that dir permissions of existing data sets should be changed.

Luckily this shouldn't be an issue if you have a standard umask (`022`).

For [Python >=3.7](https://docs.python.org/3.7/library/os.html#os.makedirs), there is an additional issue: "The mode parameter is passed to `mkdir()` for creating the leaf directory. To set the file permission bits of any newly-created parent directories you can set the umask before invoking `makedirs()`."

**Comment by bernt-matthias** [comment]
> Luckily this shouldn't be an issue if you have a standard umask (022).

@nsoranzo Extremely helpful point. Thanks a lot. Turns out that there are some strange things going on with the ACLs in der directory that contains Galaxy's job directory. Just contacted our admins to understand the problem. 

In this light I guess the PR is obsolete.

**Comment by bernt-matthias** [comment]
will be fixed by https://github.com/galaxyproject/galaxy/pull/8581

**Pull request closed without merging**
