### PR TITLE
Set HOME to . on package run.

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by blankenberg** [comment]
See https://github.com/galaxyproject/tools-iuc/issues/51

**Comment by bgruening** [comment]
:+1:

**Comment by erasche** [comment]
Refer to this link for build results (access rights to CI server needed): 
http://gx.hx42.org//job/IUC-Github/27/
Test PASSed.

**Comment by erasche** [comment]
@bgruening merging before tests finish, shame on you :P

**Comment by erasche** [comment]
(not that package installs are tested... I'll need to find a way to test those)

**Pull request merged**
