### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by ieguinoa**
Just noticed that the output files number was wrong.

### CODE REVIEW

**Comment by bgruening** [comment]
uh, this is a "nice" one. Can you increase the version please as well?

**Comment by ieguinoa** [comment]
done

**Comment by nsoranzo** [comment]
The test is failing, does it need to be updated or is this change wrong? Ping @nekrut

**Comment by bgruening** [comment]
@ieguinoa can you please revert the last commit. We will track this in your other PR.
Can you maybe update the test data here as well?

**Comment by mblue9** [comment]
Hi, I just noticed that this PR has a typo fix for one of the macs2 tools - macs2_bdgdiff.xml. It looks good to me, could this fix be added?

**Comment by bgruening** [comment]
@ieguinoa @mblue9 this one still needs a rebase.

**Comment by abretaud** [comment]
Done in 190427fb2db7e025ddf428e54d2b9298a0580424

**Pull request closed without merging**
