### PR TITLE
Add python version option to planemo test command

### PR DESCRIPTION
**Pull request by ic4f**
Also, change python version to 3.6.

This is the first step in ref to:
https://github.com/galaxyproject/tools-iuc/pull/2168

Ping @mvdbeek 

FOR CONTRIBUTOR:
* [ ] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [ ] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [ ] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by nsoranzo** [comment]
Travis fails at the lint stage (i.e. before actual testing) because several Python files are not Python3-compatible.
You can fix them with the process described in https://github.com/galaxyproject/galaxy/issues/1715 .

**Comment by ic4f** [comment]
@nosranzo got it! (i saw it failed as expected, but for the wrong reason). I'll get to this later today.

**Comment by nsoranzo** [comment]
Can you please rebase the pull request? Unfortunately we had to do a force-push on the master branch.

Please let us know if you have issues and we can do it for you.

**Comment by ic4f** [comment]
@nsoranzo yep, i'm on it.

**Comment by ic4f** [comment]
This has been replaced by https://github.com/galaxyproject/tools-iuc/pull/2493

**Pull request closed without merging**
