### PR TITLE
Add LD_LIBRARY_PATH which seems to be needed.

### PR DESCRIPTION
**Pull request by bgruening**
@mvdbeek does this seems right to you?

### CODE REVIEW

**Comment by mvdbeek** [comment]
@bgruening
Sorry, I missed it. :+1: 
When did you encounter this, and should we do this for older R versions too?

**Comment by bgruening** [comment]
No worries. Honestly, I don't know ;) Maybe the rpy2 package I have updated. It can not hurt to update the others as well I guess.

**Comment by gregvonkuster** [comment]
@bgruening @mvdbeek If updating LD_LIBRARY_PATH settings, please also add DYLD_LIBRARY_PATH to those recipes that do not have it so they will work on OS X.  Thanks!  ;)

**Comment by bgruening** [comment]
Should this be part of the framework @gregvonkuster ? If LD_LIBRARY_PATH ... include also DYLD...

**Comment by gregvonkuster** [comment]
Yes, I think so.  LD_LIBRARY_PATH on Linux == DYLD_LIBRARY_PATH on OS X.

**Pull request merged**
