### PR TITLE
Fix gtdbtk outputs

### PR DESCRIPTION
**Pull request by gregvonkuster**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by gregvonkuster** [comment]
Should hopefully fix https://github.com/galaxyproject/tools-iuc/issues/5344

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
> .. WARNING: Test should specify 'expect_num_outputs' if outputs have filters

**Comment by gregvonkuster** [comment]
> .. WARNING: Test should specify 'expect_num_outputs' if outputs have filters

Hopefully this will fix the lint issue https://github.com/galaxyproject/tools-iuc/pull/5358 - shouldn't the PR have failed before it was merged?

**Comment by gregvonkuster** [comment]
Not sure how to fix the lint issue - my attempt here https://github.com/galaxyproject/tools-iuc/pull/5358 produces this error.
```
Applying linter tests... FAIL
.. ERROR: Test 1: Cannot make assumptions on the number of outputs in a test expecting failure.
```

**Comment by mvdbeek** [comment]
> Hopefully this will fix the lint issue #5358 - shouldn't the PR have failed before it was merged?

New planemo release with new linting rules, this one is just a deadlock: https://github.com/galaxyproject/galaxy/issues/16235

**Comment by mvdbeek** [comment]
@gregvonkuster I've uploaded this manually now, the linting passes locally now but I couldn't rerun the job, probably since it was too old at this point.

**Pull request merged**
