### PR TITLE
Polish to stringtie interface and test update

### PR DESCRIPTION
**Pull request by nekrut**
This will support latest 1.0.3 version of stringtie

### CODE REVIEW

**Comment by erasche** [comment]
[Jenkins Bot] Can one of the admins sign off on testing this PR? (Security reasons, simply comment "ok to test")

**Comment by martenson** [comment]
ok to test

**Comment by nsoranzo** [comment]
LGTM

**Comment by nekrut** [comment]
I no more comments = pls, merge

**Comment by bgruening** [comment]
Thanks @nekrut!

**Pull request merged**
